Add AzureTranslation component
openmpf/openmpf-components pull request #185
Opened 2020-10-05 19:10 UTC by brosenberg42

Issue: https://github.com/openmpf/openmpf/issues/1169

2020-11-03 22:56 UTC, jrobble requested changes
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/185)* status: 0 of 20 files reviewed, 2 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[python/AzureTranslation/acs_translation_component/acs_translation_component.py, line 92 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/185#-MLFI9f8-GMSgxM5X796:-MLFI9f8-GMSgxM5X797:bsu7cpz) ([raw file](https://github.com/openmpf/openmpf-components/blob/5afefd5d8688938798020726530b7fe37b23f5a0/python/AzureTranslation/acs_translation_component/acs_translation_component.py#L92)):*
> ```Python
>         log.info(f'[{job.job_name}] Received job: {job}')
>         if ff_track is None:
>             log.warning(f'[{job.job_name}] No feed forward track provided. '
> ```

Here's an example of what Keyword Tagging does:

```
    } else {
        LOG4CXX_DEBUG(hw_logger_, "Can only process audio files in feed forward jobs.");
        throw MPFDetectionException(MPF_UNSUPPORTED_DATA_TYPE, "Can only process audio files in feed forward jobs.");
    }
```

There are similar errors for video and image data types. Generic data types can be processed without feed forward because Keyword Tagging accepts text file inputs.

I think we should generate an error like Keyword Tagging for audio, video, and image files since the component is used improperly in those cases.
___
*[python/AzureTranslation/plugin-files/descriptor/descriptor.json, line 95 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/185#-MLFHnCN3a-C2fn0AZKS:-MLFHnCN3a-C2fn0AZKT:bpstnom) ([raw file](https://github.com/openmpf/openmpf-components/blob/5afefd5d8688938798020726530b7fe37b23f5a0/python/AzureTranslation/plugin-files/descriptor/descriptor.json#L95)):*
> ```JSON
>     }
>   ],
>   "pipelines": [
> ```

Keyword Tagging has a default pipeline that accepts a text file. It's useful for debugging the component because you can copy the feed forward `TEXT` from a previous job and provide it as direct input with minor adjustments to see how that affects the results.


<!-- Sent from Reviewable.io -->

2020-11-10 15:41 UTC, jrobble commented
___
*[python/AzureTranslation/README.md, line 16 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/185#-MLmnf5OEyZ_C8EWPX2S:-MLmnf5PBx7oNIzTZQKW:bxm30un) ([raw file](https://github.com/openmpf/openmpf-components/blob/5afefd5d8688938798020726530b7fe37b23f5a0/python/AzureTranslation/README.md#L16)):*
> ```Markdown
> When a detection property is translated, the translation is put in to a new 
> detection property named using this pattern: 
> `<prop_name> (TRANSLATED TO <to_language>)` (e.g. 
> ```

As discussed, please change the output property to:

`<prop_name> TRANSLATION`

This will make it easier for @mcrensh to configure Keyword Tagging to parse these properties, if the end user wants to tag the translated output.

Also, please add a `TARGET LANG` output property to make it easier for third-party consumers.


<!-- Sent from Reviewable.io -->

2020-11-16 15:41 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/185)* status: 0 of 21 files reviewed, 3 unresolved discussions (waiting on @brosenberg42, @jrobble, and @mcrensh)

___
*[python/AzureTranslation/README.md, line 16 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/185#-MLmnf5OEyZ_C8EWPX2S:-MMGhkeH0VErF5_9qx7K:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/5afefd5d8688938798020726530b7fe37b23f5a0/python/AzureTranslation/README.md#L16)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

As discussed, please change the output property to:

`<prop_name> TRANSLATION`

This will make it easier for @mcrensh to configure Keyword Tagging to parse these properties, if the end user wants to tag the translated output.

Also, please add a `TARGET LANG` output property to make it easier for third-party consumers.
</blockquote></details>

Done.
___
*[python/AzureTranslation/acs_translation_component/acs_translation_component.py, line 92 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/185#-MLFI9f8-GMSgxM5X796:-MMGhnH_D5AjXPuOX9b7:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/5afefd5d8688938798020726530b7fe37b23f5a0/python/AzureTranslation/acs_translation_component/acs_translation_component.py#L92)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Here's an example of what Keyword Tagging does:

```
    } else {
        LOG4CXX_DEBUG(hw_logger_, "Can only process audio files in feed forward jobs.");
        throw MPFDetectionException(MPF_UNSUPPORTED_DATA_TYPE, "Can only process audio files in feed forward jobs.");
    }
```

There are similar errors for video and image data types. Generic data types can be processed without feed forward because Keyword Tagging accepts text file inputs.

I think we should generate an error like Keyword Tagging for audio, video, and image files since the component is used improperly in those cases.
</blockquote></details>

Done.
___
*[python/AzureTranslation/plugin-files/descriptor/descriptor.json, line 95 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/185#-MLFHnCN3a-C2fn0AZKS:-MMGho6j05Y0JSoFIjIe:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/5afefd5d8688938798020726530b7fe37b23f5a0/python/AzureTranslation/plugin-files/descriptor/descriptor.json#L95)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Keyword Tagging has a default pipeline that accepts a text file. It's useful for debugging the component because you can copy the feed forward `TEXT` from a previous job and provide it as direct input with minor adjustments to see how that affects the results.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-24 03:09 UTC, jrobble requested changes
> Reviewed 16 of 20 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/185)* status: all files reviewed, 15 unresolved discussions (waiting on @brosenberg42 and @mcrensh)

___
*[python/AzureTranslation/README.md, line 16 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/185#-MLmnf5OEyZ_C8EWPX2S:-MMbb_903ZtrxhdCBqIP:bt058io) ([raw file](https://github.com/openmpf/openmpf-components/blob/5afefd5d8688938798020726530b7fe37b23f5a0/python/AzureTranslation/README.md#L16)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm looking at the following properties:
- `TEXT (SOURCE LANG)`
- `TEXT (SOURCE LANG CONFIDENCE)`

We use `LANG` above but spell out the whole word in `TRANSLATION TO LANGUAGE`. Let's use the whole word to be consistent within this component and with other components. 
___
*[python/AzureTranslation/README.md, line 49 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/185#-MMbfeo95ZbC7jA86Jy4:-MMbfeo95ZbC7jA86Jy5:b-17rrvk) ([raw file](https://github.com/openmpf/openmpf-components/blob/dec54795af1d7d041c8897cd90b7f169891c9931/python/AzureTranslation/README.md#L49)):*
> ```Markdown
>    should be translated to.
> - `TRANSLATE_PROPERTIES`: Comma-separated list of job properties indicating 
>    which detection properties should be translated.
> ```

Say "Comma-separated list of feed forward detection properties", and please provide an example setting. The default is fine.
___
*[python/AzureTranslation/README.md, line 50 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/185#-MMqxkLM81P4wL4puplQ:-MMqxkLM81P4wL4puplR:b-bxkmr2) ([raw file](https://github.com/openmpf/openmpf-components/blob/dec54795af1d7d041c8897cd90b7f169891c9931/python/AzureTranslation/README.md#L50)):*
> ```Markdown
> - `TRANSLATE_PROPERTIES`: Comma-separated list of job properties indicating 
>    which detection properties should be translated.
> - `FROM_LANGUAGE`: In most cases, this property should not be used. It should
> ```

Consider mentioning using `SUGGESTED_FROM_LANGUAGE` as a fallback.
___
*[python/AzureTranslation/README.md, line 55 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/185#-MMr1BY-BHugaoFJHKKw:-MMbfPZ54zYtp1b4YI0b:bs1lizy) ([raw file](https://github.com/openmpf/openmpf-components/blob/dec54795af1d7d041c8897cd90b7f169891c9931/python/AzureTranslation/README.md#L55)):*
> ```Markdown
>   doing automatic language detection. If `FROM_LANGUAGE` is provided, and the 
>   text is actually another language, the translation endpoint will return the 
>   input text unchanged.
> ```

When translation is not actually performed, the JSON output object lacks some of the detection properties. This may confuse third-party consumers. In general, we usually just set those properties to the blank string. I'm fine doing it your way, but we'd need to inform the consumers of this behavior and make sure they are ok with it.
___
*[python/AzureTranslation/setup.py, line 32 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/185#-MMbS0Tt4cSz8pp1fuoy:-MMbS0Tt4cSz8pp1fuoz:b-eyqf46) ([raw file](https://github.com/openmpf/openmpf-components/blob/dec54795af1d7d041c8897cd90b7f169891c9931/python/AzureTranslation/setup.py#L32)):*
> ```Python
> setuptools.setup(
>     name='AzureTranslation',
>     version='5.0',
> ```

Please update the 5.0 version numbers in this file to 5.1.
___
*[python/AzureTranslation/acs_translation_component/acs_translation_component.py, line 55 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/185#-MMbU3MbEJ_wbgVWk7PY:-MMbU3MbEJ_wbgVWk7PZ:bnfh5c2) ([raw file](https://github.com/openmpf/openmpf-components/blob/dec54795af1d7d041c8897cd90b7f169891c9931/python/AzureTranslation/acs_translation_component/acs_translation_component.py#L55)):*
> ```Python
>             if ff_track is None:
>                 raise mpf.DetectionError.UNSUPPORTED_DATA_TYPE.exception(
>                     f'[{job.job_name}] Component can only process feed forward jobs, '
> ```

We generally don't provide the job name in the error messages that appear in the JSON output object. One reason is because we don't always have access to the job number depending on where the exception is thrown.

The job number appears in the WFM log already:

```
2020-11-23 18:00:53,910 INFO [Camel (camelContext) thread #45 - JmsConsumer[MPF.COMPLETED_DETECTIONS]] o.m.m.w.d.InProgressBatchJobsService - Adding detection processing error for job 285's media 19: UNSUPPORTED_DATA_TYPE - An error occurred while invoking the "get_detections_from_audio" method on the Python component: ('[Job 285:green.wav(0--1)] Component can only process feed forward jobs, but no feed forward track provided. ', <DetectionError.UNSUPPORTED_DATA_TYPE: 4>)
```
___
*[python/AzureTranslation/acs_translation_component/acs_translation_component.py, line 154 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/185#-MMbhZgfAbyCZTfDZlfE:-MMbhZgfAbyCZTfDZlfF:bedvvba) ([raw file](https://github.com/openmpf/openmpf-components/blob/dec54795af1d7d041c8897cd90b7f169891c9931/python/AzureTranslation/acs_translation_component/acs_translation_component.py#L154)):*
> ```Python
> 
>         # Certain components that process videos and don't do tracking will create tracks with a
>         # single detection. The track and detection will have the same set of properties, so
> ```

I haven't considered this problem. I now realize that keyword tagging does not add any detections to the video track it generates, so the WFM drops the tracks and the action yields "NO TRACKS" in the JSON output object.

Keyword tagging should handle each detection in the feed-foward video track, which may have unique `TEXT` / `TRANSCRIPT` properties. This is in addition to handling the track-level `TEXT` / `TRANSCRIPT` properties.

Currently, the only keyword tagging use case that could result in this is passing a video file to speech detection followed by keyword tagging. The user is not interested in using keyword tagging on speech transcripts for 5.1, so we should be fine as long as we get a fix in 5.2.

I created a separate [issue](https://github.com/openmpf/openmpf/issues/1209) for this.
___
*[python/AzureTranslation/plugin-files/descriptor/descriptor.json, line 3 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/185#-MMqMOsSCkdmW_XEUNhQ:-MMqMOsSCkdmW_XEUNhR:bg8nno5) ([raw file](https://github.com/openmpf/openmpf-components/blob/dec54795af1d7d041c8897cd90b7f169891c9931/python/AzureTranslation/plugin-files/descriptor/descriptor.json#L3)):*
> ```JSON
> {
>   "componentName": "AzureTranslation",
>   "componentVersion": "5.0",
> ```

Please update to 5.1.
___
*[python/AzureTranslation/plugin-files/descriptor/descriptor.json, line 59 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/185#-MMqymRa1HnMO3AxOLXi:-MMqMgFZCAPnfw06Cc_S:boalrkq) ([raw file](https://github.com/openmpf/openmpf-components/blob/dec54795af1d7d041c8897cd90b7f169891c9931/python/AzureTranslation/plugin-files/descriptor/descriptor.json#L59)):*
> ```JSON
>         },
>         {
>           "name": "CATEGORY",
> ```

Did the user ask for this? What's the motivation for including it?
___
*[python/AzureTranslation/plugin-files/descriptor/descriptor.json, line 75 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/185#-MMr9euv-OWhu9xvRK6U:-MMr9euv-OWhu9xvRK6V:b-h6izv4) ([raw file](https://github.com/openmpf/openmpf-components/blob/dec54795af1d7d041c8897cd90b7f169891c9931/python/AzureTranslation/plugin-files/descriptor/descriptor.json#L75)):*
> ```JSON
>   "actions": [
>     {
>       "name": "AZURE TRANSLATION ACTION",
> ```

Please call this `AZURE TRANSLATION (WITH FF REGION) ACTION`. Similarly, call the task `AZURE TRANSLATION (WITH FF REGION) TASK`.
___
*[python/AzureTranslation/plugin-files/descriptor/descriptor.json, line 86 at r2](https://reviewable.io/reviews/openmpf/ope [...]

2020-11-24 19:56 UTC, jrobble requested changes
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/185)* status: all files reviewed, 14 unresolved discussions (waiting on @brosenberg42 and @mcrensh)

___
*[python/AzureTranslation/README.md, line 49 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/185#-MMbfeo95ZbC7jA86Jy4:-MMvoOa2-TvB3QGNDy2u:b-sqbnc9) ([raw file](https://github.com/openmpf/openmpf-components/blob/dec54795af1d7d041c8897cd90b7f169891c9931/python/AzureTranslation/README.md#L49)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Say "Comma-separated list of feed forward detection properties", and please provide an example setting. The default is fine.
</blockquote></details>

I think it's clearer to name this `PROPERTIES_TO_PROCESS`. That's the name I'm using in Keyword Tagging.
___
*[python/AzureTranslation/plugin-files/descriptor/descriptor.json, line 86 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/185#-MMqMsLq2L_wHr-Qd5VI:-MMvoEQ30XX0fEFtHxKt:bj81ewc) ([raw file](https://github.com/openmpf/openmpf-components/blob/dec54795af1d7d041c8897cd90b7f169891c9931/python/AzureTranslation/plugin-files/descriptor/descriptor.json#L86)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

The Keyword Tagging component doesn't have "TEXT FILE" in the name of the default action, task, and pipeline. Please remove it here or update Keyword Tagging to add it.
</blockquote></details>

Please leave it as "TEXT FILE". I will update Keyword Tagging to also be "TEXT FILE".


<!-- Sent from Reviewable.io -->

2020-11-26 04:50 UTC, jrobble requested changes
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/185)* status: all files reviewed, 14 unresolved discussions (waiting on @brosenberg42 and @mcrensh)

___
*[python/AzureTranslation/README.md, line 49 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/185#-MMbfeo95ZbC7jA86Jy4:-MN1mjeo0Lx2TGqwFPmq:b-xetb3d) ([raw file](https://github.com/openmpf/openmpf-components/blob/dec54795af1d7d041c8897cd90b7f169891c9931/python/AzureTranslation/README.md#L49)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I think it's clearer to name this `PROPERTIES_TO_PROCESS`. That's the name I'm using in Keyword Tagging.
</blockquote></details>

I changed Keyword Tagging to use `FEED_FORWARD_PROPS_TO_PROCESS`. This is more consistent with the `FEED_FORWARD_WHITELIST_FILE` and `FEED_FORWARD_EXCLUDE_BEHAVIOR` property names in the OcvDnnDetection component.

Please use `FEED_FORWARD_PROPS_TO_PROCESS`.

---

Looking at ACS Form Detection, it can generate the following types of detections:

```
                        detection_properties = dict(OUTPUT_TYPE='LINE',
                                                    PAGE_NUM=str(page_num),
                                                    LINE_NUM=str(line_num),
                                                    TEXT=line['text'])
```

```
                    detection_properties = dict(OUTPUT_TYPE='MERGED_LINES',
                                                PAGE_NUM=str(page_num),
                                                TEXT='\n'.join(lines))
```

```
        detection_properties = dict(OUTPUT_TYPE='KEY_VALUE_PAIRS',
                                    PAGE_NUM=str(page_num),
                                    KEY_VALUE_PAIRS_JSON=json.dumps(key_val_dict))
```

```
            detection_properties = dict(OUTPUT_TYPE='TABLE',
                                        PAGE_NUM=str(page_num),
                                        TABLE_NUM=str(table_num),
                                        TABLE_CSV_OUTPUT=cs_output)
```

```
            detection_properties = dict(OUTPUT_TYPE='DOCUMENT_RESULT',
                                        DOCUMENT_TYPE=doc_type,
                                        PAGE_RANGE=json.dumps(doc_result['pageRange']),
                                        DOCUMENT_JSON_FIELDS=fields,
                                        DOCUMENT_RESULT_NUM=str(doc_num))
```

I mention this because if and when we ever want to support keyword tagging or translation on ACS Form Detection output, we will only need to ever process one of the following properties per detection: `TEXT`, `KEY_VALUE_PAIRS_JSON`, `TABLE_CSV_OUTPUT`, or `DOCUMENT_JSON_FIELDS`.

Thus, we can set `FEED_FORWARD_PROPS_TO_PROCESS=TEXT,TRANSCRIPT,KEY_VALUE_PAIRS_JSON,TABLE_CSV_OUTPUT,DOCUMENT_JSON_FIELDS` to cover all the bases.

I mention this because I don't think it's necessary to handle the case where we have a detection with more then one of these properties at a time. I updated Keyword Tagging to just look for the first available property in that list and only perform keyword tagging on that. (Note that it does a separate search for the track-level properties and the properties for each detection).

I did this for simplicity. That way I could keep using the same `TAG`, `TRIGGER_WORDS`, and `TRIGGER_WORDS_OFFSET` property names instead of changing them to  `{prop_name} TAG`, `{prop_name} TRIGGER_WORDS`, and `{prop_name} TRIGGER_WORDS_OFFSET`. This will make it easier for a consumer to parse the output. Granted, I also did this for necessity in the short term since we can't change these names in 5.1, but I'm beginning to think that's how we should keep it in the long term.


<!-- Sent from Reviewable.io -->

2020-11-26 05:03 UTC, jrobble commented
___
*[python/AzureTranslation/README.md, line 49 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/185#-MMbfeo95ZbC7jA86Jy4:-MN1t0IZ3Thidbfe6_Ry:b1gckpj) ([raw file](https://github.com/openmpf/openmpf-components/blob/dec54795af1d7d041c8897cd90b7f169891c9931/python/AzureTranslation/README.md#L49)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I changed Keyword Tagging to use `FEED_FORWARD_PROPS_TO_PROCESS`. This is more consistent with the `FEED_FORWARD_WHITELIST_FILE` and `FEED_FORWARD_EXCLUDE_BEHAVIOR` property names in the OcvDnnDetection component.

Please use `FEED_FORWARD_PROPS_TO_PROCESS`.

---

Looking at ACS Form Detection, it can generate the following types of detections:

```
                        detection_properties = dict(OUTPUT_TYPE='LINE',
                                                    PAGE_NUM=str(page_num),
                                                    LINE_NUM=str(line_num),
                                                    TEXT=line['text'])
```

```
                    detection_properties = dict(OUTPUT_TYPE='MERGED_LINES',
                                                PAGE_NUM=str(page_num),
                                                TEXT='\n'.join(lines))
```

```
        detection_properties = dict(OUTPUT_TYPE='KEY_VALUE_PAIRS',
                                    PAGE_NUM=str(page_num),
                                    KEY_VALUE_PAIRS_JSON=json.dumps(key_val_dict))
```

```
            detection_properties = dict(OUTPUT_TYPE='TABLE',
                                        PAGE_NUM=str(page_num),
                                        TABLE_NUM=str(table_num),
                                        TABLE_CSV_OUTPUT=cs_output)
```

```
            detection_properties = dict(OUTPUT_TYPE='DOCUMENT_RESULT',
                                        DOCUMENT_TYPE=doc_type,
                                        PAGE_RANGE=json.dumps(doc_result['pageRange']),
                                        DOCUMENT_JSON_FIELDS=fields,
                                        DOCUMENT_RESULT_NUM=str(doc_num))
```

I mention this because if and when we ever want to support keyword tagging or translation on ACS Form Detection output, we will only need to ever process one of the following properties per detection: `TEXT`, `KEY_VALUE_PAIRS_JSON`, `TABLE_CSV_OUTPUT`, or `DOCUMENT_JSON_FIELDS`.

Thus, we can set `FEED_FORWARD_PROPS_TO_PROCESS=TEXT,TRANSCRIPT,KEY_VALUE_PAIRS_JSON,TABLE_CSV_OUTPUT,DOCUMENT_JSON_FIELDS` to cover all the bases.

I mention this because I don't think it's necessary to handle the case where we have a detection with more then one of these properties at a time. I updated Keyword Tagging to just look for the first available property in that list and only perform keyword tagging on that. (Note that it does a separate search for the track-level properties and the properties for each detection).

I did this for simplicity. That way I could keep using the same `TAG`, `TRIGGER_WORDS`, and `TRIGGER_WORDS_OFFSET` property names instead of changing them to  `{prop_name} TAG`, `{prop_name} TRIGGER_WORDS`, and `{prop_name} TRIGGER_WORDS_OFFSET`. This will make it easier for a consumer to parse the output. Granted, I also did this for necessity in the short term since we can't change these names in 5.1, but I'm beginning to think that's how we should keep it in the long term.
</blockquote></details>

I forgot to mention, if we updated this component to return `TRANSLATION` instead of `{prop_name} TRANSLATION` then I could just default Keyword Tagging `FEED_FORWARD_PROPS_TO_PROCESS=TEXT,TRANSCRIPT,TRANSLATION` and we could support a `TESSERACT --> TRANSLATION --> KEYWORD TAGGING` pipeline just as easily as we could support an `ACS SPEECH --> TRANSLATION --> KEYWORD TAGGING` pipeline.

Otherwise, the alternative would be to do `FEED_FORWARD_PROPS_TO_PROCESS=TEXT,TRANSCRIPT,TEXT TRANSLATION,TRANSCRIPT TRANSLATION`. Granted, that's much worse.

Really, this is less about your component and more about promoting a best practice of having components only return one *text-like* finding per detection. What I mean is that if a component needs to return another finding, then it should do what ACS Form Detection is doing, and return it in a different detection. I'd like to keep each detection simple.


<!-- Sent from Reviewable.io -->

2020-12-02 17:56 UTC, brosenberg42 commented
___
*[python/AzureTranslation/README.md, line 50 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/185#-MMqxkLM81P4wL4puplQ:-MNZYzLp5sHpiB2xoFWS:b-276jyt) ([raw file](https://github.com/openmpf/openmpf-components/blob/dec54795af1d7d041c8897cd90b7f169891c9931/python/AzureTranslation/README.md#L50)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Consider mentioning using `SUGGESTED_FROM_LANGUAGE` as a fallback.
</blockquote></details>

That parameter only applies if language detection fails. I have never seen it fail, so I have never seen the parameter do anything. Even when the text is clearly a cat on a keyboard. For example this request:
```
POST http://example.com/translate?api-version=3.0&to=en&suggestedFrom=es
[
    {"Text":"kfjasdhktgkajdfaks ldjrfdasklraskdmfnasdfnaskdjrhsldkjfasndlkrfjaslkdvnsad;lkrfujmalsdkfjals adkfjalsdkjfa kfjal kdjfaslkdfj llkdjsfa "}
]
```
produces this is response:
```
[
    {
        "detectedLanguage": {
            "language": "en",
            "score": 1.0
        },
        "translations": [
            {
                "text": "kfjasdhktgkajdfaks ldjrfdasklraskdmfnasdfnaskdjrhsldkjfasndlkrfjaslkdvnsad;lkrfujmalsdkfjals adkfjalsdkjfa kfjal kdjfaslkdfj llkdjsfa ",
                "to": "en"
            }
        ]
    }
]
```


<!-- Sent from Reviewable.io -->

2020-12-02 17:58 UTC, brosenberg42 commented
___
*[python/AzureTranslation/README.md, line 50 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/185#-MMqxkLM81P4wL4puplQ:-MNZaLkt2hkIstpYpazZ:b-lyakn5) ([raw file](https://github.com/openmpf/openmpf-components/blob/dec54795af1d7d041c8897cd90b7f169891c9931/python/AzureTranslation/README.md#L50)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

That parameter only applies if language detection fails. I have never seen it fail, so I have never seen the parameter do anything. Even when the text is clearly a cat on a keyboard. For example this request:
```
POST http://example.com/translate?api-version=3.0&to=en&suggestedFrom=es
[
    {"Text":"kfjasdhktgkajdfaks ldjrfdasklraskdmfnasdfnaskdjrhsldkjfasndlkrfjaslkdvnsad;lkrfujmalsdkfjals adkfjalsdkjfa kfjal kdjfaslkdfj llkdjsfa "}
]
```
produces this is response:
```
[
    {
        "detectedLanguage": {
            "language": "en",
            "score": 1.0
        },
        "translations": [
            {
                "text": "kfjasdhktgkajdfaks ldjrfdasklraskdmfnasdfnaskdjrhsldkjfasndlkrfjaslkdvnsad;lkrfujmalsdkfjals adkfjalsdkjfa kfjal kdjfaslkdfj llkdjsfa ",
                "to": "en"
            }
        ]
    }
]
```

</blockquote></details>

Actually, I just realized that may be working as intended. Azure just thinks English speakers can't spell.


<!-- Sent from Reviewable.io -->

2020-12-02 20:02 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/185)* status: 16 of 22 files reviewed, 11 unresolved discussions (waiting on @brosenberg42, @jrobble, and @mcrensh)

___
*[python/AzureTranslation/README.md, line 16 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/185#-MLmnf5OEyZ_C8EWPX2S:-MNZfM1z8kz8ZiERNKOr:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/5afefd5d8688938798020726530b7fe37b23f5a0/python/AzureTranslation/README.md#L16)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I'm looking at the following properties:
- `TEXT (SOURCE LANG)`
- `TEXT (SOURCE LANG CONFIDENCE)`

We use `LANG` above but spell out the whole word in `TRANSLATION TO LANGUAGE`. Let's use the whole word to be consistent within this component and with other components. 
</blockquote></details>

Done.
___
*[python/AzureTranslation/README.md, line 49 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/185#-MMbfeo95ZbC7jA86Jy4:-MNZflxmEWSZgAYoKcKv:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/dec54795af1d7d041c8897cd90b7f169891c9931/python/AzureTranslation/README.md#L49)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I forgot to mention, if we updated this component to return `TRANSLATION` instead of `{prop_name} TRANSLATION` then I could just default Keyword Tagging `FEED_FORWARD_PROPS_TO_PROCESS=TEXT,TRANSCRIPT,TRANSLATION` and we could support a `TESSERACT --> TRANSLATION --> KEYWORD TAGGING` pipeline just as easily as we could support an `ACS SPEECH --> TRANSLATION --> KEYWORD TAGGING` pipeline.

Otherwise, the alternative would be to do `FEED_FORWARD_PROPS_TO_PROCESS=TEXT,TRANSCRIPT,TEXT TRANSLATION,TRANSCRIPT TRANSLATION`. Granted, that's much worse.

Really, this is less about your component and more about promoting a best practice of having components only return one *text-like* finding per detection. What I mean is that if a component needs to return another finding, then it should do what ACS Form Detection is doing, and return it in a different detection. I'd like to keep each detection simple.
</blockquote></details>

Done.
___
*[python/AzureTranslation/README.md, line 55 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/185#-MMr1BY-BHugaoFJHKKw:-MNZbTSn0UJjSMJHDXCY:b-7lxs2a) ([raw file](https://github.com/openmpf/openmpf-components/blob/dec54795af1d7d041c8897cd90b7f169891c9931/python/AzureTranslation/README.md#L55)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

When translation is not actually performed, the JSON output object lacks some of the detection properties. This may confuse third-party consumers. In general, we usually just set those properties to the blank string. I'm fine doing it your way, but we'd need to inform the consumers of this behavior and make sure they are ok with it.
</blockquote></details>

They are ok with it.
___
*[python/AzureTranslation/setup.py, line 32 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/185#-MMbS0Tt4cSz8pp1fuoy:-MNZYcDe0IGOHbhu85W3:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/dec54795af1d7d041c8897cd90b7f169891c9931/python/AzureTranslation/setup.py#L32)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please update the 5.0 version numbers in this file to 5.1.
</blockquote></details>

Done.
___
*[python/AzureTranslation/acs_translation_component/acs_translation_component.py, line 55 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/185#-MMbU3MbEJ_wbgVWk7PY:-MNUvXUTAyARMHPiQSoi:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/dec54795af1d7d041c8897cd90b7f169891c9931/python/AzureTranslation/acs_translation_component/acs_translation_component.py#L55)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

We generally don't provide the job name in the error messages that appear in the JSON output object. One reason is because we don't always have access to the job number depending on where the exception is thrown.

The job number appears in the WFM log already:

```
2020-11-23 18:00:53,910 INFO [Camel (camelContext) thread #45 - JmsConsumer[MPF.COMPLETED_DETECTIONS]] o.m.m.w.d.InProgressBatchJobsService - Adding detection processing error for job 285's media 19: UNSUPPORTED_DATA_TYPE - An error occurred while invoking the "get_detections_from_audio" method on the Python component: ('[Job 285:green.wav(0--1)] Component can only process feed forward jobs, but no feed forward track provided. ', <DetectionError.UNSUPPORTED_DATA_TYPE: 4>)
```
</blockquote></details>

Done.
___
*[python/AzureTranslation/plugin-files/descriptor/descriptor.json, line 3 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/185#-MMqMOsSCkdmW_XEUNhQ:-MNUvne3-nG1E6MW84Gs:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/dec54795af1d7d041c8897cd90b7f169891c9931/python/AzureTranslation/plugin-files/descriptor/descriptor.json#L3)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please update to 5.1.
</blockquote></details>

Done.
___
*[python/AzureTranslation/plugin-files/descriptor/descriptor.json, line 75 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/185#-MMr9euv-OWhu9xvRK6U:-MNZc2xKBkqBVl5zX2e6:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/dec54795af1d7d041c8897cd90b7f169891c9931/python/AzureTranslation/plugin-files/descriptor/descriptor.json#L75)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please call this `AZURE TRANSLATION (WITH FF REGION) ACTION`. Similarly, call the task `AZURE TRANSLATION (WITH FF REGION) TASK`.
</blockquote></details>

Done.
___
*[python/AzureTranslation/plugin-files/descriptor/descriptor.json, line 111 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/185#-MMr1OxS426aOvWad-RM:-MN_24ve1_K2HNLmAOcA:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/dec54795af1d7d041c8897cd90b7f169891c9931/python/AzureTranslation/plugin-files/descriptor/descriptor.json#L111)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please add an example Tesseract --> Translation pipeline to show how feed-forward works with this component. Maybe an EAST --> Tesseract --> Translation pipeline too, unless you think it's overkill. The first would go in the Tesseract descriptor and the second would go in the EAST descriptor.

We should add an example pipeline for speech components as well. I don't think Sphinx is worth it, but I think the others are.

I just tried out an EAST --> Tesseract --> Translation --> Markup pipeline and it worked. It was able to successfully detect and translate the three blocks of text in [this media](https://github.com/openmpf/openmpf-components/blob/master/cpp/TesseractOCRTextDetection/test/data/eng-bul.png) to English. It detected Bulgarian successfully.
</blockquote></details>

Done.
___
*[python/AzureTranslation/tests/test_acs_translation.py, line 298 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/185#-MMqWjDp3N0u7B0b_vs4:-MNZgRBd29WpymhneVqu:bcf9qhr) ([raw file](https://github.com/openmpf/openmpf-components/blob/dec54795af1d7d041c8897cd90b7f169891c9931/python/AzureTranslation/tests/test_acs_translation.py#L298)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I think you mean "two requests" here.
</blockquote></details>

That statement is now accurate.
___
*[python/AzureTranslation/tests/test_acs_translation.py, line 411 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/185#-MMqYTyN8XND5RMOOgqq:-MNZgOhjBfgeUc1Mkebi:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/dec54795af1d7d041c8897c [...]

2020-12-03 03:43 UTC, jrobble commented
___
*[python/AzureTranslation/README.md, line 50 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/185#-MMqxkLM81P4wL4puplQ:-MNaceuL0XfMgXX7CNH9:b-igyw1k) ([raw file](https://github.com/openmpf/openmpf-components/blob/dec54795af1d7d041c8897cd90b7f169891c9931/python/AzureTranslation/README.md#L50)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Actually, I just realized that may be working as intended. Azure just thinks English speakers can't spell.
</blockquote></details>

Lol. I definitely thought of this [cat on a keyboard](https://i.ytimg.com/vi/J---aiyznGQ/hqdefault.jpg).

I was able to get the `SUGGESTED_FROM_LANGUAGE` to do something. I first changed your sample script as follows:

```
    job_props = dict(TO_LANGUAGE=to_lang, ACS_URL=acs_url,
                     ACS_SUBSCRIPTION_KEY=acs_subscription_key,
                     SUGGESTED_FROM_LANGUAGE="zh")
    TranslationClient(job_props).add_translations(detection_props)
    print('Translation: ')
    print(detection_props['TRANSLATION'])
    print(detection_props['SOURCE LANGUAGE'])
    print(detection_props['SOURCE LANGUAGE CONFIDENCE'])
```

Then I ran:

```
(venv) [mpf@openmpf-master AzureTranslation]$ python sample_acs_translator.py <acs_url> <acs_subscription_key> en "1234"
...
2020-12-02 22:25:44,022 INFO  [acs_translation_component.py:183] - Successfully translated the "TEXT" property.
Translation: 
1234ã
zh-Hans
0.0
```

It doesn't appear correctly here, but that translation is "1234.", but the period is the small circle character, the Chinese unicode one.

Regardless, I now realize that `SUGGESTED_FROM_LANGUAGE` should not be paired with `FROM_LANGUAGE`, so disregard my previous comment. 


<!-- Sent from Reviewable.io -->

2020-12-03 19:12 UTC, brosenberg42 commented
___
*[python/AzureTranslation/README.md, line 50 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/185#-MMqxkLM81P4wL4puplQ:-MNe0HvFC3ZEq3rPirHL:bhnhgtt) ([raw file](https://github.com/openmpf/openmpf-components/blob/dec54795af1d7d041c8897cd90b7f169891c9931/python/AzureTranslation/README.md#L50)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Lol. I definitely thought of this [cat on a keyboard](https://i.ytimg.com/vi/J---aiyznGQ/hqdefault.jpg).

I was able to get the `SUGGESTED_FROM_LANGUAGE` to do something. I first changed your sample script as follows:

```
    job_props = dict(TO_LANGUAGE=to_lang, ACS_URL=acs_url,
                     ACS_SUBSCRIPTION_KEY=acs_subscription_key,
                     SUGGESTED_FROM_LANGUAGE="zh")
    TranslationClient(job_props).add_translations(detection_props)
    print('Translation: ')
    print(detection_props['TRANSLATION'])
    print(detection_props['SOURCE LANGUAGE'])
    print(detection_props['SOURCE LANGUAGE CONFIDENCE'])
```

Then I ran:

```
(venv) [mpf@openmpf-master AzureTranslation]$ python sample_acs_translator.py <acs_url> <acs_subscription_key> en "1234"
...
2020-12-02 22:25:44,022 INFO  [acs_translation_component.py:183] - Successfully translated the "TEXT" property.
Translation: 
1234ã
zh-Hans
0.0
```

It doesn't appear correctly here, but that translation is "1234.", but the period is the small circle character, the Chinese unicode one.

Regardless, I now realize that `SUGGESTED_FROM_LANGUAGE` should not be paired with `FROM_LANGUAGE`, so disregard my previous comment. 
</blockquote></details>

![coding-is-ruff.jpg](https://files.reviewableusercontent.io/images/reviewable/5748179/WEJSplHDqMB8ct_w5Dzyu4Ok/coding-is-ruff.jpeg)


<!-- Sent from Reviewable.io -->

2020-12-05 06:59 UTC, jrobble approved these changes
> Reviewed 6 of 6 files at r3, 9 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/185)* status: all files reviewed, 2 unresolved discussions (waiting on @brosenberg42)

___
*[python/AzureTranslation/README.md, line 16 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/185#-MLmnf5OEyZ_C8EWPX2S:-MNaU8Oa-srYuSFC-GzP:bvz6z75) ([raw file](https://github.com/openmpf/openmpf-components/blob/5afefd5d8688938798020726530b7fe37b23f5a0/python/AzureTranslation/README.md#L16)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

After running Speech Detection --> Translation I realized that it's not clear which detection properties are for speech detection and which are for translation, so I made sure to prefix all of the translation detection properties with `TRANSLATION`.

In retrospect, it would be even clearer if we prefixed all of the speech detection output properties with `TRANSCRIPT`, all of the OCR output properties with `TEXT`, etc., but it's too late for that now unless the consumers are willing to update their code.
___
*[python/AzureTranslation/README.md, line 50 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/185#-MMqxkLM81P4wL4puplQ:-MNkhk-n4xH9TbNbVmjd:bq82sci) ([raw file](https://github.com/openmpf/openmpf-components/blob/dec54795af1d7d041c8897cd90b7f169891c9931/python/AzureTranslation/README.md#L50)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

![coding-is-ruff.jpg](https://files.reviewableusercontent.io/images/reviewable/5748179/WEJSplHDqMB8ct_w5Dzyu4Ok/coding-is-ruff.jpeg)
</blockquote></details>

The tie really does it. 

Have you ever seen a score other than 0.0 or 1.0?
___
*[python/AzureTranslation/plugin-files/descriptor/descriptor.json, line 9 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/185#-MNlW__cES1Lr2hOR9HC:-MNlW__cES1Lr2hOR9HD:bq8rmz7) ([raw file](https://github.com/openmpf/openmpf-components/blob/b29dc217ab7a703b159c90abf5c83e30ef5bda4e/python/AzureTranslation/plugin-files/descriptor/descriptor.json#L9)):*
> ```JSON
>   "environmentVariables": [],
>   "algorithm": {
>     "name": "AZURE_TRANSLATION",
> ```

None of the other algorithm names have underscores in their name.
___
*[python/AzureTranslation/plugin-files/descriptor/descriptor.json, line 38 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/185#-MNaVLq6AFPk0kyIOb1o:-MNaVLq6AFPk0kyIOb1p:b-3mszyd) ([raw file](https://github.com/openmpf/openmpf-components/blob/b29dc217ab7a703b159c90abf5c83e30ef5bda4e/python/AzureTranslation/plugin-files/descriptor/descriptor.json#L38)):*
I was going to say:

> Please update Keyword Tagging so that its default value of `FEED_FORWARD_PROP_TO_PROCESS` is `TEXT,TRANSCRIPT,TRANSLATION`.

However, it occurs to me that if someone wants to create a pipeline that performs keyword tagging on translation output then they would only want that property to have a value of `TRANSLATION`. Otherwise, it would tag the un-translated `TEXT` or `TRANSCRIPT`. Therefore, they would need to create a custom Keyword Tagging action (and task) to do that.

I'm not asking you to do anything here. Just mentioning something I realized.


<!-- Sent from Reviewable.io -->

2020-12-05 07:16 UTC, jrobble requested changes
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/185)* status: all files reviewed, 2 unresolved discussions (waiting on @brosenberg42)

___
*[python/AzureTranslation/plugin-files/descriptor/descriptor.json, line 38 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/185#-MNaVLq6AFPk0kyIOb1o:-MNli5pzDuaPXoXzGLt3:b-v2wifp) ([raw file](https://github.com/openmpf/openmpf-components/blob/b29dc217ab7a703b159c90abf5c83e30ef5bda4e/python/AzureTranslation/plugin-files/descriptor/descriptor.json#L38)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I was going to say:

> Please update Keyword Tagging so that its default value of `FEED_FORWARD_PROP_TO_PROCESS` is `TEXT,TRANSCRIPT,TRANSLATION`.

However, it occurs to me that if someone wants to create a pipeline that performs keyword tagging on translation output then they would only want that property to have a value of `TRANSLATION`. Otherwise, it would tag the un-translated `TEXT` or `TRANSCRIPT`. Therefore, they would need to create a custom Keyword Tagging action (and task) to do that.

I'm not asking you to do anything here. Just mentioning something I realized.
</blockquote></details>

Thinking about this more, putting `TRANSLATION` first, as in `TRANSLATION,TEXT,TRANSCRIPT` works. I pushed a commit for this. 


<!-- Sent from Reviewable.io -->

2020-12-05 07:19 UTC, jrobble approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/185)* status: all files reviewed, 2 unresolved discussions (waiting on @brosenberg42)



<!-- Sent from Reviewable.io -->

2020-12-07 18:44 UTC, jrobble approved these changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/185)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42)



<!-- Sent from Reviewable.io -->

2020-12-07 19:30 UTC, merged