Adding Tesseract src files and custom MPF program for updating *.trai…
openmpf/openmpf-components pull request #209
Opened 2020-12-07 02:27 UTC by hhuangMITRE

…neddata models. Adding instructions to README.

2020-12-14 16:42 UTC, jrobble commented
___
*[cpp/TesseractOCRTextDetection/model_updater_tesseract_src/adaptive.h, line 7 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOX2GeF9lcFLzlhhSis:-MOX2GeF9lcFLzlhhSit:b-sbmir1) ([raw file](https://github.com/openmpf/openmpf-components/blob/bdbceabd81b2cc60439b55a73a720145ee44a355/cpp/TesseractOCRTextDetection/model_updater_tesseract_src/adaptive.h#L7)):*
> ```objc
>  ** History:    Fri Mar  8 10:00:49 1991, DSJ, Created.
>  **
>  ** (c) Copyright Hewlett-Packard Company, 1988.
> ```

How much of the code in this dir did you modify, if any?


<!-- Sent from Reviewable.io -->

2020-12-14 16:58 UTC, hhuangMITRE reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/209)* status: 0 of 145 files reviewed, 1 unresolved discussion (waiting on @brosenberg42 and @jrobble)

___
*[cpp/TesseractOCRTextDetection/model_updater_tesseract_src/adaptive.h, line 7 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOX2GeF9lcFLzlhhSis:-MOXAQZ2-nX1fDel8NJC:b-itu211) ([raw file](https://github.com/openmpf/openmpf-components/blob/bdbceabd81b2cc60439b55a73a720145ee44a355/cpp/TesseractOCRTextDetection/model_updater_tesseract_src/adaptive.h#L7)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

How much of the code in this dir did you modify, if any?
</blockquote></details>

Code within the `model_updater_tesseract_src` directory  is an unmodified copy of tesseract source files.


<!-- Sent from Reviewable.io -->

2020-12-15 03:44 UTC, jrobble requested changes
@hhuangmitre , for posterity, I remember that you mentioned that you need to do the following:
- Add unit tests.
- Fix sample binary by removing  tagging behavior.

> Reviewed 53 of 145 files at r1.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/209#-:-MOX7ejG9NelUoxFyUwn:b-2wpyc7)* status: 53 of 145 files reviewed, 14 unresolved discussions (waiting on @brosenberg42, @hhuangMITRE, and @jrobble)

___
*[cpp/TesseractOCRTextDetection/CMakeLists.txt, line 77 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOX3YYo59avgY_TXk3_:-MOX3YYo59avgY_TXk3a:b6brb6s) ([raw file](https://github.com/openmpf/openmpf-components/blob/bdbceabd81b2cc60439b55a73a720145ee44a355/cpp/TesseractOCRTextDetection/CMakeLists.txt#L77)):*
> ```CMake
> 
> # Build executable
> add_executable              (mpf_tessdata_model_updater mpf_tessdata_model_updater.cpp)
> ```

Consider removing the "mpf" prefix, unless you think that a user will confuse the binary with something that's normally provided as part of Tesseract. Note that the component sample binary doesn't have the mpf prefix.
___
*[cpp/TesseractOCRTextDetection/mpf_tessdata_model_updater.cpp, line 532 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOZQ-Tn9jIRYSGjwIFr:-MOZQ-Tn9jIRYSGjwIFs:b-6ndwv1) ([raw file](https://github.com/openmpf/openmpf-components/blob/bdbceabd81b2cc60439b55a73a720145ee44a355/cpp/TesseractOCRTextDetection/mpf_tessdata_model_updater.cpp#L532)):*
> ```cpp
>     return updated_models;
> }
> ```

Wow. This utility is quite full featured! Good stuff.

The usage statement is quite verbose. I found myself purposefully executing the binary to print out this usage for reference. That said, I think a user is better served by putting all of this information in the README. You can keep most of it here as well, but consider shortening it up and keeping the examples and detailed information for the README only.

Also, consider dividing that section of the README into at least two subsections. One for inspecting (extracting) files, and one for updating (creating) new files, each with their respective commands.

After the sections which explain the commands independently, consider providing a realistic step-by-step walkthrough in the README with the exact commands and full file list of each directory. The walkthrough could go through the process of taking an existing eng traineddata file, extracting it, generating the word list from the DAWG file, writing a new word list, combining it with the existing one, generating the new DAWG, and then generating the new traineddata file. After all that, then you can show the user how to do it the short way. I think that will help alleviate the mental burden of figuring out how to chain everything together.
___
*[cpp/TesseractOCRTextDetection/mpf_tessdata_model_updater.cpp, line 569 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOZIRofBes1qASBybaK:-MOX6uBLD1cl0d5ApMGg:bfk3qgh) ([raw file](https://github.com/openmpf/openmpf-components/blob/bdbceabd81b2cc60439b55a73a720145ee44a355/cpp/TesseractOCRTextDetection/mpf_tessdata_model_updater.cpp#L569)):*
> ```cpp
>     } else {
> 
>         printf("\n\nUsage for updating all models in target directory "
> ```

I might be doing something wrong, but I was not able to get the `-u` command to work. First I created a new `eng.word-dawg` file and placed it in an `updated` dir.

```
tree --charset=ascii tessdata updated output

tessdata
`-- eng.traineddata
updated
|-- eng.unicharset
`-- eng.word-dawg
output
```

Then I ran the update command:

```
mpf_tessdata_model_updater -u tessdata updated output

Adding lang: eng
Adding model file: updated/eng.unicharset
Adding dawg model file: updated/eng.word-dawg
...
```

Then I inspected the output:

```
tree --charset=ascii tessdata updated output

tessdata
`-- eng.traineddata
updated
|-- eng.unicharset
`-- eng.word-dawg
output
`-- eng.traineddata
```

```
cd output

mkdir extracted

mpf_tessdata_model_updater -e eng.traineddata extracted/eng

cd extracted

mpf_tessdata_model_updater -dw eng.unicharset eng.word-dawg eng.word-dawg.txt
```

I compared this `eng.word-dawg.txt` with that I pulled from `updated/eng.word-dawg`. The former lacks the two new words I added to the latter.
___
*[cpp/TesseractOCRTextDetection/mpf_tessdata_model_updater.cpp, line 576 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOX6hViBzDvT9C27Wbt:-MOX6hVj7Sxf1eMFQxzl:b-fdtgsh) ([raw file](https://github.com/openmpf/openmpf-components/blob/bdbceabd81b2cc60439b55a73a720145ee44a355/cpp/TesseractOCRTextDetection/mpf_tessdata_model_updater.cpp#L576)):*
> ```cpp
> 
>         printf("  NOTE: When updating model DAWG dictionary files, users can add new words\n"
>                "  to the respective model by naming their text-formatted word list after the target DAWG file\n"
> ```

Use period at end.
___
*[cpp/TesseractOCRTextDetection/mpf_tessdata_model_updater.cpp, line 577 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOX6juABOyVam8Vtfpk:-MOX6juABOyVam8Vtfpl:b-rin28p) ([raw file](https://github.com/openmpf/openmpf-components/blob/bdbceabd81b2cc60439b55a73a720145ee44a355/cpp/TesseractOCRTextDetection/mpf_tessdata_model_updater.cpp#L577)):*
> ```cpp
>         printf("  NOTE: When updating model DAWG dictionary files, users can add new words\n"
>                "  to the respective model by naming their text-formatted word list after the target DAWG file\n"
>                "  Other model files will be simply replaced with the newer version.\n\n"
> ```

Change "Other model files" to "Non-DAWG files" for clarity.
___
*[cpp/TesseractOCRTextDetection/mpf_tessdata_model_updater.cpp, line 580 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOX7-Iv4IsyhFqCpRt1:-MOX7-Iv4IsyhFqCpRt2:b2c3w8e) ([raw file](https://github.com/openmpf/openmpf-components/blob/bdbceabd81b2cc60439b55a73a720145ee44a355/cpp/TesseractOCRTextDetection/mpf_tessdata_model_updater.cpp#L580)):*
> ```cpp
>                "  Example: updated_eng_dawgs_dir/eng.word-dawg -> "
>                "will be added to eng.traineddata's existing word dict.\n"
>                "  Example: updated_eng_dawgs_dir/eng.unicharset -> "
> ```

When I saw this as a separate "Example" I first thought it was related to a separate execution of the `-u` command line usage. What you're really saying is that it's just another file affected by the same command. Please clarify.
___
*[cpp/TesseractOCRTextDetection/mpf_tessdata_model_updater.cpp, line 583 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOX56kD8uXpru5YBHfe:-MOX56kD8uXpru5YBHff:b-itrq8) ([raw file](https://github.com/openmpf/openmpf-components/blob/bdbceabd81b2cc60439b55a73a720145ee44a355/cpp/TesseractOCRTextDetection/mpf_tessdata_model_updater.cpp#L583)):*
> ```cpp
>                "will replace unicharset file in eng.traineddata.\n"
>                "  It will also replace the original eng.unicharset file when translating and adding new wordlists.\n\n\n",
>                argv[0], argv[0]);
> ```

The last two parameters are not used here.
___
*[cpp/TesseractOCRTextDetection/mpf_tessdata_model_updater.cpp, line 585 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOYCkfX29bJP3j9S1uZ:-MOYCkfY40x24k5HttyI:b9madgx) ([raw file](https://github.com/openmpf/openmpf-components/blob/bdbceabd81b2cc60439b55a73a720145ee44a355/cpp/TesseractOCRTextDetection/mpf_tessdata_model_updater.cpp#L585)):*
> ```cpp
>                argv[0], argv[0]);
> 
>         printf("Usage for combining tessdata components:\n"
> ```

State that the example will generate `tessdata/eng.traineddata`.

Also, consider dropping the period so it's just ` (e.g. %s tessdata/eng)`. I don't think the period is necessary.
___
*[cpp/TesseractOCRTextDetection/mpf_tessdata_model_updater.cpp, line 594 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOYAoD53cCuBrV4UM1s:-MOYAoD5 [...]

2020-12-15 03:57 UTC, jrobble requested changes
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/209)* status: 53 of 145 files reviewed, 15 unresolved discussions (waiting on @brosenberg42 and @hhuangMITRE)

___
*[cpp/TesseractOCRTextDetection/mpf_tessdata_model_updater.cpp, line 106 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOZVbqhDsSWd91Z3qZE:-MOZVbqhDsSWd91Z3qZF:b-hxmtyq) ([raw file](https://github.com/openmpf/openmpf-components/blob/bdbceabd81b2cc60439b55a73a720145ee44a355/cpp/TesseractOCRTextDetection/mpf_tessdata_model_updater.cpp#L106)):*
> ```cpp
> void MPF_Model_Updater::extractLangModel(std::string path_to_model, std::string output_prefix) {
>     tesseract::CheckSharedLibraryVersion();
>     int i;
> ```

This variable is never used.
___
*[cpp/TesseractOCRTextDetection/model_updater_tesseract_src/adaptive.h, line 7 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOX2GeF9lcFLzlhhSis:-MOZWQQWCXFkx7LgmNQY:bnld2cd) ([raw file](https://github.com/openmpf/openmpf-components/blob/bdbceabd81b2cc60439b55a73a720145ee44a355/cpp/TesseractOCRTextDetection/model_updater_tesseract_src/adaptive.h#L7)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

Code within the `model_updater_tesseract_src` directory  is an unmodified copy of tesseract source files.
</blockquote></details>

Ok. How concerned are you that traineddata files generated using this code may one day no longer be compatible with the Tesseract framework?

For example I know you're going to update version of Tesseract. How can we easily determine if that requires updating these files? Is there some kind of unit test we can write that will fail if and when that time comes?

Maybe I'm being too paranoid. When was the last time this code changed in the Tesseract project?


<!-- Sent from Reviewable.io -->

2020-12-15 04:36 UTC, hhuangMITRE reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/209)* status: 53 of 145 files reviewed, 15 unresolved discussions (waiting on @brosenberg42 and @hhuangMITRE)

___
*[cpp/TesseractOCRTextDetection/model_updater_tesseract_src/adaptive.h, line 7 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOX2GeF9lcFLzlhhSis:-MOXBCVK6C2wl2pzF_fm:b-i134dv) ([raw file](https://github.com/openmpf/openmpf-components/blob/bdbceabd81b2cc60439b55a73a720145ee44a355/cpp/TesseractOCRTextDetection/model_updater_tesseract_src/adaptive.h#L7)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Ok. How concerned are you that traineddata files generated using this code may one day no longer be compatible with the Tesseract framework?

For example I know you're going to update version of Tesseract. How can we easily determine if that requires updating these files? Is there some kind of unit test we can write that will fail if and when that time comes?

Maybe I'm being too paranoid. When was the last time this code changed in the Tesseract project?
</blockquote></details>

Hey Jeff,

That's a good question. The `mpf_tessdata_model_updater.cpp` code was based off the following training executables:

- Most important (updates tessdata model files): 
`combine_lang_model.cpp` - Last updated two years ago.

- Converting between dawgs and text files:
`dawg2wordlist.cpp` - Last updated one year, two months ago.
`wordlist2dawg.cpp` - Last updated one year, two months ago.

It seems that `combine_lang_model.cpp` is updated infrequently, possibly due to the fact that the tessdata models are also infrequently updated (many *.traineddata files last updated 3 years ago). 

A unit test we can create to ensure that all three parts of `mpf_tessdata_model_updater.cpp` is:

1. Updating the `eng.word-dawg` file in `eng.traineddata` (or use a `custom.traineddata` with a shortened wordlist for simplicity).  
2. Extract out model files from updated `eng.traineddata` using our binary.
3. Confirm that wordlist has been properly updated/replaced. 

This would ensure that the dawg-text conversion and the combine lang model parts are working as expected. Let me know what you think, thanks!

I'm submitting the unit tests shortly to the PR.


<!-- Sent from Reviewable.io -->

2020-12-15 15:34 UTC, hhuangMITRE reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/209)* status: 51 of 150 files reviewed, 15 unresolved discussions (waiting on @brosenberg42, @hhuangMITRE, and @jrobble)

___
*[cpp/TesseractOCRTextDetection/mpf_tessdata_model_updater.cpp, line 569 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOZIRofBes1qASBybaK:-MOazqAmDYAE4UGZXO9g:bze1gi8) ([raw file](https://github.com/openmpf/openmpf-components/blob/bdbceabd81b2cc60439b55a73a720145ee44a355/cpp/TesseractOCRTextDetection/mpf_tessdata_model_updater.cpp#L569)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I might be doing something wrong, but I was not able to get the `-u` command to work. First I created a new `eng.word-dawg` file and placed it in an `updated` dir.

```
tree --charset=ascii tessdata updated output

tessdata
`-- eng.traineddata
updated
|-- eng.unicharset
`-- eng.word-dawg
output
```

Then I ran the update command:

```
mpf_tessdata_model_updater -u tessdata updated output

Adding lang: eng
Adding model file: updated/eng.unicharset
Adding dawg model file: updated/eng.word-dawg
...
```

Then I inspected the output:

```
tree --charset=ascii tessdata updated output

tessdata
`-- eng.traineddata
updated
|-- eng.unicharset
`-- eng.word-dawg
output
`-- eng.traineddata
```

```
cd output

mkdir extracted

mpf_tessdata_model_updater -e eng.traineddata extracted/eng

cd extracted

mpf_tessdata_model_updater -dw eng.unicharset eng.word-dawg eng.word-dawg.txt
```

I compared this `eng.word-dawg.txt` with that I pulled from `updated/eng.word-dawg`. The former lacks the two new words I added to the latter.
</blockquote></details>

I've identified a potential fix for updating dawg files and will submit the update with the rest of the changes today. Tesseract training scripts use Tesseract::Trie to hold and store unicode strings from the wordlists during dawg-wordlist conversion. 

I'm updating `void MPF_Model_Updater::addWordListToDawg` to use `Tesseract::Trie` rather than `std::set<std::string>` to store and combine wordlist +dawgs. Submitting fix with the rest of the PR requested changes (+ discussed unit test)  today.


<!-- Sent from Reviewable.io -->

2020-12-16 23:01 UTC, jrobble commented
___
*[cpp/TesseractOCRTextDetection/sample_tesseract_ocr_detector.cpp, line 136 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOdhyXW-Ivvjn98vjaV:-MOdhyXW-Ivvjn98vjaW:b-v9mpb7) ([raw file](https://github.com/openmpf/openmpf-components/blob/dc48c806990075988f35ef59a206424241c72ca5/cpp/TesseractOCRTextDetection/sample_tesseract_ocr_detector.cpp#L136)):*
> ```cpp
>         Properties media_properties;
>         std::string job_name("OCR_test");
>         algorithm_properties["TAGGING_FILE"] = "text-tags.json";
> ```

Remove `TAGGING_FILE`.


<!-- Sent from Reviewable.io -->

2020-12-17 20:21 UTC, hhuangMITRE reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/209)* status: 49 of 151 files reviewed, 16 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[cpp/TesseractOCRTextDetection/CMakeLists.txt, line 77 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOX3YYo59avgY_TXk3_:-MOmG_Fg2rAkVuXAYjUr:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/bdbceabd81b2cc60439b55a73a720145ee44a355/cpp/TesseractOCRTextDetection/CMakeLists.txt#L77)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Consider removing the "mpf" prefix, unless you think that a user will confuse the binary with something that's normally provided as part of Tesseract. Note that the component sample binary doesn't have the mpf prefix.
</blockquote></details>

Done.
___
*[cpp/TesseractOCRTextDetection/README.md, line 66 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOX1aiP5Qz0txQO0ltJ:-MOmGedHCcTaPb8P_1l3:b-aa7l24) ([raw file](https://github.com/openmpf/openmpf-components/blob/bdbceabd81b2cc60439b55a73a720145ee44a355/cpp/TesseractOCRTextDetection/README.md#L66)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please use `<  >` around required arguments in the usage. Use `[ ]` around optional arguments. If you `man` something you'll notice that square brackets are for optional things.

This should be:

```
build_dir/mpf_tessdata_model_updater -u <ORIGINAL_TESSDATA_MODEL_DIR> <UPDATED_DICT_FILES_DIR> <UPDATED_MODEL_DIR>
```

As shown above, please change `UPDATED_DICT_FILES` to `UPDATED_DICT_FILES_DIR`.
</blockquote></details>

Done! Also thanks for the `man` example. I was using the sample binary as reference but got the brackets mixed up.
___
*[cpp/TesseractOCRTextDetection/README.md, line 72 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOX0hEU-bwdJAWYX2gR:-MOmHXEo5cOX7P3ZJjbl:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/bdbceabd81b2cc60439b55a73a720145ee44a355/cpp/TesseractOCRTextDetection/README.md#L72)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Change to "Will contain the updated ..."
</blockquote></details>

Done.
___
*[cpp/TesseractOCRTextDetection/sample_tesseract_ocr_detector.cpp, line 136 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOdhyXW-Ivvjn98vjaV:-MOmH_Tz9kMu3NJr9DPR:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/dc48c806990075988f35ef59a206424241c72ca5/cpp/TesseractOCRTextDetection/sample_tesseract_ocr_detector.cpp#L136)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Remove `TAGGING_FILE`.
</blockquote></details>

Done.
___
*[cpp/TesseractOCRTextDetection/model_updater_tesseract_src/adaptive.h, line 7 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOZS-ZjEiFCQGftv-1T:-MOmLXji3Hqc_KCSAlxl:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/bdbceabd81b2cc60439b55a73a720145ee44a355/cpp/TesseractOCRTextDetection/model_updater_tesseract_src/adaptive.h#L7)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Update the following section of the top-level component `LICENSE` file:

```
 --------------------------------------------------------------------------

 The "Tesseract OCR" project is licensed under the Apache 2.0 License.

 Some portions copyright Hewlett-Packard Company.
 Some portions copyright Google Inc.
 
 --------------------------------------------------------------------------
```



</blockquote></details>

Done.
___
*[cpp/TesseractOCRTextDetection/model_updater_tesseract_src/adaptive.h, line 7 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOX2GeF9lcFLzlhhSis:-MOmLYM52WhD7mxbWphm:bffrvpe) ([raw file](https://github.com/openmpf/openmpf-components/blob/bdbceabd81b2cc60439b55a73a720145ee44a355/cpp/TesseractOCRTextDetection/model_updater_tesseract_src/adaptive.h#L7)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I'm concerned that we might be able to use your tool to create a traineddata file that is no longer valid for the version of Tesseract we're using, so for a test I was thinking about creating a new traineddata file using your tool and then making sure it can actually be used to OCR something.

I like1-3 above, but I would also add a fourth step that uses the file to OCR something simple, if possible, in a way that can validate that our change to the file actually does something.
</blockquote></details>

Yep, I've added in the unit test that updates the eng.traineddat model, checks to ensure the newly added word exists, and that the OCR job now properly OCR's the word when an ambiguous case exists ( "Illl" vs "llll"  example). After extensive testing, it seems that the behavior change is most noticeable for the legacy engine. I think we should also mention this to Leah and in the README notes as well.  
___
*[cpp/TesseractOCRTextDetection/mpf_tessdata_model_updater.cpp, line 106 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOZVbqhDsSWd91Z3qZE:-MOmHbwXDPLnO9TpprSN:b-jwe7p2) ([raw file](https://github.com/openmpf/openmpf-components/blob/bdbceabd81b2cc60439b55a73a720145ee44a355/cpp/TesseractOCRTextDetection/mpf_tessdata_model_updater.cpp#L106)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

This variable is never used.
</blockquote></details>

Removed, thanks. 
___
*[cpp/TesseractOCRTextDetection/mpf_tessdata_model_updater.cpp, line 532 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOZQ-Tn9jIRYSGjwIFr:-MOmHg5e8LF1FSCHq8Rx:b-e9h7jd) ([raw file](https://github.com/openmpf/openmpf-components/blob/bdbceabd81b2cc60439b55a73a720145ee44a355/cpp/TesseractOCRTextDetection/mpf_tessdata_model_updater.cpp#L532)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Wow. This utility is quite full featured! Good stuff.

The usage statement is quite verbose. I found myself purposefully executing the binary to print out this usage for reference. That said, I think a user is better served by putting all of this information in the README. You can keep most of it here as well, but consider shortening it up and keeping the examples and detailed information for the README only.

Also, consider dividing that section of the README into at least two subsections. One for inspecting (extracting) files, and one for updating (creating) new files, each with their respective commands.

After the sections which explain the commands independently, consider providing a realistic step-by-step walkthrough in the README with the exact commands and full file list of each directory. The walkthrough could go through the process of taking an existing eng traineddata file, extracting it, generating the word list from the DAWG file, writing a new word list, combining it with the existing one, generating the new DAWG, and then generating the new traineddata file. After all that, then you can show the user how to do it the short way. I think that will help alleviate the mental burden of figuring out how to chain everything together.
</blockquote></details>

Thanks for the feedback! I am updating the README now to provide a full example and simplifying the binary usage statement, but in the meantime I'm including all other requested PR changes. There is another issue I wanted to discuss regarding updated DAWG files that I also want to mention in the current README.
___
*[cpp/TesseractOCRTextDetection/mpf_tessdata_model_updater.cpp, line 569 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOZIRofBes1qASBybaK:-MOmI2JS86eZD_PlKb7E:b-3od328) ([raw file](https://github.com/openmpf/openmpf-components/blob/bdbceabd81b2cc60439b55a73a720145ee44a355/ [...]

2020-12-18 04:09 UTC, jrobble requested changes
> Reviewed 92 of 145 files at r1, 1 of 7 files at r2, 5 of 8 files at r3, 1 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/209)* status: 147 of 153 files reviewed, 9 unresolved discussions (waiting on @brosenberg42, @hhuangMITRE, and @jrobble)

___
*[cpp/TesseractOCRTextDetection/Dockerfile, line 84 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOnsLR690QpQQFzZuS6:-MOnsLR77XNYRE1QdBqu:b-n7bf6) ([raw file](https://github.com/openmpf/openmpf-components/blob/1bcd510bc67877c958430fec392f935a13aea105/cpp/TesseractOCRTextDetection/Dockerfile#L84)):*
> ```Dockerfile
>                             $PLUGINS_DIR/TesseractOCRTextDetection/lib/
> 
> COPY --from=build_component $BUILD_DIR/tessdata_model_updater \
> ```

TODO: `docker exec` this.
___
*[cpp/TesseractOCRTextDetection/sample_tesseract_ocr_detector.cpp, line 59 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOdi3zJ2KjFtmBLB2Cg:-MOdi3zJ2KjFtmBLB2Ch:bp4ogj3) ([raw file](https://github.com/openmpf/openmpf-components/blob/dc48c806990075988f35ef59a206424241c72ca5/cpp/TesseractOCRTextDetection/sample_tesseract_ocr_detector.cpp#L59)):*
> ```cpp
>                  " whenever OSD returns successful predictions and can be left out." << std::endl << std::endl;
> 
>     std::cout << "Usage w/ OEM: " << argv[0] <<
> ```

TODO: Look at usage print out.
___
*[cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp, line 205 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOdh7O289LkdCbqc8bs:-MOdh7O289LkdCbqc8bt:b-o5cx5a) ([raw file](https://github.com/openmpf/openmpf-components/blob/dc48c806990075988f35ef59a206424241c72ca5/cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp#L205)):*
> ```cpp
>  * @param output_wordset - Output word vector.
>  */
> void addToWordList(const std::string &wordlist_file,
> ```

TODO: Run this locally.
___
*[cpp/TesseractOCRTextDetection/test/data/new-word.png, line 0 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOdhGOA7ePBqHm555DZ:-MOdhGOA7ePBqHm555D_:by8n5jn) ([raw file](https://github.com/openmpf/openmpf-components/blob/dc48c806990075988f35ef59a206424241c72ca5/cpp/TesseractOCRTextDetection/test/data/new-word.png#L0)):*
TODO: Look at this.
___
*[cpp/TesseractOCRTextDetection/mpf_tessdata_model_updater.cpp, line 616 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOdho512f7Hpl35fOr5:-MOdho522JIimT4-KChH:b-iuuhf1) ([raw file](https://github.com/openmpf/openmpf-components/blob/dc48c806990075988f35ef59a206424241c72ca5/cpp/TesseractOCRTextDetection/mpf_tessdata_model_updater.cpp#L616)):*
> ```cpp
>                argv[0], argv[0]);
> 
>         printf(" NOTE: If users wish to replace the entire word dictionary with a new word dictionary: \n"
> ```

TODO: Test this.
___
*[cpp/TesseractOCRTextDetection/tessdata_model_updater.cpp, line 694 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOmlEK4C7dBYCVekhBi:-MOmlEK4C7dBYCVekhBj:b-gm2rti) ([raw file](https://github.com/openmpf/openmpf-components/blob/e8b6a53571001df56dd07163367f057ea391b961/cpp/TesseractOCRTextDetection/tessdata_model_updater.cpp#L694)):*
> ```cpp
>         printf("Usage for converting word list text files back to DAWG files:\n"
>                "  %s -wd traineddata_unicharset_file wordlist_text_file traineddata_dawg_file\n"
>                "  (e.g. %s -dw eng.unicharset english_wordlist.txt eng.word-dawg)\n\n",
> ```

Use `-wd` here as well.
___
*[cpp/TesseractOCRTextDetection/tessdata_model_updater.cpp, line 75 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOo-QU70t-6BinYjoB_:-MOo-QU70t-6BinYjoBa:b6gxfnt) ([raw file](https://github.com/openmpf/openmpf-components/blob/1bcd510bc67877c958430fec392f935a13aea105/cpp/TesseractOCRTextDetection/tessdata_model_updater.cpp#L75)):*
> ```cpp
>  * @param directory - Base path for random temporary subdirectory.
>  */
> TempRandomDirectory::TempRandomDirectory(const std::string &directory, const std::string &append = "/tmp-%"){
> ```

A better variable name might be `prefix`.
___
*[cpp/TesseractOCRTextDetection/test/data/tessdata_dict_file/eng.word-dawg, line 1 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOdhJFv5Xw24xjegmhQ:-MOdhJFv5Xw24xjegmhR:bht3blb) ([raw file](https://github.com/openmpf/openmpf-components/blob/dc48c806990075988f35ef59a206424241c72ca5/cpp/TesseractOCRTextDetection/test/data/tessdata_dict_file/eng.word-dawg#L1)):*
> ```
> Illldyxne
> ```

TODO: Decode this.


<!-- Sent from Reviewable.io -->

2020-12-18 17:28 UTC, hhuangMITRE reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/209)* status: 144 of 153 files reviewed, 9 unresolved discussions (waiting on @brosenberg42, @hhuangMITRE, and @jrobble)

___
*[cpp/TesseractOCRTextDetection/tessdata_model_updater.cpp, line 694 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOmlEK4C7dBYCVekhBi:-MOqtFkr45N9J1LBbvSA:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/e8b6a53571001df56dd07163367f057ea391b961/cpp/TesseractOCRTextDetection/tessdata_model_updater.cpp#L694)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Use `-wd` here as well.
</blockquote></details>

Done.
___
*[cpp/TesseractOCRTextDetection/tessdata_model_updater.cpp, line 75 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOo-QU70t-6BinYjoB_:-MOqtCboBD8ewJ1DNf2O:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/1bcd510bc67877c958430fec392f935a13aea105/cpp/TesseractOCRTextDetection/tessdata_model_updater.cpp#L75)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

A better variable name might be `prefix`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-18 23:02 UTC, jrobble requested changes
> Reviewed 1 of 7 files at r2, 2 of 4 files at r5, 1 of 1 files at r9, 1 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/209)* status: 148 of 154 files reviewed, 11 unresolved discussions (waiting on @brosenberg42, @hhuangMITRE, and @jrobble)

___
*[cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp, line 205 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOdh7O289LkdCbqc8bs:-MOo9Ag3DY4Kvde-Mm9I:b-7nvgzs) ([raw file](https://github.com/openmpf/openmpf-components/blob/dc48c806990075988f35ef59a206424241c72ca5/cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp#L205)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

TODO: Run this locally.
</blockquote></details>

I would call this `loadWordList` for clarity.
___
*[cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp, line 68 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOo5-ZX84CQZzEtGTTe:-MOo5-ZX84CQZzEtGTTf:b-95fjmb) ([raw file](https://github.com/openmpf/openmpf-components/blob/1bcd510bc67877c958430fec392f935a13aea105/cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp#L68)):*
> ```cpp
>  * @param uri - Path to existing input media.
>  * @param custom - Custom job properties to run for job.
>  * @wild_mode - Sets the expected text type for image OCR runs (structured vs unstructured "wild" text).
> ```

Missing `@param`. Should we be documenting return types as well?

TBH, I don't think that documenting functions is necessary unless it's not intuitive what the function is doing or what the inputs are. Too much documentation clutters the code. I'm not saying you should remove these; I just want to save you some trouble if you feel the need to document everything.
___
*[cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp, line 112 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOo5G9p4sp7wwPOyV7t:-MOo5G9p4sp7wwPOyV7u:b-lg6v5h) ([raw file](https://github.com/openmpf/openmpf-components/blob/1bcd510bc67877c958430fec392f935a13aea105/cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp#L112)):*
> ```cpp
>                        std::vector<MPFImageLocation> &image_locations,
>                        const std::map<std::string, std::string> &custom = {},
>                        bool wild_mode = false) {
> ```

Missing `@param` for `wild_mode`.
___
*[cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp, line 121 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOo6z1P4Ab1avGSiKTB:-MOo6z1P4Ab1avGSiKTC:b-m8xxm6) ([raw file](https://github.com/openmpf/openmpf-components/blob/1bcd510bc67877c958430fec392f935a13aea105/cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp#L121)):*
> ```cpp
>  * Helper function for running given generic job. Checks if job results is not empty.
>  *
>  * @param doc_path - Path of given document.
> ```

`image_path` is used below. You should probably change the name of that variable in the code.
___
*[cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp, line 146 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOo77K0EF8sCk6wAy3J:-MOo77K0EF8sCk6wAy3K:b-lg6v5h) ([raw file](https://github.com/openmpf/openmpf-components/blob/1bcd510bc67877c958430fec392f935a13aea105/cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp#L146)):*
> ```cpp
>                           std::vector<MPFImageLocation> &image_locations,
>                           const std::map<std::string, std::string> &custom = {},
>                           bool wild_mode = false, MPFDetectionError error = MPF_DETECTION_SUCCESS) {
> ```

Missing `@param` for `wild_mode`.
___
*[cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp, line 292 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOo8DnC9dXY4OD-pDke:-MOo8DnC9dXY4OD-pDkf:b-rdhp5g) ([raw file](https://github.com/openmpf/openmpf-components/blob/1bcd510bc67877c958430fec392f935a13aea105/cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp#L292)):*
> ```cpp
>  *
>  * @param wordlist_file - Path of word list.
>  * @param output_wordset - Output word vector.
> ```

It's a set, not a vector.
___
*[cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp, line 318 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOoFeq61gMGHW0JN53O:-MOoFeq61gMGHW0JN53P:brdloop) ([raw file](https://github.com/openmpf/openmpf-components/blob/1bcd510bc67877c958430fec392f935a13aea105/cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp#L318)):*
> ```cpp
>     boost::filesystem::create_directories("data/model_dir/TesseractOCRTextDetection/extracted_lang");
> 
>      /* TODO: IF possible identify why wordlist-to-dawg conversion step shrinks down the original wordlist.
> ```

Indentation is off.
___
*[cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp, line 318 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOoFiff2l3OYKvmqhpG:-MOoFiff2l3OYKvmqhpH:brh2kbz) ([raw file](https://github.com/openmpf/openmpf-components/blob/1bcd510bc67877c958430fec392f935a13aea105/cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp#L318)):*
> ```cpp
>     boost::filesystem::create_directories("data/model_dir/TesseractOCRTextDetection/extracted_lang");
> 
>      /* TODO: IF possible identify why wordlist-to-dawg conversion step shrinks down the original wordlist.
> ```

Caps: "IF"


<!-- Sent from Reviewable.io -->

2020-12-18 23:03 UTC, jrobble reviewed
> Reviewed 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/209)* status: 149 of 154 files reviewed, 10 unresolved discussions (waiting on @brosenberg42, @hhuangMITRE, and @jrobble)



<!-- Sent from Reviewable.io -->

2020-12-18 23:26 UTC, jrobble requested changes
> Reviewed 1 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/209)* status: 150 of 154 files reviewed, 13 unresolved discussions (waiting on @brosenberg42, @hhuangMITRE, and @jrobble)

___
*[cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp, line 409 at r10](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOs9k2c3cky1Km-ooRX:-MOs9k2c3cky1Km-ooRY:bl1msvn) ([raw file](https://github.com/openmpf/openmpf-components/blob/9f8e6eca0dc685afec1b02d7aadccc4dd3531f7e/cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp#L409)):*
> ```cpp
> 
> 
>     ASSERT_TRUE(reference_wordset.size() == updated_wordset.size()) << "Eng model not properly updated. " <<
> ```

Should we do this assert for LSTM? If not, leave a comment explaining why.
___
*[cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp, line 412 at r10](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOs9oLc961wp-yS--cJ:-MOs9oLc961wp-yS--cK:bl1msvn) ([raw file](https://github.com/openmpf/openmpf-components/blob/9f8e6eca0dc685afec1b02d7aadccc4dd3531f7e/cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp#L412)):*
> ```cpp
>                                                                  "Mismatching dawg sizes after removing updated words.";
> 
>     ASSERT_TRUE(reference_wordset == updated_wordset) << "Eng model not properly updated. " <<
> ```

Should we do this assert for LSTM? If not, leave a comment explaining why.
___
*[cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp, line 419 at r10](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOs9QII9doK0EyNbnzg:-MOs9QIK6ajhnm4DmUKl:b-fpc0y4) ([raw file](https://github.com/openmpf/openmpf-components/blob/9f8e6eca0dc685afec1b02d7aadccc4dd3531f7e/cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp#L419)):*
> ```cpp
>     ASSERT_TRUE(ocr.Init());
>     std::map<std::string, std::string> custom_properties = {{"TESSERACT_LANGUAGE",    "eng"},
>                                                             {"TESSERACT_OEM", "0"},
> ```

Leave a comment explaining why we're only testing legacy.


<!-- Sent from Reviewable.io -->

2020-12-19 02:09 UTC, hhuangMITRE reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/209)* status: 149 of 154 files reviewed, 13 unresolved discussions (waiting on @brosenberg42, @hhuangMITRE, @jrobble, and @returns)

___
*[cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp, line 205 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOdh7O289LkdCbqc8bs:-MOsk-WgEJvy95p2OuCO:bxhitf2) ([raw file](https://github.com/openmpf/openmpf-components/blob/dc48c806990075988f35ef59a206424241c72ca5/cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp#L205)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I would call this `loadWordList` for clarity.
</blockquote></details>

Done. Also updated the same function in the model updater cpp code.
___
*[cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp, line 68 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOo5-ZX84CQZzEtGTTe:-MOsj1J24MBm-zQSMTwb:bfowj37) ([raw file](https://github.com/openmpf/openmpf-components/blob/1bcd510bc67877c958430fec392f935a13aea105/cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp#L68)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Missing `@param`. Should we be documenting return types as well?

TBH, I don't think that documenting functions is necessary unless it's not intuitive what the function is doing or what the inputs are. Too much documentation clutters the code. I'm not saying you should remove these; I just want to save you some trouble if you feel the need to document everything.
</blockquote></details>

Got it, thanks! I was trying out the auto-documentation features and got a bit carried away, lol. 

I was also wondering if it was even necessary to comment on functions that were already clear to read. 
I'll save this documentation for functions that are more complex in the future.

Updated existing documentation to mention @returns and fixed missing @param.
___
*[cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp, line 112 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOo5G9p4sp7wwPOyV7t:-MOsjq2A9al66kfFqJGr:bqvwnb8) ([raw file](https://github.com/openmpf/openmpf-components/blob/1bcd510bc67877c958430fec392f935a13aea105/cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp#L112)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Missing `@param` for `wild_mode`.
</blockquote></details>

Added in.
___
*[cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp, line 121 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOo6z1P4Ab1avGSiKTB:-MOsjsrHAwHgLvrwg_Gq:b3pay6t) ([raw file](https://github.com/openmpf/openmpf-components/blob/1bcd510bc67877c958430fec392f935a13aea105/cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp#L121)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

`image_path` is used below. You should probably change the name of that variable in the code.
</blockquote></details>

Updated to `doc_path`, thanks!
___
*[cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp, line 146 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOo77K0EF8sCk6wAy3J:-MOsjx1j7WLtUi8vEmLA:bqvwnb8) ([raw file](https://github.com/openmpf/openmpf-components/blob/1bcd510bc67877c958430fec392f935a13aea105/cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp#L146)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Missing `@param` for `wild_mode`.
</blockquote></details>

Added in.
___
*[cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp, line 292 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOo8DnC9dXY4OD-pDke:-MOsjyjF4Z4date0ieFC:bt2vr1b) ([raw file](https://github.com/openmpf/openmpf-components/blob/1bcd510bc67877c958430fec392f935a13aea105/cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp#L292)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

It's a set, not a vector.
</blockquote></details>

Fixed.
___
*[cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp, line 318 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOoFeq61gMGHW0JN53O:-MOsk4H70aKmruEoZtW2:bt2vr1b) ([raw file](https://github.com/openmpf/openmpf-components/blob/1bcd510bc67877c958430fec392f935a13aea105/cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp#L318)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Indentation is off.
</blockquote></details>

Fixed.
___
*[cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp, line 318 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOoFiff2l3OYKvmqhpG:-MOsk7Bp4U6w9VbWEKPf:bpchpy4) ([raw file](https://github.com/openmpf/openmpf-components/blob/1bcd510bc67877c958430fec392f935a13aea105/cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp#L318)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Caps: "IF"
</blockquote></details>

Fixed. Also combined with the comment below as well, since they address the same issue.
___
*[cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp, line 409 at r10](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOs9k2c3cky1Km-ooRX:-MOskFzW2oy4REXGPVUl:byt5xpl) ([raw file](https://github.com/openmpf/openmpf-components/blob/9f8e6eca0dc685afec1b02d7aadccc4dd3531f7e/cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp#L409)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Should we do this assert for LSTM? If not, leave a comment explaining why.
</blockquote></details>

I think checking the assert for LSTM is valid. I've made a slight update to the test to verify that the `lstm-dawgs` (after recompressing both of them using the current word2dawg code) are the same except for one added word. 
___
*[cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp, line 412 at r10](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOs9oLc961wp-yS--cJ:-MOskX5d8eG7ErWaWdFt:b-2gz9tl) ([raw file](https://github.com/openmpf/openmpf-components/blob/9f8e6eca0dc685afec1b02d7aadccc4dd3531f7e/cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp#L412)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Should we do this assert for LSTM? If not, leave a comment explaining why.
</blockquote></details>

Updated to include a check for the LSTM versions as well.
___
*[cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp, line 419 at r10](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOs9QII9doK0EyNbnzg:-MOska0x39wOboUytB4B:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/9f8e6eca0dc685afec1b02d7aadccc4dd3531f7e/cpp/TesseractOCRTextDetection/test/test_tesseract_ocr_detection.cpp#L419)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Leave a comment explaining why we're only testing legacy.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-19 03:07 UTC, jrobble requested changes
> Reviewed 1 of 6 files at r4, 1 of 2 files at r6, 3 of 3 files at r11.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/209)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42 and @hhuangMITRE)

___
*[cpp/TesseractOCRTextDetection/tessdata_model_updater.cpp, line 593 at r11](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOsslS298glPnfNt7U7:-MOsslS508kxu3dd9zOY:b-phl0rt) ([raw file](https://github.com/openmpf/openmpf-components/blob/8e582ee9d86177e4fb6a6171685f9224fe610c93/cpp/TesseractOCRTextDetection/tessdata_model_updater.cpp#L593)):*
> ```cpp
>                 text_format = true;
>                 target_file = boost::filesystem::path(file).replace_extension("").string();
>                 printf("Updating dawg file %s with text-based wordlist %s\n", target_file.c_str(), file.c_str());
> ```

DAWG is an acronym and should be capitalized in all log messages.

Also, in some places in the docs and print outs you have "wordlist" and others "word list". Please pick one or the other.


<!-- Sent from Reviewable.io -->

2020-12-19 03:08 UTC, jrobble reviewed
> Reviewed 3 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/209)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42 and @hhuangMITRE)



<!-- Sent from Reviewable.io -->

2020-12-19 03:53 UTC, hhuangMITRE reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/209)* status: 150 of 154 files reviewed, 1 unresolved discussion (waiting on @brosenberg42 and @jrobble)

___
*[cpp/TesseractOCRTextDetection/tessdata_model_updater.cpp, line 593 at r11](https://reviewable.io/reviews/openmpf/openmpf-components/209#-MOsslS298glPnfNt7U7:-MOt73lI4TdTumvIXj7O:b-jfj4ii) ([raw file](https://github.com/openmpf/openmpf-components/blob/8e582ee9d86177e4fb6a6171685f9224fe610c93/cpp/TesseractOCRTextDetection/tessdata_model_updater.cpp#L593)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

DAWG is an acronym and should be capitalized in all log messages.

Also, in some places in the docs and print outs you have "wordlist" and others "word list". Please pick one or the other.
</blockquote></details>

Done. Checked documentation here and in the test binary/DICTIONARY.md files. Also switched over `lstm` to `LSTM` and `wordlist` to `word list`. 


<!-- Sent from Reviewable.io -->

2020-12-19 04:10 UTC, jrobble approved these changes
> Reviewed 4 of 4 files at r13, 1 of 1 files at r14.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/209)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)



<!-- Sent from Reviewable.io -->

2020-12-19 05:08 UTC, merged