Add OcvYoloDetection component
openmpf/openmpf-components pull request #225
Opened 2021-01-29 18:37 UTC by brosenberg42

2021-02-11 22:40 UTC, jrobble commented
___
*[cpp/OcvYoloDetection/DetectionLocation.cpp, line 150 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/225#-MTI3wiBCpK2zJwAILsH:-MTI3wiC4cZxwmXpGwDD:bwwe7dn) ([raw file](https://github.com/openmpf/openmpf-components/blob/f4b4733d6cd07e9b0dd135804b00a30639b07978/cpp/OcvYoloDetection/DetectionLocation.cpp#L150)):*
Possibly because `center` is not exact integer coordinates, From the `getRectSubPix()` doc:

> the values of the pixels at non-integer coordinates are retrieved using bilinear interpolation

It makes me wonder if we're better off ensuring we get an unmodified slice of the frame data that might be a pixel or two off center, width, and/or height, so that we don't have to interpolate.

I ran some tests with the `()` operator with a `Rect2d` roi. Under the hood it's converting the double values to ints with `saturate_cast<int>(double v) { return cvRound(v); }`. Thus, no interpolation.


<!-- Sent from Reviewable.io -->

2021-02-16 04:35 UTC, jrobble requested changes
> Reviewed 11 of 57 files at r1, 57 of 59 files at r2, 13 of 13 files at r3.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/225)* status: all files reviewed, 51 unresolved discussions (waiting on @brosenberg42)

___
*[cpp/OcvYoloDetection/.dockerignore, line 8 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/225#-MSix2c33sW3QB4PWwHf:-MSix2c423yfEl8pKWeS:b-53g4lg) ([raw file](https://github.com/openmpf/openmpf-components/blob/f4b4733d6cd07e9b0dd135804b00a30639b07978/cpp/OcvYoloDetection/.dockerignore#L8)):*
> ```ignore
> # 52.227-14, Alt. IV (DEC 2007).                                            #
> #                                                                           #
> # Copyright 2020 The MITRE Corporation. All Rights Reserved.                #
> ```

Please update copyrights.
___
*[cpp/OcvYoloDetection/.gitignore, line 7 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/225#-MSixQWd-so5H0DBbDkf:-MSixQWe7p9C0YcGakKr:b-ff5a02) ([raw file](https://github.com/openmpf/openmpf-components/blob/f4b4733d6cd07e9b0dd135804b00a30639b07978/cpp/OcvYoloDetection/.gitignore#L7)):*
> ```ignore
> .unotes/
> ObjectDetection-YOLO/
> ocv_face_known_tracks_short.txt
> ```

I don't see `ocv_face_known_tracks_short.txt` or `ObjectDetection-YOLO`. Can those be removed?

Some of the other entries in this section are strange, but I can understand how they might be in Andy's dev env. The last two should probably be under the `# vs-code` section.
___
*[cpp/OcvYoloDetection/Cluster.h, line 83 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/225#-MSj5xSbBJw-QLf7V7CD:-MSj5xSbBJw-QLf7V7CE:b-1zm66e) ([raw file](https://github.com/openmpf/openmpf-components/blob/f4b4733d6cd07e9b0dd135804b00a30639b07978/cpp/OcvYoloDetection/Cluster.h#L83)):*
> ```objc
> /** ***************************************************************************
> *  very naive agglomerative clustering (not suitable for lots of items),
> *  move items from a list list of clusters that is returned
> ```

`list` implies `std::list`. We're using `std::vector`. Asking you to change all of the variable names would be too nit-picky. Minimally, I changed some of the comments.
___
*[cpp/OcvYoloDetection/Cluster.h, line 103 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/225#-MSj66WaESy0IpGJG0E1:-MSj66Wb7mJopxGG5ZzV:b-ba5imr) ([raw file](https://github.com/openmpf/openmpf-components/blob/f4b4733d6cd07e9b0dd135804b00a30639b07978/cpp/OcvYoloDetection/Cluster.h#L103)):*
> ```objc
>         auto feature = item.getClassFeature();
>         // find 1st cluster item can join
>         // TODO: Should we be using the minimum rather than the first?
> ```

Note to self: Double-check all TODOs before approving.
___
*[cpp/OcvYoloDetection/Cluster.h, line 107 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/225#-MTbYIAv30o1pRIUuLFA:-MTbYIAv30o1pRIUuLFB:b-k3s1c1) ([raw file](https://github.com/openmpf/openmpf-components/blob/f4b4733d6cd07e9b0dd135804b00a30639b07978/cpp/OcvYoloDetection/Cluster.h#L107)):*
According to:

> "maximum feature distance an object can be from its cluster's average feature"

Shouldn't this be `distanceFunc(cluster.averageFeature, feature) <= maxDist`?
___
*[cpp/OcvYoloDetection/Config.cpp, line 37 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/225#-MSj91hA92NphXrgwknp:-MSj91hA92NphXrgwknq:buzflak) ([raw file](https://github.com/openmpf/openmpf-components/blob/f4b4733d6cd07e9b0dd135804b00a30639b07978/cpp/OcvYoloDetection/Config.cpp#L37)):*
> ```cpp
> using DetectionComponentUtils::GetProperty;
> 
> // Shared static members (might need mutex locks and condition variable if multithreading... )
> ```

This comment does not instill confidence. Does this still need to be addressed?
___
*[cpp/OcvYoloDetection/Config.cpp, line 57 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/225#-MTbfZGWBzk4dDb7DOC9:-MTbfZGWBzk4dDb7DOCA:bhyijhc) ([raw file](https://github.com/openmpf/openmpf-components/blob/f4b4733d6cd07e9b0dd135804b00a30639b07978/cpp/OcvYoloDetection/Config.cpp#L57)):*
> ```cpp
>         , maxClassDist(GetProperty(jobProps, "TRACKING_MAX_CLASS_DIST", 0.99))
>         , maxFeatureDist(GetProperty(jobProps, "TRACKING_MAX_FEATURE_DIST", 0.1))
>         , maxCenterDist(GetProperty(jobProps, "TRACKING_MAX_CENTER_DIST", 0.0))
> ```

`TRACKING_MAX_CENTER_DIST` is not in `descriptor.json`. Also, a value of 0.0 indicates that this metric is essentially disabled and has no impact on forming tracks. Is this intentional?
___
*[cpp/OcvYoloDetection/DetectionLocation.h, line 27 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/225#-MSoI8ai89fTQpn5eFrP:-MSoI8ai89fTQpn5eFrQ:ba5z1ud) ([raw file](https://github.com/openmpf/openmpf-components/blob/f4b4733d6cd07e9b0dd135804b00a30639b07978/cpp/OcvYoloDetection/DetectionLocation.h#L27)):*
> ```objc
>  ******************************************************************************/
> 
> #ifndef OCVYOLODETECTION_DETECTIONLOCATION_H
> ```

Looking at the existing Darknet component, I see this kind of prefix for these kind of #ifndef lines: `OPENMPF_COMPONENTS_DARKNET*`. 

The .h files in this component are not consistent. Some have `OPENMPF_COMPONENTS_*`, some have `OPENMPF_COMPONENTS_YOLO*`, some have `OPENMPF_COMPONENTS_OCVYOLO*`, and some start with `OCVYOLODETECTION_*`.
___
*[cpp/OcvYoloDetection/DetectionLocation.h, line 37 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/225#-MSoK7Rv5qBNT6OPLkPH:-MSoK7Rv5qBNT6OPLkPI:b-93j9gw) ([raw file](https://github.com/openmpf/openmpf-components/blob/f4b4733d6cd07e9b0dd135804b00a30639b07978/cpp/OcvYoloDetection/DetectionLocation.h#L37)):*
> ```objc
> 
> 
> // TODO Should something be done about circular dependency between DetectionLocation and Track?
> ```

Could all of the functions that take a Track object be moved to the Track class and take a Detection object?
___
*[cpp/OcvYoloDetection/DetectionLocation.cpp, line 105 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/225#-MTChtFfAGvXy-FvG9N7:-MTChtFg6XIPyIKw6qCp:b-1xc02k) ([raw file](https://github.com/openmpf/openmpf-components/blob/f4b4733d6cd07e9b0dd135804b00a30639b07978/cpp/OcvYoloDetection/DetectionLocation.cpp#L105)):*
> ```cpp
> *
> *************************************************************************** */
> cv::Point2d DetectionLocation::phaseCorrelate(Track &track) {
> ```

Very similar to [this](https://github.com/opencv/opencv/blob/master/modules/imgproc/src/phasecorr.cpp#L518). Minimally, we should reference that.
___
*[cpp/OcvYoloDetection/DetectionLocation.cpp, line 161 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/225#-MTIIEop5fVLm0W8DFHG:-MTIIEop5fVLm0W8DFHH:bnsekth) ([raw file](https://github.com/openmpf/openmpf-components/blob/f4b4733d6cd07e9b0dd135804b00a30639b07978/cpp/OcvYoloDetection/DetectionLocation.cpp#L161)):*
> ```cpp
>     cv::Scalar mean = cv::mean(comp) / 255.0;
>     // combine BGR: d = BGR.BGR
>     // TODO: Why mean.ddot(mean)? That is the vector's length squared.
> ```

Looks like mean squared error to me.
___
*[cpp/OcvYoloDetection/DetectionLocation.cpp, line 211 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/225#-MT7cyH45p_tVFMQt3CT:-MT7cyH45p_tVFMQt3CU:b1uv641) ([raw file](https://github.com/openmpf/openmpf-components/blob/f4b4733d6cd07e9b0dd135804b00a30639b07978/cpp/OcvYoloDetection/DetectionLocation.cpp#L211)):*
> ```cpp
>         if (defaultWindow.empty() || defaultWindow.rows != dftSize_) {
>             //LOG_TRACE("Created default hanning window of size " << defWin.size());
>             cv::createHanningWindow(defaultWindow, cv::Size(dftSize_, dftSize_), CV_32F);
> ```

Instead of `cv::Size(dftSize_, dftSize_)`, can't we just use `size`?
___
*[cpp/OcvYoloDetection/DetectionLocation.cpp, line 252 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/225#-MT7a_kiD3jjb_11BNGc:-MT7a_kjAOak_8WrWG83:b-bulksm) ([raw file](https [...]

2021-02-17 20:19 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/225)* status: 23 of 50 files reviewed, 51 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[cpp/OcvYoloDetection/Cluster.h, line 83 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/225#-MSj5xSbBJw-QLf7V7CD:-MTf0aEFDkYBtkIaezW8:b2qvsf2) ([raw file](https://github.com/openmpf/openmpf-components/blob/f4b4733d6cd07e9b0dd135804b00a30639b07978/cpp/OcvYoloDetection/Cluster.h#L83)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

`list` implies `std::list`. We're using `std::vector`. Asking you to change all of the variable names would be too nit-picky. Minimally, I changed some of the comments.
</blockquote></details>

Andy initially used `std::list`. I switched to `std::vector` because the use of `std::list` was causing additional code to be added to deal with the fact that you can't look up items by index.
___
*[cpp/OcvYoloDetection/Cluster.h, line 107 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/225#-MTbYIAv30o1pRIUuLFA:-MTfdHvhDX2szLzBu8Xz:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/f4b4733d6cd07e9b0dd135804b00a30639b07978/cpp/OcvYoloDetection/Cluster.h#L107)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

According to:

> "maximum feature distance an object can be from its cluster's average feature"

Shouldn't this be `distanceFunc(cluster.averageFeature, feature) <= maxDist`?
</blockquote></details>

Done.
___
*[cpp/OcvYoloDetection/Config.cpp, line 37 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/225#-MSj91hA92NphXrgwknp:-MTkNl__826j-PlvUXds:b32w12) ([raw file](https://github.com/openmpf/openmpf-components/blob/f4b4733d6cd07e9b0dd135804b00a30639b07978/cpp/OcvYoloDetection/Config.cpp#L37)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

This comment does not instill confidence. Does this still need to be addressed?
</blockquote></details>

No
___
*[cpp/OcvYoloDetection/Config.cpp, line 57 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/225#-MTbfZGWBzk4dDb7DOC9:-MTfdpBa-S3pusmRbyAS:b-h83svt) ([raw file](https://github.com/openmpf/openmpf-components/blob/f4b4733d6cd07e9b0dd135804b00a30639b07978/cpp/OcvYoloDetection/Config.cpp#L57)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

`TRACKING_MAX_CENTER_DIST` is not in `descriptor.json`. Also, a value of 0.0 indicates that this metric is essentially disabled and has no impact on forming tracks. Is this intentional?
</blockquote></details>

That was taken from https://github.com/openmpf/openmpf-components/blob/555b6591e6d61df9afdf45e5be6d5b650d86bb4b/cpp/OcvYoloDetection/plugin-files/config/mpfOcvYoloDetection.ini#L63
___
*[cpp/OcvYoloDetection/DetectionLocation.h, line 27 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/225#-MSoI8ai89fTQpn5eFrP:-MTf1DI4Ep0PJik25pRD:b-tfynmx) ([raw file](https://github.com/openmpf/openmpf-components/blob/f4b4733d6cd07e9b0dd135804b00a30639b07978/cpp/OcvYoloDetection/DetectionLocation.h#L27)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Looking at the existing Darknet component, I see this kind of prefix for these kind of #ifndef lines: `OPENMPF_COMPONENTS_DARKNET*`. 

The .h files in this component are not consistent. Some have `OPENMPF_COMPONENTS_*`, some have `OPENMPF_COMPONENTS_YOLO*`, some have `OPENMPF_COMPONENTS_OCVYOLO*`, and some start with `OCVYOLODETECTION_*`.
</blockquote></details>

It doesn't matter. It just needs to be a unique string. You can change them if you want.
___
*[cpp/OcvYoloDetection/Frame.cpp, line 26 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/225#-MT2hvq-BpMn_xBEkjXq:-MTfl0YQAm7YhVgxCsSU:b32w12) ([raw file](https://github.com/openmpf/openmpf-components/blob/f4b4733d6cd07e9b0dd135804b00a30639b07978/cpp/OcvYoloDetection/Frame.cpp#L26)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Is this file necessary?
</blockquote></details>

No
___
*[cpp/OcvYoloDetection/OcvYoloDetection.cpp, line 212 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/225#-MTakun75qeEVKu8IV1x:-MTfrOVTCCYKidchMqWP:b32w12) ([raw file](https://github.com/openmpf/openmpf-components/blob/f4b4733d6cd07e9b0dd135804b00a30639b07978/cpp/OcvYoloDetection/OcvYoloDetection.cpp#L212)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

> "configuration variables are turned into environment variables for late reference"

Is that still true?
</blockquote></details>

No
___
*[cpp/OcvYoloDetection/Track.h, line 207 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/225#-MTbYs9q1BAMzuc_Isdi:-MTflcFU2KL-GueucZvv:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/f4b4733d6cd07e9b0dd135804b00a30639b07978/cpp/OcvYoloDetection/Track.h#L207)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

According to:

> "maximum feature distance an object can be from its cluster's average feature"

Shouldn't this be `distance <= maxClassDist`?
</blockquote></details>

Done.
___
*[cpp/OcvYoloDetection/YoloNetwork.cpp, line 71 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/225#-MTJHe2g5DoU2yLL7rV4:-MTkQ8VKEnS652PGsMd-:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/f4b4733d6cd07e9b0dd135804b00a30639b07978/cpp/OcvYoloDetection/YoloNetwork.cpp#L71)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

What if there are simply no GPUs available? See [here](https://android.googlesource.com/platform/external/opencv3/+/master/samples/gpu/cascadeclassifier_nvidia_api.cpp#163). 

Note to self: Test this.
</blockquote></details>

Done.
___
*[cpp/OcvYoloDetection/YoloNetwork.cpp, line 245 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/225#-MTJKu427YfFpgTCYjzI:-MTf3fl75r_FZhw6JDUv:b8zg81p) ([raw file](https://github.com/openmpf/openmpf-components/blob/f4b4733d6cd07e9b0dd135804b00a30639b07978/cpp/OcvYoloDetection/YoloNetwork.cpp#L245)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Ask Andy: `DetectionLocation.cpp` does "border replication" when calculating the pixel feature difference, but a gray background is used here. I think that's fine though.
</blockquote></details>

Originally, this used border replication. I switched it to do what the darknet library does.
___
*[cpp/OcvYoloDetection/plugin-files/descriptor/descriptor.json, line 3 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/225#-MSjAyDJ67f9pSnHXre_:-MTkQsXV5RTbowIKg3Sw:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/f4b4733d6cd07e9b0dd135804b00a30639b07978/cpp/OcvYoloDetection/plugin-files/descriptor/descriptor.json#L3)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please change the component and middleware version to match the other components when we're ready to move out of beta.
</blockquote></details>

Done.
___
*[cpp/OcvYoloDetection/plugin-files/descriptor/descriptor.json, line 109 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/225#-MSjByXG846CdKP5kujU:-MTfo7A0COrEkuFTmRNV:b-r3z1kj) ([raw file](https://github.com/openmpf/openmpf-components/blob/f4b4733d6cd07e9b0dd135804b00a30639b07978/cpp/OcvYoloDetection/plugin-files/descriptor/descriptor.json#L109)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

This is 0.005 in Config.cpp. Which should we use?
</blockquote></details>

The value in Config.cpp was taken from https://github.com/openmpf/openmpf-components/blob/555b6591e6d61df9afdf45e5be6d5b650d86bb4b/cpp/OcvYoloDetection/plugin-files/config/mpfOcvYoloDetection.ini#L66
___
* [...]

2021-02-18 06:06 UTC, jrobble requested changes
> Reviewed 2 of 59 files at r2, 30 of 30 files at r4.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/225)* status: all files reviewed, 26 unresolved discussions (waiting on @brosenberg42)

___
*[cpp/OcvYoloDetection/DetectionLocation.cpp, line 161 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/225#-MTIIEop5fVLm0W8DFHG:-MTnV9uUD5urfILm98fh:b22x8zk) ([raw file](https://github.com/openmpf/openmpf-components/blob/f4b4733d6cd07e9b0dd135804b00a30639b07978/cpp/OcvYoloDetection/DetectionLocation.cpp#L161)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Looks like mean squared error to me.
</blockquote></details>

As discussed, use MAE.
___
*[cpp/OcvYoloDetection/OcvYoloDetection.cpp, line 81 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/225#-MTbg_sWEGMVZjDGTYxo:-MTnjXPw01kIuIDO9Ql2:b-5sulvh) ([raw file](https://github.com/openmpf/openmpf-components/blob/f4b4733d6cd07e9b0dd135804b00a30639b07978/cpp/OcvYoloDetection/OcvYoloDetection.cpp#L81)):*
Only this remains:

> Implement conditional checks here to skip each of these assign blocks if the respective max distance value is <= 0.
___
*[cpp/OcvYoloDetection/OcvYoloDetection.cpp, line 184 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/225#-MTakLfqEM4Tt8GkEkHl:-MTnd8jx24Xe4UdfdosE:b-laoi24) ([raw file](https://github.com/openmpf/openmpf-components/blob/f4b4733d6cd07e9b0dd135804b00a30639b07978/cpp/OcvYoloDetection/OcvYoloDetection.cpp#L184)):*
Only this remains:

> Note to self: Check if all track clusters are empty at this time.
___
*[cpp/OcvYoloDetection/Track.cpp, line 119 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/225#-MT7Lao3DIS7Lu2HfAxZ:-MTnVRlf-CQ5MpbYPmcV:bser0hj) ([raw file](https://github.com/openmpf/openmpf-components/blob/f4b4733d6cd07e9b0dd135804b00a30639b07978/cpp/OcvYoloDetection/Track.cpp#L119)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Ask Andy: Why was MOSSE selected over the other trackers?
</blockquote></details>

Because it's fast and accurate.
___
*[cpp/OcvYoloDetection/plugin-files/descriptor/descriptor.json, line 91 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/225#-MTbasnoEVY4BLq7utFm:-MTnWeYH7QO7jzvJvrtC:b-vj95o5) ([raw file](https://github.com/openmpf/openmpf-components/blob/f4b4733d6cd07e9b0dd135804b00a30639b07978/cpp/OcvYoloDetection/plugin-files/descriptor/descriptor.json#L91)):*
Only this remains:

> Note to self: Run test and see how many clusters are formed.
___
*[cpp/OcvYoloDetection/plugin-files/descriptor/descriptor.json, line 109 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/225#-MSjByXG846CdKP5kujU:-MTnXeu72wvykpC_6KO9:b-iz42nn) ([raw file](https://github.com/openmpf/openmpf-components/blob/f4b4733d6cd07e9b0dd135804b00a30639b07978/cpp/OcvYoloDetection/plugin-files/descriptor/descriptor.json#L109)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

The value in Config.cpp was taken from https://github.com/openmpf/openmpf-components/blob/555b6591e6d61df9afdf45e5be6d5b650d86bb4b/cpp/OcvYoloDetection/plugin-files/config/mpfOcvYoloDetection.ini#L66
</blockquote></details>

We should use the same value in `descriptor.json` and `Config.cpp`. I would assume that Andy did not use the WFM for most of his development, so we should use 0.005 in `descriptor.json`too.

Different values could result in different results when running unit tests and jobs through the WFM.


<!-- Sent from Reviewable.io -->

2021-02-18 06:13 UTC, jrobble reviewed
> Reviewed 15 of 15 files at r5.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/225)* status: all files reviewed, 26 unresolved discussions (waiting on @brosenberg42)



<!-- Sent from Reviewable.io -->

2021-02-18 07:24 UTC, jrobble commented
___
*[cpp/OcvYoloDetection/plugin-files/descriptor/descriptor.json, line 82 at r5](https://reviewable.io/reviews/openmpf/openmpf-components/225#-MTo0GMv7xk-oRy-1J7v:-MTo0GMv7xk-oRy-1J7w:b9hawl4) ([raw file](https://github.com/openmpf/openmpf-components/blob/d72bb94621ba185200c3c2b362cac61c6152ed80/cpp/OcvYoloDetection/plugin-files/descriptor/descriptor.json#L82)):*
> ```JSON
>         },
>         {
>           "name": "TRACKING_MAX_FRAME_GAP",
> ```

When used by the component, this value should first be divided by the `FRAME_INTERVAL`.


<!-- Sent from Reviewable.io -->

2021-02-18 19:56 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/225)* status: 45 of 50 files reviewed, 27 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[cpp/OcvYoloDetection/DetectionLocation.cpp, line 211 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/225#-MT7cyH45p_tVFMQt3CT:-MTq_esS2p9Bk5JNC-70:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/f4b4733d6cd07e9b0dd135804b00a30639b07978/cpp/OcvYoloDetection/DetectionLocation.cpp#L211)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Instead of `cv::Size(dftSize_, dftSize_)`, can't we just use `size`?
</blockquote></details>

Done.
___
*[cpp/OcvYoloDetection/DetectionLocation.cpp, line 261 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/225#-MT7cCCJE9vy-OhZ1Xva:-MTq_lYgEwhVvGIe08Hi:bq81rta) ([raw file](https://github.com/openmpf/openmpf-components/blob/f4b4733d6cd07e9b0dd135804b00a30639b07978/cpp/OcvYoloDetection/DetectionLocation.cpp#L261)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Is this to handle the case where `TRACKING_DFT_SIZE` is greater than the frame dimensions?
</blockquote></details>

Ask Andy
___
*[cpp/OcvYoloDetection/OcvYoloDetection.cpp, line 81 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/225#-MTbg_sWEGMVZjDGTYxo:-MTqZSyMD8magIvfa3dC:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/f4b4733d6cd07e9b0dd135804b00a30639b07978/cpp/OcvYoloDetection/OcvYoloDetection.cpp#L81)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Only this remains:

> Implement conditional checks here to skip each of these assign blocks if the respective max distance value is <= 0.
</blockquote></details>

Done.
___
*[cpp/OcvYoloDetection/OcvYoloDetection.cpp, line 184 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/225#-MTakLfqEM4Tt8GkEkHl:-MTfqNAvDamJCKMb4gxi:b-f85paj) ([raw file](https://github.com/openmpf/openmpf-components/blob/f4b4733d6cd07e9b0dd135804b00a30639b07978/cpp/OcvYoloDetection/OcvYoloDetection.cpp#L184)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Only this remains:

> Note to self: Check if all track clusters are empty at this time.
</blockquote></details>

I'm not sure if you are referring to `trackCluster.members.empty()` or `trackCluster.members.at(n).locations_.empty()`.
This code does not alter the size of `trackCluster.members`. It is not moving the vector, rather it is moving the individual elements. 
`trackCluster.members.at(n).locations_` is empty because the compiler generated move constructor moves each field. This causes the entire  `trackCluster.members.at(n).locations_`  vector to be moved rather than the individual elements.
___
*[cpp/OcvYoloDetection/Track.cpp, line 115 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/225#-MT7L7at3F2127inlOde:-MTqbi_r7c2wD_OXPSXK:b-dfzyyq) ([raw file](https://github.com/openmpf/openmpf-components/blob/f4b4733d6cd07e9b0dd135804b00a30639b07978/cpp/OcvYoloDetection/Track.cpp#L115)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Leave a comment here saying that we're just checking that some part of the first track detection is within the frame.

Will we have detections that are out of the frame or have a 0 width or height? If so, should we just use the next detection in the track?
</blockquote></details>

Detections outside the frame or zero area seems like a bug. I'm not sure what would cause it to be out of the frame.
___
*[cpp/OcvYoloDetection/plugin-files/descriptor/descriptor.json, line 109 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/225#-MSjByXG846CdKP5kujU:-MTqZmw1BPrQJGbYWZZQ:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/f4b4733d6cd07e9b0dd135804b00a30639b07978/cpp/OcvYoloDetection/plugin-files/descriptor/descriptor.json#L109)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

We should use the same value in `descriptor.json` and `Config.cpp`. I would assume that Andy did not use the WFM for most of his development, so we should use 0.005 in `descriptor.json`too.

Different values could result in different results when running unit tests and jobs through the WFM.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-19 05:52 UTC, jrobble reviewed
> Reviewed 5 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/225)* status: all files reviewed, 25 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[cpp/OcvYoloDetection/README.md, line 36 at r6](https://reviewable.io/reviews/openmpf/openmpf-components/225#-MTsp9JmCWcxm_A98MXr:-MTsp9JnDueGMXb6V3Fz:b-ji5wh5) ([raw file](https://github.com/openmpf/openmpf-components/blob/b92204b8fb2aa445c0a162e4147a74fe75a0e195/cpp/OcvYoloDetection/README.md#L36)):*
> ```Markdown
> * Unassigned detections become new tracks.
> * All active tracks then have their object bounding box positions corrected and predicted forward 
>   in time with a Kalman filter for the next tracking iteration. During the assignment stages, 
> ```

Note to self: Add future research section. Mention potential improvements.


<!-- Sent from Reviewable.io -->

2021-02-19 05:58 UTC, jrobble reviewed
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/225)* status: all files reviewed, 25 unresolved discussions (waiting on @brosenberg42 and @jrobble)



<!-- Sent from Reviewable.io -->

2021-02-19 18:19 UTC, jrobble reviewed
> Reviewed 4 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/225)* status: all files reviewed, 24 unresolved discussions (waiting on @brosenberg42 and @jrobble)



<!-- Sent from Reviewable.io -->

2021-02-19 18:58 UTC, jrobble reviewed
> Reviewed 3 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/225)* status: all files reviewed, 24 unresolved discussions (waiting on @brosenberg42 and @jrobble)



<!-- Sent from Reviewable.io -->

2021-02-19 21:16 UTC, brosenberg42 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/225#-:-MTw8Zl4AahZgOLlgx89:bg7igkv)* status: 45 of 50 files reviewed, 24 unresolved discussions (waiting on @brosenberg42 and @jrobble)



<!-- Sent from Reviewable.io -->

2021-02-19 21:21 UTC, jrobble reviewed
> Reviewed 5 of 5 files at r10.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/225)* status: all files reviewed, 23 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[cpp/OcvYoloDetection/Track.cpp, line 115 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/225#-MT7L7at3F2127inlOde:-MTw9bZ92Woyr-6nhT1f:b-qcc99a) ([raw file](https://github.com/openmpf/openmpf-components/blob/f4b4733d6cd07e9b0dd135804b00a30639b07978/cpp/OcvYoloDetection/Track.cpp#L115)):*
Only this remains:

> Leave a comment here saying that we're just checking that some part of the first track detection is within the frame.


<!-- Sent from Reviewable.io -->

2021-02-19 21:27 UTC, jrobble approved these changes

2021-02-19 21:28 UTC, merged