Jrobble/triton yolov4
openmpf/openmpf-components pull request #284
Opened 2021-09-23 18:15 UTC by jrobble

**Issues:**

- https://github.com/openmpf/openmpf/issues/1 < Example
- https://github.com/openmpf/openmpf/issues/2 < Example

If a related issue doesn't exist, then create one first and assign it to yourself.

**Related PRs:**

- https://github.com/openmpf/openmpf/pull/22 < Example
- https://github.com/openmpf/openmpf/pull/53 < Example

Please review our [Contributor Guide](https://openmpf.github.io/docs/site/Contributor-Guide/index.html).

2022-01-19 21:04 UTC, brosenberg42 requested changes
> Reviewed 2 of 32 files at r1, 55 of 58 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/284)* status: all files reviewed (commit messages unreviewed), 17 unresolved discussions (waiting on @jrobble)

___
*[cpp/OcvYoloDetection/CMakeLists.txt, line 35 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/284#-MtmpLQr9Pd8ARUBy75E:-MtmpLQr9Pd8ARUBy75F:bk9i6) ([raw file](https://github.com/openmpf/openmpf-components/blob/be361d579ee6dfbed4b5010619ae3e41dc5b8dae/cpp/OcvYoloDetection/CMakeLists.txt#L35)):*
> ```CMake
> 
> set(CMAKE_BUILD_TYPE RelWithDebInfo)  # build release version with debug symbols
> #set(CMAKE_BUILD_TYPE Release)         # build release version
> ```

The build type should be set to Release.
___
*[cpp/OcvYoloDetection/Config.cpp, line 56 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/284#-MtmqMg-32aFRkqv_-Ua:-MtmqMg-32aFRkqv_-Ub:b-ikxpxp) ([raw file](https://github.com/openmpf/openmpf-components/blob/be361d579ee6dfbed4b5010619ae3e41dc5b8dae/cpp/OcvYoloDetection/Config.cpp#L56)):*
> ```cpp
> Config::Config(const Properties &jobProps)
>         : confidenceThreshold(std::max(GetProperty(jobProps, "CONFIDENCE_THRESHOLD", 0.5), 0.0)),
>           nmsThresh(GetProperty(jobProps, "DETECTION_NMS_THRESHOLD", 0.3)),
> ```

The common style for constructor initialization lists is to have the leading commas like the code did before this change.
___
*[cpp/OcvYoloDetection/Dockerfile, line 233 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/284#-MtmsYdt8OkW6QknKJf8:-MtmsYdt8OkW6QknKJf9:b-4rp0da) ([raw file](https://github.com/openmpf/openmpf-components/blob/be361d579ee6dfbed4b5010619ae3e41dc5b8dae/cpp/OcvYoloDetection/Dockerfile#L233)):*
> ```Dockerfile
> COPY --from=build_component $BUILD_DIR/libmpfOcvYoloDetection.so $PLUGINS_DIR/OcvYoloDetection/lib/
> 
> # Copy test files so that they can be used to debug issues later at runtime.
> ```

We really shouldn't be putting things like this in the runtime images. The CLI runner is better for debugging issues at runtime because you can change properties and the media to match a job that is failing.
___
*[cpp/OcvYoloDetection/KFTracker.h, line 39 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/284#-MtmuvAtCaKcZi2jTpht:-MtmuvAuEd_C6qM3F0ah:b-iby17t) ([raw file](https://github.com/openmpf/openmpf-components/blob/be361d579ee6dfbed4b5010619ae3e41dc5b8dae/cpp/OcvYoloDetection/KFTracker.h#L39)):*
> ```objc
> 
> 
> using namespace std;
> ```

`using namespace ...` should never appear in a header file because it will be applied to everything that `#include`s the header.
___
*[cpp/OcvYoloDetection/KFTracker.h, line 63 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/284#-MtmvkVw9RLwsM9dAo5D:-MtmvkVw9RLwsM9dAo5E:b-osxpu2) ([raw file](https://github.com/openmpf/openmpf-components/blob/be361d579ee6dfbed4b5010619ae3e41dc5b8dae/cpp/OcvYoloDetection/KFTracker.h#L63)):*
> ```objc
>               const cv::Mat1f &qn);
> 
>     KFTracker(KFTracker &&kft) noexcept: _kf(move(kft._kf)),
> ```

This shouldn't be declared `noexcept` because moving`cv::KalmanFilter` and `cv::Mat1f ` can throw. This can be verified because these produce errors:
```
static_assert(std::is_nothrow_move_constructible<cv::Mat1f>::value, "Is not move constructible");
static_assert(std::is_nothrow_move_constructible<cv::KalmanFilter>::value, "Is not move constructible");
```
___
*[cpp/OcvYoloDetection/OcvYoloDetection.cpp, line 233 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/284#-MtmyYvt12_C-cG7fNTZ:-MtmyYvt12_C-cG7fNT_:b2cvqbk) ([raw file](https://github.com/openmpf/openmpf-components/blob/be361d579ee6dfbed4b5010619ae3e41dc5b8dae/cpp/OcvYoloDetection/OcvYoloDetection.cpp#L233)):*
> ```cpp
>     LOG_DEBUG("Initializing OcvYoloDetector");
> 
>     srand(time(NULL));
> ```

Why is this necessary? Using the same seed every time will make the results deterministic.
___
*[cpp/OcvYoloDetection/OcvYoloDetection.cpp, line 266 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/284#-MtmzSk3EXMnkODxcPio:-MtmzSk4ChxFDyH_nk3R:b1isj8e) ([raw file](https://github.com/openmpf/openmpf-components/blob/be361d579ee6dfbed4b5010619ae3e41dc5b8dae/cpp/OcvYoloDetection/OcvYoloDetection.cpp#L266)):*
> ```cpp
>     }
> 
>     yoloNetwork_.reset(new YoloNetwork(std::move(modelSettings), config));
> ```

This should not have been changed. As the removed comment states, by making this change, there are temporarily two instances of the yolo network in memory at once. Maybe it isn't obvious initially, but `new YoloNetwork` is executed before `yoloNetwork_.reset` and the old network is in memory until reset is called.  The yolo network is relatively large and it may be in GPU memory which we don't have a lot of.
___
*[cpp/OcvYoloDetection/triton/TritonInferencer.cpp, line 183 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/284#-Mtn_-Wz7VNRkEJuEUBz:-Mtn_-Wz7VNRkEJuEUC-:brzgbxp) ([raw file](https://github.com/openmpf/openmpf-components/blob/be361d579ee6dfbed4b5010619ae3e41dc5b8dae/cpp/OcvYoloDetection/triton/TritonInferencer.cpp#L183)):*
> ```cpp
> 
> 
> bool TritonInferencer::isShmKeyPrefixInUse(const std::string &prefix) {
> ```

You might be able to make this method const.
___
*[cpp/OcvYoloDetection/triton/TritonInferencer.cpp, line 192 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/284#-Mtn74ZmCFzQMri7UHSH:-Mtn74ZmCFzQMri7UHSI:b-vw9efw) ([raw file](https://github.com/openmpf/openmpf-components/blob/be361d579ee6dfbed4b5010619ae3e41dc5b8dae/cpp/OcvYoloDetection/triton/TritonInferencer.cpp#L192)):*
> ```cpp
>                 LOG_WARN("Shared memory prefix \"" << prefix << "\" in use by region on local host: "
>                          << diread->d_name << ". Will try another prefix.");
>                 return true;
> ```

I think you should be calling `closedir(dir);` before returning here.
___
*[cpp/OcvYoloDetection/triton/TritonInferencer.cpp, line 317 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/284#-MtnaaDZ47ioI9Pl3zA0:-MtnaaDZ47ioI9Pl3zA1:b5fcm4e) ([raw file](https://github.com/openmpf/openmpf-components/blob/be361d579ee6dfbed4b5010619ae3e41dc5b8dae/cpp/OcvYoloDetection/triton/TritonInferencer.cpp#L317)):*
> ```cpp
> 
> void TritonInferencer::waitTillAllClientsReleased() noexcept {
>     if (freeClientIds_.size() != clients_.size()) {
> ```

Accessing `freeClientIds_` here is unsafe. I think you should just remove the conditional here. You don't need to check the sizes between `std::unique_lock<std::mutex> lk(freeClientIdsMtx_);` and `freeClientIdsCv_.wait`. The condition variable will check the lambda before actually waiting. 
___
*[cpp/OcvYoloDetection/triton/TritonInferencer.cpp, line 329 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/284#-Mtnfi_N2XqfOb-x6i1G:-Mtnfi_N2XqfOb-x6i1H:b-jxtao3) ([raw file](https://github.com/openmpf/openmpf-components/blob/be361d579ee6dfbed4b5010619ae3e41dc5b8dae/cpp/OcvYoloDetection/triton/TritonInferencer.cpp#L329)):*
> ```cpp
> 
> void TritonInferencer::rethrowClientException() {
>     if (clientEptr_) {
> ```

I think you need to acquire the mutex here because `clientEptr_` is set by another thread.
___
*[cpp/OcvYoloDetection/triton_server/Dockerfile, line 45 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/284#-MtmjLGk4DFsm0I5Ys9i:-MtmjLGk4DFsm0I5Ys9j:bc99mci) ([raw file](https://github.com/openmpf/openmpf-components/blob/be361d579ee6dfbed4b5010619ae3e41dc5b8dae/cpp/OcvYoloDetection/triton_server/Dockerfile#L45)):*
> ```Dockerfile
> RUN --mount=type=tmpfs,target=/tmp \
>     cd /tmp; \
>     git clone https://github.com/openmpf/yolov4-triton-tensorrt.git; \
> ```

In Dockerfiles, I download repos like this: `curl -L https://github.com/openmpf/yolov4-triton-tensorrt/archive/refs/heads/openmpf/dim-608.tar.gz | tar --extract --gzip`.  This is to avoid downloading the repo history and so that we do [...]

2022-01-21 03:30 UTC, jrobble reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/284)* status: 41 of 60 files reviewed, 17 unresolved discussions (waiting on @brosenberg42)

___
*[cpp/OcvYoloDetection/CMakeLists.txt, line 35 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/284#-MtmpLQr9Pd8ARUBy75E:-MtoJSix35JzL0C3PuJz:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/be361d579ee6dfbed4b5010619ae3e41dc5b8dae/cpp/OcvYoloDetection/CMakeLists.txt#L35)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

The build type should be set to Release.
</blockquote></details>

Done.
___
*[cpp/OcvYoloDetection/Config.cpp, line 56 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/284#-MtmqMg-32aFRkqv_-Ua:-MtoJuiZ311ex5Ov7Tx3:bj26dvg) ([raw file](https://github.com/openmpf/openmpf-components/blob/be361d579ee6dfbed4b5010619ae3e41dc5b8dae/cpp/OcvYoloDetection/Config.cpp#L56)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

The common style for constructor initialization lists is to have the leading commas like the code did before this change.
</blockquote></details>

`Code --> Reformat Code` in CLion changes it to this style by default, but I'll change it back.
___
*[cpp/OcvYoloDetection/Dockerfile, line 233 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/284#-MtmsYdt8OkW6QknKJf8:-MtucdhR0OAtafuFzXmK:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/be361d579ee6dfbed4b5010619ae3e41dc5b8dae/cpp/OcvYoloDetection/Dockerfile#L233)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

We really shouldn't be putting things like this in the runtime images. The CLI runner is better for debugging issues at runtime because you can change properties and the media to match a job that is failing.
</blockquote></details>

Done.
___
*[cpp/OcvYoloDetection/KFTracker.h, line 39 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/284#-MtmuvAtCaKcZi2jTpht:-MtteyO-DAOAj98-r-Us:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/be361d579ee6dfbed4b5010619ae3e41dc5b8dae/cpp/OcvYoloDetection/KFTracker.h#L39)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

`using namespace ...` should never appear in a header file because it will be applied to everything that `#include`s the header.
</blockquote></details>

Done.
___
*[cpp/OcvYoloDetection/KFTracker.h, line 63 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/284#-MtmvkVw9RLwsM9dAo5D:-MtoM0WoEaKmnOMnGakL:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/be361d579ee6dfbed4b5010619ae3e41dc5b8dae/cpp/OcvYoloDetection/KFTracker.h#L63)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

This shouldn't be declared `noexcept` because moving`cv::KalmanFilter` and `cv::Mat1f ` can throw. This can be verified because these produce errors:
```
static_assert(std::is_nothrow_move_constructible<cv::Mat1f>::value, "Is not move constructible");
static_assert(std::is_nothrow_move_constructible<cv::KalmanFilter>::value, "Is not move constructible");
```
</blockquote></details>

Done.
___
*[cpp/OcvYoloDetection/OcvYoloDetection.cpp, line 233 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/284#-MtmyYvt12_C-cG7fNTZ:-MtoMfZGD1OP9ceXKpL_:b-f5ik5d) ([raw file](https://github.com/openmpf/openmpf-components/blob/be361d579ee6dfbed4b5010619ae3e41dc5b8dae/cpp/OcvYoloDetection/OcvYoloDetection.cpp#L233)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Why is this necessary? Using the same seed every time will make the results deterministic.
</blockquote></details>

`rand()` is used here:

```
std::string getRandomShmKeyPrefix() {
    std::stringstream ss;
    ss << "/OcvYoloDetection_" << hostname() << "_" << std::setw(10) << std::setfill('0') << rand();
    return ss.str();
}
```

`time(NULL)` returns the number of seconds since the epoch. That will generally result in a unique seed. Here's what I get on two separate runs:

```
t: 1642630652
t: 1642630699
```
___
*[cpp/OcvYoloDetection/OcvYoloDetection.cpp, line 266 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/284#-MtmzSk3EXMnkODxcPio:-MtoQiIA1bV8xid48fZX:bqwjjpa) ([raw file](https://github.com/openmpf/openmpf-components/blob/be361d579ee6dfbed4b5010619ae3e41dc5b8dae/cpp/OcvYoloDetection/OcvYoloDetection.cpp#L266)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

This should not have been changed. As the removed comment states, by making this change, there are temporarily two instances of the yolo network in memory at once. Maybe it isn't obvious initially, but `new YoloNetwork` is executed before `yoloNetwork_.reset` and the old network is in memory until reset is called.  The yolo network is relatively large and it may be in GPU memory which we don't have a lot of.
</blockquote></details>

I was not aware. It seemed redundant to call `reset()` twice, but what you said about keeping two instances in memory makes sense.
___
*[cpp/OcvYoloDetection/triton/TritonInferencer.cpp, line 183 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/284#-Mtn_-Wz7VNRkEJuEUBz:-MtoReM7ED2U7jWYloC_:bggs6yu) ([raw file](https://github.com/openmpf/openmpf-components/blob/be361d579ee6dfbed4b5010619ae3e41dc5b8dae/cpp/OcvYoloDetection/triton/TritonInferencer.cpp#L183)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

You might be able to make this method const.
</blockquote></details>

I can. Done.
___
*[cpp/OcvYoloDetection/triton/TritonInferencer.cpp, line 192 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/284#-Mtn74ZmCFzQMri7UHSH:-MtoRlna9YXxyNkCCgEi:b6zrrkh) ([raw file](https://github.com/openmpf/openmpf-components/blob/be361d579ee6dfbed4b5010619ae3e41dc5b8dae/cpp/OcvYoloDetection/triton/TritonInferencer.cpp#L192)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I think you should be calling `closedir(dir);` before returning here.
</blockquote></details>

Good catch.
___
*[cpp/OcvYoloDetection/triton/TritonInferencer.cpp, line 317 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/284#-MtnaaDZ47ioI9Pl3zA0:-MtoT6KM8R-zMyMLefGr:bb6un1j) ([raw file](https://github.com/openmpf/openmpf-components/blob/be361d579ee6dfbed4b5010619ae3e41dc5b8dae/cpp/OcvYoloDetection/triton/TritonInferencer.cpp#L317)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Accessing `freeClientIds_` here is unsafe. I think you should just remove the conditional here. You don't need to check the sizes between `std::unique_lock<std::mutex> lk(freeClientIdsMtx_);` and `freeClientIdsCv_.wait`. The condition variable will check the lambda before actually waiting. 
</blockquote></details>

Done
___
*[cpp/OcvYoloDetection/triton/TritonInferencer.cpp, line 329 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/284#-Mtnfi_N2XqfOb-x6i1G:-MtoTkM17jlgW_EH6Hi4:b-essr4o) ([raw file](https://github.com/openmpf/openmpf-components/blob/be361d579ee6dfbed4b5010619ae3e41dc5b8dae/cpp/OcvYoloDetection/triton/TritonInferencer.cpp#L329)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I think you need to acquire the mutex here because `clientEptr_` is set by another thread.
</blockquote></details>

This function is only ever called here:

```
    void Finish() override {
        if (tritonInferencer_) {
            // wait for clients and check for client exception at the end of the job
            tritonInferencer_->waitTillAllClientsReleased();
            frameIdxComplete_ = -1;
            tritonInferencer_->rethrowClientException();
        }
    }
```

I was going to say that because `rethrowClientException` occurs after `waitTillAllClientsReleased` that it should not be possible for another thread [...]

2022-01-21 14:44 UTC, brosenberg42 requested changes
> Reviewed 19 of 19 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/284)* status: all files reviewed, 1 unresolved discussion (waiting on @jrobble)

___
*[cpp/OcvYoloDetection/OcvYoloDetection.cpp, line 233 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/284#-MtmyYvt12_C-cG7fNTZ:-Mtx0pPV8_ikdJ5iNA8Q:b2dpy6c) ([raw file](https://github.com/openmpf/openmpf-components/blob/be361d579ee6dfbed4b5010619ae3e41dc5b8dae/cpp/OcvYoloDetection/OcvYoloDetection.cpp#L233)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

`rand()` is used here:

```
std::string getRandomShmKeyPrefix() {
    std::stringstream ss;
    ss << "/OcvYoloDetection_" << hostname() << "_" << std::setw(10) << std::setfill('0') << rand();
    return ss.str();
}
```

`time(NULL)` returns the number of seconds since the epoch. That will generally result in a unique seed. Here's what I get on two separate runs:

```
t: 1642630652
t: 1642630699
```
</blockquote></details>

My concern here is that `srand` is a global change and parts of OpenCV might use `rand()`, so we might be introducing non-deterministic behavior when we don't need to be. The other thing is that if you really want unique seeds, one second is not precise enough. It is relatively likely that during a `docker stack deploy` multiple services will be started within a second. `std::random` lets you create a non-global rng. The example here: http://www.cplusplus.com/reference/random/uniform_int_distribution/uniform_int_distribution/ is pretty good except I would change it to use  `std::chrono::high_resolution_clock` instead of ` std::chrono::system_clock`.
___
*[cpp/OcvYoloDetection/triton_server/docker-entrypoint.sh, line 34 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/284#-MtmlAbCEYjE6p-Istsr:-Mtx3Qa0DTbyW1duT3oh:bus9lsl) ([raw file](https://github.com/openmpf/openmpf-components/blob/be361d579ee6dfbed4b5010619ae3e41dc5b8dae/cpp/OcvYoloDetection/triton_server/docker-entrypoint.sh#L34)):*
> I don't want anyone to provide a different LD_PRELOAD value in the service entry that omits the 608 plugin. 

If you wanted to do that, you would need something like:
`LD_PRELOAD=$LD_PRELOAD:/plugins/libyolo608layerplugin.so`


<!-- Sent from Reviewable.io -->

2022-01-21 19:32 UTC, jrobble reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/284)* status: 57 of 60 files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

___
*[cpp/OcvYoloDetection/OcvYoloDetection.cpp, line 233 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/284#-MtmyYvt12_C-cG7fNTZ:-MtxmJjm0oMcGG6zOzTq:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/be361d579ee6dfbed4b5010619ae3e41dc5b8dae/cpp/OcvYoloDetection/OcvYoloDetection.cpp#L233)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

My concern here is that `srand` is a global change and parts of OpenCV might use `rand()`, so we might be introducing non-deterministic behavior when we don't need to be. The other thing is that if you really want unique seeds, one second is not precise enough. It is relatively likely that during a `docker stack deploy` multiple services will be started within a second. `std::random` lets you create a non-global rng. The example here: http://www.cplusplus.com/reference/random/uniform_int_distribution/uniform_int_distribution/ is pretty good except I would change it to use  `std::chrono::high_resolution_clock` instead of ` std::chrono::system_clock`.
</blockquote></details>

Done.
___
*[cpp/OcvYoloDetection/triton_server/docker-entrypoint.sh, line 34 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/284#-MtmlAbCEYjE6p-Istsr:-Mty3ivX7UJ9BA7bIECT:b67faki) ([raw file](https://github.com/openmpf/openmpf-components/blob/be361d579ee6dfbed4b5010619ae3e41dc5b8dae/cpp/OcvYoloDetection/triton_server/docker-entrypoint.sh#L34)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

> I don't want anyone to provide a different LD_PRELOAD value in the service entry that omits the 608 plugin. 

If you wanted to do that, you would need something like:
`LD_PRELOAD=$LD_PRELOAD:/plugins/libyolo608layerplugin.so`
</blockquote></details>

As discussed:

Let's not do the `export`. I'll leave `ENV LD_PRELOAD /plugins/libyolo608layerplugin.so` in the `Dockerfile` since that will let things work if the user for some reason omits `LD_PRELOAD` from the service entry. This approach will enable them to completely override that default value by providing something else in the `LD_PRELOAD` service entry (they will also need to omit `--load-model=yolo-608` or there will be problems, but that's on them).


<!-- Sent from Reviewable.io -->

2022-01-21 19:50 UTC, brosenberg42 approved these changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/284)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jrobble)



<!-- Sent from Reviewable.io -->

2022-01-24 13:34 UTC, brosenberg42 approved these changes
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/284)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jrobble)



<!-- Sent from Reviewable.io -->

2022-01-24 20:08 UTC, merged