Feature/language pipeline
openmpf/openmpf-components pull request #296
Opened 2022-06-22 21:56 UTC by cdglasz

**Issues:**

- https://github.com/openmpf/openmpf/issues/1542

**Related PRs:**

- https://github.com/openmpf/openmpf/pull/63

2022-08-02 20:21 UTC, jrobble requested changes
> Reviewed 1 of 3 files at r3, 1 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/296)* status: 2 of 10 files reviewed, 10 unresolved discussions (waiting on @brosenberg42 and @cdglasz)

___
*[`python/AzureSpeechDetection/README.md` line 59 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/296#-N8UeP3g9Wo8tKGr5a_Y:-N8UeP3g9Wo8tKGr5a_Z:byhiqur) ([raw file](https://github.com/openmpf/openmpf-components/blob/eef0b35c3f249287f0a1505088a847614aca092a/python/AzureSpeechDetection/README.md#L59)):*
> ```Markdown
> 
> # Language Identifiers
> The following are the BCP-47 codes and their corresponding languages which Azure Speech-to-Text supports. The third column indicates whether the language is also supported by a proprietary upstream language identification component, and the corresponding ISO 639-3 language code that it will pass forward in a feed-forward track. For languages with multiple dialects, a BCP-47 locale was chosen according to internal data, which may not be desirable in all cases. This selection can be altered by editing `acs_speech_component/azure_utils.py`.
> ```

Explain what happens when there isn't a mapping.
___
*[`python/AzureSpeechDetection/README.md` line 68 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/296#-N8UeK6u7_Y2IJw7GRmE:-N8UeK6u7_Y2IJw7GRmF:byutljl) ([raw file](https://github.com/openmpf/openmpf-components/blob/eef0b35c3f249287f0a1505088a847614aca092a/python/AzureSpeechDetection/README.md#L68)):*
> ```Markdown
> | Arabic (Algeria)               | `ar-DZ` |           |
> | Arabic (Bahrain)               | `ar-BH` |           |
> | Arabic (Egypt)                 | `ar-EG` |  `ARA`*   |
> ```

What does the asterisk mean?

---

Looking at the code, I now understand that's the BCP-47 locale chosen for the ISO 639-3 code. What's confusing is why the other locales are listed.

I think we should separate the complete list of supported BCP-47 locals from the mapping.

There are really two uses cases:

1. Using Azure Speech directly
2. Using Azure Speech as a downstream processor

The first table, relevant to using Azure speech directly, should list all of the locales.

The second table, relevant to using Azure speech as a downstream processor, should show the ISO 639-3 code in the first column and corresponding BCP-47 local (just one) in the second column.
___
*[`python/AzureSpeechDetection/acs_speech_component/acs_speech_component.py` line 337 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/296#-N8V6M0NDviUmhZjIWAs:-N8V6M0NDviUmhZjIWAt:b-otcvtr) ([raw file](https://github.com/openmpf/openmpf-components/blob/eef0b35c3f249287f0a1505088a847614aca092a/python/AzureSpeechDetection/acs_speech_component/acs_speech_component.py#L337)):*
> ```Python
>             # If trigger key is in feed-forward properties, only run
>             #  transcription if the value matches trigger_val
>             if not (t_key in det_props and det_props[t_key] == t_val):
> ```

First check if "TRIGGER" is even provided in the feed-forward props.
___
*[`python/AzureSpeechDetection/acs_speech_component/acs_speech_component.py` line 399 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/296#-N8V7lik8S1AMVcLadrk:-N8V7lio76oUaReTQ5Ug:b-1dh8ya) ([raw file](https://github.com/openmpf/openmpf-components/blob/eef0b35c3f249287f0a1505088a847614aca092a/python/AzureSpeechDetection/acs_speech_component/acs_speech_component.py#L399)):*
Video jobs have both a "DURATION" and "FRAME_COUNT". If this is a video job, you set t0 and t1 based on frames above:

> t0, t1 = job.start_frame, job.stop_frame

However, in this line you compare t1 to "DURATION". It seems strange to compare frame numbers to millisecond duration.
___
*[`python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py` line 90 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/296#-N8V9cI6AWk96mAKfadz:-N8V9cI9Di9t5axPx9il:b-c1pqg0) ([raw file](https://github.com/openmpf/openmpf-components/blob/eef0b35c3f249287f0a1505088a847614aca092a/python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py#L90)):*
> ```Python
>                 stop -= media_start_time
> 
>                 # Convert from integer milliseconds to float seconds
> ```

I don't see a conversion.
___
*[`python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py` line 107 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/296#-N8VABpl8gH2ukr3c4vt:-N8VABpl8gH2ukr3c4vu:b-4bkkiw) ([raw file](https://github.com/openmpf/openmpf-components/blob/eef0b35c3f249287f0a1505088a847614aca092a/python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py#L107)):*
> ```Python
> 
>     @staticmethod
>     def desegment_times(
> ```

Where is this used?
___
*[`python/AzureSpeechDetection/acs_speech_component/azure_utils.py` line 2 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/296#-N8Uef5y012UJ_xu5ufH:-N8Uef5y012UJ_xu5ufI:b-tgrjbh) ([raw file](https://github.com/openmpf/openmpf-components/blob/eef0b35c3f249287f0a1505088a847614aca092a/python/AzureSpeechDetection/acs_speech_component/azure_utils.py#L2)):*
> ```Python
> 
> ISO6393_2_BCP47 = dict(
> ```

Missing header comment blocks.
___
*[`python/AzureSpeechDetection/acs_speech_component/azure_utils.py` line 2 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/296#-N8Uf2j3AHluHZEuTB40:-N8Uf2j3AHluHZEuTB41:bd72tu8) ([raw file](https://github.com/openmpf/openmpf-components/blob/eef0b35c3f249287f0a1505088a847614aca092a/python/AzureSpeechDetection/acs_speech_component/azure_utils.py#L2)):*
> ```Python
> 
> ISO6393_2_BCP47 = dict(
> ```

Please call this`ISO6393_TO_BCP47`.
___
*[`python/AzureSpeechDetection/acs_speech_component/azure_utils.py` line 2 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/296#-N8UfZZMEFxtjMqlMoAE:-N8UfZZN4ugFHx8WEihn:b-1x5wub) ([raw file](https://github.com/openmpf/openmpf-components/blob/eef0b35c3f249287f0a1505088a847614aca092a/python/AzureSpeechDetection/acs_speech_component/azure_utils.py#L2)):*
> ```Python
> 
> ISO6393_2_BCP47 = dict(
> ```

Add a comment in this file explaining how the first language in the mapping is selected. Specifically, in the code you do:

```
language=languages[0],
```
___
*[`python/AzureSpeechDetection/plugin-files/descriptor/descriptor.json` line 133 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/296#-N8VCBfr1Q9-blSXRQ3Y:-N8VCBfsDJayGCo3Jjy8:brdloop) ([raw file](https://github.com/openmpf/openmpf-components/blob/eef0b35c3f249287f0a1505088a847614aca092a/python/AzureSpeechDetection/plugin-files/descriptor/descriptor.json#L133)):*
> ```JSON
>           "value": "SPEECH_DETECTOR=AZURESPEECH"
>         },
> 	{
> ```

Indentation is off.


<!-- Sent from Reviewable.io -->

2022-08-02 20:21 UTC, jrobble requested changes
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/296)* status: 2 of 10 files reviewed, 11 unresolved discussions (waiting on @brosenberg42 and @cdglasz)

___
*[`python/AzureSpeechDetection/README.md` line 59 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/296#-N8Udyep37gMX_HibYVm:-N8Udyes5UdT3PnKSHPP:b-3gkat0) ([raw file](https://github.com/openmpf/openmpf-components/blob/eef0b35c3f249287f0a1505088a847614aca092a/python/AzureSpeechDetection/README.md#L59)):*
You can just say:

> whether the language is also supported by an upstream language identification component


<!-- Sent from Reviewable.io -->

2022-08-02 20:22 UTC, jrobble reviewed
> Reviewed 2 of 10 files at r1, 6 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/296)* status: all files reviewed, 11 unresolved discussions (waiting on @brosenberg42 and @cdglasz)



<!-- Sent from Reviewable.io -->

2022-08-02 21:11 UTC, jrobble requested changes
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/296)* status: all files reviewed, 12 unresolved discussions (waiting on @brosenberg42 and @cdglasz)

___
*[`python/AzureSpeechDetection/plugin-files/descriptor/descriptor.json` line 126 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/296#-N8VGvo45px5sBt7CM0N:-N8VGvo56KTa0U8aA6lW:b-at2drx) ([raw file](https://github.com/openmpf/openmpf-components/blob/eef0b35c3f249287f0a1505088a847614aca092a/python/AzureSpeechDetection/plugin-files/descriptor/descriptor.json#L126)):*
I was going to say Change "perform speech-to-text in with language" to "perform speech-to-text with language"; however, in a different component this behavior is described as:

> Runs ALG on audio or video using language provided in feed-forward track.

I think the latter description is more concise, so we should use that in all of the downstream component actions.


<!-- Sent from Reviewable.io -->

2022-08-04 20:04 UTC, jrobble reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/296)* status: all files reviewed, 11 unresolved discussions (waiting on @brosenberg42 and @cdglasz)

___
*[`python/AzureSpeechDetection/acs_speech_component/acs_speech_component.py` line 337 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/296#-N8V6M0NDviUmhZjIWAs:-N8eSHTt7_APuj6UtDMi:bgo1jbe) ([raw file](https://github.com/openmpf/openmpf-components/blob/eef0b35c3f249287f0a1505088a847614aca092a/python/AzureSpeechDetection/acs_speech_component/acs_speech_component.py#L337)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

First check if "TRIGGER" is even provided in the feed-forward props.
</blockquote></details>

Never mind. This is fine. My misunderstanding.


<!-- Sent from Reviewable.io -->

2022-08-08 15:32 UTC, brosenberg42 requested changes
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/296)* status: all files reviewed, 16 unresolved discussions (waiting on @cdglasz)

___
*[`python/AzureSpeechDetection/acs_speech_component/acs_speech_component.py` line 479 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/296#-N8y2bYg4P4HY88zzHZf:-N8y2bYg4P4HY88zzHZg:b-ptd5iy) ([raw file](https://github.com/openmpf/openmpf-components/blob/eef0b35c3f249287f0a1505088a847614aca092a/python/AzureSpeechDetection/acs_speech_component/acs_speech_component.py#L479)):*
> ```Python
> 
>         except Exception as e:
>             logger.exception('Exception raised while converting to video track: {e}')
> ```

The string is missing the leading f.
___
*[`python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py` line 107 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/296#-N8xxktW1Kbt6JGg9NDN:-N8xxktW1Kbt6JGg9NDO:beux6a3) ([raw file](https://github.com/openmpf/openmpf-components/blob/eef0b35c3f249287f0a1505088a847614aca092a/python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py#L107)):*
> ```Python
> 
>     @staticmethod
>     def desegment_times(
> ```

I think calling this from process_audio is better than including the code in process_audio.
___
*[`python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py` line 114 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/296#-N8UzSm84exV-AIsAX2u:-N8UzSm84exV-AIsAX2v:bgds1zh) ([raw file](https://github.com/openmpf/openmpf-components/blob/eef0b35c3f249287f0a1505088a847614aca092a/python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py#L114)):*
> ```Python
> 
>             :param regions: sorted RegionScores
>             :param annotation_regions: sorted AnnotationRegions
> ```

The parameter names in the comment don't match the actual parameter names.
___
*[`python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py` line 193 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/296#-N8dJ_kn4EIU6SgJKB-H:-N8dJ_kn4EIU6SgJKB-I:bwo1p0h) ([raw file](https://github.com/openmpf/openmpf-components/blob/eef0b35c3f249287f0a1505088a847614aca092a/python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py#L193)):*
> ```Python
>                 if 'This locale does not support diarization' in str(e):
>                     self.logger.warning(
>                         f'Locale "{lang}" does not support diarization. '
> ```

`"{lang}"` needs to be changed to `"{language}"`
___
*[`python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py` line 225 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/296#-N8xZlM1-kI1VD6ABaou:-N8xZlM1-kI1VD6ABaov:b156wq6) ([raw file](https://github.com/openmpf/openmpf-components/blob/eef0b35c3f249287f0a1505088a847614aca092a/python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py#L225)):*
> ```Python
>             #  feedforward segment, so that utterance timestamps can be shifted
>             #  to be relative to the beginning of the input audio file.
>             segbegs, segends, seglens = zip(*(
> ```

`segends` is not used


<!-- Sent from Reviewable.io -->

2022-08-15 17:56 UTC, cdglasz reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/296)* status: 9 of 10 files reviewed, 16 unresolved discussions (waiting on @cdglasz and @jrobble)

___
*[`python/AzureSpeechDetection/README.md` line 59 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/296#-N8UeP3g9Wo8tKGr5a_Y:-N9XdcDVB9k3FHfixJPh:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/eef0b35c3f249287f0a1505088a847614aca092a/python/AzureSpeechDetection/README.md#L59)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Explain what happens when there isn't a mapping.
</blockquote></details>

Done.
___
*[`python/AzureSpeechDetection/README.md` line 59 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/296#-N8Udyep37gMX_HibYVm:-N9Xddgy7IRGuCVoVF3U:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/eef0b35c3f249287f0a1505088a847614aca092a/python/AzureSpeechDetection/README.md#L59)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

You can just say:

> whether the language is also supported by an upstream language identification component
</blockquote></details>

Done.
___
*[`python/AzureSpeechDetection/README.md` line 68 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/296#-N8UeK6u7_Y2IJw7GRmE:-N9Xdg8jEBOGmgFp_2we:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/eef0b35c3f249287f0a1505088a847614aca092a/python/AzureSpeechDetection/README.md#L68)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

What does the asterisk mean?

---

Looking at the code, I now understand that's the BCP-47 locale chosen for the ISO 639-3 code. What's confusing is why the other locales are listed.

I think we should separate the complete list of supported BCP-47 locals from the mapping.

There are really two uses cases:

1. Using Azure Speech directly
2. Using Azure Speech as a downstream processor

The first table, relevant to using Azure speech directly, should list all of the locales.

The second table, relevant to using Azure speech as a downstream processor, should show the ISO 639-3 code in the first column and corresponding BCP-47 local (just one) in the second column.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-16 16:32 UTC, cdglasz reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/296)* status: 7 of 10 files reviewed, 16 unresolved discussions (waiting on @cdglasz and @jrobble)

___
*[`python/AzureSpeechDetection/acs_speech_component/acs_speech_component.py` line 399 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/296#-N8V7lik8S1AMVcLadrk:-N9bUhL05eC3QW08Qbbq:b-dltd) ([raw file](https://github.com/openmpf/openmpf-components/blob/eef0b35c3f249287f0a1505088a847614aca092a/python/AzureSpeechDetection/acs_speech_component/acs_speech_component.py#L399)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Video jobs have both a "DURATION" and "FRAME_COUNT". If this is a video job, you set t0 and t1 based on frames above:

> t0, t1 = job.start_frame, job.stop_frame

However, in this line you compare t1 to "DURATION". It seems strange to compare frame numbers to millisecond duration.
</blockquote></details>

Switched things around to use FRAME_COUNT first
___
*[`python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py` line 90 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/296#-N8V9cI6AWk96mAKfadz:-N9XevTjD8DWHkje3FQD:b9ni7az) ([raw file](https://github.com/openmpf/openmpf-components/blob/eef0b35c3f249287f0a1505088a847614aca092a/python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py#L90)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I don't see a conversion.
</blockquote></details>

I believe this is a hold-over from another component where the conversion was necessary. Misleading comment removed.


<!-- Sent from Reviewable.io -->

2022-08-16 16:42 UTC, cdglasz reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/296)* status: 7 of 10 files reviewed, 16 unresolved discussions (waiting on @brosenberg42, @cdglasz, and @jrobble)

___
*[`python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py` line 107 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/296#-N8VABpl8gH2ukr3c4vt:-N9bWbSL5dS0ISmJwgrU:b-291z69) ([raw file](https://github.com/openmpf/openmpf-components/blob/eef0b35c3f249287f0a1505088a847614aca092a/python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py#L107)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Where is this used?
</blockquote></details>

Functionality had been absorbed into main processing function, reworked it back into this one. Now used.
___
*[`python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py` line 107 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/296#-N8xxktW1Kbt6JGg9NDN:-N9bWovvDwFfOV_gmq62:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/eef0b35c3f249287f0a1505088a847614aca092a/python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py#L107)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I think calling this from process_audio is better than including the code in process_audio.
</blockquote></details>

Done.
___
*[`python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py` line 114 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/296#-N8UzSm84exV-AIsAX2u:-N9bWpjd8ioM6vY85kNF:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/eef0b35c3f249287f0a1505088a847614aca092a/python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py#L114)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

The parameter names in the comment don't match the actual parameter names.
</blockquote></details>

Done.
___
*[`python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py` line 225 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/296#-N8xZlM1-kI1VD6ABaou:-N9bX7xECl268oNrcFh7:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/eef0b35c3f249287f0a1505088a847614aca092a/python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py#L225)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

`segends` is not used
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-16 16:48 UTC, cdglasz reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/296)* status: 6 of 10 files reviewed, 16 unresolved discussions (waiting on @brosenberg42, @cdglasz, and @jrobble)

___
*[`python/AzureSpeechDetection/acs_speech_component/azure_utils.py` line 2 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/296#-N8Uef5y012UJ_xu5ufH:-N9bYh30C410fBpZn_lY:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/eef0b35c3f249287f0a1505088a847614aca092a/python/AzureSpeechDetection/acs_speech_component/azure_utils.py#L2)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Missing header comment blocks.
</blockquote></details>

Done.
___
*[`python/AzureSpeechDetection/acs_speech_component/azure_utils.py` line 2 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/296#-N8Uf2j3AHluHZEuTB40:-N9bYhIMEp7sQKGYnyh3:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/eef0b35c3f249287f0a1505088a847614aca092a/python/AzureSpeechDetection/acs_speech_component/azure_utils.py#L2)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please call this`ISO6393_TO_BCP47`.
</blockquote></details>

Done.
___
*[`python/AzureSpeechDetection/acs_speech_component/azure_utils.py` line 2 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/296#-N8UfZZMEFxtjMqlMoAE:-N9bYhfiDLnWLlUGp1Td:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/eef0b35c3f249287f0a1505088a847614aca092a/python/AzureSpeechDetection/acs_speech_component/azure_utils.py#L2)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Add a comment in this file explaining how the first language in the mapping is selected. Specifically, in the code you do:

```
language=languages[0],
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-16 16:54 UTC, cdglasz reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/296)* status: 5 of 10 files reviewed, 16 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[`python/AzureSpeechDetection/acs_speech_component/acs_speech_component.py` line 479 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/296#-N8y2bYg4P4HY88zzHZf:-N9bZS7y1RT7gr7U-sOW:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/eef0b35c3f249287f0a1505088a847614aca092a/python/AzureSpeechDetection/acs_speech_component/acs_speech_component.py#L479)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

The string is missing the leading f.
</blockquote></details>

Done.
___
*[`python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py` line 193 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/296#-N8dJ_kn4EIU6SgJKB-H:-N9bZwRe8smWtbfdpbRq:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/eef0b35c3f249287f0a1505088a847614aca092a/python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py#L193)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

`"{lang}"` needs to be changed to `"{language}"`
</blockquote></details>

Done.
___
*[`python/AzureSpeechDetection/plugin-files/descriptor/descriptor.json` line 126 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/296#-N8VGvo45px5sBt7CM0N:-N9bZQnkDvBzbiZM8ia5:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/eef0b35c3f249287f0a1505088a847614aca092a/python/AzureSpeechDetection/plugin-files/descriptor/descriptor.json#L126)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I was going to say Change "perform speech-to-text in with language" to "perform speech-to-text with language"; however, in a different component this behavior is described as:

> Runs ALG on audio or video using language provided in feed-forward track.

I think the latter description is more concise, so we should use that in all of the downstream component actions.
</blockquote></details>

Done.
___
*[`python/AzureSpeechDetection/plugin-files/descriptor/descriptor.json` line 133 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/296#-N8VCBfr1Q9-blSXRQ3Y:-N9bZR2C2n-mevtLpUm1:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/eef0b35c3f249287f0a1505088a847614aca092a/python/AzureSpeechDetection/plugin-files/descriptor/descriptor.json#L133)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Indentation is off.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-21 22:15 UTC, jrobble requested changes
> Reviewed 1 of 1 files at r5, 1 of 2 files at r8, 1 of 4 files at r9, 1 of 3 files at r10, 1 of 3 files at r11, 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/296)* status: all files reviewed, 1 unresolved discussion (waiting on @cdglasz)

___
*[`python/AzureSpeechDetection/tests/create_test_case.py` line 110 at r12](https://reviewable.io/reviews/openmpf/openmpf-components/296#-NCWgIJ-AEh6gjR0qiDX:-NCWgIJ22aRgRjjiav6Z:brsmf5i) ([raw file](https://github.com/openmpf/openmpf-components/blob/e33350f27e91db2bc6a6120507f10e96014690a1/python/AzureSpeechDetection/tests/create_test_case.py#L110)):*
> ```Python
> 
>     comp = AcsSpeechComponent()
>     parsed_properties = comp._parse_job_props(properties)
> ```

`_parse_job_props` is not defined in the AcsSpeechComponent.


<!-- Sent from Reviewable.io -->

2022-09-28 18:22 UTC, cdglasz reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/296)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @brosenberg42 and @jrobble)

___
*[`python/AzureSpeechDetection/tests/create_test_case.py` line 110 at r12](https://reviewable.io/reviews/openmpf/openmpf-components/296#-NCWgIJ-AEh6gjR0qiDX:-ND4KYw94Ov74VdIMCXA:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/e33350f27e91db2bc6a6120507f10e96014690a1/python/AzureSpeechDetection/tests/create_test_case.py#L110)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

`_parse_job_props` is not defined in the AcsSpeechComponent.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-09 02:26 UTC, jrobble requested changes
> Reviewed 1 of 1 files at r13, 1 of 4 files at r14.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/296)* status: 7 of 11 files reviewed, 1 unresolved discussion (waiting on @brosenberg42 and @cdglasz)

___
*[`python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py` line 210 at r15](https://reviewable.io/reviews/openmpf/openmpf-components/296#-NIndQ8_8TENuEezIeoJ:-NIndQ8b-2RtCz31pbnY:bf4rmwj) ([raw file](https://github.com/openmpf/openmpf-components/blob/e32e100145367f7801827a92fe20508028c12b7f/python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py#L210)):*
I see:

> Neither the language supplied in feed-forward track (URD), nor any other detected language are supported. Transcribing with component default (en-US) instead.

In cases like this, please add the unsupported language (URD) to `MISSING_LANGUAGE_MODELS` for consistency.

---

Looking at all of the tracks where `urd` is used, they have `"SPEAKER_LANGUAGES": "urd, eng"`. Trying to figure out why the log message says "nor any other detected language are supported" because `eng` is in the list.

This is the speaker detection track being fed into Azure:

```json
                     {
                        "index": 2,
                        "id": "9b76c89ca19e11f204ad05f99815d3bd72f745269553870a77a381415ae31c85",
                        "startOffsetFrame": 0,
                        "stopOffsetFrame": 0,
                        "startOffsetTime": 7117,
                        "stopOffsetTime": 17817,
                        "type": "SPEECH",
                        "source": "+#SOMEALG SPEAKER DETECTION (EQUAL PRIORITY AZURE) ACTION",
                        "confidence": 0.26245913,
                        "trackProperties": {
                           "GENDER": "male",
                           "GENDER_CONFIDENCE": "0.8141511789470208",
                           "LANGUAGE": "urd",
                           "LONG_SPEAKER_ID": "0-EOF-3",
                           "SPEAKER_ID": "3",
                           "SPEAKER_LANGUAGES": "urd, eng",
                           "SPEAKER_LANGUAGE_CONFIDENCES": "0.2624591258361664, -1.0",
                           "SPEECH_DETECTOR": "AZURESPEECH",
                           "VOICED_SEGMENTS": "7117-8267, 16657-17817"
                        },
```

I saw that in upstream speaker detection stage that you force the default language(s) (`eng`) to be added to the `SPEAKER_LANGUAGES`. I understand why that is. It's just that it doesn't seem to be used properly downstream.

I think you want to convert the `lang` to uppercase with you use the map in this line:

```
if lang not in ISO6393_TO_BCP47:
```

Before we get to the above line, in this code you convert to lowercase:

```
        languages = [lab.strip().lower() for lab in languages.split(',')]
        language_scores = [float(s.strip()) for s in language_scores.split(',')]
        language_scores = defaultdict(
            lambda: -1.0,
            zip(languages, language_scores)
        )
```


<!-- Sent from Reviewable.io -->

2023-01-03 19:47 UTC, cdglasz reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/296)* status: 7 of 11 files reviewed, 1 unresolved discussion (waiting on @brosenberg42 and @jrobble)

___
*[`python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py` line 210 at r15](https://reviewable.io/reviews/openmpf/openmpf-components/296#-NIndQ8_8TENuEezIeoJ:-NKsmtniC0LvSMm-J-wi:bkjjmg7) ([raw file](https://github.com/openmpf/openmpf-components/blob/e32e100145367f7801827a92fe20508028c12b7f/python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py#L210)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I see:

> Neither the language supplied in feed-forward track (URD), nor any other detected language are supported. Transcribing with component default (en-US) instead.

In cases like this, please add the unsupported language (URD) to `MISSING_LANGUAGE_MODELS` for consistency.

---

Looking at all of the tracks where `urd` is used, they have `"SPEAKER_LANGUAGES": "urd, eng"`. Trying to figure out why the log message says "nor any other detected language are supported" because `eng` is in the list.

This is the speaker detection track being fed into Azure:

```json
                     {
                        "index": 2,
                        "id": "9b76c89ca19e11f204ad05f99815d3bd72f745269553870a77a381415ae31c85",
                        "startOffsetFrame": 0,
                        "stopOffsetFrame": 0,
                        "startOffsetTime": 7117,
                        "stopOffsetTime": 17817,
                        "type": "SPEECH",
                        "source": "+#SOMEALG SPEAKER DETECTION (EQUAL PRIORITY AZURE) ACTION",
                        "confidence": 0.26245913,
                        "trackProperties": {
                           "GENDER": "male",
                           "GENDER_CONFIDENCE": "0.8141511789470208",
                           "LANGUAGE": "urd",
                           "LONG_SPEAKER_ID": "0-EOF-3",
                           "SPEAKER_ID": "3",
                           "SPEAKER_LANGUAGES": "urd, eng",
                           "SPEAKER_LANGUAGE_CONFIDENCES": "0.2624591258361664, -1.0",
                           "SPEECH_DETECTOR": "AZURESPEECH",
                           "VOICED_SEGMENTS": "7117-8267, 16657-17817"
                        },
```

I saw that in upstream speaker detection stage that you force the default language(s) (`eng`) to be added to the `SPEAKER_LANGUAGES`. I understand why that is. It's just that it doesn't seem to be used properly downstream.

I think you want to convert the `lang` to uppercase with you use the map in this line:

```
if lang not in ISO6393_TO_BCP47:
```

Before we get to the above line, in this code you convert to lowercase:

```
        languages = [lab.strip().lower() for lab in languages.split(',')]
        language_scores = [float(s.strip()) for s in language_scores.split(',')]
        language_scores = defaultdict(
            lambda: -1.0,
            zip(languages, language_scores)
        )
```

</blockquote></details>

On adding to `MISSING_LANGUAGE_MODELS`: A language could be considered "missing" because it is simply not supported by Azure Speech, *or* because there is no valid mapping to a BCP-47 format. Do we want to avoid `MISSING_LANGUAGE_MODELS` mixing formats (e.g., `MISSING_LANGUAGE_MODELS="URD, ka-GE, BEN, sw-KE"`)?


<!-- Sent from Reviewable.io -->

2023-01-03 21:23 UTC, jrobble commented
*[`python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py` line 210 at r15](https://reviewable.io/reviews/openmpf/openmpf-components/296#-NIndQ8_8TENuEezIeoJ:-NKtU-IF44X9NRkRLNOd:bo5q542) ([raw file](https://github.com/openmpf/openmpf-components/blob/e32e100145367f7801827a92fe20508028c12b7f/python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py#L210)):*
<details><summary><i>Previously, cdglasz (Christopher Glasz) wrote…</i></summary><blockquote>

On adding to `MISSING_LANGUAGE_MODELS`: A language could be considered "missing" because it is simply not supported by Azure Speech, *or* because there is no valid mapping to a BCP-47 format. Do we want to avoid `MISSING_LANGUAGE_MODELS` mixing formats (e.g., `MISSING_LANGUAGE_MODELS="URD, ka-GE, BEN, sw-KE"`)?
</blockquote></details>

Honestly, `MISSING_LANGUAGE_MODELS` is mostly for user awareness, so consistency in the format isn't that important. Also, a user can specify anything when setting `LANGUAGE`, which would show up as a missing model. It's probably best to just keep the language string as it is rather than try to modify it. That way it represents exactly what caused the failure.


<!-- Sent from Reviewable.io -->

2023-01-05 17:54 UTC, cdglasz reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/296)* status: 5 of 11 files reviewed, 1 unresolved discussion (waiting on @brosenberg42 and @jrobble)

___
*[`python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py` line 210 at r15](https://reviewable.io/reviews/openmpf/openmpf-components/296#-NIndQ8_8TENuEezIeoJ:-NL22d5O5bxuZxXY0wXZ:b-u4t4r) ([raw file](https://github.com/openmpf/openmpf-components/blob/e32e100145367f7801827a92fe20508028c12b7f/python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py#L210)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Honestly, `MISSING_LANGUAGE_MODELS` is mostly for user awareness, so consistency in the format isn't that important. Also, a user can specify anything when setting `LANGUAGE`, which would show up as a missing model. It's probably best to just keep the language string as it is rather than try to modify it. That way it represents exactly what caused the failure.
</blockquote></details>

I think this is resolved. Note, however, that if `SPEAKER_LANGUAGES="eng, urd"`, `urd` will not be listed in `MISSING_LANGUAGE_MODELS`, while it *would* be if `SPEAKER_LANGUAGES="urd, eng"`. This is because languages are added to the missing language list after they are attempted to be used, and if `eng` is earlier in the `SPEAKER_LANGUAGES` list, it has a higher confidence, and is therefore used without `urd` ever being checked.


<!-- Sent from Reviewable.io -->

2023-01-09 19:34 UTC, cdglasz reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/296)* status: all files reviewed, 3 unresolved discussions (waiting on @jrobble)

___
*[`python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py` line 250 at r18](https://reviewable.io/reviews/openmpf/openmpf-components/296#-NLMuz-8A9jJZuhHUF6a:-NLN-mGd10dzQaig0Qh4:bamn0s5) ([raw file](https://github.com/openmpf/openmpf-components/blob/c539c0c133c2646bd653f077ecaa875f5617aa3c/python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py#L250)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Should we just state the highest-scoring locale here, for clarity? The "'{lang}', or '{locale}'" part makes it seem like we're not sure, like it could be one or the other.
</blockquote></details>

The intention is for the user to be able to see what the highest scoring ISO 639-3 language from VISTA was, and its corresponding BCP-47 code, which is what's actually sent to Azure. It would read something like `Transcribing with highest-scoring language ('eng', or 'en-US') instead.`
___
*[`python/AzureSpeechDetection/acs_speech_component/job_parsing.py` line 38 at r18](https://reviewable.io/reviews/openmpf/openmpf-components/296#-NL7mLwH4q5kuAvhssOt:-NLN0SOu2fGj6zyKn0XC:b-uuzuk6) ([raw file](https://github.com/openmpf/openmpf-components/blob/c539c0c133c2646bd653f077ecaa875f5617aa3c/python/AzureSpeechDetection/acs_speech_component/job_parsing.py#L38)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

This isn't used.
</blockquote></details>

Easier for later updates if the logger is loaded and ready to go, so any future developers don't have to go cross-reference other components to know how to properly log messages. Could comment it out if that's better?


<!-- Sent from Reviewable.io -->

2023-01-11 21:41 UTC, jrobble requested changes
> Reviewed 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/296)* status: all files reviewed, 3 unresolved discussions (waiting on @cdglasz)

___
*[`python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py` line 250 at r18](https://reviewable.io/reviews/openmpf/openmpf-components/296#-NLMuz-8A9jJZuhHUF6a:-NLWyerB8SoBcjR3tqg8:b-ra8qa8) ([raw file](https://github.com/openmpf/openmpf-components/blob/c539c0c133c2646bd653f077ecaa875f5617aa3c/python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py#L250)):*
I agree that keeping both is useful. Could we say:

> Transcribing with highest-scoring language (`eng`, using `eng-US` locale) instead.

It's really just the "or" part that may confuse an uninformed user.
___
*[`python/AzureSpeechDetection/acs_speech_component/job_parsing.py` line 38 at r18](https://reviewable.io/reviews/openmpf/openmpf-components/296#-NL7mLwH4q5kuAvhssOt:-NLWzrBC9PJiK3iLiCf_:bqempq2) ([raw file](https://github.com/openmpf/openmpf-components/blob/c539c0c133c2646bd653f077ecaa875f5617aa3c/python/AzureSpeechDetection/acs_speech_component/job_parsing.py#L38)):*
<details><summary><i>Previously, cdglasz (Christopher Glasz) wrote…</i></summary><blockquote>

Easier for later updates if the logger is loaded and ready to go, so any future developers don't have to go cross-reference other components to know how to properly log messages. Could comment it out if that's better?
</blockquote></details>

I understand your point, but I still prefer to remove it. It's a small thing, but will turn up as dead code when using a static code analysis tool. I'm all for keeping code commented out if it's non-trivial, but I think it will be pretty obvious what needs to be done here if there is no logger. A dev just needs to look at another .py file in this component.


<!-- Sent from Reviewable.io -->

2023-01-24 17:07 UTC, jrobble reviewed
> Reviewed 6 of 6 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/296)* status: all files reviewed, 2 unresolved discussions (waiting on @cdglasz)



<!-- Sent from Reviewable.io -->

2023-01-24 19:23 UTC, cdglasz reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/296)* status: 15 of 17 files reviewed, 2 unresolved discussions (waiting on @jrobble)

___
*[`python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py` line 250 at r18](https://reviewable.io/reviews/openmpf/openmpf-components/296#-NLMuz-8A9jJZuhHUF6a:-NM_E2xg6XtnXH-bl6Xp:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/c539c0c133c2646bd653f077ecaa875f5617aa3c/python/AzureSpeechDetection/acs_speech_component/acs_speech_processor.py#L250)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I agree that keeping both is useful. Could we say:

> Transcribing with highest-scoring language (`eng`, using `eng-US` locale) instead.

It's really just the "or" part that may confuse an uninformed user.
</blockquote></details>

Done.
___
*[`python/AzureSpeechDetection/acs_speech_component/job_parsing.py` line 38 at r18](https://reviewable.io/reviews/openmpf/openmpf-components/296#-NL7mLwH4q5kuAvhssOt:-NM_E1qmBeWLxEBMiJ0j:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/c539c0c133c2646bd653f077ecaa875f5617aa3c/python/AzureSpeechDetection/acs_speech_component/job_parsing.py#L38)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I understand your point, but I still prefer to remove it. It's a small thing, but will turn up as dead code when using a static code analysis tool. I'm all for keeping code commented out if it's non-trivial, but I think it will be pretty obvious what needs to be done here if there is no logger. A dev just needs to look at another .py file in this component.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-26 17:40 UTC, jrobble reviewed
> Reviewed 2 of 2 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/296)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cdglasz)



<!-- Sent from Reviewable.io -->

2023-01-26 18:35 UTC, jrobble approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/296#-:-NMjMCcr7WEz-m_BfpJr:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cdglasz)



<!-- Sent from Reviewable.io -->

2023-01-26 18:42 UTC, merged