Feature/argos translate
openmpf/openmpf-components pull request #306
Opened 2022-10-06 18:36 UTC by mcrensh

**Issues:**

- https://github.com/openmpf/openmpf/issues/1547

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/306)

2022-12-14 06:39 UTC, hhuangMITRE requested changes
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/306)* status: 9 of 11 files reviewed, 14 unresolved discussions (waiting on @mcrensh)

___
*[`python/ArgosTranslation/argos_translation_component/argos_translation_component.py` line 46 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NJDGDRB6jVkAiEbXfBC:-NJEM0NG1dYR8z9kbCni:bb9lpju) ([raw file](https://github.com/openmpf/openmpf-components/blob/3c5520f0915b9e00917a307f13b7825b8620a924/python/ArgosTranslation/argos_translation_component/argos_translation_component.py#L46)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

The following code block:
```
        try:
            if job.feed_forward_track is None:
                raise mpf.DetectionError.UNSUPPORTED_DATA_TYPE.exception(
                    f'Component can only process feed forward '
                    ' jobs, but no feed forward track provided. ')

            tw = TranslationWrapper(job.job_properties)
            tw.add_translations(job.feed_forward_track.detection_properties)

            for ff_location in job.feed_forward_track.frame_locations.values():
                tw.add_translations(ff_location.detection_properties)
            return [job.feed_forward_track]

        except Exception:
            logger.exception(
                f'Failed to complete job due to the following exception:')
            raise

```
Is very similar in 3 of the four get_detections, with a larger variation for the generic version.

I recommend creating a helper function to further reduce the amount of repeated code, with the input to the function being:

from_video: `job.feed_forward_track` and `job.feed_forward_track.frame_locations.values()`
from_image: `job.feed_forward_location` and `[job.feed_forward_location]`
from_audio:  `job.feed_forward_track` and `[job.feed_forward_track]`

That way you can reuse the helper function `from_video` for the other two media types. Let me know if this is not clear. I used something similar to reduce the amount of code in TikaTextDetection after I was staring at it for a bit.

I feel that the generic could also be refactored but it does operate slightly differently from the other three so it's fine to keep that one unique. 
</blockquote></details>

By generic I meant generic `get_detections`, that one can be left as is.


<!-- Sent from Reviewable.io -->

2022-12-14 06:46 UTC, hhuangMITRE requested changes
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/306)* status: 9 of 11 files reviewed, 13 unresolved discussions (waiting on @mcrensh)

___
*[`python/ArgosTranslation/argos_translation_component/argos_translation_component.py` line 217 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NJENEEv4fc4Gbw5Ol2o:-NJENEEv4fc4Gbw5Ol2p:b-we8108) ([raw file](https://github.com/openmpf/openmpf-components/blob/3c5520f0915b9e00917a307f13b7825b8620a924/python/ArgosTranslation/argos_translation_component/argos_translation_component.py#L217)):*
> ```Python
>         if self._from_lang not in self.installed_lang_codes:
>             logger.info(f"Language {self._from_lang} is not installed. Installing package.")
>             available_packages = package.get_available_packages()
> ```

This block of code, was it adapted from this example?
https://github.com/argosopentech/argos-translate#python

It's fine to reuse, but out of fairness, we can add a line such as:

```
Helper code (X lines) adapted from Argos Translate (https://github.com/argosopentech/argos-translate#python) for [PURPOSE]
```

Or :

```
From Argos Translate for downloading language models. (https://github.com/argosopentech/argos-translate#python)
```

There was a similar lambda function call above but I assume you wrote that one following this example. This section looks like it's been copied from their example so we want to add a quick cite here.

If there were several sections of adapted code/directly copied from their repo, we can add a general descriptor at the top of the class.

It's also useful in case some of their functionalities change and we need to update.

So in summary if several sections were adapted, include a single reference at the top of this class, and a short indicator where sections are directly copied to track potential changes.


<!-- Sent from Reviewable.io -->

2022-12-14 06:46 UTC, hhuangMITRE requested changes
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/306)* status: 9 of 11 files reviewed, 13 unresolved discussions (waiting on @mcrensh)

___
*[`python/ArgosTranslation/argos_translation_component/argos_translation_component.py` line 217 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NJENEEv4fc4Gbw5Ol2o:-NJEN_Tg4t2-_qUq75Q7:b5v6q0) ([raw file](https://github.com/openmpf/openmpf-components/blob/3c5520f0915b9e00917a307f13b7825b8620a924/python/ArgosTranslation/argos_translation_component/argos_translation_component.py#L217)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

This block of code, was it adapted from this example?
https://github.com/argosopentech/argos-translate#python

It's fine to reuse, but out of fairness, we can add a line such as:

```
Helper code (X lines) adapted from Argos Translate (https://github.com/argosopentech/argos-translate#python) for [PURPOSE]
```

Or :

```
From Argos Translate for downloading language models. (https://github.com/argosopentech/argos-translate#python)
```

There was a similar lambda function call above but I assume you wrote that one following this example. This section looks like it's been copied from their example so we want to add a quick cite here.

If there were several sections of adapted code/directly copied from their repo, we can add a general descriptor at the top of the class.

It's also useful in case some of their functionalities change and we need to update.

So in summary if several sections were adapted, include a single reference at the top of this class, and a short indicator where sections are directly copied to track potential changes.
</blockquote></details>

I apologize for the other retracted versions, please ignore them and refer to this active comment.


<!-- Sent from Reviewable.io -->

2023-01-05 21:19 UTC, mcrensh reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/306)* status: 9 of 11 files reviewed, 13 unresolved discussions (waiting on @hhuangMITRE)

___
*[`python/ArgosTranslation/Dockerfile` line 37 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NJCI_sY24bUIGjwstG_:-NL2nCNU3yy6F-QpRokZ:b-a8es6k) ([raw file](https://github.com/openmpf/openmpf-components/blob/3c5520f0915b9e00917a307f13b7825b8620a924/python/ArgosTranslation/Dockerfile#L37)):*
> Download another supported model of interest by adding
Added a comment on how to download models in the Dockerfile. We had discussed having Chinese installed but due to its very bad performance on Chinese we chose to leave it out


<!-- Sent from Reviewable.io -->

2023-01-05 21:52 UTC, mcrensh commented
*[`python/ArgosTranslation/plugin-files/descriptor/descriptor.json` line 32 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NJDQm5J1qsVosuB2d7B:-NL2rpAuDtqfDoRH27WJ:b-1geg6z) ([raw file](https://github.com/openmpf/openmpf-components/blob/3c5520f0915b9e00917a307f13b7825b8620a924/python/ArgosTranslation/plugin-files/descriptor/descriptor.json#L32)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

Add `ISO_LANGUAGE` for our Tika component pipeline and support for ISO-639-2 if possible.
</blockquote></details>

Added ISO_LANGAUGE to default values of LANGUAGE_FEED_FORWARD_PROP


<!-- Sent from Reviewable.io -->

2023-01-05 21:52 UTC, mcrensh reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/306)* status: 9 of 11 files reviewed, 13 unresolved discussions (waiting on @hhuangMITRE and @mcrensh)

___
*[`python/ArgosTranslation/README.md` line 13 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NJDByU4EG0jm5yqp6_m:-NL2nWMc-TzE_PgpsaiK:bkoytmz) ([raw file](https://github.com/openmpf/openmpf-components/blob/3c5520f0915b9e00917a307f13b7825b8620a924/python/ArgosTranslation/README.md#L13)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

Can we also add support for ISO-639-2 as well?

If you need a reference, please check [here](https://github.com/openmpf/openmpf-components/blob/8e70ffc8e1b24c1816f638bcff05d1ffb88ca267/java/TikaTextDetection/src/main/java/org/mitre/mpf/detection/tika/ISOLangMapper.java#L113) for many of the ISO mappings.
</blockquote></details>

Added mapping for ISO-639-2
___
*[`python/ArgosTranslation/README.md` line 27 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NJDCqUz5asQsih7Kmb0:-NL2ndC_8jJIXImC7Q8D:blsqupw) ([raw file](https://github.com/openmpf/openmpf-components/blob/3c5520f0915b9e00917a307f13b7825b8620a924/python/ArgosTranslation/README.md#L27)):*
> ISO-639-2
Added ISO-639-2 mappings
___
*[`python/ArgosTranslation/README.md` line 31 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NJCIkdU0aqlo9g_tU8F:-NL2nhKtAXOw2eVXmmPx:bf027zz) ([raw file](https://github.com/openmpf/openmpf-components/blob/3c5520f0915b9e00917a307f13b7825b8620a924/python/ArgosTranslation/README.md#L31)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

Quick question: Does it offer Chinese Simplified vs. Traditional or both?

Update: I checked the docs, only one Chinese option is offered so we can test for that later. 
</blockquote></details>

I remember when I was investigating how bad it was at translating Chinese I was able to pass in both simplified and traditional, but I'm not sure if it is better at one vs the other since in general the translations were...not great.
___
*[`python/ArgosTranslation/argos_translation_component/argos_translation_component.py` line 46 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NJDGDRB6jVkAiEbXfBC:-NL2oBG12EyfmwQpRImY:b-hvuiy0) ([raw file](https://github.com/openmpf/openmpf-components/blob/3c5520f0915b9e00917a307f13b7825b8620a924/python/ArgosTranslation/argos_translation_component/argos_translation_component.py#L46)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

By generic I meant generic `get_detections`, that one can be left as is.
</blockquote></details>

Refactored the get detections for video, audio, and image. Left generic alone. I ended up tweaking your suggestion a bit because there was issues passing job.feed_forward_track.frame_locations.values() when job.feed_foward_track is null, and I wanted to keep the null check in the method to avoid repeating it in all the methods. 
___
*[`python/ArgosTranslation/argos_translation_component/argos_translation_component.py` line 69 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NJDI93S2qSfoVAwXa_6:-NL2oXVi3ewiOE37tlaA:b-x9b4ca) ([raw file](https://github.com/openmpf/openmpf-components/blob/3c5520f0915b9e00917a307f13b7825b8620a924/python/ArgosTranslation/argos_translation_component/argos_translation_component.py#L69)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

Consider refactoring with the above comment.
</blockquote></details>

Refactored
___
*[`python/ArgosTranslation/argos_translation_component/argos_translation_component.py` line 89 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NJDIBMF3T3WytYITEhu:-NL2oZLQESGcb5u2uWVE:b-x9b4ca) ([raw file](https://github.com/openmpf/openmpf-components/blob/3c5520f0915b9e00917a307f13b7825b8620a924/python/ArgosTranslation/argos_translation_component/argos_translation_component.py#L89)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

Consider refactoring with the above comment.
</blockquote></details>

Refactored
___
*[`python/ArgosTranslation/argos_translation_component/argos_translation_component.py` line 108 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NJDIEh73Y1P-_FjdgQl:-NL2oaGpABX7lSxj_jV8:b-a1h6fw) ([raw file](https://github.com/openmpf/openmpf-components/blob/3c5520f0915b9e00917a307f13b7825b8620a924/python/ArgosTranslation/argos_translation_component/argos_translation_component.py#L108)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

With the above refactor changes we may be able to refactor this too. I'll leave that up to you, or for another reviewer to add their thoughts in.
</blockquote></details>

I've left generic as is
___
*[`python/ArgosTranslation/argos_translation_component/argos_translation_component.py` line 153 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NJDI-gx9ZB_3hBvyGGv:-NL2oczw3esfHD9Yi39v:b-kxpsnc) ([raw file](https://github.com/openmpf/openmpf-components/blob/3c5520f0915b9e00917a307f13b7825b8620a924/python/ArgosTranslation/argos_translation_component/argos_translation_component.py#L153)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

Can we update this list to also include `ISO_LANGUAGE` with support for ISO-639-2? This is to ensure compatibility with Tika Language Detection.
</blockquote></details>

The list of supported languages in the code is still ISO-639-1, but I've added mappings for ISO-639-2. I've also added the ISO-639-2 codes to the README
___
*[`python/ArgosTranslation/argos_translation_component/argos_translation_component.py` line 172 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NJDLUi2E_u_vS-E9uwY:-NL2pLmg3YqeM4dMwdVL:b-p8hn7r) ([raw file](https://github.com/openmpf/openmpf-components/blob/3c5520f0915b9e00917a307f13b7825b8620a924/python/ArgosTranslation/argos_translation_component/argos_translation_component.py#L172)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

Sorry to nitpick, but some log lines have punctuation, and others don't. I personally like to add `.` to let the debugger know where the single-statement ends. 

Thinking about it some more, feel free to ignores this comment, unless another reviewer wants it as well. I don't think it matters since the logger would print out a new line anyways.
</blockquote></details>

Added punctuation. I agree punctuation or not, it should be consistent.
___
*[`python/ArgosTranslation/argos_translation_component/argos_translation_component.py` line 176 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NJDOEqU5jJo443NcWBT:-NL2uhcP181WOpC6Qg3j:bu2qtcg) ([raw file](https://github.com/openmpf/openmpf-components/blob/3c5520f0915b9e00917a307f13b7825b8620a924/python/ArgosTranslation/argos_translation_component/argos_translation_component.py#L176)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

See next comment. I assume this is fine as is.
</blockquote></details>

I didn't add a citation for this section, but I did for the section you commented more about.
___
*[`python/ArgosTranslation/argos_translation_component/argos_translation_component.py` line 216 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NJDN3lxCQPstXQuFLDC:-NL2qJwy1S6XOZrlXrRn:blsxbzc) ([raw file](https://github.com/openmpf/openmpf-components/blob/3c5520f0915b9e00917a307f13b7825b8620a924/python/ArgosTranslation/argos_translation_component/argos_translation_component.py#L216)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

This block of code, was it adapted from this example?
h [...]

2023-02-23 06:05 UTC, hhuangMITRE requested changes
Looks good! Please review the requested changes and let me know if you have any questions.

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/306#-:-NOws97d9QF3s4TgMNVc:b-5sflz3)* status: all files reviewed, 7 unresolved discussions (waiting on @mcrensh)

___
*[`python/ArgosTranslation/Dockerfile` line 37 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NJCI_sY24bUIGjwstG_:-NOwdQ67DgojNKljYcCq:b-aa642b) ([raw file](https://github.com/openmpf/openmpf-components/blob/3c5520f0915b9e00917a307f13b7825b8620a924/python/ArgosTranslation/Dockerfile#L37)):*
<details><summary><i>Previously, mcrensh wrote…</i></summary><blockquote>

> Download another supported model of interest by adding
Added a comment on how to download models in the Dockerfile. We had discussed having Chinese installed but due to its very bad performance on Chinese we chose to leave it out
</blockquote></details>

Got it, thanks, in that case, I'm fine with leaving it out.
___
*[`python/ArgosTranslation/README.md` line 13 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NJDByU4EG0jm5yqp6_m:-NOwdiR3AWe46ed9ckg6:b-imytql) ([raw file](https://github.com/openmpf/openmpf-components/blob/3c5520f0915b9e00917a307f13b7825b8620a924/python/ArgosTranslation/README.md#L13)):*
<details><summary><i>Previously, mcrensh wrote…</i></summary><blockquote>

Added mapping for ISO-639-2
</blockquote></details>

I appreciate it, adding support makes it easier as we have one (potentially more) components that will return language detections in that format. Also good to standardize as well. 
___
*[`python/ArgosTranslation/README.md` line 27 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NJDCqUz5asQsih7Kmb0:-NOwdvzKAGJ0F5LSj1aA:ban2okn) ([raw file](https://github.com/openmpf/openmpf-components/blob/3c5520f0915b9e00917a307f13b7825b8620a924/python/ArgosTranslation/README.md#L27)):*
<details><summary><i>Previously, mcrensh wrote…</i></summary><blockquote>

> ISO-639-2
Added ISO-639-2 mappings
</blockquote></details>

Thanks, I appreciate it!
___
*[`python/ArgosTranslation/README.md` line 31 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NJCIkdU0aqlo9g_tU8F:-NOwe-JE74imh8-nnsU-:boeus0h) ([raw file](https://github.com/openmpf/openmpf-components/blob/3c5520f0915b9e00917a307f13b7825b8620a924/python/ArgosTranslation/README.md#L31)):*
<details><summary><i>Previously, mcrensh wrote…</i></summary><blockquote>

I remember when I was investigating how bad it was at translating Chinese I was able to pass in both simplified and traditional, but I'm not sure if it is better at one vs the other since in general the translations were...not great.
</blockquote></details>

Ah, got it. Some other services we tested also showed ... not great Chinese -> English translations.
___
*[`python/ArgosTranslation/README.md` line 17 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NOwezjnD7L-izGLjbDQ:-NOwezjnD7L-izGLjbDR:bxgwcje) ([raw file](https://github.com/openmpf/openmpf-components/blob/ad30c858d5d6c7d1bfc64f21c7f2877d520b2c5d/python/ArgosTranslation/README.md#L17)):*
> ```Markdown
> - `DEFAULT_SOURCE_LANGUAGE`: The default source language to use if none of the property names listed in `LANGUAGE_FEED_FORWARD_PROP` are present in a feed-forward track or detection. This language is used when running a generic job with a raw text file (hence no feed-forward tracks).
> ```

For consistency, just like Whisper, please include info on which properties are output by Argos Translate.
___
*[`python/ArgosTranslation/argos_translation_component/argos_translation_component.py` line 46 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NJDGDRB6jVkAiEbXfBC:-NOwfGSAEHACqo8L0DEu:b-n9blv6) ([raw file](https://github.com/openmpf/openmpf-components/blob/3c5520f0915b9e00917a307f13b7825b8620a924/python/ArgosTranslation/argos_translation_component/argos_translation_component.py#L46)):*
<details><summary><i>Previously, mcrensh wrote…</i></summary><blockquote>

Refactored the get detections for video, audio, and image. Left generic alone. I ended up tweaking your suggestion a bit because there was issues passing job.feed_forward_track.frame_locations.values() when job.feed_foward_track is null, and I wanted to keep the null check in the method to avoid repeating it in all the methods. 
</blockquote></details>

Gotcha, yep, that makes sense. Thanks for making the refactor!
___
*[`python/ArgosTranslation/argos_translation_component/argos_translation_component.py` line 153 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NJDI-gx9ZB_3hBvyGGv:-NOwfbraEKTVFvBL1Af9:b-m2uo8j) ([raw file](https://github.com/openmpf/openmpf-components/blob/3c5520f0915b9e00917a307f13b7825b8620a924/python/ArgosTranslation/argos_translation_component/argos_translation_component.py#L153)):*
<details><summary><i>Previously, mcrensh wrote…</i></summary><blockquote>

The list of supported languages in the code is still ISO-639-1, but I've added mappings for ISO-639-2. I've also added the ISO-639-2 codes to the README
</blockquote></details>

Thanks, again I appreciate the effort made to support the additional ISO format. 
___
*[`python/ArgosTranslation/argos_translation_component/argos_translation_component.py` line 172 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NJDLUi2E_u_vS-E9uwY:-NOwfkCu2g0iP4HPoLus:b-6gsmpr) ([raw file](https://github.com/openmpf/openmpf-components/blob/3c5520f0915b9e00917a307f13b7825b8620a924/python/ArgosTranslation/argos_translation_component/argos_translation_component.py#L172)):*
<details><summary><i>Previously, mcrensh wrote…</i></summary><blockquote>

Added punctuation. I agree punctuation or not, it should be consistent.
</blockquote></details>

Thanks, and moving forward (if it's ok), I'm happy to make comment/typo changes as well. I would like to avoid nitpicking as often. 
___
*[`python/ArgosTranslation/argos_translation_component/argos_translation_component.py` line 176 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NJDOEqU5jJo443NcWBT:-NOwg1AZ5T7hkB1sanvh:b-8ry0my) ([raw file](https://github.com/openmpf/openmpf-components/blob/3c5520f0915b9e00917a307f13b7825b8620a924/python/ArgosTranslation/argos_translation_component/argos_translation_component.py#L176)):*
<details><summary><i>Previously, mcrensh wrote…</i></summary><blockquote>

I didn't add a citation for this section, but I did for the section you commented more about.
</blockquote></details>

Yep, I agree if it's a barebones example, not much can be done to update, and paraphrasing code isn't really needed either.

Thinking back to what I mentioned, I think the proper course of action is to mention that we used the Argos library for this component in a LICENSE file. Regardless, we'll need to reference the licensing the Argos team is working with.

Please add a LICENSE file for this component, containing the OpenMPF license, and possibly the Argos license as well. In that LICENSE file, we can mention that the Argos library is used in `argos_translation_component.py`.

UPDATE: I see Argos has two open-source libraries available. I think either of them is fine, include a copy of that in our LICENSE file, thanks! If you need a sample, refer to the Tika/Tesseract or other open-source python component LICENSE files. 
___
*[`python/ArgosTranslation/argos_translation_component/argos_translation_component.py` line 216 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NJDN3lxCQPstXQuFLDC:-NOwhO4sAeRWObtgA4tY:b-nfscnz) ([raw file](https://github.com/openmpf/openmpf-components/blob/3c5520f0915b9e00917a307f13b7825b8620a924/python/ArgosTranslation/argos_translation_component/argos_translation_component.py#L216)):*
<details><summary><i>Previously, mcrensh wrote…</i></summary><blockquote>

I just used the example code so we don't need to add a genera [...]

2023-03-16 16:17 UTC, mcrensh reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/306)* status: 5 of 13 files reviewed, 7 unresolved discussions (waiting on @hhuangMITRE and @mcrensh)

___
*[`python/ArgosTranslation/README.md` line 17 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NOwezjnD7L-izGLjbDQ:-NQeujU3ERgH1BtrJJDa:b-fk3nps) ([raw file](https://github.com/openmpf/openmpf-components/blob/ad30c858d5d6c7d1bfc64f21c7f2877d520b2c5d/python/ArgosTranslation/README.md#L17)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

For consistency, just like Whisper, please include info on which properties are output by Argos Translate.
</blockquote></details>

Added a section on output properties
___
*[`python/ArgosTranslation/argos_translation_component/argos_translation_component.py` line 46 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NJDGDRB6jVkAiEbXfBC:-NQcvCT-728QNN_obtG4:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/3c5520f0915b9e00917a307f13b7825b8620a924/python/ArgosTranslation/argos_translation_component/argos_translation_component.py#L46)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

Gotcha, yep, that makes sense. Thanks for making the refactor!
</blockquote></details>

Done.
___
*[`python/ArgosTranslation/argos_translation_component/argos_translation_component.py` line 172 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NJDLUi2E_u_vS-E9uwY:-NQcvFiW0GNymQxPnBhN:b-9eb97z) ([raw file](https://github.com/openmpf/openmpf-components/blob/3c5520f0915b9e00917a307f13b7825b8620a924/python/ArgosTranslation/argos_translation_component/argos_translation_component.py#L172)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

Thanks, and moving forward (if it's ok), I'm happy to make comment/typo changes as well. I would like to avoid nitpicking as often. 
</blockquote></details>

Yep you can make those changes!
___
*[`python/ArgosTranslation/argos_translation_component/argos_translation_component.py` line 176 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NJDOEqU5jJo443NcWBT:-NQewH9e36RmieBRlUx0:b-cwwyro) ([raw file](https://github.com/openmpf/openmpf-components/blob/3c5520f0915b9e00917a307f13b7825b8620a924/python/ArgosTranslation/argos_translation_component/argos_translation_component.py#L176)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

Yep, I agree if it's a barebones example, not much can be done to update, and paraphrasing code isn't really needed either.

Thinking back to what I mentioned, I think the proper course of action is to mention that we used the Argos library for this component in a LICENSE file. Regardless, we'll need to reference the licensing the Argos team is working with.

Please add a LICENSE file for this component, containing the OpenMPF license, and possibly the Argos license as well. In that LICENSE file, we can mention that the Argos library is used in `argos_translation_component.py`.

UPDATE: I see Argos has two open-source libraries available. I think either of them is fine, include a copy of that in our LICENSE file, thanks! If you need a sample, refer to the Tika/Tesseract or other open-source python component LICENSE files. 
</blockquote></details>

Added LICENSE
___
*[`python/ArgosTranslation/argos_translation_component/argos_translation_component.py` line 216 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NJDN3lxCQPstXQuFLDC:-NQf0tYXE3QxkjEk4mhW:b-cwwyro) ([raw file](https://github.com/openmpf/openmpf-components/blob/3c5520f0915b9e00917a307f13b7825b8620a924/python/ArgosTranslation/argos_translation_component/argos_translation_component.py#L216)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

Got it, thanks! As mentioned above, I forgot that a LICENSE file would also properly attribute our usage of Argos Translate (library), and is also needed for our components. Please refer to the above comment. I'll mark these as accepted.
</blockquote></details>

Added LICENSE
___
*[`python/ArgosTranslation/argos_translation_component/argos_translation_component.py` line 217 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NJENEEv4fc4Gbw5Ol2o:-NQf0vWT-Fld5EBsmeym:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/3c5520f0915b9e00917a307f13b7825b8620a924/python/ArgosTranslation/argos_translation_component/argos_translation_component.py#L217)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

Agreed. Please refer to above comment for adding in a LICENSE file. We will also need that in place when this lands. 
</blockquote></details>

Done.
___
*[`python/ArgosTranslation/argos_translation_component/argos_translation_component.py` line 8 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NOwlAbC2p4S4Hl1s0TG:-NQevSDPCgPBhou0ku3c:b-5k3aqi) ([raw file](https://github.com/openmpf/openmpf-components/blob/ad30c858d5d6c7d1bfc64f21c7f2877d520b2c5d/python/ArgosTranslation/argos_translation_component/argos_translation_component.py#L8)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

Update to 2023, or let me know if I can update it, thanks!
</blockquote></details>

Updated, feel free to update it next time!
___
*[`python/ArgosTranslation/argos_translation_component/argos_translation_component.py` line 196 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NOwjP422-hB98AaZHHQ:-NQf0kuPEVbMvb1Xp4-W:b-dfo0dx) ([raw file](https://github.com/openmpf/openmpf-components/blob/ad30c858d5d6c7d1bfc64f21c7f2877d520b2c5d/python/ArgosTranslation/argos_translation_component/argos_translation_component.py#L196)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

From Brian's component:

```
        # Certain components that process videos and don't do tracking will create tracks with a
        # single detection. The track and detection will have the same set of properties, so
        # it is relatively likely we will run in to duplicate text.
```

Brian then uses a dictionary to hold past TEXT results and reuse them if the same tracks are encountered again during a job. I think for this code, we can include a similar functionality to save processing time:

1. Store input text and associated translation settings (i.e. key = "FR->EN:<input_FR_text>") in a dictionary along with its processed translation.
2. Retrieve processed translation from dict if we encounter it again. 

I'd imagine it would also be useful for scenarios where we're processing many sentence fragments/tracks at once. It's likely we'd run into repeats.

For reference, please check the code here: https://github.com/openmpf/openmpf-components/blob/3723d2479d104bdd88960b5648155b2eb369d337/python/AzureTranslation/acs_translation_component/acs_translation_component.py
(lines 183, 236, 271). 

</blockquote></details>

Added caching of past results
___
*[`python/ArgosTranslation/plugin-files/descriptor/descriptor.json` line 3 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NOwl34gBuwa3xO4ahXI:-NQf0wy41hQRPrrEI-99:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/ad30c858d5d6c7d1bfc64f21c7f2877d520b2c5d/python/ArgosTranslation/plugin-files/descriptor/descriptor.json#L3)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

We'll likely need to update these numbers to match the latest version of OpenMPF.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-21 04:46 UTC, hhuangMITRE requested changes
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/306)* status: all files reviewed, 2 unresolved discussions (waiting on @mcrensh)

___
*[`python/ArgosTranslation/Dockerfile` line 37 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NR1TT_y2fhEe5RSB3eP:-NR1TT_y2fhEe5RSB3eQ:baof300) ([raw file](https://github.com/openmpf/openmpf-components/blob/4a70a0999649527b7ec6262f4043f2a10d61881e/python/ArgosTranslation/Dockerfile#L37)):*
> ```Dockerfile
> 
> RUN argospm update
> ```

I'm running into Docker build issues for the latest version of this component. @mcrensh please confirm if you can build the latest images with tests passing. I will look into the issue on my end as well. 
___
*[`python/ArgosTranslation/tests/test_argos_translation.py` line 215 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NR1U5cnCq9u29hc2uOh:-NR1U5cnCq9u29hc2uOi:b-t71rv7) ([raw file](https://github.com/openmpf/openmpf-components/blob/4a70a0999649527b7ec6262f4043f2a10d61881e/python/ArgosTranslation/tests/test_argos_translation.py#L215)):*
> ```Python
>                 1: mpf.ImageLocation(0, 10, 10, 10, -1, dict(TRANSCRIPT=SPANISH_SHORT_SAMPLE, LANGUAGE='ES'))
>             },
>             dict(TEXT=SPANISH_SHORT_SAMPLE, LANGUAGE='ES'))
> ```

Consider switching one of the input language codes to ISO-639-2 to confirm that the iso mapper is working as expected: i.e. "ES" -> "ESP"


<!-- Sent from Reviewable.io -->

2023-05-02 14:56 UTC, hhuangMITRE requested changes
@mcrensh please request Brian's or Jeff's review of this component. Looking through, it doesn't seem that you've added/requested them to look at this yet, so I've added them now. Following up later today in our sync.

> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/306#-:-NURwnwQ5jFRujukIHg1:b-55v89z)* status: 11 of 13 files reviewed, 1 unresolved discussion (waiting on @brosenberg42, @jrobble, and @mcrensh)

___
*[`python/ArgosTranslation/Dockerfile` line 42 at r5](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NURxW_N2czpMZ6FU-S7:-NURxW_N2czpMZ6FU-S8:bnymvq6) ([raw file](https://github.com/openmpf/openmpf-components/blob/f8b12dd7080685013939aa65eaa633feb4d01b7a/python/ArgosTranslation/Dockerfile#L42)):*
> ```Dockerfile
>     argospm install translate-fr_en && \
>     argospm install translate-ru_en && \
>     argospm install translate-es_en
> ```

As Brian noted in the other channel, some environments can't allow for model downloads.

Although the zh_en model isn't great, I'd request that it be added anyway if we need to check back on it in the future.


<!-- Sent from Reviewable.io -->

2023-05-02 14:59 UTC, hhuangMITRE reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/306)* status: 11 of 13 files reviewed, all discussions resolved (waiting on @brosenberg42 and @jrobble)

___
*[`python/ArgosTranslation/Dockerfile` line 42 at r5](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NURxW_N2czpMZ6FU-S7:-NURyQCBDk9_G4a-Ejfg:b4v7wz) ([raw file](https://github.com/openmpf/openmpf-components/blob/f8b12dd7080685013939aa65eaa633feb4d01b7a/python/ArgosTranslation/Dockerfile#L42)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

As Brian noted in the other channel, some environments can't allow for model downloads.

Although the zh_en model isn't great, I'd request that it be added anyway if we need to check back on it in the future.

</blockquote></details>

If there are other languages of interest that are supported, we should consider adding them also. Thanks!


<!-- Sent from Reviewable.io -->

2023-05-19 18:02 UTC, mcrensh reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/306)* status: 7 of 13 files reviewed, 8 unresolved discussions (waiting on @brosenberg42, @hhuangMITRE, and @jrobble)

___
*[`python/ArgosTranslation/Dockerfile` line 42 at r5](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NURxW_N2czpMZ6FU-S7:-NVoue2H-cwS7d1qp4O7:b-4htua1) ([raw file](https://github.com/openmpf/openmpf-components/blob/f8b12dd7080685013939aa65eaa633feb4d01b7a/python/ArgosTranslation/Dockerfile#L42)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

If there are other languages of interest that are supported, we should consider adding them also. Thanks!
</blockquote></details>

I've added Arabic as a downloaded model
___
*[`python/ArgosTranslation/README.md` line 23 at r6](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NV-Q_zg37XWAONai-Xa:-NVov-z54q6jBAefwzzx:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/6fb55f5f77811b24e8f135c4b9800e989fd85cce/python/ArgosTranslation/README.md#L23)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Language is spelled wrong here.
</blockquote></details>

Done.
___
*[`python/ArgosTranslation/setup.cfg` line 29 at r6](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NV-Qk74BgxfUgSrcX-H:-NVov5cc7xcEhGKiXUvD:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/6fb55f5f77811b24e8f135c4b9800e989fd85cce/python/ArgosTranslation/setup.cfg#L29)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Change this to 7.2.
</blockquote></details>

Done.
___
*[`python/ArgosTranslation/setup.cfg` line 35 at r6](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NV-Qgxt4zEcO099ZjeG:-NVovFCGCmtQveklRCyu:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/6fb55f5f77811b24e8f135c4b9800e989fd85cce/python/ArgosTranslation/setup.cfg#L35)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Change these to 7.2
</blockquote></details>

Done.
___
*[`python/ArgosTranslation/argos_translation_component/argos_translation_component.py` line 127 at r6](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NV-Lkvh-4ol4eiB2fNK:-NVovnno1HgWhHKKvMqf:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/6fb55f5f77811b24e8f135c4b9800e989fd85cce/python/ArgosTranslation/argos_translation_component/argos_translation_component.py#L127)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

This should be: `default_value='ISO_LANGUAGE,DECODED_LANGUAGE,LANGUAGE'`
</blockquote></details>

Done.
___
*[`python/ArgosTranslation/argos_translation_component/argos_translation_component.py` line 172 at r6](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NV-LGzn1zp0Nww6CdQq:-NVowPPiAfDwoighlBK6:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/6fb55f5f77811b24e8f135c4b9800e989fd85cce/python/ArgosTranslation/argos_translation_component/argos_translation_component.py#L172)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

This should be: `self._translation_cache: Dict[str, Tuple[str, str]] = {}`
</blockquote></details>

Done.
___
*[`python/ArgosTranslation/plugin-files/descriptor/descriptor.json` line 32 at r6](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NV-M6FiAW87D0yHkktd:-NVowYR04gTrrY9SU0Av:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/6fb55f5f77811b24e8f135c4b9800e989fd85cce/python/ArgosTranslation/plugin-files/descriptor/descriptor.json#L32)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

This is in the wrong order. It should be: `ISO_LANGUAGE,DECODED_LANGUAGE,LANGUAGE`
</blockquote></details>

Done.
___
*[`python/ArgosTranslation/plugin-files/descriptor/descriptor.json` line 38 at r6](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NUw43WD5XZF5JCfikOK:-NVp78hGD71UPjCSRaab:bkkb9xz) ([raw file](https://github.com/openmpf/openmpf-components/blob/6fb55f5f77811b24e8f135c4b9800e989fd85cce/python/ArgosTranslation/plugin-files/descriptor/descriptor.json#L38)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I don't think it makes sense to assume the input text is in Spanish. I think the default value should be `""`. The component should `raise mpf.DetectionError.MISSING_PROPERTY.exception("<description>")` when there isn't a match for `LANGUAGE_FEED_FORWARD_PROP` and `DEFAULT_SOURCE_LANGUAGE` is empty.
</blockquote></details>

Added this behavior and added a test for it
___
*[`python/ArgosTranslation/tests/test_argos_translation.py` line 215 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NR1U5cnCq9u29hc2uOh:-NVp7ema3JHldJ-w68y7:bjbeh5p) ([raw file](https://github.com/openmpf/openmpf-components/blob/4a70a0999649527b7ec6262f4043f2a10d61881e/python/ArgosTranslation/tests/test_argos_translation.py#L215)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

Correction: "ES" -> "SPA". 
</blockquote></details>

Switched second one to SPA
___
*[`python/ArgosTranslation/tests/test_argos_translation.py` line 235 at r6](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NUwOpBMDTYqnuVSCmGP:-NVp7mJnAKBqjBMaeYvl:b-yplu1c) ([raw file](https://github.com/openmpf/openmpf-components/blob/6fb55f5f77811b24e8f135c4b9800e989fd85cce/python/ArgosTranslation/tests/test_argos_translation.py#L235)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

These tests don't currently run as part of the docker build. To get them to run, you need to add:
```python
if __name__ == '__main__':
    unittest.main(verbosity=2)
```
After adding that and running the docker build, the unit tests fail. They also fail when I run them outside of docker.
</blockquote></details>

Added. The Chinese model seems to have been updated, updated the expected translation output for Chinese translation


<!-- Sent from Reviewable.io -->

2023-06-08 13:03 UTC, brosenberg42 requested changes
Please create a PR in the openmp-docker repo to add argos to docker-compose.components.yml.

> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/306#-:-NXPjBPg6n8Ba_aBgME1:bn6a6gg)* status: 7 of 13 files reviewed, 2 unresolved discussions (waiting on @hhuangMITRE, @jrobble, and @mcrensh)

___
*[`python/ArgosTranslation/argos_translation_component/argos_translation_component.py` line 227 at r8](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NXPiuGLCq2PixGic5Kf:-NXPiuGLCq2PixGic5Kg:bz6ndm6) ([raw file](https://github.com/openmpf/openmpf-components/blob/2df33f0629ccfd46a8cbadd47fe10e0080f11877/python/ArgosTranslation/argos_translation_component/argos_translation_component.py#L227)):*
> ```Python
> 
>             if self._from_lang == "":
>                 raise mpf.DetectionError.MISSING_PROPERTY.exception("LANGUAGE_FEED_FORWARD_PROP mismatch and no DEFAULT_SOURCE_LANGUAGE provided.")
> ```

Change this to:
```python
raise mpf.DetectionError.MISSING_PROPERTY.exception(
    'None of the properties from "LANGUAGE_FEED_FORWARD_PROP" '
    f'({self._lang_prop_names}) were found in the feed forward track and no '
    '"DEFAULT_SOURCE_LANGUAGE" was provided.')
```


<!-- Sent from Reviewable.io -->

2023-09-01 11:19 UTC, brosenberg42 approved these changes
> Reviewed 3 of 11 files at r1, 1 of 6 files at r2, 3 of 8 files at r3, 3 of 6 files at r7, 1 of 2 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/306)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jrobble)

___
*[`python/ArgosTranslation/argos_translation_component/argos_translation_component.py` line 208 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/306#-NOwkmwK9ZY1ak8XoIhY:-NdFSd9REQ2JBT7fWM-p:bka2v0g) ([raw file](https://github.com/openmpf/openmpf-components/blob/ad30c858d5d6c7d1bfc64f21c7f2877d520b2c5d/python/ArgosTranslation/argos_translation_component/argos_translation_component.py#L208)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

Not sure if we should return detection failed or SKIPPED TRANSLATION, so I'm just leaving a comment here to discuss later.
</blockquote></details>

`SKIPPED TRANSLATION` is used when the translation does not occur because the text is already in the target language. Raising the exception here is the correct behavior.


<!-- Sent from Reviewable.io -->

2023-09-01 13:03 UTC, brosenberg42 approved these changes

2023-09-01 13:07 UTC, brosenberg42 approved these changes
> Dismissed @hhuangMITRE from a discussion.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/306)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jrobble)



<!-- Sent from Reviewable.io -->

2023-09-01 13:10 UTC, brosenberg42 approved these changes

2023-09-01 14:05 UTC, hhuangMITRE approved these changes

2023-09-01 14:41 UTC, merged