Feature/whisper
openmpf/openmpf-components pull request #313
Opened 2022-12-13 20:59 UTC by mcrensh

**Issues:**

- https://github.com/openmpf/openmpf/issues/1598

2022-12-14 06:38 UTC, hhuangMITRE requested changes
> Reviewed 11 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/313)* status: 11 of 12 files reviewed, 11 unresolved discussions (waiting on @mcrensh)

___
*[`python/WhisperDetection/README.md` line 11 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NJECCXy5J97xxplEkns:-NJECCXz4fu51OY3OV6T:b-m7sgca) ([raw file](https://github.com/openmpf/openmpf-components/blob/440f824ea60bf2e2d0a756a363dc8e162c8c90bd/python/WhisperDetection/README.md#L11)):*
> ```Markdown
> 
> # Input Properties
> - `WHISPER_MODEL_SIZE`: Size of the Whisper model. Whisper has tiny, base, small, medium, and large models available.
> ```

Include a quick note about model limits for English-only models. 
Also include info if English-only models are not meant for translation or language-ID tasks.

Lastly, include some info about the odd properties of Whisper handling Multi-Lingual situations:

 I think for simplicity here, we can include a copy of your investigation and link it to the README, we can check with Jeff later if that works. There are useful details from the investigation about this component and it would be beneficial for any users as well.

PLEASE NOTE: I have already created a Markdown converted version of your investigation and linked it in our shared repo: it's right next to your original Whisper investigation doc, except with a markdown `.md` extension. 

Please feel free to add a copy of that and link to README. If you do use it, 'also include the source/citation for the text inputs`.
___
*[`python/WhisperDetection/plugin-files/descriptor/descriptor.json` line 24 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NJE-kfUC0j5ct4DWA6s:-NJE-kfV8GP8Awvc9Ppu:b-wgv9vm) ([raw file](https://github.com/openmpf/openmpf-components/blob/440f824ea60bf2e2d0a756a363dc8e162c8c90bd/python/WhisperDetection/plugin-files/descriptor/descriptor.json#L24)):*
> ```JSON
>         {
>           "name": "WHISPER_MODEL_LANG",
>           "description": "Whisper has English-only models and multilingual models. Set to en for English-only models and multi for multilingual models.",
> ```

Add single quotation marks to highlight user-input options: 

"Set to 'en' for English-only models and 'multi' for multilingual models."

I will also need to update my own Tika hotfix after this: I used backticks but during this review, I noticed that other descriptor files apply single quotes for these cases. These things generally are more noticeable from the reviewer side. 
___
*[`python/WhisperDetection/plugin-files/descriptor/descriptor.json` line 30 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NJE26cX67tAe22WDDGm:-NJE26cY0c9nOlZXNnIn:bg7k5na) ([raw file](https://github.com/openmpf/openmpf-components/blob/440f824ea60bf2e2d0a756a363dc8e162c8c90bd/python/WhisperDetection/plugin-files/descriptor/descriptor.json#L30)):*
> ```JSON
>         {
>           "name": "WHISPER_MODEL_SIZE",
>           "description": "Whisper models come in multiple sizes; tiny, base, small, medium, and large. Multilingual models are available in all 5 sizes, English-only is not available in large.",
> ```

Update description to:

`Whisper models come in five sizes: 'tiny', 'base', 'small', 'medium', and 'large'. Multilingual models are available in all five sizes. English-only transcription models are not available in 'large' size, but are available in the other four sizes .`

Feel free to adjust as needed if I misquoted something. I also assume English-only models are only good for transcription. The notes you provided on Whisper Multi-Lingual Audio mentioned English multimodal models, so I assume there is a difference here.

Please also mention the model size limits and limits of English-only models in the README.
___
*[`python/WhisperDetection/plugin-files/descriptor/descriptor.json` line 36 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NJE2T_fB6RkBm2bNsCG:-NJE2T_fB6RkBm2bNsCH:b8jnzo8) ([raw file](https://github.com/openmpf/openmpf-components/blob/440f824ea60bf2e2d0a756a363dc8e162c8c90bd/python/WhisperDetection/plugin-files/descriptor/descriptor.json#L36)):*
> ```JSON
>         {
>           "name": "WHISPER_MODE",
>           "description": "Set to 0 for spoken language detection, 1 for speech-to-text transcription, and 2 for speech translation.",
> ```

Mark '0', '1', and '2'. 
___
*[`python/WhisperDetection/plugin-files/descriptor/descriptor.json` line 42 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NJE4mro6RF2R9U1WJkr:-NJE4mrp7l6JNNzT8Van:bti85rd) ([raw file](https://github.com/openmpf/openmpf-components/blob/440f824ea60bf2e2d0a756a363dc8e162c8c90bd/python/WhisperDetection/plugin-files/descriptor/descriptor.json#L42)):*
> ```JSON
>         {
>           "name": "AUDIO_LANGUAGE",
>           "description": "Language audio to transcribe or translate is in. If none is provided then Whisper will automatically detect language from the first 30 seconds of audio.",
> ```

Consider rewording to:

`"Optional property that indicates the language to use for audio translation or transcription. If left as an empty string, Whisper will automatically detect a single language from the first 30 seconds of audio."`

Please update the revised comment ("will automatically detect **`a single`** language") if Whisper can actually detect multiple languages. 

I recalled it cannot based on our previous discussion and your notes on Whisper for multi-lingual audio showed that it auto translates/transcribes for a single language.
___
*[`python/WhisperDetection/tests/test_whisper_detection.py` line 33 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NJE6RrMA00bTZ5MD4rV:-NJE6RrMA00bTZ5MD4rW:b78v1fw) ([raw file](https://github.com/openmpf/openmpf-components/blob/440f824ea60bf2e2d0a756a363dc8e162c8c90bd/python/WhisperDetection/tests/test_whisper_detection.py#L33)):*
> ```Python
> import warnings
> from whisper_detection_component import WhisperDetectionComponent
> ```

Leaving a note to myself to test this out later.
___
*[`python/WhisperDetection/tests/test_whisper_detection.py` line 107 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NJE8Bts3xeZ8FTrRXT1:-NJE8Bts3xeZ8FTrRXT2:b-bi32i2) ([raw file](https://github.com/openmpf/openmpf-components/blob/440f824ea60bf2e2d0a756a363dc8e162c8c90bd/python/WhisperDetection/tests/test_whisper_detection.py#L107)):*
> ```Python
> 
>     def test_transcribe_given_language(self):
>         expected_text = (
> ```

I really like this text sample, could you add a quick site if it came from a source? Thanks!
___
*[`python/WhisperDetection/tests/test_whisper_detection.py` line 142 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NJE8INa0k8RuHgtutDf:-NJE8INa0k8RuHgtutDg:b-7lj0mc) ([raw file](https://github.com/openmpf/openmpf-components/blob/440f824ea60bf2e2d0a756a363dc8e162c8c90bd/python/WhisperDetection/tests/test_whisper_detection.py#L142)):*
> ```Python
>     def test_translation(self):
>         expected_text = (
>             'I communicate with different people in English and Spanish or mixing both languages. '
> ```

Could you add a quick site if it came from a source? Thanks!
___
*[`python/WhisperDetection/tests/test_whisper_detection.py` line 163 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NJE8l411m-OSrc-D0kM:-NJE8l411m-OSrc-D0kN:b-y449cx) ([raw file](https://github.com/openmpf/openmpf-components/blob/440f824ea60bf2e2d0a756a363dc8e162c8c90bd/python/WhisperDetection/tests/test_whisper_detection.py#L163)):*
> ```Python
> 
>         job_props = dict(WHISPER_MODE=2, AUDIO_LANGUAGE='es')
>         job = mpf.AudioJob('test', self._get_test_file('bilingual.mp3'), 0, -1, job_props, {})
> ```

Add a quick citation on the audio samples in NOTICE, thanks!
___
*[`python/WhisperDetection/whisper_detection_component/whisper_detection_component.py` line 40 at r1](https://reviewable [...]

2022-12-30 19:36 UTC, mcrensh commented
*[`python/WhisperDetection/plugin-files/descriptor/descriptor.json` line 24 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NJE-kfUC0j5ct4DWA6s:-NKZX3XQAmzDaKzUBCI2:b6u1jz4) ([raw file](https://github.com/openmpf/openmpf-components/blob/440f824ea60bf2e2d0a756a363dc8e162c8c90bd/python/WhisperDetection/plugin-files/descriptor/descriptor.json#L24)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

Add single quotation marks to highlight user-input options: 

"Set to 'en' for English-only models and 'multi' for multilingual models."

I will also need to update my own Tika hotfix after this: I used backticks but during this review, I noticed that other descriptor files apply single quotes for these cases. These things generally are more noticeable from the reviewer side. 
</blockquote></details>

Added single quotes


<!-- Sent from Reviewable.io -->

2022-12-30 20:00 UTC, mcrensh commented
*[`python/WhisperDetection/plugin-files/descriptor/descriptor.json` line 30 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NJE26cX67tAe22WDDGm:-NKZXCMd23fckKhD3Cwr:bh0bbym) ([raw file](https://github.com/openmpf/openmpf-components/blob/440f824ea60bf2e2d0a756a363dc8e162c8c90bd/python/WhisperDetection/plugin-files/descriptor/descriptor.json#L30)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

Update description to:

`Whisper models come in five sizes: 'tiny', 'base', 'small', 'medium', and 'large'. Multilingual models are available in all five sizes. English-only transcription models are not available in 'large' size, but are available in the other four sizes .`

Feel free to adjust as needed if I misquoted something. I also assume English-only models are only good for transcription. The notes you provided on Whisper Multi-Lingual Audio mentioned English multimodal models, so I assume there is a difference here.

Please also mention the model size limits and limits of English-only models in the README.
</blockquote></details>

Added single quotes and edited README. There's only English and multilingual models, the expected behavior for the English-only model is it can only transcribe English audio, but my notes found it can also translate. However, I don't think that is something it should be able to do that, English-only models can't do language detection and transcribing with English-only models automatically sets the language to English. I looked through the GitHub and paper again real quick and they don't define what they mean by English-only, but I would assume it only accepts English audio and therefore translating to English would be a moot point.


<!-- Sent from Reviewable.io -->

2022-12-30 20:00 UTC, mcrensh commented
*[`python/WhisperDetection/plugin-files/descriptor/descriptor.json` line 36 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NJE2T_fB6RkBm2bNsCG:-NKZbhk4Br76bV4GZeZg:b9dvxey) ([raw file](https://github.com/openmpf/openmpf-components/blob/440f824ea60bf2e2d0a756a363dc8e162c8c90bd/python/WhisperDetection/plugin-files/descriptor/descriptor.json#L36)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

Mark '0', '1', and '2'. 
</blockquote></details>

Added single quotes


<!-- Sent from Reviewable.io -->

2022-12-30 20:00 UTC, mcrensh commented
*[`python/WhisperDetection/plugin-files/descriptor/descriptor.json` line 42 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NJE4mro6RF2R9U1WJkr:-NKZbm3ACUoYg6R2ZOCX:bs67vf1) ([raw file](https://github.com/openmpf/openmpf-components/blob/440f824ea60bf2e2d0a756a363dc8e162c8c90bd/python/WhisperDetection/plugin-files/descriptor/descriptor.json#L42)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

Consider rewording to:

`"Optional property that indicates the language to use for audio translation or transcription. If left as an empty string, Whisper will automatically detect a single language from the first 30 seconds of audio."`

Please update the revised comment ("will automatically detect **`a single`** language") if Whisper can actually detect multiple languages. 

I recalled it cannot based on our previous discussion and your notes on Whisper for multi-lingual audio showed that it auto translates/transcribes for a single language.
</blockquote></details>

Yep, it will only transcribe/translate for a single language, and detects language from the first 30 seconds of audio.


<!-- Sent from Reviewable.io -->

2022-12-30 20:01 UTC, mcrensh commented
*[`python/WhisperDetection/tests/test_whisper_detection.py` line 107 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NJE8Bts3xeZ8FTrRXT1:-NKZUC2_C-Ej5oUiy6JI:b28tujz) ([raw file](https://github.com/openmpf/openmpf-components/blob/440f824ea60bf2e2d0a756a363dc8e162c8c90bd/python/WhisperDetection/tests/test_whisper_detection.py#L107)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

I really like this text sample, could you add a quick site if it came from a source? Thanks!
</blockquote></details>

It's a transcription of bilingual.mp3, I've added a NOTICE to the test data folder.


<!-- Sent from Reviewable.io -->

2022-12-30 20:02 UTC, mcrensh commented
*[`python/WhisperDetection/tests/test_whisper_detection.py` line 142 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NJE8INa0k8RuHgtutDf:-NKZc7NrCXSmp3lrLPuZ:bc34sd9) ([raw file](https://github.com/openmpf/openmpf-components/blob/440f824ea60bf2e2d0a756a363dc8e162c8c90bd/python/WhisperDetection/tests/test_whisper_detection.py#L142)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

Could you add a quick site if it came from a source? Thanks!
</blockquote></details>

Added NOTICE


<!-- Sent from Reviewable.io -->

2022-12-30 20:02 UTC, mcrensh commented
*[`python/WhisperDetection/tests/test_whisper_detection.py` line 163 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NJE8l411m-OSrc-D0kM:-NKZcBtqAfDMCg73FlT-:bc34sd9) ([raw file](https://github.com/openmpf/openmpf-components/blob/440f824ea60bf2e2d0a756a363dc8e162c8c90bd/python/WhisperDetection/tests/test_whisper_detection.py#L163)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

Add a quick citation on the audio samples in NOTICE, thanks!
</blockquote></details>

Added NOTICE


<!-- Sent from Reviewable.io -->

2022-12-30 20:03 UTC, mcrensh commented
*[`python/WhisperDetection/whisper_detection_component/whisper_detection_component.py` line 88 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NJE9adF432txeOAlYS7:-NKZcOzd5zZNZ41JcOYH:b-kqdjnv) ([raw file](https://github.com/openmpf/openmpf-components/blob/440f824ea60bf2e2d0a756a363dc8e162c8c90bd/python/WhisperDetection/whisper_detection_component/whisper_detection_component.py#L88)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

Are these commented lines still useful for debugging? We can keep it if that's the case. Otherwise, they would be removed.
</blockquote></details>

Whisper doesn't break audio up into utterances so these lines were unnecessary, I've removed them.


<!-- Sent from Reviewable.io -->

2022-12-30 20:05 UTC, mcrensh commented
*[`python/WhisperDetection/whisper_detection_component/whisper_detection_component.py` line 156 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NJEA5TC7jW_7YMAN1DE:-NKZcaYC7kbs_cvdcH6D:b-k4peya) ([raw file](https://github.com/openmpf/openmpf-components/blob/440f824ea60bf2e2d0a756a363dc8e162c8c90bd/python/WhisperDetection/whisper_detection_component/whisper_detection_component.py#L156)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

Please include a note of this in the README regarding Whisper English model size limits.
</blockquote></details>

Added to README


<!-- Sent from Reviewable.io -->

2022-12-30 20:14 UTC, mcrensh commented
*[`python/WhisperDetection/whisper_detection_component/whisper_detection_component.py` line 169 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NJEAI6g9VIwBkpiWQ-8:-NKZew_d-b41mxenJTUM:b-ukh12) ([raw file](https://github.com/openmpf/openmpf-components/blob/440f824ea60bf2e2d0a756a363dc8e162c8c90bd/python/WhisperDetection/whisper_detection_component/whisper_detection_component.py#L169)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

Also, add a note in the README explaining that English-only models cannot perform language detection. 

I've created a markdown copy of your audio investigation, we should include that and link to README so users are aware of the multilingual quirks as well. 
</blockquote></details>

Added the markdown and linked it in the README.


<!-- Sent from Reviewable.io -->

2022-12-30 20:15 UTC, mcrensh commented
*[`python/WhisperDetection/README.md` line 11 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NJECCXy5J97xxplEkns:-NKZf47cA2M1ekGoaOXS:bkyysv5) ([raw file](https://github.com/openmpf/openmpf-components/blob/440f824ea60bf2e2d0a756a363dc8e162c8c90bd/python/WhisperDetection/README.md#L11)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

Include a quick note about model limits for English-only models. 
Also include info if English-only models are not meant for translation or language-ID tasks.

Lastly, include some info about the odd properties of Whisper handling Multi-Lingual situations:

 I think for simplicity here, we can include a copy of your investigation and link it to the README, we can check with Jeff later if that works. There are useful details from the investigation about this component and it would be beneficial for any users as well.

PLEASE NOTE: I have already created a Markdown converted version of your investigation and linked it in our shared repo: it's right next to your original Whisper investigation doc, except with a markdown `.md` extension. 

Please feel free to add a copy of that and link to README. If you do use it, 'also include the source/citation for the text inputs`.


</blockquote></details>

Clarified English-only can only transcribe English audio, added your markdown and linked it in the README.


<!-- Sent from Reviewable.io -->

2023-02-23 05:52 UTC, hhuangMITRE requested changes
Overall, looks good! I added some requested tooltip updates and an request for adding ISO-639-2 formatted language detection outputs (optional) + update to sample code. Aside from that, let me know moving forward if it's alright for me to make some quick edits as well to the component. 

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/313#-:-NOwd0ktDzRYSlIbTgOe:b7q24r8)* status: all files reviewed, 9 unresolved discussions (waiting on @mcrensh)

___
*[`python/WhisperDetection/README.md` line 11 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NJECCXy5J97xxplEkns:-NOvvSGPB5a9C63U3MZI:b-ucfknh) ([raw file](https://github.com/openmpf/openmpf-components/blob/440f824ea60bf2e2d0a756a363dc8e162c8c90bd/python/WhisperDetection/README.md#L11)):*
<details><summary><i>Previously, mcrensh wrote…</i></summary><blockquote>

Clarified English-only can only transcribe English audio, added your markdown and linked it in the README.
</blockquote></details>

Thanks!
___
*[`python/WhisperDetection/README.md` line 12 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NOwCDe61lBZqjnVmwbf:-NOwCDe61lBZqjnVmwbg:b-7ygpuo) ([raw file](https://github.com/openmpf/openmpf-components/blob/51f6964f4089741642667c2834593ab399a2052a/python/WhisperDetection/README.md#L12)):*
> ```Markdown
> # Input Properties
> - `WHISPER_MODEL_SIZE`: Size of the Whisper model. Whisper has tiny, base, small, medium, and large models available for multilingual models. English-only models are available in tiny, base, small, and medium. 
> - `WHISPER_MODE`: Determines whether Whisper will perform language detection, speech-to-text transcription, or speech translation. English-only models can only transcribe English audio. 
> ```

Please also copy over the description of `0`,`1`, and `2` options for `WHISPER_MODE`.
___
*[`python/WhisperDetection/README.md` line 16 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NOwc2kI3faFidGNFqWO:-NOwc2kI3faFidGNFqWP:b-y1yz3b) ([raw file](https://github.com/openmpf/openmpf-components/blob/51f6964f4089741642667c2834593ab399a2052a/python/WhisperDetection/README.md#L16)):*
> ```Markdown
> 
> # Output Properties
> - `DETECTED_LANGUAGE`: Language with the highest confidence value.
> ```

Please add a short list of language outputs provided by Whisper, in the same format returned by Whisper if possible.

See discussion below on perhaps adding an `ISO_LANGUAGE` property, that request is optional as this component already handles translation. 
___
*[`python/WhisperDetection/README.md` line 17 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NOvwOik9uZCj-BYkrzk:-NOvwOik9uZCj-BYkrzl:b4e8di6) ([raw file](https://github.com/openmpf/openmpf-components/blob/51f6964f4089741642667c2834593ab399a2052a/python/WhisperDetection/README.md#L17)):*
> ```Markdown
> # Output Properties
> - `DETECTED_LANGUAGE`: Language with the highest confidence value.
> - `DETECTED_LANGUAGE_CONFIDENCE`: The confidence value of the language with the highest confidence.
> ```

Can we also get descriptions of the following outputs?

`TRANSCRIPT` - for transcription runs.
`TRANSLATED_AUDIO` - for translated audio runs.

Please also mention that the output property changes if the user sets `WHISPER_MODE` to translate or transcribe, so that there is no confusion about what the component returns under different modes.
___
*[`python/WhisperDetection/sample_whisper_detector.py` line 10 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NOvvfnyCGBSmrGIkUyd:-NOvvfnyCGBSmrGIkUye:b-j1dn1t) ([raw file](https://github.com/openmpf/openmpf-components/blob/51f6964f4089741642667c2834593ab399a2052a/python/WhisperDetection/sample_whisper_detector.py#L10)):*
> ```Python
> # 52.227-14, Alt. IV (DEC 2007).                                            #
> #                                                                           #
> # Copyright 2022 The MITRE Corporation. All Rights Reserved.                #
> ```

Copyright is now 2023.

If it's alright, next time I can make this change myself and push in the change (with a note of what changed). Let me know if that works.
___
*[`python/WhisperDetection/sample_whisper_detector.py` line 36 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NOvwmXZ71rAbzDhgbVg:-NOvwmXZ71rAbzDhgbVh:b-v67z85) ([raw file](https://github.com/openmpf/openmpf-components/blob/51f6964f4089741642667c2834593ab399a2052a/python/WhisperDetection/sample_whisper_detector.py#L36)):*
> ```Python
> def main():
>     if len(sys.argv) != 2:
>         sys.exit(f'Usage {sys.argv[0]} <audio_file>')
> ```

Can we also include an optional third parameter to set `WHISPER_MODE` for Transcription/Auto-Translate to English, and view those results too?

Thanks!
___
*[`python/WhisperDetection/setup.cfg` line 34 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NOwCjsb8JYHpV8reNCc:-NOwCjsb8JYHpV8reNCd:b4t9hyi) ([raw file](https://github.com/openmpf/openmpf-components/blob/51f6964f4089741642667c2834593ab399a2052a/python/WhisperDetection/setup.cfg#L34)):*
> ```INI
> packages = whisper_detection_component
> install_requires =
>     mpf_component_api>=7.0
> ```

I believe our component API number has been updated, please review the latest python component for `master`/`develop` and update, thanks.
___
*[`python/WhisperDetection/plugin-files/descriptor/descriptor.json` line 24 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NJE-kfUC0j5ct4DWA6s:-NOvx41C1HBicXP22i02:bfzkme6) ([raw file](https://github.com/openmpf/openmpf-components/blob/440f824ea60bf2e2d0a756a363dc8e162c8c90bd/python/WhisperDetection/plugin-files/descriptor/descriptor.json#L24)):*
<details><summary><i>Previously, mcrensh wrote…</i></summary><blockquote>

Added single quotes
</blockquote></details>

Thanks!

Moving forward, let me know if it's ok for me to make the edit and attach a note after to avoid feeling nitpicky. I don't want to cause extra hassle and it's no trouble on my end to make the updates, if that works. 
___
*[`python/WhisperDetection/plugin-files/descriptor/descriptor.json` line 30 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NJE26cX67tAe22WDDGm:-NOvySst7nuKIuCbDt7I:by5wfj7) ([raw file](https://github.com/openmpf/openmpf-components/blob/440f824ea60bf2e2d0a756a363dc8e162c8c90bd/python/WhisperDetection/plugin-files/descriptor/descriptor.json#L30)):*
<details><summary><i>Previously, mcrensh wrote…</i></summary><blockquote>

Added single quotes and edited README. There's only English and multilingual models, the expected behavior for the English-only model is it can only transcribe English audio, but my notes found it can also translate. However, I don't think that is something it should be able to do that, English-only models can't do language detection and transcribing with English-only models automatically sets the language to English. I looked through the GitHub and paper again real quick and they don't define what they mean by English-only, but I would assume it only accepts English audio and therefore translating to English would be a moot point.
</blockquote></details>

Interesting, I agree that the additional unexpected feature is a bit odd, considering that they have specific translation models designed for this task. Perhaps it's something inherent to their models?

If their notes specify that these are `English-only` models, I agree with your assessment that it's a moot point to have translation available too. Again, seems odd...
___
*[`python/WhisperDetection/plugin-files/descriptor/descriptor.json` line 42 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NJE4mro6RF2R9U1WJkr:-NOvyw5W4BiARCWM2_Mc:bcr5s2o) ([raw file](https://github.com/openmpf/openmpf-components/blob/440f824ea60bf2e2d0a756a363dc8e162c8c90bd/python/WhisperDetection/plugin-files/descriptor/descriptor.json#L42)):*
<de [...]

2023-02-23 22:48 UTC, hhuangMITRE requested changes
Update: from discussion with Jeff.

1. Can we get language detected results from whisper modes 1 and 2? 
2. Please support the ISO_LANGUAGE output property as well. 

> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/313#-:-NP-SB7q8vNv2WfzTx4i:bkoyrcx)* status: all files reviewed, 10 unresolved discussions (waiting on @mcrensh)

___
*[`python/WhisperDetection/README.md` line 16 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NOwc2kI3faFidGNFqWO:-NP-S1FW8qWT9FbYVtmd:b-objgpc) ([raw file](https://github.com/openmpf/openmpf-components/blob/51f6964f4089741642667c2834593ab399a2052a/python/WhisperDetection/README.md#L16)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

Please add a short list of language outputs provided by Whisper, in the same format returned by Whisper if possible.

See discussion below on perhaps adding an `ISO_LANGUAGE` property, that request is optional as this component already handles translation. 
</blockquote></details>

As a follow-up, Jeff said it would be good if we can include this property. Please add it as a to-do task for this PR, thanks. 
___
*[`python/WhisperDetection/whisper_detection_component/whisper_detection_component.py` line 202 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NP-Mmtt7UPVzN-qRSTX:-NP-Mmtt7UPVzN-qRSTY:b-2fatvs) ([raw file](https://github.com/openmpf/openmpf-components/blob/51f6964f4089741642667c2834593ab399a2052a/python/WhisperDetection/whisper_detection_component/whisper_detection_component.py#L202)):*
> ```Python
> 
>             audio_tracks.append(track)
>         elif mode == 2:
> ```

From discussion with Jeff: For transcription and translation, can we also retrieve the reported detected language? End users would like to know what the original language would be. 

Jeff asked if this would be easy or difficult to retrieve from the transcription or translation modes. 

If this info is not accessible from translation/transcription, please let us know. I assume the next best option might be to auto-run detect language first.


<!-- Sent from Reviewable.io -->

2023-02-24 17:04 UTC, hhuangMITRE requested changes
Additional tasks:

Questions for the Whisper team:
- Can we get timestamps for the transcription?
- Can we run translation independently on raw text?
- Can we get the transcription output when we do STT + translation? (Currently, we need to run the STT part twice).



For the language property output by the component, we would like:


1. For Language Detection: Keep the DETECTED_LANGUAGE property as is.


2. For Transcription: Return a DECODED_LANGUAGE property for the STT step. The user may provide it, or it is found by the component.
3. Return an ISO_LANGUAGE property converting DETECTED_LANGUAGE and DECODED_LANGUAGE into standardized ISO-639-2 format.

> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/313#-:-NP37dy2CNr7X77nRJf8:bi89v8n)* status: all files reviewed, 11 unresolved discussions (waiting on @mcrensh)

___
*[`python/WhisperDetection/README.md` line 16 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NOwc2kI3faFidGNFqWO:-NP3D-h_7aYiLBoDpUCl:b-t0i6u1) ([raw file](https://github.com/openmpf/openmpf-components/blob/51f6964f4089741642667c2834593ab399a2052a/python/WhisperDetection/README.md#L16)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

As a follow-up, Jeff said it would be good if we can include this property. Please add it as a to-do task for this PR, thanks. 
</blockquote></details>

For clarification: "DETECTED_LANGUAGE" is kept for audio language ID

In transcription and translation: we will call this "DECODED_LANGUAGE" instead. 
In both cases, we'll also convert to `ISO_LANGUAGE` for standardization of language outputs.
___
*[`python/WhisperDetection/README.md` line 17 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NOvwOik9uZCj-BYkrzk:-NP3LqMJ9DFfygeJnNC8:b-v80vgo) ([raw file](https://github.com/openmpf/openmpf-components/blob/51f6964f4089741642667c2834593ab399a2052a/python/WhisperDetection/README.md#L17)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

Can we also get descriptions of the following outputs?

`TRANSCRIPT` - for transcription runs.
`TRANSLATED_AUDIO` - for translated audio runs.

Please also mention that the output property changes if the user sets `WHISPER_MODE` to translate or transcribe, so that there is no confusion about what the component returns under different modes.
</blockquote></details>

Correction: Mention that Translation returns both properties but Transcription only returns TRANSCRIPT. 
___
*[`python/WhisperDetection/whisper_detection_component/whisper_detection_component.py` line 202 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NP-Mmtt7UPVzN-qRSTX:-NP31AON7IjPHcbDhRVy:bhztht7) ([raw file](https://github.com/openmpf/openmpf-components/blob/51f6964f4089741642667c2834593ab399a2052a/python/WhisperDetection/whisper_detection_component/whisper_detection_component.py#L202)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

From discussion with Jeff: For transcription and translation, can we also retrieve the reported detected language? End users would like to know what the original language would be. 

Jeff asked if this would be easy or difficult to retrieve from the transcription or translation modes. 

If this info is not accessible from translation/transcription, please let us know. I assume the next best option might be to auto-run detect language first.
</blockquote></details>

Update: retracted as translation/transcription should return a "DECODED_LANGUAGE" for their steps.

We'll reach out to the Whisper Team to see if this processing step could be optimized. Right now, we run transcription twice in order to get the native transcript + translated text for translation (mode=2) runs.
___
*[`python/WhisperDetection/whisper_detection_component/whisper_detection_component.py` line 236 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NP34LMFAuVzImgC72zD:-NP34LMFAuVzImgC72zE:buk29dc) ([raw file](https://github.com/openmpf/openmpf-components/blob/51f6964f4089741642667c2834593ab399a2052a/python/WhisperDetection/whisper_detection_component/whisper_detection_component.py#L236)):*
> ```Python
>             properties = dict(
>                 DETECTED_LANGUAGE=result['language'],
>                 TRANSCRIPT=result['text'].strip()
> ```

Preference would be to add an "ISO_LANGUAGE" and convert "DETECTED_LANGUAGE" -> "DECODED LANGUAGE" for transcription tasks.
___
*[`python/WhisperDetection/whisper_detection_component/whisper_detection_component.py` line 242 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NP342uR5KZRFmWdp_bq:-NP342uR5KZRFmWdp_br:b2ej7zk) ([raw file](https://github.com/openmpf/openmpf-components/blob/51f6964f4089741642667c2834593ab399a2052a/python/WhisperDetection/whisper_detection_component/whisper_detection_component.py#L242)):*
> ```Python
>             result = self.model.transcribe(target_file, language=language)
>             properties = dict(
>                 TRANSCRIPT=result['text'].strip()
> ```

Preference would be to add an "ISO_LANGUAGE" and convert "DETECTED_LANGUAGE" -> "DECODED LANGUAGE" for transcription tasks. In this case, the user provides a transcript language model to use, so we'll return that as the DECODED_LANGUAGE property.


<!-- Sent from Reviewable.io -->

2023-03-21 04:18 UTC, hhuangMITRE requested changes
I've completed my review of the component. Updated the license file to use the 2023 copyright. Updated the test script to check for `ISO_LANGUAGE` and updated API version for the setup.cfg file to `7.1`

> Reviewed 10 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/313#-:-NR1Ed14EfaNw_cFO6XW:b83iz17)* status: 12 of 15 files reviewed, 1 unresolved discussion (waiting on @mcrensh)

___
*[`python/WhisperDetection/Dockerfile` line 33 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NR1NXdd0nQg5dh_M8-c:-NR1NXdd0nQg5dh_M8-d:b-4oaiew) ([raw file](https://github.com/openmpf/openmpf-components/blob/d2b9f749d2ae12d17cba4e7330e487f855173889/python/WhisperDetection/Dockerfile#L33)):*
> ```Dockerfile
> FROM ${BUILD_REGISTRY}openmpf_python_executor_ssb:${BUILD_TAG}
> 
> RUN apt install git-all
> ```

I'm not sure why but this line is failing for my Docker builds. I will debug over the week and see if it's an issue on my end.

@mcrensh please double check that the docker build and unit test is working. I'll submit a build on Reviewable as well. 

I've updated the unit tests to check for the `ISO_LANGUAGE` property. Please ensure that this test passes with the change or update the check as needed. 
___
*[`python/WhisperDetection/LICENSE` line 2 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NQvpEw6Di1SUNfAU3pn:-NQvpEw78ABOx_zfSKX2:b-142g1m) ([raw file](https://github.com/openmpf/openmpf-components/blob/d2b9f749d2ae12d17cba4e7330e487f855173889/python/WhisperDetection/LICENSE#L2)):*
> ```
> /******************************************************************************
>  * Copyright 2022 The MITRE Corporation                                       *
> ```

Fixing the copyright in an update to this PR.
___
*[`python/WhisperDetection/README.md` line 16 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NOwc2kI3faFidGNFqWO:-NQvpZZN7oTWKY3nTZpN:b-1c7zpk) ([raw file](https://github.com/openmpf/openmpf-components/blob/51f6964f4089741642667c2834593ab399a2052a/python/WhisperDetection/README.md#L16)):*
<details><summary><i>Previously, mcrensh wrote…</i></summary><blockquote>

Switched transcription and translation to use decoded language, added iso language for both decoded and detected language.
</blockquote></details>

Thanks, I've added a check to the test script for `ISO_LANGUAGE`
___
*[`python/WhisperDetection/sample_whisper_detector.py` line 10 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NOvvfnyCGBSmrGIkUyd:-NQvpolwCje-ZqsCeCEF:b-g70y9w) ([raw file](https://github.com/openmpf/openmpf-components/blob/51f6964f4089741642667c2834593ab399a2052a/python/WhisperDetection/sample_whisper_detector.py#L10)):*
<details><summary><i>Previously, mcrensh wrote…</i></summary><blockquote>

Updated the copyright. Totally fine with you updating it too next time!
</blockquote></details>

Ok great, I will update the copyright for the LICENSE file then.
___
*[`python/WhisperDetection/setup.cfg` line 34 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NOwCjsb8JYHpV8reNCc:-NR1E66s9xbIflkpNNX1:b-c0dumz) ([raw file](https://github.com/openmpf/openmpf-components/blob/51f6964f4089741642667c2834593ab399a2052a/python/WhisperDetection/setup.cfg#L34)):*
<details><summary><i>Previously, mcrensh wrote…</i></summary><blockquote>

updated API version
</blockquote></details>

I didn't see the API version updated so I made the update. 

Referencing other python .cfg files, the mpf_component_api is now `7.1`


<!-- Sent from Reviewable.io -->

2023-03-21 04:47 UTC, hhuangMITRE reviewed
> Reviewed 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/313)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @mcrensh)

___
*[`python/WhisperDetection/tests/test_whisper_detection.py` line 55 at r5](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NR1UV4f7WzxHbEiLL0p:-NR1UV4g337eXn_vITcm:bgvf0i1) ([raw file](https://github.com/openmpf/openmpf-components/blob/d0859c0e553af7ee73b6f8207d77a0d4c66bc029/python/WhisperDetection/tests/test_whisper_detection.py#L55)):*
> ```Python
>         self.assertEqual(1, len(result))
>         self.assertEqual('en', result[0].detection_properties['DETECTED_LANGUAGE'])
>         self.assertEqual('eng', result[0].detection_properties['ISO_LANGUAGE'])
> ```

Running a new Jenkins build to check that tests pass and images are built properly. 


<!-- Sent from Reviewable.io -->

2023-04-04 16:34 UTC, brosenberg42 requested changes
Please create a PR to add this to https://github.com/openmpf/openmpf-docker/blob/master/docker-compose.components.yml

> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/313#-:-NS76FVCBprLXO24XkcT:bi1zo1e)* status: 11 of 15 files reviewed, 16 unresolved discussions (waiting on @hhuangMITRE and @mcrensh)

___
*[`python/WhisperDetection/Dockerfile` line 32 at r6](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NS6Evq7-wCbRqfKXT01:-NS6Evq7-wCbRqfKXT02:b-pg3s03) ([raw file](https://github.com/openmpf/openmpf-components/blob/a5a8e663427c51961d1b3865e496f718ed7f0931/python/WhisperDetection/Dockerfile#L32)):*
> ```Dockerfile
> ARG BUILD_TAG=latest
> FROM ${BUILD_REGISTRY}openmpf_python_executor_ssb:${BUILD_TAG}
> ```

Add `RUN pip install --no-cache-dir openai-whisper==20230314 'numpy<1.24,>=1.18'` to prevent the dependencies from being downloaded every time the component code changes.
___
*[`python/WhisperDetection/Dockerfile` line 32 at r6](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NS6FWGj5kKTUZ2JK_-3:-NS6FWGj5kKTUZ2JK_-4:bkphwir) ([raw file](https://github.com/openmpf/openmpf-components/blob/a5a8e663427c51961d1b3865e496f718ed7f0931/python/WhisperDetection/Dockerfile#L32)):*
> ```Dockerfile
> ARG BUILD_TAG=latest
> FROM ${BUILD_REGISTRY}openmpf_python_executor_ssb:${BUILD_TAG}
> ```

After adding the pip install command I mentioned add lines like:
```
RUN python -c 'import whisper; whisper.load_model("base")'

RUN python -c 'import whisper; whisper.load_model("tiny")'
```
So the necessary models are downloaded at build time.
___
*[`python/WhisperDetection/README.md` line 23 at r7](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NSBt-VcBV-Q5oRUxGD1:-NSBt-VcBV-Q5oRUxGD2:b-4uvqv1) ([raw file](https://github.com/openmpf/openmpf-components/blob/50f2cf4feaafa888a6601ab238bac74d77c06e1a/python/WhisperDetection/README.md#L23)):*
> ```Markdown
> 
> # Behavior
> Some quirks in Whisper's behavior when transcribing or translating audio with multiple languages has been observed. See [whisper_behavior_notes.md](whisper_behavior_notes.md) for more details.
> ```

The important information in whisper_behavior_notes.md is too spread out. We need a more concise and easily understandable description of the behavior. I think we should include the tables below. We should explain that the tables contain the results of running an audio file where the beginning was in Spanish and the end was in English. We should also say "See [whisper_behavior_notes.md](whisper_behavior_notes.md) for more details and examples."

```
### Transcribe ###

Size  | Provided Language | Result for Spanish Part | Result for English Part
------|-------------------|-------------------------|-------------------------
base  | Auto-detected     | Correctly transcribed   | Gibberish
large | Auto-detected     | Correctly transcribed   | Translated to Spanish
base  | English           | Translated to English   | Correctly transcribed 
large | English           | Translated to English   | Correctly transcribed 




### Translate ###

Size  | Provided Language | Result for Spanish Part | Result for English Part
------|-------------------|-------------------------|------------------------
base  | Auto-detected     | Correctly translated    | Not included in output
base  | English           | Correctly translated    | Transcribed
large | Auto-detected     | Correctly translated    | Mostly skipped
large | English           | Correctly translated    | Mostly skipped

```
___
*[`python/WhisperDetection/README.md` line 30 at r7](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NSBV-Zs2XNe0R8aYaIJ:-NSBV-Zs2XNe0R8aYaIK:b-t9aq3t) ([raw file](https://github.com/openmpf/openmpf-components/blob/50f2cf4feaafa888a6601ab238bac74d77c06e1a/python/WhisperDetection/README.md#L30)):*
> ```Markdown
> All translations are to English.
> 
> | ISO-639-1 | ISO-639-2 | Language         |
> ```

Change the references to "ISO-639-2" to "ISO 639-3". In the other components, `ISO_LANGUAGE` is the ISO 639-3 language code. The language codes you have listed are the same in ISO 639-2 and ISO 639-3, so don't need to change any of the language codes you listed.
___
*[`python/WhisperDetection/setup.cfg` line 36 at r6](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NS6EgeuEAlNh5AXzxbA:-NS6EgeuEAlNh5AXzxbB:b7em1lc) ([raw file](https://github.com/openmpf/openmpf-components/blob/a5a8e663427c51961d1b3865e496f718ed7f0931/python/WhisperDetection/setup.cfg#L36)):*
> ```INI
>     mpf_component_api>=7.0
>     mpf_component_util>=7.0
>     openai-whisper==20230314
> ```

I needed to add `numpy<1.24,>=1.18`, otherwise numba will fail to initialize.
___
*[`python/WhisperDetection/whisper_behavior_notes.md` line 14 at r6](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NS7M7OS41FKP1auwykH:-NS7M7OTDKUpVehCQ6NJ:b-6jiy9l) ([raw file](https://github.com/openmpf/openmpf-components/blob/a5a8e663427c51961d1b3865e496f718ed7f0931/python/WhisperDetection/whisper_behavior_notes.md#L14)):*
> ```Markdown
> translate.
> 
> Example: First half of audio is in Spanish, `second half in English`
> ```

Instead of surrounding the text with back ticks use two asterisks to make it bold. For example: `**bold text**`
___
*[`python/WhisperDetection/whisper_behavior_notes.md` line 19 at r6](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NS7MdI19q0OGOZHYexh:-NS7MdI19q0OGOZHYexi:b-wa1l0p) ([raw file](https://github.com/openmpf/openmpf-components/blob/a5a8e663427c51961d1b3865e496f718ed7f0931/python/WhisperDetection/whisper_behavior_notes.md#L19)):*
> ```Markdown
> language) output:
> 
> -   \'Me comunico con diversas personas en inglés y en español o
> ```

There are a bunch of `\'` in this file. Remove the preceding back slashes.
___
*[`python/WhisperDetection/whisper_behavior_notes.md` line 1 at r7](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NSBu6sF3z5MBBKjP7Ko:-NSBu6sF3z5MBBKjP7Kp:bs3yich) ([raw file](https://github.com/openmpf/openmpf-components/blob/50f2cf4feaafa888a6601ab238bac74d77c06e1a/python/WhisperDetection/whisper_behavior_notes.md#L1)):*
> ```Markdown
> Whisper Multi-Lingual Audio Investigation
> ```

Change this to: "# Whisper Multi-Lingual Behavior"
___
*[`python/WhisperDetection/whisper_behavior_notes.md` line 33 at r7](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NSBuN8sDnEtNwrSrbmw:-NSBuN8sDnEtNwrSrbmx:b-c0hj6e) ([raw file](https://github.com/openmpf/openmpf-components/blob/50f2cf4feaafa888a6601ab238bac74d77c06e1a/python/WhisperDetection/whisper_behavior_notes.md#L33)):*
> ```Markdown
>     su'`
> 
> -   `Highlighted part` is English audio, returns different results each
> ```

In these sections, I would put the bullets containing your observations and descriptions of the behavior before the output bullets.
___
*[`python/WhisperDetection/plugin-files/descriptor/descriptor.json` line 36 at r6](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NS73yl41DcK5xFhjC96:-NS73yl51l5F-PaQHKAb:b7uayco) ([raw file](https://github.com/openmpf/openmpf-components/blob/a5a8e663427c51961d1b3865e496f718ed7f0931/python/WhisperDetection/plugin-files/descriptor/descriptor.json#L36)):*
> ```JSON
>         {
>           "name": "WHISPER_MODE",
>           "description": "Set to '0' for spoken language detection, '1' for speech-to-text transcription, and '2' for speech translation.",
> ```

We should use strings here. For example, we could use `LANGUAGE_DETECTION`, `TRANSCRIPTION`,  and `SPEECH_TRANSLATION`. That will make it easier for a user to understand what the property does when looking at a job or pipeline. 
___
*[`python/WhisperDetection/whisper_detection_component/whisper_detection_component.py` line 59 at r6](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NS7RY5LABcOeCzBzG2i:-NS7RY5LABcOeCzBzG2j:bryhwbx) ([raw file](https://github.com/openmpf/openmpf-components/blob/a5a8e663427c51961d1b3865e496f718 [...]

2023-05-12 06:38 UTC, mcrensh reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/313)* status: 8 of 15 files reviewed, 16 unresolved discussions (waiting on @brosenberg42 and @hhuangMITRE)

___
*[`python/WhisperDetection/Dockerfile` line 33 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NR1NXdd0nQg5dh_M8-c:-NVDZ_QU-Ev4KXKssDqh:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/d2b9f749d2ae12d17cba4e7330e487f855173889/python/WhisperDetection/Dockerfile#L33)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

I'm not sure why but this line is failing for my Docker builds. I will debug over the week and see if it's an issue on my end.

@mcrensh please double check that the docker build and unit test is working. I'll submit a build on Reviewable as well. 

I've updated the unit tests to check for the `ISO_LANGUAGE` property. Please ensure that this test passes with the change or update the check as needed. 
</blockquote></details>

Done.
___
*[`python/WhisperDetection/Dockerfile` line 32 at r6](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NS6Evq7-wCbRqfKXT01:-NVDXs9x1ifdYCzJEwPQ:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/a5a8e663427c51961d1b3865e496f718ed7f0931/python/WhisperDetection/Dockerfile#L32)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Add `RUN pip install --no-cache-dir openai-whisper==20230314 'numpy<1.24,>=1.18'` to prevent the dependencies from being downloaded every time the component code changes.
</blockquote></details>

Done.
___
*[`python/WhisperDetection/Dockerfile` line 32 at r6](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NS6FWGj5kKTUZ2JK_-3:-NVDY4Si4pfxFIbQ5qbF:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/a5a8e663427c51961d1b3865e496f718ed7f0931/python/WhisperDetection/Dockerfile#L32)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

After adding the pip install command I mentioned add lines like:
```
RUN python -c 'import whisper; whisper.load_model("base")'

RUN python -c 'import whisper; whisper.load_model("tiny")'
```
So the necessary models are downloaded at build time.
</blockquote></details>

Done.
___
*[`python/WhisperDetection/README.md` line 23 at r7](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NSBt-VcBV-Q5oRUxGD1:-NVDZ4f_3jqrIhDGJ8Dy:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/50f2cf4feaafa888a6601ab238bac74d77c06e1a/python/WhisperDetection/README.md#L23)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

The important information in whisper_behavior_notes.md is too spread out. We need a more concise and easily understandable description of the behavior. I think we should include the tables below. We should explain that the tables contain the results of running an audio file where the beginning was in Spanish and the end was in English. We should also say "See [whisper_behavior_notes.md](whisper_behavior_notes.md) for more details and examples."

```
### Transcribe ###

Size  | Provided Language | Result for Spanish Part | Result for English Part
------|-------------------|-------------------------|-------------------------
base  | Auto-detected     | Correctly transcribed   | Gibberish
large | Auto-detected     | Correctly transcribed   | Translated to Spanish
base  | English           | Translated to English   | Correctly transcribed 
large | English           | Translated to English   | Correctly transcribed 




### Translate ###

Size  | Provided Language | Result for Spanish Part | Result for English Part
------|-------------------|-------------------------|------------------------
base  | Auto-detected     | Correctly translated    | Not included in output
base  | English           | Correctly translated    | Transcribed
large | Auto-detected     | Correctly translated    | Mostly skipped
large | English           | Correctly translated    | Mostly skipped

```
</blockquote></details>

Done.



_Code quote:_
```Markdown
Some quirks in Whisper's behavior when transcribing or translating audio with multiple languages has been observed.
```
___
*[`python/WhisperDetection/README.md` line 30 at r7](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NSBV-Zs2XNe0R8aYaIJ:-NVD21Yu7DuDvwTNxUmU:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/50f2cf4feaafa888a6601ab238bac74d77c06e1a/python/WhisperDetection/README.md#L30)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Change the references to "ISO-639-2" to "ISO 639-3". In the other components, `ISO_LANGUAGE` is the ISO 639-3 language code. The language codes you have listed are the same in ISO 639-2 and ISO 639-3, so don't need to change any of the language codes you listed.
</blockquote></details>

Done.
___
*[`python/WhisperDetection/setup.cfg` line 36 at r6](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NS6EgeuEAlNh5AXzxbA:-NVD2u__6hT4zzgLcSjO:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/a5a8e663427c51961d1b3865e496f718ed7f0931/python/WhisperDetection/setup.cfg#L36)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I needed to add `numpy<1.24,>=1.18`, otherwise numba will fail to initialize.
</blockquote></details>

Done.
___
*[`python/WhisperDetection/whisper_behavior_notes.md` line 14 at r6](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NS7M7OS41FKP1auwykH:-NVD4nTn3FCZBah2TB7F:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/a5a8e663427c51961d1b3865e496f718ed7f0931/python/WhisperDetection/whisper_behavior_notes.md#L14)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Instead of surrounding the text with back ticks use two asterisks to make it bold. For example: `**bold text**`
</blockquote></details>

Done.
___
*[`python/WhisperDetection/whisper_behavior_notes.md` line 19 at r6](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NS7MdI19q0OGOZHYexh:-NVD4oHI4U-Mvxqh16vs:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/a5a8e663427c51961d1b3865e496f718ed7f0931/python/WhisperDetection/whisper_behavior_notes.md#L19)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

There are a bunch of `\'` in this file. Remove the preceding back slashes.
</blockquote></details>

Done.
___
*[`python/WhisperDetection/whisper_behavior_notes.md` line 1 at r7](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NSBu6sF3z5MBBKjP7Ko:-NVD2zPX9nT5oUETffrj:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/50f2cf4feaafa888a6601ab238bac74d77c06e1a/python/WhisperDetection/whisper_behavior_notes.md#L1)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Change this to: "# Whisper Multi-Lingual Behavior"
</blockquote></details>

Done.
___
*[`python/WhisperDetection/whisper_behavior_notes.md` line 33 at r7](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NSBuN8sDnEtNwrSrbmw:-NVD5Mg6C1y1crPjcx-n:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/50f2cf4feaafa888a6601ab238bac74d77c06e1a/python/WhisperDetection/whisper_behavior_notes.md#L33)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

In these sections, I would put the bullets containing your observations and descriptions of the behavior before the output bullets.
</blockquote></details>

Done.
___
*[`python/WhisperDetection/plugin-files/descriptor/descriptor.json` line 36 at r6](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NS73yl41DcK5xFhjC96:-NVD603i8aPD-vDBoIbq:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/a5a8e663427c51961d1b3865e496f718ed7f0931/python/WhisperDetection/p [...]

2023-05-12 15:54 UTC, brosenberg42 requested changes
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/313)* status: 8 of 15 files reviewed, 5 unresolved discussions (waiting on @hhuangMITRE and @mcrensh)

___
*[`python/WhisperDetection/setup.cfg` line 29 at r9](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NVETduR4bUF_Tg5c02M:-NVETduS6AMtSH0lUpqp:b-suxq2a) ([raw file](https://github.com/openmpf/openmpf-components/blob/11ad49ee3cebd8f584dab176b013d95c584dd60e/python/WhisperDetection/setup.cfg#L29)):*
> ```INI
> [metadata]
> name = WhisperDetection
> version = 0.1
> ```

Please change this to `version = 7.2`
___
*[`python/WhisperDetection/plugin-files/descriptor/descriptor.json` line 2 at r9](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NVFTjxG1np_93-3QVux:-NVFTjxG1np_93-3QVuy:bsr91ea) ([raw file](https://github.com/openmpf/openmpf-components/blob/11ad49ee3cebd8f584dab176b013d95c584dd60e/python/WhisperDetection/plugin-files/descriptor/descriptor.json#L2)):*
> ```JSON
> {
>   "componentName": "WhisperDetection",
> ```

In today's meeting, we were discussing what the name of the component should be. We decided that it should be called "WhisperSpeechDetection".
___
*[`python/WhisperDetection/plugin-files/descriptor/descriptor.json` line 3 at r9](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NVFDx0i2zYvoGPHKFIG:-NVFDx0i2zYvoGPHKFIH:b-cjhf3n) ([raw file](https://github.com/openmpf/openmpf-components/blob/11ad49ee3cebd8f584dab176b013d95c584dd60e/python/WhisperDetection/plugin-files/descriptor/descriptor.json#L3)):*
> ```JSON
> {
>   "componentName": "WhisperDetection",
>   "componentVersion": "7.1",
> ```

Change this to 7.2
___
*[`python/WhisperDetection/plugin-files/descriptor/descriptor.json` line 4 at r9](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NVFE1o19weoRfgk7I00:-NVFE1o19weoRfgk7I01:b-cjhf3n) ([raw file](https://github.com/openmpf/openmpf-components/blob/11ad49ee3cebd8f584dab176b013d95c584dd60e/python/WhisperDetection/plugin-files/descriptor/descriptor.json#L4)):*
> ```JSON
>   "componentName": "WhisperDetection",
>   "componentVersion": "7.1",
>   "middlewareVersion": "7.1",
> ```

Change this to 7.2


<!-- Sent from Reviewable.io -->

2023-05-19 20:59 UTC, mcrensh reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/313)* status: 0 of 15 files reviewed, 5 unresolved discussions (waiting on @brosenberg42 and @hhuangMITRE)

___
*[`python/WhisperDetection/setup.cfg` line 29 at r9](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NVETduR4bUF_Tg5c02M:-NVpAZ1DB8cgydM9x84G:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/11ad49ee3cebd8f584dab176b013d95c584dd60e/python/WhisperDetection/setup.cfg#L29)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Please change this to `version = 7.2`
</blockquote></details>

Done.
___
*[`python/WhisperDetection/plugin-files/descriptor/descriptor.json` line 2 at r9](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NVFTjxG1np_93-3QVux:-NVplyJi16xOrl1fxt5j:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/11ad49ee3cebd8f584dab176b013d95c584dd60e/python/WhisperDetection/plugin-files/descriptor/descriptor.json#L2)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

In today's meeting, we were discussing what the name of the component should be. We decided that it should be called "WhisperSpeechDetection".
</blockquote></details>

Done.
___
*[`python/WhisperDetection/plugin-files/descriptor/descriptor.json` line 3 at r9](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NVFDx0i2zYvoGPHKFIG:-NVpAe9s6d208oI8FHqL:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/11ad49ee3cebd8f584dab176b013d95c584dd60e/python/WhisperDetection/plugin-files/descriptor/descriptor.json#L3)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Change this to 7.2
</blockquote></details>

Done.
___
*[`python/WhisperDetection/plugin-files/descriptor/descriptor.json` line 4 at r9](https://reviewable.io/reviews/openmpf/openmpf-components/313#-NVFE1o19weoRfgk7I00:-NVpAeiED5EsT8nJ7X1T:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/11ad49ee3cebd8f584dab176b013d95c584dd60e/python/WhisperDetection/plugin-files/descriptor/descriptor.json#L4)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Change this to 7.2
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-25 14:32 UTC, brosenberg42 approved these changes
> Reviewed 11 of 15 files at r10, 3 of 3 files at r11.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/313)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @hhuangMITRE)



<!-- Sent from Reviewable.io -->

2023-09-01 14:10 UTC, hhuangMITRE approved these changes
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/313)* status: 14 of 15 files reviewed, all discussions resolved (waiting on @mcrensh)



<!-- Sent from Reviewable.io -->

2023-09-01 20:08 UTC, merged