Adding ClipDetection component code.
openmpf/openmpf-components pull request #326
Opened 2023-04-26 13:10 UTC by ZachCafego

**Issues:**

- https://github.com/openmpf/openmpf/issues/1 < Example
- https://github.com/openmpf/openmpf/issues/2 < Example

If a related issue doesn't exist, then create one first and assign it to yourself.

**Related PRs:**

- https://github.com/openmpf/openmpf/pull/22 < Example
- https://github.com/openmpf/openmpf/pull/53 < Example

Please review our [Contributor Guide](https://openmpf.github.io/docs/site/Contributor-Guide/index.html).

2023-04-26 15:41 UTC, jrobble requested changes
> Reviewed 15 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/326)* status: 15 of 25 files reviewed, 18 unresolved discussions (waiting on @ZachCafego)

___
*[`python/ClipDetection/clip_component/data/seven_templates.txt` line 3 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NTy4NJmD3ABs4UGylSl:-NTy4NJmD3ABs4UGylSm:bblvwqq) ([raw file](https://github.com/openmpf/openmpf-components/blob/74e91d9962edc444267519d714d03aab50b3cb2e/python/ClipDetection/clip_component/data/seven_templates.txt#L3)):*
> ```help
> itap of a {}.
> a bad photo of the {}.
> an origami {}.
> ```

origami? That's interesting. Not saying we need to change anything.
___
*[`python/ClipDetection/clip_component/triton_server/Dockerfile` line 45 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NTy4kpd6fIB8FHWKwAm:-NTy4kpd6fIB8FHWKwAn:b-tz93fk) ([raw file](https://github.com/openmpf/openmpf-components/blob/74e91d9962edc444267519d714d03aab50b3cb2e/python/ClipDetection/clip_component/triton_server/Dockerfile#L45)):*
> ```Dockerfile
> 
> LABEL org.label-schema.license="Apache 2.0" \
>       org.label-schema.name="OpenMPF CLIP Detection" \
> ```

Call this "OpenMPF CLIP Detection Triton Server".
___
*[`python/ClipDetection/clip_component/triton_server/models/ip_clip_512/config.pbtxt` line 4 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NTy56awCnjAIdGy9XIL:-NTy56awCnjAIdGy9XIM:b-fhhmj5) ([raw file](https://github.com/openmpf/openmpf-components/blob/74e91d9962edc444267519d714d03aab50b3cb2e/python/ClipDetection/clip_component/triton_server/models/ip_clip_512/config.pbtxt#L4)):*
https://github.com/openmpf/openmpf-components/blob/master/cpp/OcvYoloDetection/triton_server/models/yolo-608.config.pbtxt doesn't have an `instance_group`.

The Triton docs say:

> By default, a single execution instance of the model is created for each GPU available in the system.

That is the default behavior we want. If a user wants to change it they can modify this file with their own `instance_group`, or groups.
___
*[`python/ClipDetection/plugin-files/descriptor/descriptor.json` line 3 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NTy5akc7Kocr60z07E_:-NTy5akc7Kocr60z07Ea:ba13mi6) ([raw file](https://github.com/openmpf/openmpf-components/blob/74e91d9962edc444267519d714d03aab50b3cb2e/python/ClipDetection/plugin-files/descriptor/descriptor.json#L3)):*
> ```JSON
> {
>     "componentName": "ClipDetection",
>     "componentVersion": "6.3",
> ```

Change to 7.1.
___
*[`python/ClipDetection/plugin-files/descriptor/descriptor.json` line 4 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NTy5dgO8NZnvH8DcBM-:-NTy5dgO8NZnvH8DcBM0:ba13mi6) ([raw file](https://github.com/openmpf/openmpf-components/blob/74e91d9962edc444267519d714d03aab50b3cb2e/python/ClipDetection/plugin-files/descriptor/descriptor.json#L4)):*
> ```JSON
>     "componentName": "ClipDetection",
>     "componentVersion": "6.3",
>     "middlewareVersion": "6.3",
> ```

Change to 7.1.
___
*[`python/ClipDetection/plugin-files/descriptor/descriptor.json` line 37 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NTy5loP3QGJET756dnf:-NTy5loP3QGJET756dng:b-z64yr) ([raw file](https://github.com/openmpf/openmpf-components/blob/74e91d9962edc444267519d714d03aab50b3cb2e/python/ClipDetection/plugin-files/descriptor/descriptor.json#L37)):*
> ```JSON
>                 {
>                     "name": "CLASSIFICATION_LIST",
>                     "description": "Specifies the classification list that will be tokenized for the text encoder (supports ImageNet and COCO). By default, the ImageNet classifications will be used.",
> ```

Say:

```
(supports "imagenet" and "coco")
```

to be clear exactly which strings the user needs to type in.
___
*[`python/ClipDetection/plugin-files/descriptor/descriptor.json` line 42 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NTy6Ck02dzPXk2oP0VR:-NTy6Ck02dzPXk2oP0VS:b-jyhfs1) ([raw file](https://github.com/openmpf/openmpf-components/blob/74e91d9962edc444267519d714d03aab50b3cb2e/python/ClipDetection/plugin-files/descriptor/descriptor.json#L42)):*
> ```JSON
>                 },
>                 {
>                     "name": "CLASSFICATION_PATH",
> ```

Spelling: "CLASSIFICATION"
___
*[`python/ClipDetection/plugin-files/descriptor/descriptor.json` line 43 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NTy6NNtCjfcCuHYAcbR:-NTy6NNu8cIjcu7ttrbj:bqm1xv6) ([raw file](https://github.com/openmpf/openmpf-components/blob/74e91d9962edc444267519d714d03aab50b3cb2e/python/ClipDetection/plugin-files/descriptor/descriptor.json#L43)):*
> ```JSON
>                 {
>                     "name": "CLASSFICATION_PATH",
>                     "description": "Specifies a path to a csv file containing two names for each classification: one is the full name to display and the other to enter into the CLIP text encoding.",
> ```

Say "Optionally specifies a path to a custom csv file ..."

That will make it clear that this is optional, and the "custom" part makes it clearer why there is no default value.
___
*[`python/ClipDetection/plugin-files/descriptor/descriptor.json` line 49 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NTy6aOz1lUr-3rjXDtx:-NTy6aOz1lUr-3rjXDty:bgirpgv) ([raw file](https://github.com/openmpf/openmpf-components/blob/74e91d9962edc444267519d714d03aab50b3cb2e/python/ClipDetection/plugin-files/descriptor/descriptor.json#L49)):*
> ```JSON
>                 {
>                     "name": "TEMPLATE_PATH",
>                     "description": "Specifies a path to a text file containing custom templates for use in the CLIP model. Include a single {} where each classification is to be inserted.",
> ```

Say "Optionally specifies a path to a custom text file ..."

That will make it clear that this is optional, and the "custom" part makes it clearer why there is no default value.
___
*[`python/ClipDetection/plugin-files/descriptor/descriptor.json` line 76 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NTy8mUw9zhPBmG5wf2P:-NTy8mUw9zhPBmG5wf2Q:bkhgls7) ([raw file](https://github.com/openmpf/openmpf-components/blob/74e91d9962edc444267519d714d03aab50b3cb2e/python/ClipDetection/plugin-files/descriptor/descriptor.json#L76)):*
> ```JSON
>     "actions": [
>         {
>             "name": "CLIP CLASSIFICATION ACTION",
> ```

Call this "CLIP COCO CLASSIFICATION ACTION".
___
*[`python/ClipDetection/plugin-files/descriptor/descriptor.json` line 77 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NTy6o3NB8V4PaYUQ9XS:-NTy6o3NB8V4PaYUQ9XT:bimnmd6) ([raw file](https://github.com/openmpf/openmpf-components/blob/74e91d9962edc444267519d714d03aab50b3cb2e/python/ClipDetection/plugin-files/descriptor/descriptor.json#L77)):*
> ```JSON
>         {
>             "name": "CLIP CLASSIFICATION ACTION",
>             "description": "Runs CLIP classification on the COCO dataset classes, or with a specified set of classifications and templates.",
> ```

I think we should remove the "or with a specified set of classifications and templates" part from here and elsewhere in this file. We should assume the user is going to use this action without additional job properties, so they won't be providing a custom set of classifications or templates.

More generally, we shouldn't bother describing the pipeline behavior if the user is going to modify it my providing their own properties that override the defaults.
___
*[`python/ClipDetection/plugin-files/descriptor/descriptor.json` line 121 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NTy8qfa5kf-eVJ94zq0:-NTy8qfa5kf-eVJ94zq1:b9srxue) ([raw file](https://github.com/openmpf/openmpf-components/blob/74e91d9962edc444267519d714d03aab50b3cb2e/python/ClipDetection/plugin-files/descriptor/descriptor.json#L121)):*
> ```JSON
>     "tasks": [
>      [...]

2023-04-26 21:47 UTC, jrobble requested changes
> Reviewed 8 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/326)* status: 17 of 25 files reviewed, 35 unresolved discussions (waiting on @ZachCafego)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NTyd5Ix1tGLvLHFttJy:-NTyd5Ix1tGLvLHFttJz:b-s11qkq) (no related file):*
As discussed, please create an `openmpf-docker` PR where you add an entry for the CLIP client and server, and link that PR to this one, and vice versa.

___
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NTyhLpp160ZKEFOV8ZN:-NTyhLpp160ZKEFOV8ZO:b-mnykme) (no related file):*
Generating the 80 text embeddings takes too long to make running the unit tests as part of monolithic build feasible. Please update the unit tests to use `NUMBER_OF_TEMPLATES=1`.

Additionally, we should set `ENABLE_CROPPING=false` for the unit tests to further speed them up.

Also, it's quicker to generate the embeddings for COCO then ImageNet, so let's change the sturgeon unit test + image to detect a COCO class.

___
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NTz6mBk84EW3VwiLyO0:-NTyw92476rvP8TnNKBi:bfmbqe4) (no related file):*
A note to myself to run the Jenkins build for you once the existing comments are addressed.

___
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NTzNe6WBjNryBvFtEUK:-NTzNe6Y6tfQYqEZFt60:b3a9m8j) (no related file):*
Please note in the README that the following warning is expected if building on a host without a GPU:

```
(venv) mpf@openmpf-dev-ubuntu:~/git/openmpf-projects/openmpf-components/python/ClipDetection/tmp/openai-CLIP-a9b1bf5$ python3 -c 'import clip; clip.load("ViT-B/32")'
/home/mpf/git/openmpf-projects/openmpf-components/python/ClipDetection/venv/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
```

___
___
*[`python/ClipDetection/README.md` line 23 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NTyfpeKCVwfWwJmmIdt:-NTyfpeKCVwfWwJmmIdu:b-mhc0yr) ([raw file](https://github.com/openmpf/openmpf-components/blob/74e91d9962edc444267519d714d03aab50b3cb2e/python/ClipDetection/README.md#L23)):*
> ```Markdown
> - `ENABLE_TRITON`: A boolean toggle to specify whether the component should use a Triton inference server to process the image job. By default this is set to false.
> 
> - `TRITON_SERVER`: Specifies the Triton server <host>:<port> to use for inferencing. By default, this is set to 'clip-detection-server:8001'.
> ```

You need to use backticks around `<host>:<port>` for the Markdown to render properly:

```
`TRITON_SERVER`: Specifies the Triton server `<host>:<port>` to use for inferencing. By default, this is set to 'clip-detection-server:8001'.
```
___
*[`python/ClipDetection/README.md` line 45 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NTygnOCBortDcvRGiM9:-NTygnODEZ5Qt3Aph2QJ:b-wbqrdq) ([raw file](https://github.com/openmpf/openmpf-components/blob/74e91d9962edc444267519d714d03aab50b3cb2e/python/ClipDetection/README.md#L45)):*
> ```Markdown
> # Custom Classifications
> 
> The need for custom classifications arose when training on the ImageNet classifications, where any different class can have many equivalent names. For example, one of the classes is "great white shark, white shark, man-eater, man-eating shark, Carcharodon carcharias". We found the model to be most performant when given a single representative class title. For this case, 'great white shark' makes the most sense but the 'imagenet_classification_list.csv' file gives representative titles for each class, adapted from .ipynb files on the CLIP GitHub page. 
> ```

Let's rephrase this as:

```
For this case, 'great white shark' makes the most sense. The `imagenet_classification_list.csv` file gives representative titles for each class, adapted from .ipynb files on the CLIP GitHub page.·
```

First, I removed the "but" since it seemed misleading. Second, I used backticks around `imagenet_classification_list.csv` since it's a file name / path.
___
*[`python/ClipDetection/setup.cfg` line 42 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NTzWCBv0tM6DkTis9kP:-NTzWCByBEHBBoX-zjYU:bkhqt1s) ([raw file](https://github.com/openmpf/openmpf-components/blob/74e91d9962edc444267519d714d03aab50b3cb2e/python/ClipDetection/setup.cfg#L42)):*
> ```INI
>     component = clip_component.clip_component:ClipComponent
> 
> [options.package_data]
> ```

You need to prefix all of these with `data/` as I did here:

```
[options.package_data]
clip_component = data/imagenet_classification_list.csv, data/coco_classification_list.csv, data/eighty_templates.txt, data/seven_templates.txt, data/one_template.txt
```

Or else the following command will fail:

```
DOCKER_BUILDKIT=1 docker build . --progress=plain --build-arg RUN_TESTS=true -t openmpf_clip_detection:jrobble

<snip>

#13 19.71 FileNotFoundError: [Errno 2] No such file or directory: '/opt/mpf/plugin-venv/lib/python3.8/site-packages/clip_component/data/one_template.txt'
```
___
*[`python/ClipDetection/clip_component/clip_component.py` line 36 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NTyiSelBjMOOU9AVSnW:-NTyiSelBjMOOU9AVSnX:b-cxmct5) ([raw file](https://github.com/openmpf/openmpf-components/blob/74e91d9962edc444267519d714d03aab50b3cb2e/python/ClipDetection/clip_component/clip_component.py#L36)):*
> ```Python
> import clip
> 
> import sys
> ```

Pylance in VScode says this isn't used. Please remove it.
___
*[`python/ClipDetection/clip_component/clip_component.py` line 43 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NTyiIkT8Y5a_zd1HR3h:-NTyiIkU5slmJdTxOpdB:b-cxmct5) ([raw file](https://github.com/openmpf/openmpf-components/blob/74e91d9962edc444267519d714d03aab50b3cb2e/python/ClipDetection/clip_component/clip_component.py#L43)):*
> ```Python
> import tritonclient.grpc as grpcclient
> from tritonclient.utils import InferenceServerException, triton_to_np_dtype
> import tritonclient.utils
> ```

Pylance in VScode says this isn't used. Please remove it.
___
*[`python/ClipDetection/clip_component/clip_component.py` line 60 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NTz9-8t1GJpwLL9p3vS:-NTz9-8t1GJpwLL9p3vT:b-fbz7ku) ([raw file](https://github.com/openmpf/openmpf-components/blob/74e91d9962edc444267519d714d03aab50b3cb2e/python/ClipDetection/clip_component/clip_component.py#L60)):*
> ```Python
> 
>             image = image_reader.get_image()
>             return JobRunner().get_classifications(image, image_job.job_properties)
> ```

We should always log some kind of "job complete" message. It usually takes the form:

```
            logger.info(
                f'Job complete. Found {len(some_detections)} detections.')
```
___
*[`python/ClipDetection/clip_component/clip_component.py` line 73 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NTzHfxQ6LCINgcUybO6:-NTzHfxU5D31Ia4ENPO_:b-ia5ye2) ([raw file](https://github.com/openmpf/openmpf-components/blob/74e91d9962edc444267519d714d03aab50b3cb2e/python/ClipDetection/clip_component/clip_component.py#L73)):*
> ```Python
>         self.model = model
> 
>         self.classification_path = ''
> ```

Class variables should start with an underscore, like [this](https://github.com/openmpf/openmpf-components/blob/master/python/AzureFormDetection/acs_form_detection_component/acs_form_detection_component.py#L86).

Also, functions that are private (as in not invoked by anything but the class itself), should start with an underscore as well.
___
*[`python/ClipDetection/clip_component/clip_component.py` line 78 at r1](https://reviewable.io/re [...]

2023-04-27 19:06 UTC, ZachCafego reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/326)* status: 15 of 26 files reviewed, 35 unresolved discussions (waiting on @jrobble)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NTyd5Ix1tGLvLHFttJy:-NU35XLCBoeovsvfkW_c:b-896fix) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

As discussed, please create an `openmpf-docker` PR where you add an entry for the CLIP client and server, and link that PR to this one, and vice versa.
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NTyhLpp160ZKEFOV8ZN:-NU35_hzBRjInX6MsMae:b-896fix) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Generating the 80 text embeddings takes too long to make running the unit tests as part of monolithic build feasible. Please update the unit tests to use `NUMBER_OF_TEMPLATES=1`.

Additionally, we should set `ENABLE_CROPPING=false` for the unit tests to further speed them up.

Also, it's quicker to generate the embeddings for COCO then ImageNet, so let's change the sturgeon unit test + image to detect a COCO class.
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NTzNe6WBjNryBvFtEUK:-NU35dju9B_YoLHvFPpH:b-896fix) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please note in the README that the following warning is expected if building on a host without a GPU:

```
(venv) mpf@openmpf-dev-ubuntu:~/git/openmpf-projects/openmpf-components/python/ClipDetection/tmp/openai-CLIP-a9b1bf5$ python3 -c 'import clip; clip.load("ViT-B/32")'
/home/mpf/git/openmpf-projects/openmpf-components/python/ClipDetection/venv/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
```
</blockquote></details>

Done.

___
___
*[`python/ClipDetection/README.md` line 23 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NTyfpeKCVwfWwJmmIdt:-NU35iHz25np3Xrrp-sf:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/74e91d9962edc444267519d714d03aab50b3cb2e/python/ClipDetection/README.md#L23)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

You need to use backticks around `<host>:<port>` for the Markdown to render properly:

```
`TRITON_SERVER`: Specifies the Triton server `<host>:<port>` to use for inferencing. By default, this is set to 'clip-detection-server:8001'.
```
</blockquote></details>

Done.
___
*[`python/ClipDetection/README.md` line 45 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NTygnOCBortDcvRGiM9:-NU35jW5EsvvZxL1VYYB:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/74e91d9962edc444267519d714d03aab50b3cb2e/python/ClipDetection/README.md#L45)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Let's rephrase this as:

```
For this case, 'great white shark' makes the most sense. The `imagenet_classification_list.csv` file gives representative titles for each class, adapted from .ipynb files on the CLIP GitHub page.·
```

First, I removed the "but" since it seemed misleading. Second, I used backticks around `imagenet_classification_list.csv` since it's a file name / path.
</blockquote></details>

Done.
___
*[`python/ClipDetection/setup.cfg` line 42 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NTzWCBv0tM6DkTis9kP:-NU35ksT0m5bRJPnN6Za:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/74e91d9962edc444267519d714d03aab50b3cb2e/python/ClipDetection/setup.cfg#L42)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

You need to prefix all of these with `data/` as I did here:

```
[options.package_data]
clip_component = data/imagenet_classification_list.csv, data/coco_classification_list.csv, data/eighty_templates.txt, data/seven_templates.txt, data/one_template.txt
```

Or else the following command will fail:

```
DOCKER_BUILDKIT=1 docker build . --progress=plain --build-arg RUN_TESTS=true -t openmpf_clip_detection:jrobble

<snip>

#13 19.71 FileNotFoundError: [Errno 2] No such file or directory: '/opt/mpf/plugin-venv/lib/python3.8/site-packages/clip_component/data/one_template.txt'
```
</blockquote></details>

Done.
___
*[`python/ClipDetection/clip_component/clip_component.py` line 36 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NTyiSelBjMOOU9AVSnW:-NU35mW62xndvAVkRgfR:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/74e91d9962edc444267519d714d03aab50b3cb2e/python/ClipDetection/clip_component/clip_component.py#L36)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Pylance in VScode says this isn't used. Please remove it.
</blockquote></details>

Done.
___
*[`python/ClipDetection/clip_component/clip_component.py` line 43 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NTyiIkT8Y5a_zd1HR3h:-NU35nsi3LuO8GtyHtf9:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/74e91d9962edc444267519d714d03aab50b3cb2e/python/ClipDetection/clip_component/clip_component.py#L43)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Pylance in VScode says this isn't used. Please remove it.
</blockquote></details>

Done.
___
*[`python/ClipDetection/clip_component/clip_component.py` line 60 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NTz9-8t1GJpwLL9p3vS:-NU35p851K_y7sfYVJZz:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/74e91d9962edc444267519d714d03aab50b3cb2e/python/ClipDetection/clip_component/clip_component.py#L60)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

We should always log some kind of "job complete" message. It usually takes the form:

```
            logger.info(
                f'Job complete. Found {len(some_detections)} detections.')
```
</blockquote></details>

Done.
___
*[`python/ClipDetection/clip_component/clip_component.py` line 73 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NTzHfxQ6LCINgcUybO6:-NU35u2k5GMFO4xx_96s:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/74e91d9962edc444267519d714d03aab50b3cb2e/python/ClipDetection/clip_component/clip_component.py#L73)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Class variables should start with an underscore, like [this](https://github.com/openmpf/openmpf-components/blob/master/python/AzureFormDetection/acs_form_detection_component/acs_form_detection_component.py#L86).

Also, functions that are private (as in not invoked by anything but the class itself), should start with an underscore as well.
</blockquote></details>

Done.
___
*[`python/ClipDetection/clip_component/clip_component.py` line 78 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NTzATvu2aCeiCehZKkg:-NU35vmrANxlLXSP3rCD:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/74e91d9962edc444267519d714d03aab50b3cb2e/python/ClipDetection/clip_component/clip_component.py#L78)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please give this variable a more descriptive name.
</blockquote></details>

Done.
___
*[`python/ClipDetection/clip_component/clip_component.py` line 121 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NTzBwiCAVm0Po8wd4QZ:-NU35 [...]

2023-04-29 00:18 UTC, jrobble requested changes
> Reviewed 3 of 7 files at r2, 1 of 1 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/326)* status: 25 of 26 files reviewed, 6 unresolved discussions (waiting on @ZachCafego)

___
*[`python/ClipDetection/README.md` line 5 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NU3h_2v-kJrN2mEqy75:-NU3h_2v-kJrN2mEqy76:bb64xgs) ([raw file](https://github.com/openmpf/openmpf-components/blob/4855d9afee1d037d79c30aa0bd29c1d058bc72bf/python/ClipDetection/README.md#L5)):*
> ```Markdown
> This repository contains source code for the OpenMPF CLIP detection component. CLIP (Contrastive Language-Image Pre-Training) was developed by OpenAI and published in 2021. https://arxiv.org/abs/2103.00020
> 
> When building on a host without a GPU, the following warning is expected:
> ```

This is too low level to be in the Overview section. Please move to the bottom of the README in a `# Known Issues` section.
___
*[`python/ClipDetection/clip_component/clip_component.py` line 60 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NTz3pE_AOKoOcNozKXe:-NTz3pEa45eUBKmaqI4H:b-b1z9o4) ([raw file](https://github.com/openmpf/openmpf-components/blob/74e91d9962edc444267519d714d03aab50b3cb2e/python/ClipDetection/clip_component/clip_component.py#L60)):*
> ```Python
> 
>             image = image_reader.get_image()
>             return JobRunner().get_classifications(image, image_job.job_properties)
> ```

Creating a new instance of `JobRunner` for every job does not allow you to cache the text embeddings between jobs. To see if the text embeddings were being cached I modified your unit test:

```    def test_image_file(self):
        component = ClipComponent()

        job = mpf.ImageJob(
            job_name='test-image',
            data_uri=self._get_test_file('sturgeon.jpg'),
            job_properties=dict(
                NUMBER_OF_CLASSIFICATIONS = 1,
                NUMBER_OF_TEMPLATES = 1,
                CLASSIFICATION_LIST = 'coco',
                ENABLE_CROPPING='false'
            ),
            media_properties={},
            feed_forward_location=None
        )
        result = list(component.get_detections_from_image(job))[0]
        
        result = list(component.get_detections_from_image(job))[0]

        result = list(component.get_detections_from_image(job))[0]
```

I saw it generate the embeddings for each `get_detections_from_image()` call.

I'm not saying you should permanently update your unit test that way. I made the change temporarily just to test this out.

In retrospect, the reason that only the Azure components may be using a `JobRunner` is because they don't need to cache anything between jobs. That's because they are simple clients to the Azure Cognitive Services REST endpoints.

With this in mind, it's probably best to refactor your code not to use a `JobRunner`. Creating a new `JobRunner` each time also does `clip.load()` each time.

You may want to consider refactoring it into a wrapper class like [this](https://github.com/openmpf/openmpf-components/blob/master/python/NlpTextCorrection/nlp_correction_component/nlp_correction_component.py#L65). Alternatively, EAST just caches its model directly [here](https://github.com/openmpf/openmpf-components/blob/master/python/EastTextDetection/east_component/east_processor.py#L108).
___
*[`python/ClipDetection/clip_component/triton_server/Dockerfile` line 32 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NU8fEjJ9OBW4t-iC0O2:-NU8fEjKA-kvkbIxcboi:bq9j96u) ([raw file](https://github.com/openmpf/openmpf-components/blob/4855d9afee1d037d79c30aa0bd29c1d058bc72bf/python/ClipDetection/clip_component/triton_server/Dockerfile#L32)):*
> ```Dockerfile
> ARG BUILD_TAG=latest
> 
> FROM ${MODELS_REGISTRY}openmpf_clip_detection_triton_models:${BUILD_TAG} as models
> ```

We need to push this to DockerHub, like we do with the OcvYoloDetection model files [here](https://hub.docker.com/r/openmpf/openmpf_ocv_yolo_detection_triton_models). Let's talk about that in our next meeting. Right now I can't do the build since I don't have access to this Docker image.
___
*[`python/ClipDetection/tests/test_clip.py` line 74 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NU8Smn77fR8lucBJT3h:-NU8SmnC7n1gM7_HJZUW:b-7kmocb) ([raw file](https://github.com/openmpf/openmpf-components/blob/4855d9afee1d037d79c30aa0bd29c1d058bc72bf/python/ClipDetection/tests/test_clip.py#L74)):*
This fails for me:

```
>>> "violent" in ['violent scene', 'dangerous scene', 'safe scene', 'peaceful scene']
False
```

I think you want

```
self.assertTrue("violent scene" in self._output_to_list(result.detection_properties["CLASSIFICATION LIST"]))
self.assertEqual("violent scene", result.detection_properties["CLASSIFICATION"])
```

Also, the latter assert failed because `result.detection_properties["CLASSIFICATION"]` was " violent scene" (with the space as the first character). I left a different comment on the CSV file to address this.
___
*[`python/ClipDetection/tests/data/violence_classes.csv` line 1 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NU8UEko1WqEaUlXp24h:-NU8UEko1WqEaUlXp24i:b-sp1cqt) ([raw file](https://github.com/openmpf/openmpf-components/blob/4855d9afee1d037d79c30aa0bd29c1d058bc72bf/python/ClipDetection/tests/data/violence_classes.csv#L1)):*
> ```CSV
> peaceful, peaceful scene
> ```

Remove the space after the commas here.

Also, I recommend trimming the whitespace off of the tokens in each line when you parse the CSV to prevent users from making the same mistake.


<!-- Sent from Reviewable.io -->

2023-04-29 00:20 UTC, jrobble commented
*[`python/ClipDetection/clip_component/clip_component.py` line 60 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NTz3pE_AOKoOcNozKXe:-NU9NGihBtJTU-vndL84:bsd5l9w) ([raw file](https://github.com/openmpf/openmpf-components/blob/74e91d9962edc444267519d714d03aab50b3cb2e/python/ClipDetection/clip_component/clip_component.py#L60)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Creating a new instance of `JobRunner` for every job does not allow you to cache the text embeddings between jobs. To see if the text embeddings were being cached I modified your unit test:

```    def test_image_file(self):
        component = ClipComponent()

        job = mpf.ImageJob(
            job_name='test-image',
            data_uri=self._get_test_file('sturgeon.jpg'),
            job_properties=dict(
                NUMBER_OF_CLASSIFICATIONS = 1,
                NUMBER_OF_TEMPLATES = 1,
                CLASSIFICATION_LIST = 'coco',
                ENABLE_CROPPING='false'
            ),
            media_properties={},
            feed_forward_location=None
        )
        result = list(component.get_detections_from_image(job))[0]
        
        result = list(component.get_detections_from_image(job))[0]

        result = list(component.get_detections_from_image(job))[0]
```

I saw it generate the embeddings for each `get_detections_from_image()` call.

I'm not saying you should permanently update your unit test that way. I made the change temporarily just to test this out.

In retrospect, the reason that only the Azure components may be using a `JobRunner` is because they don't need to cache anything between jobs. That's because they are simple clients to the Azure Cognitive Services REST endpoints.

With this in mind, it's probably best to refactor your code not to use a `JobRunner`. Creating a new `JobRunner` each time also does `clip.load()` each time.

You may want to consider refactoring it into a wrapper class like [this](https://github.com/openmpf/openmpf-components/blob/master/python/NlpTextCorrection/nlp_correction_component/nlp_correction_component.py#L65). Alternatively, EAST just caches its model directly [here](https://github.com/openmpf/openmpf-components/blob/master/python/EastTextDetection/east_component/east_processor.py#L108).


</blockquote></details>

I meant to post this comment with the first round of review, so that's why it's using sturgeon.


<!-- Sent from Reviewable.io -->

2023-05-02 21:00 UTC, jrobble requested changes
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/326)* status: 25 of 26 files reviewed, 8 unresolved discussions (waiting on @ZachCafego)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NUTEjgNDABioSmaDvQY:-NUTEjgNDABioSmaDvQZ:b-ae6vk3) (no related file):*
Move "triton_server" up one directory in your code.

___
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NUTFgUeCP9KKSzqGT3t:-NUTFgUeCP9KKSzqGT3u:b-a2y4oa) (no related file):*
Also, I've been wondering how concerned we are that the model we're downloading on the client side during the build may get updated and no longer be compatible with the model we're running in Triton. The Triton model is static. It's never going to change unless we change it, whereas the client model is whatever is downloaded using the clip framework.





More specifically, since we're generating embeddings for the prompts on the client side, is there a chance that those will one day no longer be compatible with image embeddings from the servicer?





If so, one option would be to generate the embeddings for the prompts using the server, but as a stop-gap measure can we specify a specific model version when downloading the model on the client side when using the following command?




```
clip.load("ViT-B/32")
```

___


<!-- Sent from Reviewable.io -->

2023-05-10 20:13 UTC, jrobble requested changes
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/326)* status: 25 of 26 files reviewed, 12 unresolved discussions (waiting on @ZachCafego)

___
*[`python/ClipDetection/setup.cfg` line 29 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NV6HabG0cp7u0rTtY9g:-NV6HabG0cp7u0rTtY9h:b-19stul) ([raw file](https://github.com/openmpf/openmpf-components/blob/4855d9afee1d037d79c30aa0bd29c1d058bc72bf/python/ClipDetection/setup.cfg#L29)):*
> ```INI
> [metadata]
> name = ClipDetection
> version = 7.1
> ```

Change to `7.2`.
___
*[`python/ClipDetection/setup.cfg` line 34 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NV6Heek-TCUVGn0x06A:-NV6Heek-TCUVGn0x06B:b-qizoz8) ([raw file](https://github.com/openmpf/openmpf-components/blob/4855d9afee1d037d79c30aa0bd29c1d058bc72bf/python/ClipDetection/setup.cfg#L34)):*
> ```INI
> packages = clip_component
> install_requires =
>     mpf_component_api>=7.1
> ```

Change the api and util dependencies to `7.2`.
___
*[`python/ClipDetection/plugin-files/descriptor/descriptor.json` line 3 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NV6H9zZ3Wigw4S1ycEi:-NV6H9zZ3Wigw4S1ycEj:b-tjj62) ([raw file](https://github.com/openmpf/openmpf-components/blob/4855d9afee1d037d79c30aa0bd29c1d058bc72bf/python/ClipDetection/plugin-files/descriptor/descriptor.json#L3)):*
> ```JSON
> {
>     "componentName": "ClipDetection",
>     "componentVersion": "7.1",
> ```

Update `componentVersion` and `middlewareVersion` to `7.2`.
___
*[`python/ClipDetection/plugin-files/descriptor/descriptor.json` line 8 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NV6HRvb8DExwg1UnkzA:-NV6HRvb8DExwg1UnkzB:b-xhg81p) ([raw file](https://github.com/openmpf/openmpf-components/blob/4855d9afee1d037d79c30aa0bd29c1d058bc72bf/python/ClipDetection/plugin-files/descriptor/descriptor.json#L8)):*
> ```JSON
>     "batchLibrary": "ClipDetection",
>     "environmentVariables": [],
>     "algorithm": {
> ```

Add `outputChangedCounter` like it's done [here](https://github.com/openmpf/openmpf-components/blob/develop/python/EastTextDetection/plugin-files/descriptor/descriptor.json#L12).


<!-- Sent from Reviewable.io -->

2023-05-11 19:06 UTC, ZachCafego reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/326)* status: 16 of 26 files reviewed, 13 unresolved discussions (waiting on @jrobble)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NUTEjgNDABioSmaDvQY:-NVBBRl9DROuQvfzGfK7:b-896fix) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Move "triton_server" up one directory in your code.
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NUTFgUeCP9KKSzqGT3t:-NVBBW50D925REZt0dbe:b-896fix) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Also, I've been wondering how concerned we are that the model we're downloading on the client side during the build may get updated and no longer be compatible with the model we're running in Triton. The Triton model is static. It's never going to change unless we change it, whereas the client model is whatever is downloaded using the clip framework.





More specifically, since we're generating embeddings for the prompts on the client side, is there a chance that those will one day no longer be compatible with image embeddings from the servicer?





If so, one option would be to generate the embeddings for the prompts using the server, but as a stop-gap measure can we specify a specific model version when downloading the model on the client side when using the following command?




```
clip.load("ViT-B/32")
```
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NVAlc6A8jZpC70O1w_B:-NVBBdtU-vzRlqIm6KKy:bqxx1j7) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please update the component to optionally return a detection property representing the whole-image feature embedding. Call the property `FEATURE`. This will be similar to the TRTIS component, which has this in its README:

> each detection will have a `FEATURE` detection property set to the value of the base64-encoded version of the feature vector

Only include the `FEATURE` property when the `INCLUDE_FEATURES` property is set to true (false by default).


</blockquote></details>

Working, added to descriptor file. Still need to implement detection property if True.

___
___
*[`python/ClipDetection/README.md` line 5 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NU3h_2v-kJrN2mEqy75:-NVBBsiK9bcN_LTkYtWM:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/4855d9afee1d037d79c30aa0bd29c1d058bc72bf/python/ClipDetection/README.md#L5)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

This is too low level to be in the Overview section. Please move to the bottom of the README in a `# Known Issues` section.
</blockquote></details>

Done.
___
*[`python/ClipDetection/setup.cfg` line 29 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NV6HabG0cp7u0rTtY9g:-NVBBuvU0pUH7UO9jXT4:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/4855d9afee1d037d79c30aa0bd29c1d058bc72bf/python/ClipDetection/setup.cfg#L29)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Change to `7.2`.
</blockquote></details>

Done.
___
*[`python/ClipDetection/setup.cfg` line 34 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NV6Heek-TCUVGn0x06A:-NVBBw8GCo4o1erQvKPr:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/4855d9afee1d037d79c30aa0bd29c1d058bc72bf/python/ClipDetection/setup.cfg#L34)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Change the api and util dependencies to `7.2`.
</blockquote></details>

Done.
___
*[`python/ClipDetection/clip_component/clip_component.py` line 60 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NTz3pE_AOKoOcNozKXe:-NVBBzpBEfdcWuYV4wjg:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/74e91d9962edc444267519d714d03aab50b3cb2e/python/ClipDetection/clip_component/clip_component.py#L60)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I meant to post this comment with the first round of review, so that's why it's using sturgeon.
</blockquote></details>

Done.
___
*[`python/ClipDetection/plugin-files/descriptor/descriptor.json` line 3 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NV6H9zZ3Wigw4S1ycEi:-NVBC4I453Q7LQuZRGCI:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/4855d9afee1d037d79c30aa0bd29c1d058bc72bf/python/ClipDetection/plugin-files/descriptor/descriptor.json#L3)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Update `componentVersion` and `middlewareVersion` to `7.2`.
</blockquote></details>

Done.
___
*[`python/ClipDetection/plugin-files/descriptor/descriptor.json` line 8 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NV6HRvb8DExwg1UnkzA:-NVBC61RA7I9z4SeFpRp:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/4855d9afee1d037d79c30aa0bd29c1d058bc72bf/python/ClipDetection/plugin-files/descriptor/descriptor.json#L8)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Add `outputChangedCounter` like it's done [here](https://github.com/openmpf/openmpf-components/blob/develop/python/EastTextDetection/plugin-files/descriptor/descriptor.json#L12).
</blockquote></details>

Done.
___
*[`python/ClipDetection/tests/test_clip.py` line 74 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NU8Smn77fR8lucBJT3h:-NVBCAN1EGHO4c1uxERk:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/4855d9afee1d037d79c30aa0bd29c1d058bc72bf/python/ClipDetection/tests/test_clip.py#L74)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

This fails for me:

```
>>> "violent" in ['violent scene', 'dangerous scene', 'safe scene', 'peaceful scene']
False
```

I think you want

```
self.assertTrue("violent scene" in self._output_to_list(result.detection_properties["CLASSIFICATION LIST"]))
self.assertEqual("violent scene", result.detection_properties["CLASSIFICATION"])
```

Also, the latter assert failed because `result.detection_properties["CLASSIFICATION"]` was " violent scene" (with the space as the first character). I left a different comment on the CSV file to address this.
</blockquote></details>

Done.
___
*[`python/ClipDetection/tests/data/violence_classes.csv` line 1 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NU8UEko1WqEaUlXp24h:-NVBCCuf2lAd9n-UFAMj:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/4855d9afee1d037d79c30aa0bd29c1d058bc72bf/python/ClipDetection/tests/data/violence_classes.csv#L1)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Remove the space after the commas here.

Also, I recommend trimming the whitespace off of the tokens in each line when you parse the CSV to prevent users from making the same mistake.
</blockquote></details>

Done.
___
*[`python/ClipDetection/clip_component/triton_server/Dockerfile` line 32 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NU8fEjJ9OBW4t-iC0O2:-NVBCH_F2u2ry6thFYmA:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/4855d9afee1d037d79c30aa0bd29c1d058bc72bf/python/ClipDetection/clip_component/triton_server/Dockerfile#L32)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

We need to push this to DockerHub, like we do with the OcvYoloDetection model files [here](https://hub.docker.com/r/openmpf/openmpf_ocv_yolo_detection_triton_models). Let's talk about that in our next meeting. Right now I ca [...]

2023-05-22 21:16 UTC, jrobble requested changes
> Reviewed 2 of 9 files at r5, 4 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/326)* status: 19 of 27 files reviewed, 3 unresolved discussions (waiting on @ZachCafego)

___
*[`python/ClipDetection/clip_component/clip_component.py` line 64 at r6](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NVp2iDADxYYZg4GxrfU:-NVp2iDC6rgqQ23DvD7e:bfxqng1) ([raw file](https://github.com/openmpf/openmpf-components/blob/754619238b048059413df3b187b371a304495fb8/python/ClipDetection/clip_component/clip_component.py#L64)):*
> ```Python
> 
>             if not self.initialized:
>                 self.wrapper = ClipWrapper()
> ```

I addressed the following issue and merged in the changes. Just leaving the comment for posterity:

---

We never have a reason to change the wrapper. It will be configured the same no matter the job. For that reason we should create it in `__init__`.
___
*[`python/ClipDetection/plugin-files/descriptor/descriptor.json` line 131 at r6](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NW3YHST34Rm8ZbxeaLq:-NW3YHST34Rm8ZbxeaLr:b45h6i6) ([raw file](https://github.com/openmpf/openmpf-components/blob/754619238b048059413df3b187b371a304495fb8/python/ClipDetection/plugin-files/descriptor/descriptor.json#L131)):*
> ```JSON
>             "description": "Runs CLIP classification on the COCO dataset classes.",
>             "actions": [
>                 "CLIP CLASSIFICATION ACTION"
> ```

I addressed the following issue and merged in the changes. Just leaving the comment for posterity:

---

This needs to be `CLIP COCO CLASSIFICATION ACTION`.
___
*[`python/ClipDetection/plugin-files/descriptor/descriptor.json` line 138 at r6](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NW3YE16AKq2BIJ2SNPR:-NW3YE16AKq2BIJ2SNPS:b-merqzu) ([raw file](https://github.com/openmpf/openmpf-components/blob/754619238b048059413df3b187b371a304495fb8/python/ClipDetection/plugin-files/descriptor/descriptor.json#L138)):*
> ```JSON
>             "description": "Runs CLIP classification on the COCO dataset classes using a Triton Inferencing Server.",
>             "actions": [
>                 "CLIP TRITON CLASSIFICATION ACTION"
> ```

I addressed the following issue and merged in the changes. Just leaving the comment for posterity:

---

This needs to be `CLIP TRITON COCO CLASSIFICATION ACTION`.
___
*[`python/ClipDetection/plugin-files/descriptor/descriptor.json` line 161 at r6](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NVp2HjF72xNKUcvVZL-:-NVp2HjG757cmctYBaSM:bao3ghp) ([raw file](https://github.com/openmpf/openmpf-components/blob/754619238b048059413df3b187b371a304495fb8/python/ClipDetection/plugin-files/descriptor/descriptor.json#L161)):*
> ```JSON
>             "description": "Runs CLIP classification on the COCO dataset classes.",
>             "tasks": [
>                 "CLIP CLASSIFICATION TASK"
> ```

I addressed the following issue and merged in the changes. Just leaving the comment for posterity:

---

This needs to be `CLIP COCO CLASSIFICATION TASK`.
___
*[`python/ClipDetection/plugin-files/descriptor/descriptor.json` line 168 at r6](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NW3Pgco6BdDgGH3qGwh:-NW3Pgco6BdDgGH3qGwi:bq385gl) ([raw file](https://github.com/openmpf/openmpf-components/blob/754619238b048059413df3b187b371a304495fb8/python/ClipDetection/plugin-files/descriptor/descriptor.json#L168)):*
> ```JSON
>             "description": "Runs CLIP classification on the COCO dataset classes using a Triton Inferencing Server.",
>             "tasks": [
>                 "CLIP TRITON CLASSIFICATION TASK"
> ```

I addressed the following issue and merged in the changes. Just leaving the comment for posterity:

---

This needs to be `CLIP TRITON COCO CLASSIFICATION TASK`.
___
*[`python/ClipDetection/tests/test_clip.py` line 38 at r6](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NVozIBl1WW-H_FQbX_h:-NVozIBl1WW-H_FQbX_i:b-u3wrxz) ([raw file](https://github.com/openmpf/openmpf-components/blob/754619238b048059413df3b187b371a304495fb8/python/ClipDetection/tests/test_clip.py#L38)):*
> ```Python
> import mpf_component_api as mpf
> 
> expected_feature = '/dJWPEgftjycQt28dfsEPcTnuDpHFmG9XWPQPHTyLz0vWE89H/b5PJHe37ytpLK8SB82PVODs7wu5pg9DCxXPGYdELwuT/q6x+YkPeaYpbtCnX08QvsAvBqPQD1g1HI7PrHPvJfSzjzG3U89Qp39OwQ5fLyxooq8MVe7PP5N4jzQSza8+eYoO8yYI73weEI7feWKPFo+BzzNQ3W9fZBcO92lSr1OCtA874uAPICPyLzI3Ls751UhvWPcs7zjJ4M6Q3YMPQTQGjvKJwG7AtqDPGpCWTtzsL886wi0u3mb2bvVLfs8y6IMPTDcr7v8V8s6VP6+PPgpLbvhKBc9aBMnu3OwP70dlwG9FZFoOwiMAj2sm928xHUCvTjGtbyHcPm6vvwePXwV0bvddQS9hc+QvKPElTytpLK8Go/AOdHGQTu6/kY6JXiyu5VqAbzxwwe9p7kYPHavqzsWmr09sQvsvAe8SLxfWWe8zFYzO15sJb3brzO/YeYcPSqvpbzUQLk8OL3gvPtOdrxDdgy9W2RkPSTEC7wKgpm73vAPPWxBRTwaj8A8OQgmvWFYUztgaxE9uYwQuu+LALyksde8F9wtvTFXOzykuiy9KyqxO+r/3rx9Hia9xdT6vNK8WD3o0Ky6AE1OugY46DyT3Us9jelcvLeEzzxtjIo6kd7fu1xtOTw6Spa7pfwcvI13Jj3P0Kq8t//auwJMuj1yLN88MNyvPLv0XTxKFc29+igZvQ4+gTw+qHo8EHaIPIu6Kj0IxR08x62JuyPrfD0dl4E88cOHPVODszw8B5I70I2mvAq7NDxGKZ898fNNvbjPFLyGEQE9NJiXPLAeKroahuu7b7u8PLzElzte3ts8NxIPPf5WN7yQ8Z07fx2SvLSFY7xpx0097P7KPCnf6zzG3U89LygJvAJMOj2yHZY8PrHPOwuo9rymsMM8vP0yPOQLcD2gvFS6jm29O/gygjtQ0CA9lFhXvL66LrpaPge8MKMUPMjT5ry+w4O8if0uPbWOODyx26W8CDfUu8etibzMHRi9qyBSPI92Ejx0uRQ73zIAvlMIqLubHIA8ZdLKPOr/3jwi/jo9kd5fvBoBd7y1VZ087waMOrv03TzMXwg9K97XvPR2mj0Mscs7piL6O0rcsbyHjAy960qkutWCqTx3pcI9Mcnxu+l7fj36WN88dyq3vIvzRT2NuZa8I0mAPFh4Njy59XG8yVdHPGYdEDzFYkS89t7nPKybXTyS5zQ8CIwCPOgJyLuR3t+77kkQvTxArTxEKjO9hoO3vK9qgzuUWFc9Yd3HvD6xT7z0+w48BDl8PIMJQL37TvY8jPwaPZ1LsjzTxS28kTMOu1aCHzx0uZQ8AR0IvM1Ddbwt8AG9CsQJvn8Uvbyc0Ka8ifTZPDJEfTzHWFu9Ehdxu2u9ZDw6g7G8nlSHOzlBQTzrzxg74SgXPHsoDz11NCA97IM/PK2kMjyiLXc8AkPlu+tKJD3gH8K8azhwPDhLqrtEKrO8wPI1vXsojzs7N1g8SSgLPdWCqb2FCKw8zJijvIHajTzvb+25orvAOg8rQzuEhEs8OMa1OTNWp7pjTmq7Uo0cPYaDt7sPK8O8uREFPAdBvbxh3ce8XG05PI92krw6vMy8z0LhvAbGMTyYogg9hnpiPHyjGr3Io6A9ex+6PbIUwbxU9ek6uAiwvCNJgD0pbTU9kue0vAJDZb1ebKU9wujMPRhgDr1mHRA9VXB1vN0zlDsWmj27H40YvW+7vLyiu8A8XWPQvN4g1ryR3l+8l1dDvdFBTTx08i+926+zO+MerjxjTmo7obLrvO6Cq7tQCTy8bYwKvZTmID1Veco845Bku2xBxTshxR89QjScvHuR8LwvWE+9ehblO9W7xLqfs/+8FigHPGdfgDwt8AE9PTbEPH/bIT2jxJU8Pbu4PAs2QLyoNKQ8TgpQPRB2CL2Y2yM884CDvGoSk7yObb28a73kvOWGe7ypKrs8wGTsPOAfQjwMgQW9H//OuqXDAT4ouQ49kTMOvH+G8zwr3lc817owvYz8GryUWNc8G9EwPaGya7xlmS+94B/CPFcGgDx8FdG8NNGyvDlBwb3oCcg8mtE6vWJhqDgDx0U8QjScu68V1bzkoo69PECtvV/nMDpzsD+8+d3TPOnZAb3uSZC8orvAvN4pK7yG9W07aL74PB2XAb0l6mg9QD4FveYK3Lwr3lc8nb3ovN2lSjycx1G8qpzxPG7FJbzugiu9X66VvPHDBz0u5hi8jfKxvXqtAz0Qpk48+9PqPIh5zrw5QcG9QD6FO3thqjugN2A8JYGHO4Z64rvDY1g8QD4FvP2ikL3ugiu8gF+CvAJMujtc3++7Vz+bPBWR6Lznjjw8+DICPRMgxrwZFLU8TQF7vDSYl7zJ5ZC8qpzxPC5rDb3MmKM8kmJAPKoX/bwZ25m7sJBgPGZN1jtNHY48EmyfPIETqbze8I+8I0mAvPd1hrwE0Jo9XHaOPGlVlzyX0k48xVlvvUabVTvjYJ49glUZPSfp1LypKju98neuO/LpZLwC0S68UADnPBxVETxkVz+8Us+MPAaNFr2P6Mg7qSq7ulcGgLw12oe826beuxJsn7sHgy29zB0YOHGxUztgYjy7A8fFPLjPFL3weEI8UAm8vKqlxrpZZXg9jfIxvdCNpjuL80W9Go9AvU4TJbxcdg48AcjZPCtsoTwx5YS9F9wtPAy6IL3+HRw8j3aSvGdfALw='
> ```

I addressed the following issue and merged in the changes. Just leaving the comment for posterity:

---

Remove this.
___
*[`python/ClipDetection/tests/test_clip_triton.py` line 52 at r6](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NVozgDl-HNUrogSBFIh:-NVozgDl-HNUrogSBFIi:b2q0qv9) ([raw file](https://github.com/openmpf/openmpf-components/blob/754619238b048059413df3b187b371a304495fb8/python/ClipDetection/tests/test_clip_triton.py#L52)):*
> ```Python
>                 ENABLE_CROPPING='True', 
>                 ENABLE_TRITON='True',
>                 TRITON_SERVER='localhost:8001'
> ```

I addressed the following issue and merged in the changes. Just leaving the comment for posterity:

---

YOLO does:

```
std::string TRITON_SERVER = "ocv-yolo-detection-server:8001"
```
___
*[`python/ClipDetection/tests/test_clip_triton.py` line 59 at r6](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NW4GV8R-OXBCvVQGPoA:-NW4GV8SBPo1y8JTgq9u:b-a3i0jr) ([raw file](https://github.com/openmpf/openmpf- [...]

2023-05-22 21:17 UTC, jrobble reviewed
> Reviewed 1 of 6 files at r6, 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/326)* status: all files reviewed, 3 unresolved discussions (waiting on @ZachCafego)



<!-- Sent from Reviewable.io -->

2023-05-23 02:12 UTC, jrobble reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/326)* status: 26 of 27 files reviewed, 2 unresolved discussions (waiting on @ZachCafego)

___
*[`python/ClipDetection/clip_component/clip_component.py` line 285 at r7](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NW5N6pW09dFCnqNieQC:-NW5N6pW09dFCnqNieQD:b6xwsno) ([raw file](https://github.com/openmpf/openmpf-components/blob/88cfd6ec102b3347ea447376111dec5ad07ff323/python/ClipDetection/clip_component/clip_component.py#L285)):*
> ```Python
>             raise
> 
>         try:
> ```

I removed these and some other data members that weren't being used.


<!-- Sent from Reviewable.io -->

2023-05-23 02:12 UTC, jrobble reviewed
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/326)* status: all files reviewed, 2 unresolved discussions (waiting on @ZachCafego)



<!-- Sent from Reviewable.io -->

2023-06-06 02:08 UTC, jrobble reviewed
> Reviewed 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/326)* status: all files reviewed, 2 unresolved discussions (waiting on @ZachCafego)

___
*[`python/ClipDetection/clip_component/clip_component.py` line 334 at r8](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NXDHRAI1Mef2VwcvLlZ:-NXDHRAI1Mef2VwcvLl_:b-bcspap) ([raw file](https://github.com/openmpf/openmpf-components/blob/3f4e978fcca4c122860d4da113dd3f1322737ce3/python/ClipDetection/clip_component/clip_component.py#L334)):*
> ```Python
>             self.preprocess = self.crop
>         elif enable_triton:
>             self.preprocess = lambda image: TF.to_tensor(image).unsqueeze(0)
> ```

What the reason for removing this?
___
*[`python/ClipDetection/tests/test_clip_triton.py` line 59 at r9](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NXDRKsJCex72cUeDmqW:-NXDRKsK9b8O1wCWqu98:b-bok0t4) ([raw file](https://github.com/openmpf/openmpf-components/blob/2494aa951f3afdc5392b5561b32d99b837a9ccac/python/ClipDetection/tests/test_clip_triton.py#L59)):*
> ```Python
>         result = list(ClipComponent().get_detections_from_image(job))[0]
>         self.assertEqual(job.job_properties["NUMBER_OF_CLASSIFICATIONS"], len(self._output_to_list(result.detection_properties["CLASSIFICATION LIST"])))
>         self.assertTrue("collie" in self._output_to_list(result.detection_properties["CLASSIFICATION LIST"]))
> ```

I'm not getting "collie" in the top 5, but it does show up in slot 10. Here's what I get:

```
toy terrier; wire-haired fox terrier; Ibizan hound, Ibizan Podenco; Chihuahua; papillon; Border collie; Scotch terrier, Scottish terrier, Scottie; Australian terrier; basenji; collie
0.11867158859968185; 0.11635984480381012; 0.08234529942274094; 0.05162452161312103; 0.049181509763002396; 0.047043319791555405; 0.043919168412685394; 0.04185420647263527; 0.0391409806907177; 0.03007649816572666
```

Please set `NUMBER_OF_CLASSIFICATIONS` to 10 and check for "collie" or "Border collie". Either class is acceptable. That should work in most cases.


<!-- Sent from Reviewable.io -->

2023-06-06 20:44 UTC, jrobble commented
*[`python/ClipDetection/tests/test_clip_triton.py` line 58 at r10](https://reviewable.io/reviews/openmpf/openmpf-components/326#-NXHRpvR7MOerJvSnPNz:-NXHRpvS6kTZqSbtPNub:b73wo2j) ([raw file](https://github.com/openmpf/openmpf-components/blob/614eacc933563c3f9552c9f810a52ea7fdf34aab/python/ClipDetection/tests/test_clip_triton.py#L58)):*
> ```Python
>         )      
>         result = list(ClipComponent().get_detections_from_image(job))[0]
>         self.assertTrue("collie" in self._output_to_list(result.detection_properties["CLASSIFICATION LIST"]) or "border collie" in self._output_to_list(result.detection_properties["CLASSIFICATION LIST"]))
> ```

Please capitalize the "b" since the class is "Border collie".


<!-- Sent from Reviewable.io -->

2023-06-06 20:45 UTC, jrobble reviewed
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/326)* status: all files reviewed, 2 unresolved discussions (waiting on @ZachCafego)



<!-- Sent from Reviewable.io -->

2023-06-07 15:41 UTC, ZachCafego commented
> 

So basically, the reason for removing this is that the resize_pad function is doing what that lambda function was doing, except that it resizes and pads into the 224x224 image containing the entire image before converting to a tensor. We could compare the performances but I felt like it made the most sense for the resize_pad to be the default preprocessing.

2023-06-07 16:50 UTC, jrobble approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/326#-:-NXLkzuZ9hStytlFp496:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ZachCafego)



<!-- Sent from Reviewable.io -->

2023-06-07 16:54 UTC, jrobble approved these changes
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/326)* status: all files reviewed, 1 unresolved discussion (waiting on @ZachCafego)



<!-- Sent from Reviewable.io -->

2023-06-07 17:02 UTC, jrobble approved these changes
> Dismissed @ZachCafego from a discussion.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/326)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ZachCafego)



<!-- Sent from Reviewable.io -->

2023-06-07 17:09 UTC, merged