Update CLIP component to support video
openmpf/openmpf-components pull request #338
Opened 2023-09-29 14:36 UTC by ZachCafego

**Issues:**

- https://github.com/openmpf/openmpf/issues/1694

If a related issue doesn't exist, then create one first and assign it to yourself.

2023-10-23 14:52 UTC, jrobble commented
*[`python/ClipDetection/README.md` line 80 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/338#-NhS-cwq2MoRoFP9JQgT:-NhS-cwq2MoRoFP9JQgU:b-xxdd9a) ([raw file](https://github.com/openmpf/openmpf-components/blob/585c83d6235f56fa0e3a9a7cf10585e055bf1dfe/python/ClipDetection/README.md#L80)):*
> ```Markdown
> |   ViT-L/14 |        512 |             105.8889 |                           3.7873 |                  135.1889 |
> 
> # Triton Performance
> ```

Please state which model was used.

The numbers for a batch of 16 and 32 are very high. I was under the impression that Triton didn't offer much, but those numbers are significantly better than when using non-Triton for the same batch sizes (for ViT_B/32).

I remember we talked about potentially using shared memory between the Triton client and server to alleviate performance loss when using Triton, but these number tell a different story.

Are these numbers the same ones we talked about before?


<!-- Sent from Reviewable.io -->

2023-11-27 22:01 UTC, jrobble requested changes
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/338)* status: all files reviewed, 9 unresolved discussions (waiting on @ZachCafego)

___
*[`python/ClipDetection/README.md` line 64 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/338#-NkHJJFZ1lTDL8-u0N9i:-NkHJJFZ1lTDL8-u0N9j:bi9pbl8) ([raw file](https://github.com/openmpf/openmpf-components/blob/585c83d6235f56fa0e3a9a7cf10585e055bf1dfe/python/ClipDetection/README.md#L64)):*
> ```Markdown
> ```
> # Non-Triton Performance
> The table below shows the performance of this component on a Nvidia Tesla V100 32GB GPU, for varying batch sizes with both models:
> ```

Use all caps for NVIDIA. Search for other usages in this file and update them.
___
*[`python/ClipDetection/README.md` line 80 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/338#-NhS-cwq2MoRoFP9JQgT:-NkHIqeE-7q4it60-nQ4:b96nzcs) ([raw file](https://github.com/openmpf/openmpf-components/blob/585c83d6235f56fa0e3a9a7cf10585e055bf1dfe/python/ClipDetection/README.md#L80)):*
Please address this:

> Please state which model was used.
___
*[`python/ClipDetection/clip_component/clip_component.py` line 59 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/338#-NkHLabz6fOYQZ5uHJgw:-NkHLabz6fOYQZ5uHJgx:bw72j6j) ([raw file](https://github.com/openmpf/openmpf-components/blob/585c83d6235f56fa0e3a9a7cf10585e055bf1dfe/python/ClipDetection/clip_component/clip_component.py#L59)):*
> ```Python
> 
>     @staticmethod
>     def _get_prop(job_properties, key, default_value, accep_values=[]):
> ```

Nitpick: Let's call this `accept_values`.
___
*[`python/ClipDetection/clip_component/clip_component.py` line 110 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/338#-NkHLq3p6CiiBTXGOQCF:-NkHLq3p6CiiBTXGOQCG:b-xmn2t1) ([raw file](https://github.com/openmpf/openmpf-components/blob/585c83d6235f56fa0e3a9a7cf10585e055bf1dfe/python/ClipDetection/clip_component/clip_component.py#L110)):*
> ```Python
>                 yield detection
>                 num_detections += 1
>             logger.info(f"Job complete. Found {num_detections} detection{'' if num_detections == 1 else 's'}.")
> ```

In general, we don't worry about this and just use the plural.
___
*[`python/ClipDetection/clip_component/clip_component.py` line 150 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/338#-NkHMhmq5sCtS-dfkGjx:-NkHMhmr3mm2fQqU717I:b-2810k) ([raw file](https://github.com/openmpf/openmpf-components/blob/585c83d6235f56fa0e3a9a7cf10585e055bf1dfe/python/ClipDetection/clip_component/clip_component.py#L150)):*
> ```Python
>         for n, batch in batch_gen:
>             try:
>                 detection = list(islice(wrapper.get_classifications(batch, **kwargs), n))
> ```

`get_detections` would be a more accurate name for this function. Also, it can return more than one detection. Let's use this:

```python
detections += list(islice(wrapper.get_detections(batch, **kwargs), n))
```
___
*[`python/ClipDetection/clip_component/clip_component.py` line 450 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/338#-NkHY5IT0c9c2pkiUEhB:-NkHY5IUBXNMG8ggwpYu:bhx6kgj) ([raw file](https://github.com/openmpf/openmpf-components/blob/585c83d6235f56fa0e3a9a7cf10585e055bf1dfe/python/ClipDetection/clip_component/clip_component.py#L450)):*
> ```Python
>         new_w, new_h = (round(width * resize_ratio), round(height * resize_ratio))
> 
>         # if width < self.image_size and height < self.image_size:
> ```

Please remove dead code, unless this is important enough to be turned into a comment for future reference.
___
*[`python/ClipDetection/plugin-files/descriptor/descriptor.json` line 26 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/338#-NkHK_gxClwfzX16zO7X:-NkHK_gxClwfzX16zO7Y:b-jcfitt) ([raw file](https://github.com/openmpf/openmpf-components/blob/585c83d6235f56fa0e3a9a7cf10585e055bf1dfe/python/ClipDetection/plugin-files/descriptor/descriptor.json#L26)):*
> ```JSON
>                 {
>                     "name": "MODEL_NAME",
>                     "description": "Specifies which CLIP model to load for inferencing. The only available models are 'ViT-L/14' and 'ViT-B/32'.",
> ```

Please remove "only".
___
*[`python/ClipDetection/plugin-files/descriptor/descriptor.json` line 91 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/338#-NkHdgUZCE27kPnQSXJv:-NkHdgUZCE27kPnQSXJw:b-tu4bgn) ([raw file](https://github.com/openmpf/openmpf-components/blob/585c83d6235f56fa0e3a9a7cf10585e055bf1dfe/python/ClipDetection/plugin-files/descriptor/descriptor.json#L91)):*
> ```JSON
>                 },
>                 {
>                     "name": "DETECTION_FRAME_BATCH_SIZE_TRITON",
> ```

The OcvDNN component has one property called `DETECTION_FRAME_BATCH_SIZE` that it uses for both non-Triton and Triton runs (although in that case it uses a value of 16 for everything). For consistency, I think we should use one property here too. A user may forget that there is a Triton and non-Triton version of the property.

Please add `"DETECTION_FRAME_BATCH_SIZE" : "32"` to the Triton actions you defined below.
___
*[`python/ClipDetection/tests/data/test_video.mp4` line 0 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/338#-NkHK34NAlH4LRzOfhZP:-NkHK34NAlH4LRzOfhZQ:b-gz6wi5) ([raw file](https://github.com/openmpf/openmpf-components/blob/585c83d6235f56fa0e3a9a7cf10585e055bf1dfe/python/ClipDetection/tests/data/test_video.mp4#L0)):*
Add an entry to the `NOTICE` file in this directory for this piece of media. Explain what images were used to create it and their respective licenses. 


<!-- Sent from Reviewable.io -->

2023-11-27 22:38 UTC, jrobble reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/338)* status: all files reviewed, 10 unresolved discussions (waiting on @ZachCafego)

___
*[`python/ClipDetection/triton_server/Dockerfile` line 31 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/338#-NkHtZb42rxhX_E8HtY6:-NkHtZb42rxhX_E8HtY7:bqdo59h) ([raw file](https://github.com/openmpf/openmpf-components/blob/585c83d6235f56fa0e3a9a7cf10585e055bf1dfe/python/ClipDetection/triton_server/Dockerfile#L31)):*
> ```Dockerfile
> ARG MODELS_REGISTRY=openmpf/
> 
> FROM ${MODELS_REGISTRY}openmpf_clip_detection_triton_models:7.2.0 as models
> ```

I don't see this renamed version on Docker Hub, so I created it. We will need to delete https://hub.docker.com/r/openmpf/openmpf_clip_detection_models from Docker Hub once this PR lands to develop.


<!-- Sent from Reviewable.io -->

2023-11-27 22:44 UTC, jrobble requested changes
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/338)* status: all files reviewed, 11 unresolved discussions (waiting on @ZachCafego)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf-components/338#-NkHwp_oB2wCH1oEuSZ5:-NkHwp_oB2wCH1oEuSZ6:b-glzunb) (no related file):*
From the Dockerfile:

```
COPY --from=models /models/ViT-B-32.pt /models/ViT-B-32.pt
```

Please pre-install ViT-L-14 as well.

___


<!-- Sent from Reviewable.io -->

2023-11-28 02:21 UTC, jrobble requested changes
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/338)* status: all files reviewed, 15 unresolved discussions (waiting on @ZachCafego)

___
*[`python/ClipDetection/clip_component/clip_component.py` line 348 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/338#-NkIY-ee7m4wQZe0AHVz:-NkIY-ee7m4wQZe0AHW-:b-gi3w6c) ([raw file](https://github.com/openmpf/openmpf-components/blob/585c83d6235f56fa0e3a9a7cf10585e055bf1dfe/python/ClipDetection/clip_component/clip_component.py#L348)):*
> ```Python
>     '''
>     def __init__(self, triton_server: int):
>         self._model_name = 'ip_clip_512'
> ```

As mentioned in a separate comment, this needs to be configurable to ViT-B/32 or ViT-L/14.
___
*[`python/ClipDetection/clip_component/clip_component.py` line 396 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/338#-NkIayTT8kObSiirYZP7:-NkIayTT8kObSiirYZP8:bg1n7oc) ([raw file](https://github.com/openmpf/openmpf-components/blob/585c83d6235f56fa0e3a9a7cf10585e055bf1dfe/python/ClipDetection/clip_component/clip_component.py#L396)):*
> ```Python
>         except Exception:
>             raise mpf.DetectionException(
>                 f"Inference failed.",
> ```

If possible, the exception should contain the original exception message.

For example, when I ran `CLIP TRITON IMAGENET CLASSIFICATION TASK` on this [video](https://github.com/openmpf/openmpf-components/blob/master/cpp/OcvFaceDetection/test/data/test_vids/new_face_video.avi) these log messages mention the protobuf and serialization:

```
2023-11-28 01:49:50,289 ERROR [clip_component.py:152] - [Job 6:new_face_video.avi(0-509)] Job failed due to: Inference failed. (DetectionError.NETWORK_ERROR)
Traceback (most recent call last):
  File "/opt/mpf/plugin-venv/lib/python3.8/site-packages/clip_component/clip_component.py", line 392, in get_responses
    responses.append(self._triton_client.infer(model_name=self._model_name, inputs=inputs, outputs=outputs))
  File "/opt/mpf/plugin-venv/lib/python3.8/site-packages/tritonclient/grpc/_client.py", line 1380, in infer
    raise_error_grpc(rpc_error)
  File "/opt/mpf/plugin-venv/lib/python3.8/site-packages/tritonclient/grpc/_utils.py", line 77, in raise_error_grpc
    raise get_error_grpc(rpc_error) from None
tritonclient.utils.InferenceServerException: [StatusCode.INTERNAL] Exception serializing request!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mpf/plugin-venv/lib/python3.8/site-packages/clip_component/clip_component.py", line 149, in get_detections_from_video_capture
    detection = list(islice(wrapper.get_classifications(batch, **kwargs), n))
  File "/opt/mpf/plugin-venv/lib/python3.8/site-packages/clip_component/clip_component.py", line 202, in get_classifications
    results = self._inferencing_server.get_responses(torch_imgs)
  File "/opt/mpf/plugin-venv/lib/python3.8/site-packages/clip_component/clip_component.py", line 394, in get_responses
    raise mpf.DetectionException(
mpf_component_api.mpf_component_api.DetectionException: Inference failed. (DetectionError.NETWORK_ERROR)
2023-11-28 01:49:50,290 ERROR [org.mitre.mpf.detection:0] - [Job 6:new_face_video.avi(0-509)] An error occurred while invoking the "get_detections_from_video" method on the Python component: DetectionException: Inference failed. (DetectionError.NETWORK_ERROR)

At:
  /opt/mpf/plugin-venv/lib/python3.8/site-packages/clip_component/clip_component.py(394): get_responses
  /opt/mpf/plugin-venv/lib/python3.8/site-packages/clip_component/clip_component.py(202): get_classifications

2023-11-28 01:49:50,292 ERROR [org.mitre.mpf.detection:0] - [Job 6:new_face_video.avi(0-509)] Video detection method returned an error for /opt/mpf/share/remote-media/new_face_video.avi
Exception serializing message!2023-11-28 01:49:50,289 ERROR [_common.py:91] - [Job 6:new_face_video.avi(0-509)] Exception serializing message!
Traceback (most recent call last):
  File "/opt/mpf/plugin-venv/lib/python3.8/site-packages/grpc/_common.py", line 89, in _transform
    return transformer(message)
ValueError: Message inference.ModelInferRequest exceeds maximum protobuf size of 2GB: 2774532167
```

However, what I see in the JSON output is pretty generic:

```
            {
               "source": "CLIP",
               "code": "NETWORK_ERROR",
               "message": "An error occurred while invoking the \"get_detections_from_video\" method on the Python component: Inference failed. (DetectionError.NETWORK_ERROR) (Frames: 0 - 509)"
            }
```

---


Here's the REST request that resulted in the above error:

```json
{
  "jobProperties": {
    "MODEL_NAME": "ViT-B/32",
    "DETECTION_FRAME_BATCH_SIZE_TRITON": "32",
  },
  "media": [
    {
      "mediaUri": "file:///opt/mpf/share/remote-media/new_face_video.avi"
    }
  ],
  "pipelineName": "CLIP TRITON IMAGENET CLASSIFICATION PIPELINE",
  "priority": 0
}
```

Adding  `"ENABLE_CROPPING" : "false"` as a job property allows the job to complete successfully. The issue seems to be that you're not considering the number of crops (in this case 144) against the batch size.

To be clear, a single image with 144 crops is equivalent to 144 frames with a single crop for each. In each case that's a batch of 144 images. If using a batch size of 32 that would be 4 full batches with a partial batch of 16.
___
*[`python/ClipDetection/plugin-files/descriptor/descriptor.json` line 62 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/338#-NkIfTZo-VTFU3Hm0Ppw:-NkIfTZqEdR6jx387pS1:b9ah00) ([raw file](https://github.com/openmpf/openmpf-components/blob/585c83d6235f56fa0e3a9a7cf10585e055bf1dfe/python/ClipDetection/plugin-files/descriptor/descriptor.json#L62)):*
> ```JSON
>                 {
>                     "name": "ENABLE_CROPPING",
>                     "description": "If true, the image will be cropped into 144 images of size 224x224. The results from each of these images is averaged to get the results. Not available for use on CPU.",
> ```

Do you mean "Not recommended for use on CPU" instead of "Not available ..." ? Does something prevent this from running on the CPU?
___
*[`python/ClipDetection/triton_server/Dockerfile` line 35 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/338#-NkIXI0g-I0ySjiYWaof:-NkIXI0g-I0ySjiYWaog:b-na1koo) ([raw file](https://github.com/openmpf/openmpf-components/blob/585c83d6235f56fa0e3a9a7cf10585e055bf1dfe/python/ClipDetection/triton_server/Dockerfile#L35)):*
> ```Dockerfile
> FROM nvcr.io/nvidia/tritonserver:22.04-py3 as openmpf_triton_server
> 
> COPY --from=models /models/model.pt /models/ip_clip_512/1/model.pt
> ```

This is the ViT-B/32 model, right? We need to support the ViT-L/14 model on Triton too. The user should be able to select that model using the existing `MODEL_NAME` property. 


<!-- Sent from Reviewable.io -->

2023-11-29 19:19 UTC, jrobble commented
*[`python/ClipDetection/triton_server/Dockerfile` line 35 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/338#-NkIXI0g-I0ySjiYWaof:-NkRVzx-4TmNibslyMKc:bfpsb) ([raw file](https://github.com/openmpf/openmpf-components/blob/585c83d6235f56fa0e3a9a7cf10585e055bf1dfe/python/ClipDetection/triton_server/Dockerfile#L35)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

This is the ViT-B/32 model, right? We need to support the ViT-L/14 model on Triton too. The user should be able to select that model using the existing `MODEL_NAME` property.
</blockquote></details>

In `docker-compose.components.yml` please update this:

```yaml
    command: [tritonserver,
              --model-repository=/models,
              --strict-model-config=false,
              --model-control-mode=explicit,
              --load-model=ip_clip_512,
              # --log-verbose=1,  # (optional)
              --grpc-infer-allocation-pool-size=16 ]
```

Set `--load-model` to pre-load the ViT-L/14 model. An admin will have to change this if they ever want to use ViT-B/32.

Also, please test that when a user specifies `MODEL_NAME` set to ViT-B/32 that an appropriate error message is generated saying that the model is not available on Triton. Check the error in the JSON output object.


<!-- Sent from Reviewable.io -->

2023-11-29 19:45 UTC, jrobble commented
*[`python/ClipDetection/clip_component/clip_component.py` line 396 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/338#-NkIayTT8kObSiirYZP7:-NkRZXNo47QpnGihu99-:b89z6w9) ([raw file](https://github.com/openmpf/openmpf-components/blob/585c83d6235f56fa0e3a9a7cf10585e055bf1dfe/python/ClipDetection/clip_component/clip_component.py#L396)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

If possible, the exception should contain the original exception message.

For example, when I ran `CLIP TRITON IMAGENET CLASSIFICATION TASK` on this [video](https://github.com/openmpf/openmpf-components/blob/master/cpp/OcvFaceDetection/test/data/test_vids/new_face_video.avi) these log messages mention the protobuf and serialization:

```
2023-11-28 01:49:50,289 ERROR [clip_component.py:152] - [Job 6:new_face_video.avi(0-509)] Job failed due to: Inference failed. (DetectionError.NETWORK_ERROR)
Traceback (most recent call last):
  File "/opt/mpf/plugin-venv/lib/python3.8/site-packages/clip_component/clip_component.py", line 392, in get_responses
    responses.append(self._triton_client.infer(model_name=self._model_name, inputs=inputs, outputs=outputs))
  File "/opt/mpf/plugin-venv/lib/python3.8/site-packages/tritonclient/grpc/_client.py", line 1380, in infer
    raise_error_grpc(rpc_error)
  File "/opt/mpf/plugin-venv/lib/python3.8/site-packages/tritonclient/grpc/_utils.py", line 77, in raise_error_grpc
    raise get_error_grpc(rpc_error) from None
tritonclient.utils.InferenceServerException: [StatusCode.INTERNAL] Exception serializing request!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mpf/plugin-venv/lib/python3.8/site-packages/clip_component/clip_component.py", line 149, in get_detections_from_video_capture
    detection = list(islice(wrapper.get_classifications(batch, **kwargs), n))
  File "/opt/mpf/plugin-venv/lib/python3.8/site-packages/clip_component/clip_component.py", line 202, in get_classifications
    results = self._inferencing_server.get_responses(torch_imgs)
  File "/opt/mpf/plugin-venv/lib/python3.8/site-packages/clip_component/clip_component.py", line 394, in get_responses
    raise mpf.DetectionException(
mpf_component_api.mpf_component_api.DetectionException: Inference failed. (DetectionError.NETWORK_ERROR)
2023-11-28 01:49:50,290 ERROR [org.mitre.mpf.detection:0] - [Job 6:new_face_video.avi(0-509)] An error occurred while invoking the "get_detections_from_video" method on the Python component: DetectionException: Inference failed. (DetectionError.NETWORK_ERROR)

At:
  /opt/mpf/plugin-venv/lib/python3.8/site-packages/clip_component/clip_component.py(394): get_responses
  /opt/mpf/plugin-venv/lib/python3.8/site-packages/clip_component/clip_component.py(202): get_classifications

2023-11-28 01:49:50,292 ERROR [org.mitre.mpf.detection:0] - [Job 6:new_face_video.avi(0-509)] Video detection method returned an error for /opt/mpf/share/remote-media/new_face_video.avi
Exception serializing message!2023-11-28 01:49:50,289 ERROR [_common.py:91] - [Job 6:new_face_video.avi(0-509)] Exception serializing message!
Traceback (most recent call last):
  File "/opt/mpf/plugin-venv/lib/python3.8/site-packages/grpc/_common.py", line 89, in _transform
    return transformer(message)
ValueError: Message inference.ModelInferRequest exceeds maximum protobuf size of 2GB: 2774532167
```

However, what I see in the JSON output is pretty generic:

```
            {
               "source": "CLIP",
               "code": "NETWORK_ERROR",
               "message": "An error occurred while invoking the \"get_detections_from_video\" method on the Python component: Inference failed. (DetectionError.NETWORK_ERROR) (Frames: 0 - 509)"
            }
```

---


Here's the REST request that resulted in the above error:

```json
{
  "jobProperties": {
    "MODEL_NAME": "ViT-B/32",
    "DETECTION_FRAME_BATCH_SIZE_TRITON": "32",
  },
  "media": [
    {
      "mediaUri": "file:///opt/mpf/share/remote-media/new_face_video.avi"
    }
  ],
  "pipelineName": "CLIP TRITON IMAGENET CLASSIFICATION PIPELINE",
  "priority": 0
}
```

Adding  `"ENABLE_CROPPING" : "false"` as a job property allows the job to complete successfully. The issue seems to be that you're not considering the number of crops (in this case 144) against the batch size.

To be clear, a single image with 144 crops is equivalent to 144 frames with a single crop for each. In each case that's a batch of 144 images. If using a batch size of 32 that would be 4 full batches with a partial batch of 16.
</blockquote></details>

In the long run, if and when we seriously want to consider enabling cropping for videos, we should first look at using a 5-crop approach instead of a 144-crop approach.

For now, if the user sets `ENABLE_CROPPING` to true, let's ignore the value of `DETECTION_FRAME_BATCH_SIZE` and just just a batch size of 1 to ensure that we process all crops in one request.

Update the description of `DETECTION_FRAME_BATCH_SIZE` in `descriptor.json` to mention that it will be ignored when `ENABLE_CROPPING` is true.


<!-- Sent from Reviewable.io -->

2023-11-29 23:12 UTC, jrobble requested changes
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/338)* status: all files reviewed, 15 unresolved discussions (waiting on @ZachCafego)

___
*[`python/ClipDetection/README.md` line 80 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/338#-NhS-cwq2MoRoFP9JQgT:-NkSLQvVEt0KfB2qz0Mh:b-tsdehf) ([raw file](https://github.com/openmpf/openmpf-components/blob/585c83d6235f56fa0e3a9a7cf10585e055bf1dfe/python/ClipDetection/README.md#L80)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please address this:

> Please state which model was used.
</blockquote></details>

We discussed that these numbers were generated for ViT-B/32. Please generate them for ViT-L/14 as well.
___
*[`python/ClipDetection/clip_component/clip_component.py` line 396 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/338#-NkIayTT8kObSiirYZP7:-NkSLc06EMSG4SxoZgDA:b-g6c4h5) ([raw file](https://github.com/openmpf/openmpf-components/blob/585c83d6235f56fa0e3a9a7cf10585e055bf1dfe/python/ClipDetection/clip_component/clip_component.py#L396)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

In the long run, if and when we seriously want to consider enabling cropping for videos, we should first look at using a 5-crop approach instead of a 144-crop approach.

For now, if the user sets `ENABLE_CROPPING` to true, let's ignore the value of `DETECTION_FRAME_BATCH_SIZE` and just just a batch size of 1 to ensure that we process all crops in one request.

Update the description of `DETECTION_FRAME_BATCH_SIZE` in `descriptor.json` to mention that it will be ignored when `ENABLE_CROPPING` is true.
</blockquote></details>

Also, please test the 144 crop on Triton on an image that is 1080p, just as a sanity check.


<!-- Sent from Reviewable.io -->

2023-12-11 20:47 UTC, jrobble requested changes
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/338)* status: all files reviewed, 17 unresolved discussions (waiting on @ZachCafego)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf-components/338#-NlPc2f34BNKzyZEi-uh:-NlPc2f4CaCEmw0fvPIh:b-rhpt7f) (no related file):*
Please update the CLIP classification list to be:

```
crane bird,crane bird
construction crane,construction crane
```

___
___
*[`python/ClipDetection/plugin-files/descriptor/descriptor.json` line 37 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/338#-NlPcKAU9MfHdxPOOT6B:-NlPcKAU9MfHdxPOOT6C:bnrbvvy) ([raw file](https://github.com/openmpf/openmpf-components/blob/585c83d6235f56fa0e3a9a7cf10585e055bf1dfe/python/ClipDetection/plugin-files/descriptor/descriptor.json#L37)):*
> ```JSON
>                 }, 
>                 {
>                     "name": "NUMBER_OF_TEMPLATES",
> ```

Please change this to `TEMPLATE_TYPE` with the acceptable values of `openai-1`, `openai-7`, and `openai-80`.

This will lay the groundwork for `coop` templates in the future.


<!-- Sent from Reviewable.io -->

2024-01-26 14:05 UTC, ZachCafego reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/338)* status: 3 of 13 files reviewed, 15 unresolved discussions (waiting on @jrobble)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf-components/338#-NkHwp_oB2wCH1oEuSZ5:-NomqdGR-gRQhP5d3dNy:b-896fix) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

From the Dockerfile:

```
COPY --from=models /models/ViT-B-32.pt /models/ViT-B-32.pt
```

Please pre-install ViT-L-14 as well.
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf-components/338#-NlPc2f34BNKzyZEi-uh:-Nomqie-Dfy4R7iCY-dL:b-896fix) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please update the CLIP classification list to be:

```
crane bird,crane bird
construction crane,construction crane
```
</blockquote></details>

Done.

___
___
*[`python/ClipDetection/clip_component/clip_component.py` line 59 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/338#-NkHLabz6fOYQZ5uHJgw:-NomqvgvAM9fhuQKkbHR:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/585c83d6235f56fa0e3a9a7cf10585e055bf1dfe/python/ClipDetection/clip_component/clip_component.py#L59)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Nitpick: Let's call this `accept_values`.
</blockquote></details>

Done.
___
*[`python/ClipDetection/clip_component/clip_component.py` line 150 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/338#-NkHMhmq5sCtS-dfkGjx:-Nomr-Bl2d0QcanF5-j8:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/585c83d6235f56fa0e3a9a7cf10585e055bf1dfe/python/ClipDetection/clip_component/clip_component.py#L150)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

`get_detections` would be a more accurate name for this function. Also, it can return more than one detection. Let's use this:

```python
detections += list(islice(wrapper.get_detections(batch, **kwargs), n))
```
</blockquote></details>

Done.
___
*[`python/ClipDetection/clip_component/clip_component.py` line 348 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/338#-NkIY-ee7m4wQZe0AHVz:-NomrMjn8CYwA6pc1x3R:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/585c83d6235f56fa0e3a9a7cf10585e055bf1dfe/python/ClipDetection/clip_component/clip_component.py#L348)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

As mentioned in a separate comment, this needs to be configurable to ViT-B/32 or ViT-L/14.
</blockquote></details>

Done.
___
*[`python/ClipDetection/clip_component/clip_component.py` line 396 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/338#-NkIayTT8kObSiirYZP7:-NomrgM23XNVMKsyfPRM:bybnf0f) ([raw file](https://github.com/openmpf/openmpf-components/blob/585c83d6235f56fa0e3a9a7cf10585e055bf1dfe/python/ClipDetection/clip_component/clip_component.py#L396)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Also, please test the 144 crop on Triton on an image that is 1080p, just as a sanity check.
</blockquote></details>

Need to test 144 crop on Triton, 1080p.
___
*[`python/ClipDetection/clip_component/clip_component.py` line 450 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/338#-NkHY5IT0c9c2pkiUEhB:-NomrovK7yepiv6z71xg:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/585c83d6235f56fa0e3a9a7cf10585e055bf1dfe/python/ClipDetection/clip_component/clip_component.py#L450)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please remove dead code, unless this is important enough to be turned into a comment for future reference.
</blockquote></details>

Done.
___
*[`python/ClipDetection/plugin-files/descriptor/descriptor.json` line 26 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/338#-NkHK_gxClwfzX16zO7X:-NomrsMp16z6rDfcN4Qr:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/585c83d6235f56fa0e3a9a7cf10585e055bf1dfe/python/ClipDetection/plugin-files/descriptor/descriptor.json#L26)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please remove "only".
</blockquote></details>

Done.
___
*[`python/ClipDetection/plugin-files/descriptor/descriptor.json` line 37 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/338#-NlPcKAU9MfHdxPOOT6B:-Nomru8o82hhG1ruZaod:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/585c83d6235f56fa0e3a9a7cf10585e055bf1dfe/python/ClipDetection/plugin-files/descriptor/descriptor.json#L37)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please change this to `TEMPLATE_TYPE` with the acceptable values of `openai-1`, `openai-7`, and `openai-80`.

This will lay the groundwork for `coop` templates in the future.
</blockquote></details>

Done.
___
*[`python/ClipDetection/plugin-files/descriptor/descriptor.json` line 62 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/338#-NkIfTZo-VTFU3Hm0Ppw:-Nomrwg63pPS0B3C3OTG:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/585c83d6235f56fa0e3a9a7cf10585e055bf1dfe/python/ClipDetection/plugin-files/descriptor/descriptor.json#L62)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Do you mean "Not recommended for use on CPU" instead of "Not available ..." ? Does something prevent this from running on the CPU?
</blockquote></details>

Done.
___
*[`python/ClipDetection/plugin-files/descriptor/descriptor.json` line 91 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/338#-NkHdgUZCE27kPnQSXJv:-NomsKF2Bpi0PcKrVirY:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/585c83d6235f56fa0e3a9a7cf10585e055bf1dfe/python/ClipDetection/plugin-files/descriptor/descriptor.json#L91)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

The OcvDNN component has one property called `DETECTION_FRAME_BATCH_SIZE` that it uses for both non-Triton and Triton runs (although in that case it uses a value of 16 for everything). For consistency, I think we should use one property here too. A user may forget that there is a Triton and non-Triton version of the property.

Please add `"DETECTION_FRAME_BATCH_SIZE" : "32"` to the Triton actions you defined below.
</blockquote></details>

Done.
___
*[`python/ClipDetection/tests/data/test_video.mp4` line  at r1](https://reviewable.io/reviews/openmpf/openmpf-components/338#-NkHK34NAlH4LRzOfhZP:-NomsQssBdlRoLgkT44w:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/585c83d6235f56fa0e3a9a7cf10585e055bf1dfe/python/ClipDetection/tests/data/test_video.mp4#L)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Add an entry to the `NOTICE` file in this directory for this piece of media. Explain what images were used to create it and their respective licenses.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-23 18:55 UTC, jrobble commented
*[`python/ClipDetection/clip_component/clip_component.py` line 269 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/338#-NrC5FcD42-UJay5c5Dg:-NrC5FcK5gkloExXbQBF:bavtkf8) ([raw file](https://github.com/openmpf/openmpf-components/blob/a8ff906b2808f63306fcf3dd0163ad5faa56128f/python/ClipDetection/clip_component/clip_component.py#L269)):*
> ```Python
>                     )
>         elif (self._templates == None) or (number_of_templates[template_type] != len(self._templates)):
>             if number_of_templates[template_type] == 80:
> ```

Couldn't you just check to see if `template_type` is equal to "openai_80", "openai_7", or "openai_1"?


<!-- Sent from Reviewable.io -->

2024-02-23 18:55 UTC, jrobble commented
*[`python/ClipDetection/tests/test_clip.py` line 106 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/338#-NrDWaNN0a5kpqkZLSZe:-NrDWaNOB9OHk7VZS-Gi:b-r3a7xd) ([raw file](https://github.com/openmpf/openmpf-components/blob/a8ff906b2808f63306fcf3dd0163ad5faa56128f/python/ClipDetection/tests/test_clip.py#L106)):*
> ```Python
>             job_properties=dict(
>                 NUMBER_OF_TEMPLATES = 1,
>                 CLASSIFICATION_LIST = 'imagenet',
> ```

This test alone took 1 hour and 50 min to generate the ImageNet text embeddings as part of the Jenkins build. Please update this test to use the COCO classes. ImageNet simply takes too long to be part of the build.

For comparison, generating the COCO embeddings takes about 9 minutes, which is nearing the limit of the amount of time we want to spend on unit tests (10 min).

Another option is to pre-generate the embeddings.


<!-- Sent from Reviewable.io -->

2024-02-23 18:55 UTC, jrobble commented
*[`python/ClipDetection/triton_server/Dockerfile` line 36 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/338#-NrC86JPBEQOD7YzGGBK:-NrC86JPBEQOD7YzGGBL:btek9zi) ([raw file](https://github.com/openmpf/openmpf-components/blob/a8ff906b2808f63306fcf3dd0163ad5faa56128f/python/ClipDetection/triton_server/Dockerfile#L36)):*
> ```Dockerfile
> 
> COPY --from=models /models/vit_b_32.pt /models/vit_b_32/1/vit_b_32.pt
> COPY models/vit_b_32.config.pbtxt /models/ip_clip_512/config.pbtxt
> ```

`ip_clip_512` in the destination path seems like a mistake.


<!-- Sent from Reviewable.io -->

2024-03-05 01:13 UTC, jrobble commented
*[`python/ClipDetection/tests/test_clip.py` line 120 at r6](https://reviewable.io/reviews/openmpf/openmpf-components/338#-NsAc5q70RUK2HGWxiuw:-NsAc5q70RUK2HGWxiux:bciq4oe) ([raw file](https://github.com/openmpf/openmpf-components/blob/ce5ab601befea967a6c5067ae5495070d63de611/python/ClipDetection/tests/test_clip.py#L120)):*
> ```Python
>         self.assertEqual(results[0].stop_frame, 4)
> 
>         self.assertEqual(results[1].detection_properties['CLASSIFICATION'], "fish")
> ```

The Jenkins build failed with:

```
#19 254.3 ======================================================================
#19 254.3 FAIL: test_video_file (__main__.TestClip)
#19 254.3 ----------------------------------------------------------------------
#19 254.3 Traceback (most recent call last):
#19 254.3   File "tests/test_clip.py", line 120, in test_video_file
#19 254.3     self.assertEqual(results[1].detection_properties['CLASSIFICATION'], "fish")
#19 254.3 AssertionError: 'orange' != 'fish'
#19 254.3 - orange
#19 254.3 + fish
```

`fish` is not a COCO class.


<!-- Sent from Reviewable.io -->

2024-03-29 03:53 UTC, jrobble approved these changes
> Reviewed 2 of 10 files at r2, 1 of 4 files at r3, 7 of 7 files at r4, 2 of 4 files at r5, 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/338)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ZachCafego)



<!-- Sent from Reviewable.io -->

2024-03-29 03:56 UTC, merged