Changes to update keyword tagging
openmpf/openmpf-components pull request #355
Opened 2024-03-11 17:48 UTC by fpc0002

**Issues:**

https://github.com/openmpf/openmpf/issues/1770

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-components/355)

2024-03-15 18:00 UTC, brosenberg42 commented
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 38 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/355#-Nt2Esei7pCEpH8m7xn1:-Nt2Esei7pCEpH8m7xn2:b72weit) ([raw file](https://github.com/openmpf/openmpf-components/blob/bc8b3581f83e3963ec31f1694b256acd051251ea/cpp/KeywordTagging/plugin-files/config/text-tags.json#L38)):*
> ```JSON
> 			{"pattern": "(\\b)savings(\\b)"},
> 			{"pattern": "(\\b)transaction(\\b)"},
> 			{"pattern": "\\u060B"},
> ```

Using `\\u` won't work. It would be better to replace these with the actual characters. JSON lets you escape unicode characters with a single slash `\u`, but it is preferable to use the actual symbol instead. This file is interpreted as utf-8, so all unicode characters can be used literally. So, this can be:
```json
{"pattern": "؋"}
```
or 
```json
{"pattern": "\u060B"}
```


<!-- Sent from Reviewable.io -->

2024-03-15 19:56 UTC, fpc0002 commented
> _[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 38 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/355#-Nt2Esei7pCEpH8m7xn1:-Nt2Esei7pCEpH8m7xn2:b72weit) ([raw file](https://github.com/openmpf/openmpf-components/blob/bc8b3581f83e3963ec31f1694b256acd051251ea/cpp/KeywordTagging/plugin-files/config/text-tags.json#L38)):_
> 
> > ```json
> > 			{"pattern": "(\\b)savings(\\b)"},
> > 			{"pattern": "(\\b)transaction(\\b)"},
> > 			{"pattern": "\\u060B"},
> > ```
> 
> Using `\\u` won't work. It would be better to replace these with the actual characters. JSON lets you escape unicode characters with a single slash `\u`, but it is preferable to use the actual symbol instead. This file is interpreted as utf-8, so all unicode characters can be used literally. So, this can be:
> 
> ```json
> {"pattern": "؋"}
> ```
> 
> or
> 
> ```json
> {"pattern": "\u060B"}
> ```

Change `\\u` to `\u`

2024-04-02 02:17 UTC, jrobble requested changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/355)* status: all files reviewed, 17 unresolved discussions (waiting on @brosenberg42 and @fpc0002)

___
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 38 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/355#-Nt2Esei7pCEpH8m7xn1:-NuP_3Dp7zsaaxi15QsH:byran4y) ([raw file](https://github.com/openmpf/openmpf-components/blob/bc8b3581f83e3963ec31f1694b256acd051251ea/cpp/KeywordTagging/plugin-files/config/text-tags.json#L38)):*
<details><summary><i>Previously, fpc0002 wrote…</i></summary><blockquote>

Changed `\\u` to `\u`
</blockquote></details>

I agree with Brian that it's preferable to use the actual symbols. That will enable a reader to understand what's in this file more easily. I don't have all of the unicode codes memorized :)
___
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 46 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NuRXh4z9yyYsEdao_rd:-NuRXh4z9yyYsEdao_re:b-5q0ryp) ([raw file](https://github.com/openmpf/openmpf-components/blob/eb573c590b5891ce827c05b3d33b69d6eb829523/cpp/KeywordTagging/plugin-files/config/text-tags.json#L46)):*
> ```JSON
> 			{"pattern": "\u0434\u0435\u043D"},
> 			{"pattern": "\u0434\u0438\u043D"},
> 			{"pattern": "\\.\u062F\\.\u062C"},
> ```

Please add a unit test section for currency. You don't have to test all of these, but at least some, including some of the ones with periods in them.

Another reason for this is so that you can link to the source(s) where you got the currency symbols from.
___
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 52 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NuRXv8OEobs2Bm_6xPu:-NuRXv8OEobs2Bm_6xPv:b-qzch5m) ([raw file](https://github.com/openmpf/openmpf-components/blob/eb573c590b5891ce827c05b3d33b69d6eb829523/cpp/KeywordTagging/plugin-files/config/text-tags.json#L52)):*
> ```JSON
> 			{"pattern": "\\.\u062F\\.\u0643"},
> 			{"pattern": "\\.\u062F\\.\u062A"},
> 			{"pattern": "\\.\u062F.\u0645"},
> ```

Should this be as follows?

```
\\.\u062F\\.\u0645
```

You're missing slashes in front of the second period.
___
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 109 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NuRG2fu95XVfC3-GHNg:-NuRG2fu95XVfC3-GHNh:b-an6q8q) ([raw file](https://github.com/openmpf/openmpf-components/blob/eb573c590b5891ce827c05b3d33b69d6eb829523/cpp/KeywordTagging/plugin-files/config/text-tags.json#L109)):*
> ```JSON
> 			{"pattern": "(\\b)username(\\b)"},
> 			{"pattern": "(?<![\\/\\?\\-:.\\w])(\\+?\\d{1,3}[ .-]*)?[ .-]*(\\(?\\d{3}\\)?)?[ .-]*\\d{3}[ .-]*\\d{4}(?!([\\/\\?.\\-@]?\\w))"},
> 			{"pattern": "(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|\"(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21\\x23-\\x5b\\x5d-\\x7f]|\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])*\")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\\[(?:(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9]))\\.){3}(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9])|[a-z0-9-]*[a-z0-9]:(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21-\\x5a\\x53-\\x7f]|\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])+)\\])"}
> ```

This appears twice in the regex:

```
[a-z0-9!#$%&'*+/=?^_`{|}~-]
```

Does `/` need to be escaped? E.g. `\/`?
___
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 109 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NuRNR4a-rFfTHCl5kbf:-NuRNR4bDjr7xcvigNDF:b-95d3zr) ([raw file](https://github.com/openmpf/openmpf-components/blob/eb573c590b5891ce827c05b3d33b69d6eb829523/cpp/KeywordTagging/plugin-files/config/text-tags.json#L109)):*
Providing this in regex101:

> @iiuoiu.@unusual@strange.example.com

matches on:

> unusual@strange.example.com

It seems like we should provide negative lookbehind and lookahead.
___
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 109 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NuRVC321vVqi3kSoIpE:-NuRVC321vVqi3kSoIpF:br74pup) ([raw file](https://github.com/openmpf/openmpf-components/blob/eb573c590b5891ce827c05b3d33b69d6eb829523/cpp/KeywordTagging/plugin-files/config/text-tags.json#L109)):*
> ```JSON
> 			{"pattern": "(\\b)username(\\b)"},
> 			{"pattern": "(?<![\\/\\?\\-:.\\w])(\\+?\\d{1,3}[ .-]*)?[ .-]*(\\(?\\d{3}\\)?)?[ .-]*\\d{3}[ .-]*\\d{4}(?!([\\/\\?.\\-@]?\\w))"},
> 			{"pattern": "(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|\"(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21\\x23-\\x5b\\x5d-\\x7f]|\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])*\")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\\[(?:(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9]))\\.){3}(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9])|[a-z0-9-]*[a-z0-9]:(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21-\\x5a\\x53-\\x7f]|\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])+)\\])"}
> ```

This appears twice in the regex:

```
-\\x7f]|\\[\\x01
```

I think that needs to be:

```
-\\x7f]|\\\[\\x01
```

You're missing a `\`.

I determined that by looking at the [diagram](https://i.stack.imgur.com/YI6KR.png) and trying to come up with at least one example that uses an ASCII control character. This matches in regex101:

```
"\	"@gmail.com
```

Note that the space is actually a tab control character. It would be good if we can add this to the unit test.
___
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 130 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NuQeysg8Hzlh9rY-abj:-NuQeysj8dxV4XqXvR1o:bcgym9q) ([raw file](https://github.com/openmpf/openmpf-components/blob/eb573c590b5891ce827c05b3d33b69d6eb829523/cpp/KeywordTagging/plugin-files/config/text-tags.json#L130)):*
> ```JSON
> 			{"pattern": "(\\b)address(\\b)"},
> 			{"pattern": "(\\b)nationality(\\b)"},
> 			{"pattern": "(?<![A-Za-z])(?!pb)(Post|p)[\\.\\-\/\t ]*(?=(office|o|box|b))((Office|o)[\\.\\-\/\t ]*)?((Box|B)[\\.\\-\/\t ]*)?(#?[\\.\\-\/\t ]*\\d{0,9})(?![A-Za-z])"}
> ```

Is the `(?!pb)` part just to ensure that office is represented in there somewhere? The following is valid for this regex: `postb 778888888`. Is that desired?

Is the `(?=(office|o|box|b))` part just to ensure that "Post" or "p" don't appear by themself?
___
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 145 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NuRYPq6AT_NDHlZk-P6:-NuRYPq6AT_NDHlZk-P7:bg8ciu9) ([raw file](https://github.com/openmpf/openmpf-components/blob/eb573c590b5891ce827c05b3d33b69d6eb829523/cpp/KeywordTagging/plugin-files/config/text-tags.json#L145)):*
> ```JSON
> 			{"pattern": "(\\b)trip(\\b)"}
> 		],
> 		"DATE": [
> ```

For consistency, use lowercase for the `date` and `time` tags.
___
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 146 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NuPlaBoAejDzM8lMGio:-NuPlaBoAejDzM8lMGip:b-9dcdsd) ([raw file](https://github.com/openmpf/openmpf-components/blob/eb573c590b5891ce827c05b3d33b69d6eb829523/cpp/KeywordTagging/plugin-files/config/text-tags.json#L146)):*
> ```JSON
> 		],
> 		"DATE": [
> 			{"pattern": "(?<![\\-0-9])(3[01]|[12][0-9]|0?[1-9])(\\/|-|\\.| )(1[0-2]|0?[1-9])\\2([0-9]{2})?[0-9]{2}(?![\\-0-9])"},
> ```

`\\2` - reusing a capture group. That's fancy.
___
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 149 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NuQPjFU6wkviXgIyiWd:-NuQPjFX3V8d395Ibr6C:b-wf6eop) ([raw file](https://github.com/openmpf/openmpf-components/blob/eb573c590b5891ce827c05b3d33b69d6eb829523/cpp/KeywordTagging/plugin-files/config/text-tags.json#L149)):*
This matches on:

> Sep     30,,,,, , , , , ,  , ,,  ,,  ,  , ,  1921

Similarly, the regex below matches on:

> 30 Sep,, , , , , 1982

That's a lot of commas. Do we want to limit that to one?
___
*[`cpp/Keywo [...]

2024-04-03 22:35 UTC, fpc0002 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/355)* status: all files reviewed, 14 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 109 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NuRG2fu95XVfC3-GHNg:-Nu_vIRSDyJqWfg7pz7-:bam1m37) ([raw file](https://github.com/openmpf/openmpf-components/blob/eb573c590b5891ce827c05b3d33b69d6eb829523/cpp/KeywordTagging/plugin-files/config/text-tags.json#L109)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

This appears twice in the regex:

```
[a-z0-9!#$%&'*+/=?^_`{|}~-]
```

Does `/` need to be escaped? E.g. `\/`?
</blockquote></details>

This does not need escaped because it is part of a character class.
___
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 109 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NuRNR4a-rFfTHCl5kbf:-Nu_vN7k4OjHF9VMYddn:b-7ovava) ([raw file](https://github.com/openmpf/openmpf-components/blob/eb573c590b5891ce827c05b3d33b69d6eb829523/cpp/KeywordTagging/plugin-files/config/text-tags.json#L109)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Providing this in regex101:

> @iiuoiu.@unusual@strange.example.com

matches on:

> unusual@strange.example.com

It seems like we should provide negative lookbehind and lookahead.
</blockquote></details>

Don't think we should do anything different here, even gitlab here is matching on the same sub-string.
___
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 109 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NuRVC321vVqi3kSoIpE:-Nu_y_tL3zyrjuNPUEaN:bwaird5) ([raw file](https://github.com/openmpf/openmpf-components/blob/eb573c590b5891ce827c05b3d33b69d6eb829523/cpp/KeywordTagging/plugin-files/config/text-tags.json#L109)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

This appears twice in the regex:

```
-\\x7f]|\\[\\x01
```

I think that needs to be:

```
-\\x7f]|\\\[\\x01
```

You're missing a `\`.

I determined that by looking at the [diagram](https://i.stack.imgur.com/YI6KR.png) and trying to come up with at least one example that uses an ASCII control character. This matches in regex101:

```
"\	"@gmail.com
```

Note that the space is actually a tab control character. It would be good if we can add this to the unit test.
</blockquote></details>

Looks like it should actually be four '\', based on the SO post. I changed it and added a test.
___
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 130 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NuQeysg8Hzlh9rY-abj:-Nu_yz0w01H9dto4k1VP:b-lznet1) ([raw file](https://github.com/openmpf/openmpf-components/blob/eb573c590b5891ce827c05b3d33b69d6eb829523/cpp/KeywordTagging/plugin-files/config/text-tags.json#L130)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Is the `(?!pb)` part just to ensure that office is represented in there somewhere? The following is valid for this regex: `postb 778888888`. Is that desired?

Is the `(?=(office|o|box|b))` part just to ensure that "Post" or "p" don't appear by themself?
</blockquote></details>

`(?!pb)` just makes sure that `pb` isn't a match - we don't want to confuse our PB & J sandwiches with post boxes ;)
RE: `postb 778888888` I'm not sure, I went back and forth a while on that, it is a complicated expression, and I was not sure we wanted to complicate it more or just accept it as it is.
`(?=(office|o|box|b))` - yup that's exactly what it does
___
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 145 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NuRYPq6AT_NDHlZk-P6:-Nu_zryeDUD1gRfjlDHE:biay1rk) ([raw file](https://github.com/openmpf/openmpf-components/blob/eb573c590b5891ce827c05b3d33b69d6eb829523/cpp/KeywordTagging/plugin-files/config/text-tags.json#L145)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

For consistency, use lowercase for the `date` and `time` tags.
</blockquote></details>

understood
___
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 149 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NuQPjFU6wkviXgIyiWd:-Nu_zx2QDGl4l6f3r_DP:b-seaxss) ([raw file](https://github.com/openmpf/openmpf-components/blob/eb573c590b5891ce827c05b3d33b69d6eb829523/cpp/KeywordTagging/plugin-files/config/text-tags.json#L149)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

This matches on:

> Sep     30,,,,, , , , , ,  , ,,  ,,  ,  , ,  1921

Similarly, the regex below matches on:

> 30 Sep,, , , , , 1982

That's a lot of commas. Do we want to limit that to one?
</blockquote></details>

figured it didn't hurt to match on that, makes it more robust to typos or weird formatting
___
*[`cpp/KeywordTagging/test/test_keyword_tagging.cpp` line 231 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NuPf--Q4wdbbgOPauz_:-Nua4-z0EL2R2Qu9Th20:b2ni8oq) ([raw file](https://github.com/openmpf/openmpf-components/blob/5ab64e97dc4dfa536690057bdb13b53754d9efb0/cpp/KeywordTagging/test/test_keyword_tagging.cpp#L231)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Thanks for the clean up.
</blockquote></details>

np!


<!-- Sent from Reviewable.io -->

2024-04-08 16:56 UTC, jrobble requested changes
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/355)* status: all files reviewed, 12 unresolved discussions (waiting on @brosenberg42 and @fpc0002)

___
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 109 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NuRG2fu95XVfC3-GHNg:-NuyZFkQErVE0upO7eFp:bhrnci5) ([raw file](https://github.com/openmpf/openmpf-components/blob/eb573c590b5891ce827c05b3d33b69d6eb829523/cpp/KeywordTagging/plugin-files/config/text-tags.json#L109)):*
<details><summary><i>Previously, fpc0002 wrote…</i></summary><blockquote>

This does not need escaped because it is part of a character class.
</blockquote></details>

regex101 found an issue with it:

![delimiter.PNG](https://files.reviewableusercontent.io/images/reviewable/1039601/J8oWcjxfjD-ixriPDvnV51J7/delimiter.png)

Please add a unit test for an email with a valid slash like this to make sure it works as expected.
___
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 109 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NuRNR4a-rFfTHCl5kbf:-Nuy_RSeCaZC7i1fFZRZ:b-ejrabs) ([raw file](https://github.com/openmpf/openmpf-components/blob/eb573c590b5891ce827c05b3d33b69d6eb829523/cpp/KeywordTagging/plugin-files/config/text-tags.json#L109)):*
<details><summary><i>Previously, fpc0002 wrote…</i></summary><blockquote>

Don't think we should do anything different here, even gitlab here is matching on the same sub-string.
</blockquote></details>

Ok. Let's not worry about it.
___
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 130 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NuQeysg8Hzlh9rY-abj:-NuyadMC14J2EUBAzG4e:bynpc30) ([raw file](https://github.com/openmpf/openmpf-components/blob/eb573c590b5891ce827c05b3d33b69d6eb829523/cpp/KeywordTagging/plugin-files/config/text-tags.json#L130)):*
<details><summary><i>Previously, fpc0002 wrote…</i></summary><blockquote>

`(?!pb)` just makes sure that `pb` isn't a match - we don't want to confuse our PB & J sandwiches with post boxes ;)
RE: `postb 778888888` I'm not sure, I went back and forth a while on that, it is a complicated expression, and I was not sure we wanted to complicate it more or just accept it as it is.
`(?=(office|o|box|b))` - yup that's exactly what it does
</blockquote></details>

Ok. Let's leave as is for now.
___
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 149 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NuQPjFU6wkviXgIyiWd:-Nuyb4Ph5S4oTiTcyvdf:b-jhwbzf) ([raw file](https://github.com/openmpf/openmpf-components/blob/eb573c590b5891ce827c05b3d33b69d6eb829523/cpp/KeywordTagging/plugin-files/config/text-tags.json#L149)):*
<details><summary><i>Previously, fpc0002 wrote…</i></summary><blockquote>

figured it didn't hurt to match on that, makes it more robust to typos or weird formatting
</blockquote></details>

Sees a little odd since we don't accept:

```
Sep... 20, 2014
```

However, thinking more about this, I think we should make the year optional. For example:

```
(Jan(?:uary|\.)?|Feb(?:ruary|\.)?|Mar(?:ch|\.)?|Apr(?:il|\.)?|May(\.)?|Jun(?:e|\.)?|Jul(?:y|\.)?|Aug(?:ust|\.)?|Sep(?:tember|\.)?|Oct(?:ober|\.)?|Nov(?:ember|\.)?|Dec(?:ember|\.)?)[\t ]+(([0-2]?\d)|3[01])([\t ,]+([0-9]{2})?[0-9]{2})?
```

The change I made was to the last `([\t ,]+([0-9]{2})?[0-9]{2})?` part.

That will match on `Sep 20`, which will be fine if someone writes `Sep 20th`.

Also, September is commonly shortened to Sept. Let's use `|Sep(?:tember|\.|t|t\.)?`. That will accept all of these:

```
Sep. 20th
Sept. 20th
Sep 20
Sept 20
```


<!-- Sent from Reviewable.io -->

2024-04-08 19:50 UTC, fpc0002 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/355)* status: all files reviewed, 12 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 38 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/355#-Nt2Esei7pCEpH8m7xn1:-NuzD648CPAfbRqsSg-T:bb6un1j) ([raw file](https://github.com/openmpf/openmpf-components/blob/bc8b3581f83e3963ec31f1694b256acd051251ea/cpp/KeywordTagging/plugin-files/config/text-tags.json#L38)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I agree with Brian that it's preferable to use the actual symbols. That will enable a reader to understand what's in this file more easily. I don't have all of the unicode codes memorized :)
</blockquote></details>

Done
___
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 46 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NuRXh4z9yyYsEdao_rd:-NuzD9jw9UBFiVbHefx1:bb6un1j) ([raw file](https://github.com/openmpf/openmpf-components/blob/eb573c590b5891ce827c05b3d33b69d6eb829523/cpp/KeywordTagging/plugin-files/config/text-tags.json#L46)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please add a unit test section for currency. You don't have to test all of these, but at least some, including some of the ones with periods in them.

Another reason for this is so that you can link to the source(s) where you got the currency symbols from.
</blockquote></details>

Done
___
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 52 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NuRXv8OEobs2Bm_6xPu:-NuzDB5I0eiAs00lyr5V:bc5mq7t) ([raw file](https://github.com/openmpf/openmpf-components/blob/eb573c590b5891ce827c05b3d33b69d6eb829523/cpp/KeywordTagging/plugin-files/config/text-tags.json#L52)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Should this be as follows?

```
\\.\u062F\\.\u0645
```

You're missing slashes in front of the second period.
</blockquote></details>

changed to use full symbols, so OBE
___
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 109 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NuRG2fu95XVfC3-GHNg:-NuzDR0c7N8EG1WLp6f7:b-40wj6a) ([raw file](https://github.com/openmpf/openmpf-components/blob/eb573c590b5891ce827c05b3d33b69d6eb829523/cpp/KeywordTagging/plugin-files/config/text-tags.json#L109)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

regex101 found an issue with it:

![delimiter.PNG](https://files.reviewableusercontent.io/images/reviewable/1039601/J8oWcjxfjD-ixriPDvnV51J7/delimiter.png)

Please add a unit test for an email with a valid slash like this to make sure it works as expected.
</blockquote></details>

yea probably dependent on the flavor/engine, I added a test and it worked fine `ASSERT_NO_FATAL_FAILURE(assertTextAndTagFound(tagger, "a/b/c@website.com", "personal"));`


<!-- Sent from Reviewable.io -->

2024-04-08 21:02 UTC, fpc0002 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/355)* status: 1 of 3 files reviewed, 12 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[`cpp/KeywordTagging/test/test_keyword_tagging.cpp` line 114 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NuPeW-F69JTIYWWMVjq:-NuzJA6ZBprtQKWn7tRY:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/eb573c590b5891ce827c05b3d33b69d6eb829523/cpp/KeywordTagging/test/test_keyword_tagging.cpp#L114)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Instead of providing `TRANSLATION` and `TEXT`, remove this comment and just provide `TEXT`. Do the same in `assertTextNotFound()`.

We already have a separate test that tests `FEED_FORWARD_PROP_TO_PROCESS` in this way.
</blockquote></details>

Done.
___
*[`cpp/KeywordTagging/test/test_keyword_tagging.cpp` line 116 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NuPdeEaDmLYmKiyNliO:-NuzQWx34rVwRzLrG5WG:b-nppteu) ([raw file](https://github.com/openmpf/openmpf-components/blob/eb573c590b5891ce827c05b3d33b69d6eb829523/cpp/KeywordTagging/test/test_keyword_tagging.cpp#L116)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Leave a comment explaining why 5 is used here.
</blockquote></details>

Done - changed to 4, can you confirm my comment is right? I wasn't 100% sure
___
*[`cpp/KeywordTagging/test/test_keyword_tagging.cpp` line 140 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NuPeCSq9A48k_FvHf0I:-NuzTIc3AmcPrTfByCGg:bquxfay) ([raw file](https://github.com/openmpf/openmpf-components/blob/eb573c590b5891ce827c05b3d33b69d6eb829523/cpp/KeywordTagging/test/test_keyword_tagging.cpp#L140)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Instead of asserting what you don't want it to be, assert what you want it to be and leave a comment explaining why you want it to be that size.
</blockquote></details>

done, can you confirm my comment is right? I wasn't 100% sure
___
*[`cpp/KeywordTagging/test/test_keyword_tagging.cpp` line 679 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NuRTfG_Abf-lcF-AOAm:-NuzTkTw8prx9gC-01Dn:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/eb573c590b5891ce827c05b3d33b69d6eb829523/cpp/KeywordTagging/test/test_keyword_tagging.cpp#L679)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Add a least one test with capital letters to ensure this isn't case sensitive.
</blockquote></details>

Done.
___
*[`cpp/KeywordTagging/test/test_keyword_tagging.cpp` line 722 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NuPg_Xd2yNR0JYAsiRN:-NuzVaAT5j4JnReaqcjw:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/eb573c590b5891ce827c05b3d33b69d6eb829523/cpp/KeywordTagging/test/test_keyword_tagging.cpp#L722)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Have at least one test where you make sure it properly handles junk characters before and after the time string.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-09 13:48 UTC, fpc0002 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/355)* status: 1 of 3 files reviewed, 12 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 149 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NuQPjFU6wkviXgIyiWd:-NuzYtFM3LzlWQwPLNzM:bir7n6s) ([raw file](https://github.com/openmpf/openmpf-components/blob/eb573c590b5891ce827c05b3d33b69d6eb829523/cpp/KeywordTagging/plugin-files/config/text-tags.json#L149)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Sees a little odd since we don't accept:

```
Sep... 20, 2014
```

However, thinking more about this, I think we should make the year optional. For example:

```
(Jan(?:uary|\.)?|Feb(?:ruary|\.)?|Mar(?:ch|\.)?|Apr(?:il|\.)?|May(\.)?|Jun(?:e|\.)?|Jul(?:y|\.)?|Aug(?:ust|\.)?|Sep(?:tember|\.)?|Oct(?:ober|\.)?|Nov(?:ember|\.)?|Dec(?:ember|\.)?)[\t ]+(([0-2]?\d)|3[01])([\t ,]+([0-9]{2})?[0-9]{2})?
```

The change I made was to the last `([\t ,]+([0-9]{2})?[0-9]{2})?` part.

That will match on `Sep 20`, which will be fine if someone writes `Sep 20th`.

Also, September is commonly shortened to Sept. Let's use `|Sep(?:tember|\.|t|t\.)?`. That will accept all of these:

```
Sep. 20th
Sept. 20th
Sep 20
Sept 20
```
</blockquote></details>

Making the year optional has some other side effects that could be undesired. I'll look into it more.


<!-- Sent from Reviewable.io -->

2024-04-12 18:39 UTC, fpc0002 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/355)* status: 1 of 3 files reviewed, 12 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 149 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NuQPjFU6wkviXgIyiWd:-NvIaEFD2cXFiYpQKu2R:b-6inqyw) ([raw file](https://github.com/openmpf/openmpf-components/blob/eb573c590b5891ce827c05b3d33b69d6eb829523/cpp/KeywordTagging/plugin-files/config/text-tags.json#L149)):*
<details><summary><i>Previously, fpc0002 wrote…</i></summary><blockquote>

Making the year optional has some other side effects that could be undesired. I'll look into it more.
</blockquote></details>

So the issue I'm having with this is the following:
```
String "14 MAR 24"

expected_trigger_words
    Which is: "14 MAR 24"
props["TEXT " + expected_tag + " TRIGGER WORDS"]
    Which is: "14 MAR 24; MAR 24"
```

While is isn't necessarily a bad thing, it does introduce some trigger words that are substrings of others. I'm not sure of a good way to fix this. Let me know if you're ok with this, or if you want me to work to remove this behavior.  


<!-- Sent from Reviewable.io -->

2024-04-12 21:42 UTC, jrobble requested changes
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/355)* status: 1 of 3 files reviewed, 11 unresolved discussions (waiting on @brosenberg42 and @fpc0002)

___
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 149 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NuQPjFU6wkviXgIyiWd:-NvJ1RxQ6IgnI94XdhAi:b-2yl59u) ([raw file](https://github.com/openmpf/openmpf-components/blob/eb573c590b5891ce827c05b3d33b69d6eb829523/cpp/KeywordTagging/plugin-files/config/text-tags.json#L149)):*
<details><summary><i>Previously, fpc0002 wrote…</i></summary><blockquote>

So the issue I'm having with this is the following:
```
String "14 MAR 24"

expected_trigger_words
    Which is: "14 MAR 24"
props["TEXT " + expected_tag + " TRIGGER WORDS"]
    Which is: "14 MAR 24; MAR 24"
```

While is isn't necessarily a bad thing, it does introduce some trigger words that are substrings of others. I'm not sure of a good way to fix this. Let me know if you're ok with this, or if you want me to work to remove this behavior.
</blockquote></details>

Good catch. Matching on the same thing twice may be confusing.

Consider one regex where we just OR the two patterns together:

```
((Jan(?:uary|\.)?|Feb(?:ruary|\.)?|Mar(?:ch|\.)?|Apr(?:il|\.)?|May(\.)?|Jun(?:e|\.)?|Jul(?:y|\.)?|Aug(?:ust|\.)?|Sep(?:tember|\.)?|Oct(?:ober|\.)?|Nov(?:ember|\.)?|Dec(?:ember|\.)?)[\t ]+(([0-2]?\d)|3[01])([\t ,]+([0-9]{2})?[0-9]{2})?)

|

((([0-2]?\d)|3[01])[\t ]+(Jan(?:uary|\.)?|Feb(?:ruary|\.)?|Mar(?:ch|\.)?|Apr(?:il|\.)?|May(\.)?|Jun(?:e|\.)?|Jul(?:y|\.)?|Aug(?:ust|\.)?|Sep(?:tember|\.)?|Oct(?:ober|\.)?|Nov(?:ember|\.)?|Dec(?:ember|\.)?)([\t ,]+([0-9]{2})?[0-9]{2})?)
```

Note that I added the spacing around the `|` for clarity.

That would prevent a double capture, but consider this text:

```
iPhone11 Mar 19, 24
```

That prioritizes capturing `11 Mar 19`, but `Mar 19, 24` is more valid.

Even you wanted to prioritize the month-day-year format over the other, you could have:

```
On 3 Mar 19, 24 men swam a race
``` 

Here, `3 Mar 19` is more valid than `Mar 19, 24`.

I think using two regexes, each with an optional year, as you have it, is preferable. 

---

However, it does beg the question, do we care about things like below?

```
Mar 2024
```

I think we should make the date optional. To do that, we would need a regex that accepts the month-day-year, month-year, and month-day:

```
(Jan(?:uary|\.)?|Feb(?:ruary|\.)?|Mar(?:ch|\.)?|Apr(?:il|\.)?|May(\.)?|Jun(?:e|\.)?|Jul(?:y|\.)?|Aug(?:ust|\.)?|Sep(?:tember|\.)?|Oct(?:ober|\.)?|Nov(?:ember|\.)?|Dec(?:ember|\.)?)((([\t ]+(([0-2]?\d)|3[01]))?([\t ,]+([0-9]{2})?[0-9]{2}))|([\t ,]+([0-9]{2})?[0-9]{2})|([\t ]+(([0-2]?\d)|3[01])))
```

Note that on regex101 the month-day-year has to come first in the list of options or else it will prioritize just month-day. Similarly, month-year has to come before month-day or it will not capture the full year because it will consider the number a date.

We will also need to update the day-month-year regex to accept day-month by making the year optional:

```
((([0-2]?\d)|3[01])[\t ]+)?(Jan(?:uary|\.)?|Feb(?:ruary|\.)?|Mar(?:ch|\.)?|Apr(?:il|\.)?|May(\.)?|Jun(?:e|\.)?|Jul(?:y|\.)?|Aug(?:ust|\.)?|Sep(?:tember|\.)?|Oct(?:ober|\.)?|Nov(?:ember|\.)?|Dec(?:ember|\.)?)([\t ,]+([0-9]{2})?[0-9]{2})?
```

We don't want to update this regex to accept month-year since the previous one already does that.
___
*[`cpp/KeywordTagging/test/test_keyword_tagging.cpp` line 116 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NuPdeEaDmLYmKiyNliO:-NvJD9CsBKVN_AtREJ5d:bjoptyp) ([raw file](https://github.com/openmpf/openmpf-components/blob/eb573c590b5891ce827c05b3d33b69d6eb829523/cpp/KeywordTagging/test/test_keyword_tagging.cpp#L116)):*
<details><summary><i>Previously, fpc0002 wrote…</i></summary><blockquote>

Done - changed to 4, can you confirm my comment is right? I wasn't 100% sure
</blockquote></details>

You want `TEXT <TAG> TRIGGER WORDS OFFSET`, not `LOCATION`.
___
*[`cpp/KeywordTagging/test/test_keyword_tagging.cpp` line 140 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NuPeCSq9A48k_FvHf0I:-NvJCD8aDI1pyQ7I3h5Y:b-ljn7s) ([raw file](https://github.com/openmpf/openmpf-components/blob/eb573c590b5891ce827c05b3d33b69d6eb829523/cpp/KeywordTagging/test/test_keyword_tagging.cpp#L140)):*
<details><summary><i>Previously, fpc0002 wrote…</i></summary><blockquote>

done, can you confirm my comment is right? I wasn't 100% sure
</blockquote></details>

This is right. You assert those entries from `props` below, so those have to be the only ones if it's a size of 2.


<!-- Sent from Reviewable.io -->

2024-04-15 20:52 UTC, fpc0002 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/355)* status: 1 of 3 files reviewed, 11 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 149 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NuQPjFU6wkviXgIyiWd:-NvXWQYH5aVNadsxscwL:bgiwbqu) ([raw file](https://github.com/openmpf/openmpf-components/blob/eb573c590b5891ce827c05b3d33b69d6eb829523/cpp/KeywordTagging/plugin-files/config/text-tags.json#L149)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Good catch. Matching on the same thing twice may be confusing.

Consider one regex where we just OR the two patterns together:

```
((Jan(?:uary|\.)?|Feb(?:ruary|\.)?|Mar(?:ch|\.)?|Apr(?:il|\.)?|May(\.)?|Jun(?:e|\.)?|Jul(?:y|\.)?|Aug(?:ust|\.)?|Sep(?:tember|\.)?|Oct(?:ober|\.)?|Nov(?:ember|\.)?|Dec(?:ember|\.)?)[\t ]+(([0-2]?\d)|3[01])([\t ,]+([0-9]{2})?[0-9]{2})?)

|

((([0-2]?\d)|3[01])[\t ]+(Jan(?:uary|\.)?|Feb(?:ruary|\.)?|Mar(?:ch|\.)?|Apr(?:il|\.)?|May(\.)?|Jun(?:e|\.)?|Jul(?:y|\.)?|Aug(?:ust|\.)?|Sep(?:tember|\.)?|Oct(?:ober|\.)?|Nov(?:ember|\.)?|Dec(?:ember|\.)?)([\t ,]+([0-9]{2})?[0-9]{2})?)
```

Note that I added the spacing around the `|` for clarity.

That would prevent a double capture, but consider this text:

```
iPhone11 Mar 19, 24
```

That prioritizes capturing `11 Mar 19`, but `Mar 19, 24` is more valid.

Even you wanted to prioritize the month-day-year format over the other, you could have:

```
On 3 Mar 19, 24 men swam a race
``` 

Here, `3 Mar 19` is more valid than `Mar 19, 24`.

I think using two regexes, each with an optional year, as you have it, is preferable. 

---

However, it does beg the question, do we care about things like below?

```
Mar 2024
```

I think we should make the date optional. To do that, we would need a regex that accepts the month-day-year, month-year, and month-day:

```
(Jan(?:uary|\.)?|Feb(?:ruary|\.)?|Mar(?:ch|\.)?|Apr(?:il|\.)?|May(\.)?|Jun(?:e|\.)?|Jul(?:y|\.)?|Aug(?:ust|\.)?|Sep(?:tember|\.)?|Oct(?:ober|\.)?|Nov(?:ember|\.)?|Dec(?:ember|\.)?)((([\t ]+(([0-2]?\d)|3[01]))?([\t ,]+([0-9]{2})?[0-9]{2}))|([\t ,]+([0-9]{2})?[0-9]{2})|([\t ]+(([0-2]?\d)|3[01])))
```

Note that on regex101 the month-day-year has to come first in the list of options or else it will prioritize just month-day. Similarly, month-year has to come before month-day or it will not capture the full year because it will consider the number a date.

We will also need to update the day-month-year regex to accept day-month by making the year optional:

```
((([0-2]?\d)|3[01])[\t ]+)?(Jan(?:uary|\.)?|Feb(?:ruary|\.)?|Mar(?:ch|\.)?|Apr(?:il|\.)?|May(\.)?|Jun(?:e|\.)?|Jul(?:y|\.)?|Aug(?:ust|\.)?|Sep(?:tember|\.)?|Oct(?:ober|\.)?|Nov(?:ember|\.)?|Dec(?:ember|\.)?)([\t ,]+([0-9]{2})?[0-9]{2})?
```

We don't want to update this regex to accept month-year since the previous one already does that.
</blockquote></details>

this is unfortunately a very complicated problem, and I think trying to perfect it is not worth our time. I tried using your suggestions above, but ran into additional issues with other edge cases. I updated the expressions and tests to what I believe is a reasonable solution. Having the substring triggers is annoying, but given that we provide the offsets for these triggers it allows consumers of the data to make their own decisions on how to handle them.
___
*[`cpp/KeywordTagging/test/test_keyword_tagging.cpp` line 116 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NuPdeEaDmLYmKiyNliO:-NvXOs-YA-yAyJsL0Rzi:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/eb573c590b5891ce827c05b3d33b69d6eb829523/cpp/KeywordTagging/test/test_keyword_tagging.cpp#L116)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

You want `TEXT <TAG> TRIGGER WORDS OFFSET`, not `LOCATION`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-19 00:36 UTC, jrobble commented
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 150 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NvngMDo2fdCuu9v8uoE:-NvngMDo2fdCuu9v8uoF:b-k63naq) ([raw file](https://github.com/openmpf/openmpf-components/blob/daecf930dc0f473cc4f9f73010baf83977fe7b5a/cpp/KeywordTagging/plugin-files/config/text-tags.json#L150)):*
> ```JSON
> 			{"pattern": "(?<![\\-0-9])([0-9]{2}|[0-9]{4})(\\/|-|\\.| )(1[0-2]|0?[1-9])\\2(3[01]|[12][0-9]|0?[1-9])(?![\\-0-9])"},
> 			{"pattern": "(Jan(?:uary|\\.)?|Feb(?:ruary|\\.)?|Mar(?:ch|\\.)?|Apr(?:il|\\.)?|May(\\.)?|Jun(?:e|\\.)?|Jul(?:y|\\.)?|Aug(?:ust|\\.)?|Sep(?:tember|t\\.|t|\\.)?|Oct(?:ober|\\.)?|Nov(?:ember|\\.)?|Dec(?:ember|\\.)?)[\\t ,]+(3[01]|([0-2]?\\d))([\\t ,]*(st|nd|rd|th){1})?([\\t ,]+([0-9]{2})?[0-9]{2})?(?!\\d)"},
> 			{"pattern": "((3[01]|([0-2]?\\d))([\\t ,]*(:?st|nd|rd|th|))?[\\t ,]+)?(Jan(?:uary|\\.)?|Feb(?:ruary|\\.)?|Mar(?:ch|\\.)?|Apr(?:il|\\.)?|May(\\.)?|Jun(?:e|\\.)?|Jul(?:y|\\.)?|Aug(?:ust|\\.)?|Sep(?:tember|t\\.|t|\\.)?|Oct(?:ober|\\.)?|Nov(?:ember|\\.)?|Dec(?:ember|\\.)?)([\\t ,]+(([0-9]{2})?([0-9]{2})))?"}
> ```

Providing `Jan 5 2023` will capture just `Jan`. I don't think we want all of this to be optional:

```
((3[01]|([0-2]?\\d))([\\t ,]*(:?st|nd|rd|th|))?[\\t ,]+)?
```

We want the leading date required. For example "5 Jan 2023" would require "5" in front of "Jan".

Right now the regex makes the leading date and trailing year optional, leaving only the month required.

Consider using this to make the date required:

```
(3[01]|([0-2]?\d))[\t ,]*(:?st|nd|rd|th|)?[\t ,]+(Jan(?:uary|\.)?|Feb(?:ruary|\.)?|Mar(?:ch|\.)?|Apr(?:il|\.)?|May(\.)?|Jun(?:e|\.)?|Jul(?:y|\.)?|Aug(?:ust|\.)?|Sep(?:tember|t\.|t|\.)?|Oct(?:ober|\.)?|Nov(?:ember|\.)?|Dec(?:ember|\.)?)([\t ,]+(([0-9]{2})?([0-9]{2})))?
```

If we use DMY version I provided above with the MDY regex you recently updated then we will not capture things like `Jan 2024`. The regex I previously proposed accounted for that:

```
(Jan(?:uary|\.)?|Feb(?:ruary|\.)?|Mar(?:ch|\.)?|Apr(?:il|\.)?|May(\.)?|Jun(?:e|\.)?|Jul(?:y|\.)?|Aug(?:ust|\.)?|Sep(?:tember|\.)?|Oct(?:ober|\.)?|Nov(?:ember|\.)?|Dec(?:ember|\.)?)((([\t ]+(([0-2]?\d)|3[01]))?([\t ,]+([0-9]{2})?[0-9]{2}))|([\t ,]+([0-9]{2})?[0-9]{2})|([\t ]+(([0-2]?\d)|3[01])))
```

The reason we can't just update your MDY to make the D optional is because the Y is already optional, meaning it will only capture M.


<!-- Sent from Reviewable.io -->

2024-04-19 15:11 UTC, fpc0002 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/355)* status: 1 of 3 files reviewed, 12 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 150 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NvngMDo2fdCuu9v8uoE:-NvqQ6Ux-TROVV6IYxB7:b49jp81) ([raw file](https://github.com/openmpf/openmpf-components/blob/daecf930dc0f473cc4f9f73010baf83977fe7b5a/cpp/KeywordTagging/plugin-files/config/text-tags.json#L150)):*
> Providing `Jan 5 2023` will capture just `Jan`. I don't think we want all of this to be optional:

Ok, we can require the day in front. Was wondering if we wanted to capture just months, but I can see how that might be a bit excessive.

> If we use DMY version I provided above with the MDY regex you recently updated then we will not capture things like `Jan 2024`. The regex I previously proposed accounted for that:

I believe the reason I didn't want to do this was because it was resulting in multiple matches for things like `5 JAN 2023` which returns both `5 JAN 2023` and `JAN 2023`. - but I'm not sure we can do anything about that.

Let me know how you want me to proceed. The update DMY I am working with is below:

`(Jan(?:uary|\\.)?|Feb(?:ruary|\\.)?|Mar(?:ch|\\.)?|Apr(?:il|\\.)?|May(\\.)?|Jun(?:e|\\.)?|Jul(?:y|\\.)?|Aug(?:ust|\\.)?|Sep(?:tember|t\\.|t|\\.)?|Oct(?:ober|\\.)?|Nov(?:ember|\\.)?|Dec(?:ember|\\.)?)(((\[\\t ,\]+(3\[01\]|(\[0-2\]?\\d))(\[\\t ,\]\*(st|nd|rd|th))?)?(\[\\t ,\]+(\[0-9\]{2})?\[0-9\]{2}))|(\[\\t ,\]+(\[0-9\]{2})?\[0-9\]{2})|(\[\\t ,\]+(3\[01\]|(\[0-2\]?\\d)(\[\\t ,\]\*(st|nd|rd|th))?)))`


<!-- Sent from Reviewable.io -->

2024-04-19 21:04 UTC, jrobble commented
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 150 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NvngMDo2fdCuu9v8uoE:-Nvs8T5S1WqfRRIx8IrB:b-k2v68w) ([raw file](https://github.com/openmpf/openmpf-components/blob/daecf930dc0f473cc4f9f73010baf83977fe7b5a/cpp/KeywordTagging/plugin-files/config/text-tags.json#L150)):*
<details><summary><i>Previously, fpc0002 wrote…</i></summary><blockquote>

> Providing `Jan 5 2023` will capture just `Jan`. I don't think we want all of this to be optional:

Ok, we can require the day in front. Was wondering if we wanted to capture just months, but I can see how that might be a bit excessive.

> If we use DMY version I provided above with the MDY regex you recently updated then we will not capture things like `Jan 2024`. The regex I previously proposed accounted for that:

I believe the reason I didn't want to do this was because it was resulting in multiple matches for things like `5 JAN 2023` which returns both `5 JAN 2023` and `JAN 2023`. - but I'm not sure we can do anything about that.

Let me know how you want me to proceed. The update DMY I am working with is below:

`(Jan(?:uary|\\.)?|Feb(?:ruary|\\.)?|Mar(?:ch|\\.)?|Apr(?:il|\\.)?|May(\\.)?|Jun(?:e|\\.)?|Jul(?:y|\\.)?|Aug(?:ust|\\.)?|Sep(?:tember|t\\.|t|\\.)?|Oct(?:ober|\\.)?|Nov(?:ember|\\.)?|Dec(?:ember|\\.)?)(((\[\\t ,\]+(3\[01\]|(\[0-2\]?\\d))(\[\\t ,\]\*(st|nd|rd|th))?)?(\[\\t ,\]+(\[0-9\]{2})?\[0-9\]{2}))|(\[\\t ,\]+(\[0-9\]{2})?\[0-9\]{2})|(\[\\t ,\]+(3\[01\]|(\[0-2\]?\\d)(\[\\t ,\]\*(st|nd|rd|th))?)))`
</blockquote></details>

Looks good. So for clarity, these are the two I'm using in regex101.

```
(3[01]|([0-2]?\d))[\t ,]*(:?st|nd|rd|th|)?[\t ,]+(Jan(?:uary|\.)?|Feb(?:ruary|\.)?|Mar(?:ch|\.)?|Apr(?:il|\.)?|May(\.)?|Jun(?:e|\.)?|Jul(?:y|\.)?|Aug(?:ust|\.)?|Sep(?:tember|t\.|t|\.)?|Oct(?:ober|\.)?|Nov(?:ember|\.)?|Dec(?:ember|\.)?)([\t ,]+(([0-9]{2})?([0-9]{2})))?
```

```
(Jan(?:uary|\.)?|Feb(?:ruary|\.)?|Mar(?:ch|\.)?|Apr(?:il|\.)?|May(\.)?|Jun(?:e|\.)?|Jul(?:y|\.)?|Aug(?:ust|\.)?|Sep(?:tember|t\.|t|\.)?|Oct(?:ober|\.)?|Nov(?:ember|\.)?|Dec(?:ember|\.)?)((([\t ,]+(3[01]|([0-2]?\d))([\t ,]*(st|nd|rd|th))?)?([\t ,]+([0-9]{2})?[0-9]{2}))|([\t ,]+([0-9]{2})?[0-9]{2})|([\t ,]+(3[01]|([0-2]?\d)([\t ,]*(st|nd|rd|th))?)))
```

The second regex is what you just shared, but I removed some of the `\`. Specifically, you have slashes in front of `\[`, `\]`, and `\*`. Slashes aren't used in that way to escape those things for any of the other regexes we have in the JSON file currently. Not sure why you added them here.

The first regex is the same as what I shared in my previous comment where I took your version and made the date required.


<!-- Sent from Reviewable.io -->

2024-04-29 16:36 UTC, fpc0002 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/355)* status: 1 of 3 files reviewed, 12 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 150 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NvngMDo2fdCuu9v8uoE:-Nweho7KDxbwU8ZUVgxK:btrw1ag) ([raw file](https://github.com/openmpf/openmpf-components/blob/daecf930dc0f473cc4f9f73010baf83977fe7b5a/cpp/KeywordTagging/plugin-files/config/text-tags.json#L150)):*
<details><summary><i>Previously, fpc0002 wrote…</i></summary><blockquote>

I think it might have been a formatting issue with reviewable - I fixed it below I think. If that looks good I'll update the tests and push the changes.
</blockquote></details>

I pushed up new changes for these expressions and tests


<!-- Sent from Reviewable.io -->

2024-05-06 16:31 UTC, fpc0002 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/355)* status: 1 of 3 files reviewed, 14 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 109 at r6](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NwobD-B44EKkQzrbzTL:-NxDQaJ-0byDaaghGS41:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/0924c8f02c158495e3e78992d36dd359f1b66302/cpp/KeywordTagging/plugin-files/config/text-tags.json#L109)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I believe that `\\\\` is the same as `\\x5C`. Please confirm. If so, please replace the last instance of `\\\\` with `\\x5C` for consistency.
</blockquote></details>

Done.
___
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 109 at r6](https://reviewable.io/reviews/openmpf/openmpf-components/355#-Nwoc4kP4o7P7R9RHF-Q:-NxDQdIZ0BVw_VaxUZmI:b-6z43jt) ([raw file](https://github.com/openmpf/openmpf-components/blob/0924c8f02c158495e3e78992d36dd359f1b66302/cpp/KeywordTagging/plugin-files/config/text-tags.json#L109)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

At the end of this regex you replaced:

```
\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21-\\x5a\\x53-\\x7f]|\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f
```

With

```
\\w\\d\\t\\r\\f!\"#$&'()*+,./\\\\:;<=>?@\\[\\]^_`{|}~-
```

Is that a subset of what it was before?

----


```
\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21-\\x5a\\x53-\\x7f]|\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f
```

was also near the beginning of the regex, but you did not replace it with the same thing. Why is that?
</blockquote></details>

yes it should be a subset of that. The beginning of the expression was previously more complicated. I removed the path that contained these characters and added some of them to the first groups (as needed)
___
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 109 at r6](https://reviewable.io/reviews/openmpf/openmpf-components/355#-Nwod15m4EwaDVE9bH-L:-NxDTNZMB9pm51lwhtNT:b-4o930l) ([raw file](https://github.com/openmpf/openmpf-components/blob/0924c8f02c158495e3e78992d36dd359f1b66302/cpp/KeywordTagging/plugin-files/config/text-tags.json#L109)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Near the beginning of the regex you have:

```
[a-z0-9\\x5C!#$%&'*+/=?^_`\\{|}~\"-]
```

Why do you have `\\` in front of `{`? The first slash is escaping the second slash so we can represent this in JSON, but the second slash is escaping the `{`. Does that need to be escaped? It wasn't before, and the `}` is not escaped.
</blockquote></details>

I think this was just a typo from when I was messing with things.
___
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 109 at r6](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NwobHTI7DaAxwegbhLW:-NxDjZlJ-JLHl3pTQpwG:b-ehqqfa) ([raw file](https://github.com/openmpf/openmpf-components/blob/0924c8f02c158495e3e78992d36dd359f1b66302/cpp/KeywordTagging/plugin-files/config/text-tags.json#L109)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

You removed non-capturing groups in favor of capturing groups. I'm reading that non-capturing is faster and takes less memory since there's less data captured in the buffer: [https://stackoverflow.com/a/33250820](https://stackoverflow.com/a/33250820)

Please run a test of capturing vs. non-capturing. If capturing is not faster, please revert back to non-capturing.
</blockquote></details>

One some test data I was not seeing any significant difference in speed, so I reverted back to non-capturing.


<!-- Sent from Reviewable.io -->

2024-06-06 19:53 UTC, jrobble requested changes
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/355)* status: all files reviewed, 3 unresolved discussions (waiting on @brosenberg42 and @fpc0002)

___
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 150 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NvngMDo2fdCuu9v8uoE:-NzirFB93_FKZFvW1Gh0:b-7q18bs) ([raw file](https://github.com/openmpf/openmpf-components/blob/daecf930dc0f473cc4f9f73010baf83977fe7b5a/cpp/KeywordTagging/plugin-files/config/text-tags.json#L150)):*
I ran some tests using your most recent component code. These were valid:

```
Jan 202022
Jan202022
Jan 20 2022nd
Jan 20 2067th
Jan99
```

These were not:

```
Jan9987
202022
```

What's up with allowing endings like "nd" and "th" after the year?

I'm on board with no delimiter between the month and day. Same goes for between month and year. 

At first I found no delimiter between day and year confusing, although I can understand your desire to be robust to whitespace issues. If we say no delimiter is acceptable then `Jan9987` should be valid. Instead, the code matched on `Jan998`.

We can modify the order of clauses in the regex like this makes to make it work:

```
{"pattern": "(Jan(?:uary|\\.)?|Feb(?:ruary|\\.)?|Mar(?:ch|\\.)?|Apr(?:il|\\.)?|May(\\.)?|Jun(?:e|\\.)?|Jul(?:y|\\.)?|Aug(?:ust|\\.)?|Sep(?:tember|t\\.|t|\\.)?|Oct(?:ober|\\.)?|Nov(?:ember|\\.)?|Dec(?:ember|\\.)?)((([\\t ,]*([0-9]{2})?[0-9]{2})|([\\t ,]*(3[01]|([0-2]?\\d))([\\t ,]*(st|nd|rd|th))?)?([\\t ,]*([0-9]{2})?[0-9]{2})([\\t ,]*(st|nd|rd|th))?)|([\\t ,]*(3[01]|([0-2]?\\d)([\\t ,]*(st|nd|rd|th))?)))"},
```

But then it fails on this:

```
22│ │ │ Expected equality of these values:
$22│ │ │   expected_trigger_words
$22│ │ │     Which is: "11 Mar 19; Mar 19, 24"
$22│ │ │   props["TEXT " + expected_tag + " TRIGGER WORDS"]
$22│ │ │     Which is: "11 Mar 19; Mar 19"
```

I don't think there's an easy way to support both cases. My preference would be to require a delimiter between day and year. This would require changing one of your `*` back to `+`:

```
{"pattern": "(Jan(?:uary|\\.)?|Feb(?:ruary|\\.)?|Mar(?:ch|\\.)?|Apr(?:il|\\.)?|May(\\.)?|Jun(?:e|\\.)?|Jul(?:y|\\.)?|Aug(?:ust|\\.)?|Sep(?:tember|t\\.|t|\\.)?|Oct(?:ober|\\.)?|Nov(?:ember|\\.)?|Dec(?:ember|\\.)?)((([\\t ,]*(3[01]|([0-2]?\\d))([\\t ,]*(st|nd|rd|th))?)?([\\t ,]+([0-9]{2})?[0-9]{2})([\\t ,]*(st|nd|rd|th))?)|([\\t ,]*([0-9]{2})?[0-9]{2})|([\\t ,]*(3[01]|([0-2]?\\d)([\\t ,]*(st|nd|rd|th))?)))"},
```

That now matches on `Jan9987`, as expected, and for `Jan99872` matches on the `Jan9987` substring, as expected. Please add those as unit tests.

---

> What's up with allowing endings like "nd" and "th" after the year?

Removing those:

```
{"pattern": "(Jan(?:uary|\\.)?|Feb(?:ruary|\\.)?|Mar(?:ch|\\.)?|Apr(?:il|\\.)?|May(\\.)?|Jun(?:e|\\.)?|Jul(?:y|\\.)?|Aug(?:ust|\\.)?|Sep(?:tember|t\\.|t|\\.)?|Oct(?:ober|\\.)?|Nov(?:ember|\\.)?|Dec(?:ember|\\.)?)((([\\t ,]*(3[01]|([0-2]?\\d))([\\t ,]*(st|nd|rd|th))?)?([\\t ,]+([0-9]{2})?[0-9]{2}))|([\\t ,]*([0-9]{2})?[0-9]{2})|([\\t ,]*(3[01]|([0-2]?\\d)([\\t ,]*(st|nd|rd|th))?)))"},
```

It now fails on:

```
$28│ │ Failure @ ./test/test_keyword_tagging.cpp:116
$28│ │ │ Expected equality of these values:
$28│ │ │   expected_trigger_words
$28│ │ │     Which is: "September 20th"
$28│ │ │   props["TEXT " + expected_tag + " TRIGGER WORDS"]
$28│ │ │     Which is: "September 20"
```

I messed around with the ordering of clauses to try to address that in ended up making things worse:

```
31│ │ Failure @ ./test/test_keyword_tagging.cpp:116
$31│ │ │ Expected equality of these values:
$31│ │ │   expected_trigger_words
$31│ │ │     Which is: "Jan9987"
$31│ │ │   props["TEXT " + expected_tag + " TRIGGER WORDS"]
$31│ │ │     Which is: "Jan9"
```

Keeping the "nd" and "th" endings after the year is the lesser of the two evils, so let's go with that.
___
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 47 at r7](https://reviewable.io/reviews/openmpf/openmpf-components/355#-Nzibs4M1hZApam-J_yW:-Nzibs4M1hZApam-J_yX:b-swqhm7) ([raw file](https://github.com/openmpf/openmpf-components/blob/9158fad4b6b9dfef416fde85b2271a79cc7edeb4/cpp/KeywordTagging/plugin-files/config/text-tags.json#L47)):*
> ```JSON
> 			{"pattern": "дин"},
> 			{"pattern": ".د.ج"},
> 			{"pattern": ".د.ب"},
> ```

As discussed elsewhere, please remove the leading and trailing periods from the Arabic currency symbols.


<!-- Sent from Reviewable.io -->

2024-06-07 21:40 UTC, fpc0002 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/355)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 150 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/355#-NvngMDo2fdCuu9v8uoE:-NzoX3R68ptBDIgwXqty:bb6un1j) ([raw file](https://github.com/openmpf/openmpf-components/blob/daecf930dc0f473cc4f9f73010baf83977fe7b5a/cpp/KeywordTagging/plugin-files/config/text-tags.json#L150)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I ran some tests using your most recent component code. These were valid:

```
Jan 202022
Jan202022
Jan 20 2022nd
Jan 20 2067th
Jan99
```

These were not:

```
Jan9987
202022
```

What's up with allowing endings like "nd" and "th" after the year?

I'm on board with no delimiter between the month and day. Same goes for between month and year. 

At first I found no delimiter between day and year confusing, although I can understand your desire to be robust to whitespace issues. If we say no delimiter is acceptable then `Jan9987` should be valid. Instead, the code matched on `Jan998`.

We can modify the order of clauses in the regex like this makes to make it work:

```
{"pattern": "(Jan(?:uary|\\.)?|Feb(?:ruary|\\.)?|Mar(?:ch|\\.)?|Apr(?:il|\\.)?|May(\\.)?|Jun(?:e|\\.)?|Jul(?:y|\\.)?|Aug(?:ust|\\.)?|Sep(?:tember|t\\.|t|\\.)?|Oct(?:ober|\\.)?|Nov(?:ember|\\.)?|Dec(?:ember|\\.)?)((([\\t ,]*([0-9]{2})?[0-9]{2})|([\\t ,]*(3[01]|([0-2]?\\d))([\\t ,]*(st|nd|rd|th))?)?([\\t ,]*([0-9]{2})?[0-9]{2})([\\t ,]*(st|nd|rd|th))?)|([\\t ,]*(3[01]|([0-2]?\\d)([\\t ,]*(st|nd|rd|th))?)))"},
```

But then it fails on this:

```
22│ │ │ Expected equality of these values:
$22│ │ │   expected_trigger_words
$22│ │ │     Which is: "11 Mar 19; Mar 19, 24"
$22│ │ │   props["TEXT " + expected_tag + " TRIGGER WORDS"]
$22│ │ │     Which is: "11 Mar 19; Mar 19"
```

I don't think there's an easy way to support both cases. My preference would be to require a delimiter between day and year. This would require changing one of your `*` back to `+`:

```
{"pattern": "(Jan(?:uary|\\.)?|Feb(?:ruary|\\.)?|Mar(?:ch|\\.)?|Apr(?:il|\\.)?|May(\\.)?|Jun(?:e|\\.)?|Jul(?:y|\\.)?|Aug(?:ust|\\.)?|Sep(?:tember|t\\.|t|\\.)?|Oct(?:ober|\\.)?|Nov(?:ember|\\.)?|Dec(?:ember|\\.)?)((([\\t ,]*(3[01]|([0-2]?\\d))([\\t ,]*(st|nd|rd|th))?)?([\\t ,]+([0-9]{2})?[0-9]{2})([\\t ,]*(st|nd|rd|th))?)|([\\t ,]*([0-9]{2})?[0-9]{2})|([\\t ,]*(3[01]|([0-2]?\\d)([\\t ,]*(st|nd|rd|th))?)))"},
```

That now matches on `Jan9987`, as expected, and for `Jan99872` matches on the `Jan9987` substring, as expected. Please add those as unit tests.

---

> What's up with allowing endings like "nd" and "th" after the year?

Removing those:

```
{"pattern": "(Jan(?:uary|\\.)?|Feb(?:ruary|\\.)?|Mar(?:ch|\\.)?|Apr(?:il|\\.)?|May(\\.)?|Jun(?:e|\\.)?|Jul(?:y|\\.)?|Aug(?:ust|\\.)?|Sep(?:tember|t\\.|t|\\.)?|Oct(?:ober|\\.)?|Nov(?:ember|\\.)?|Dec(?:ember|\\.)?)((([\\t ,]*(3[01]|([0-2]?\\d))([\\t ,]*(st|nd|rd|th))?)?([\\t ,]+([0-9]{2})?[0-9]{2}))|([\\t ,]*([0-9]{2})?[0-9]{2})|([\\t ,]*(3[01]|([0-2]?\\d)([\\t ,]*(st|nd|rd|th))?)))"},
```

It now fails on:

```
$28│ │ Failure @ ./test/test_keyword_tagging.cpp:116
$28│ │ │ Expected equality of these values:
$28│ │ │   expected_trigger_words
$28│ │ │     Which is: "September 20th"
$28│ │ │   props["TEXT " + expected_tag + " TRIGGER WORDS"]
$28│ │ │     Which is: "September 20"
```

I messed around with the ordering of clauses to try to address that in ended up making things worse:

```
31│ │ Failure @ ./test/test_keyword_tagging.cpp:116
$31│ │ │ Expected equality of these values:
$31│ │ │   expected_trigger_words
$31│ │ │     Which is: "Jan9987"
$31│ │ │   props["TEXT " + expected_tag + " TRIGGER WORDS"]
$31│ │ │     Which is: "Jan9"
```

Keeping the "nd" and "th" endings after the year is the lesser of the two evils, so let's go with that.
</blockquote></details>

Done
___
*[`cpp/KeywordTagging/plugin-files/config/text-tags.json` line 47 at r7](https://reviewable.io/reviews/openmpf/openmpf-components/355#-Nzibs4M1hZApam-J_yW:-NzoVsrkEzb-MjCrv17A:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/9158fad4b6b9dfef416fde85b2271a79cc7edeb4/cpp/KeywordTagging/plugin-files/config/text-tags.json#L47)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Also, add the relevant unit test.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-10 16:34 UTC, jrobble requested changes
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/355)* status: all files reviewed, 2 unresolved discussions (waiting on @brosenberg42 and @fpc0002)

___
*[`cpp/KeywordTagging/test/test_keyword_tagging.cpp` line 894 at r8](https://reviewable.io/reviews/openmpf/openmpf-components/355#-O-1zsfoCTWDga2BLNQS:-O-1zsfpBCR_fabUeM2x:bkktvee) ([raw file](https://github.com/openmpf/openmpf-components/blob/fc424ca69749e4dcd81a1446cbdbf9d7d21516ac/cpp/KeywordTagging/test/test_keyword_tagging.cpp#L894)):*
> ```cpp
>     ASSERT_NO_FATAL_FAILURE(assertTextAndTagFound(tagger, "ABC ден 123", "ден", "financial"));
>     ASSERT_NO_FATAL_FAILURE(assertTextAndTagFound(tagger, "123฿123", "฿", "financial"));
>     ASSERT_NO_FATAL_FAILURE(assertTextAndTagFound(tagger, ".د.ج", "د.ج", "financial"));
> ```

Please add the full unit test:

```
رابط التسجيل في منحة 1500 د.ج بالجزائر 2024
```

Just FYI, that translates to:

```
Link to register for the 1500 DZD scholarship in Algeria 2024
```


<!-- Sent from Reviewable.io -->

2024-06-10 18:15 UTC, fpc0002 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/355)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[`cpp/KeywordTagging/test/test_keyword_tagging.cpp` line 894 at r8](https://reviewable.io/reviews/openmpf/openmpf-components/355#-O-1zsfoCTWDga2BLNQS:-O-2M8xH7R84thFCiLvb:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/fc424ca69749e4dcd81a1446cbdbf9d7d21516ac/cpp/KeywordTagging/test/test_keyword_tagging.cpp#L894)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please add the full unit test:

```
رابط التسجيل في منحة 1500 د.ج بالجزائر 2024
```

Just FYI, that translates to:

```
Link to register for the 1500 DZD scholarship in Algeria 2024
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-10 21:17 UTC, jrobble approved these changes
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/355)* status: all files reviewed, 2 unresolved discussions (waiting on @brosenberg42 and @fpc0002)

___
*[`cpp/KeywordTagging/test/test_keyword_tagging.cpp` line 896 at r9](https://reviewable.io/reviews/openmpf/openmpf-components/355#-O-2zfIB1mveN3I_T3en:-O-2zfIB1mveN3I_T3eo:bwqrqf9) ([raw file](https://github.com/openmpf/openmpf-components/blob/966aa195f350480af77da9559b959b5b0df6befe/cpp/KeywordTagging/test/test_keyword_tagging.cpp#L896)):*
> ```cpp
>     ASSERT_NO_FATAL_FAILURE(assertTextAndTagFound(tagger, ".د.ج", "د.ج", "financial"));
>     ASSERT_NO_FATAL_FAILURE(assertTextAndTagFound(tagger, ".د.م", "د.م", "financial"));
>     ASSERT_NO_FATAL_FAILURE(assertTextAndTagFound(tagger, "رابط التسجيل في منحة 1500 د.ج بالجزائر 2024", "د.ج", "financial"));
> ```

How this shows up in Reviewable (GitHub PR UI is similar):

![Reviewable Screenshot 2024-06-10 171052.png](https://files.reviewableusercontent.io/images/reviewable/1039601/l1p74EZP3getFupQm4irTAzN/Reviewable%20Screenshot%202024-06-10%20171052.png)

How this shows up in the raw file on GitHub (VScode is similar):

![Raw Screenshot 2024-06-10 171123.png](https://files.reviewableusercontent.io/images/reviewable/1039601/TemsFEXokL59dHQpaM4Z5MEi/Raw%20Screenshot%202024-06-10%20171123.png)

The latter looks right. The former is strange. At first I was confused since it seemed like you got the method parameters out of order, but yet, somehow, the test was still passing. In the first case ج is dropped completely from the one parameter.

I'm not asking you to do anything. Just pointing out that Reviewable and GitHub render the Arabic text strangely here.


<!-- Sent from Reviewable.io -->

2024-06-12 12:49 UTC, merged