Update Azure Translation character limits. Add NLP TextSplitting Models. Update TextSplitter for input langs.
openmpf/openmpf-components pull request #359
Opened 2024-04-02 19:43 UTC by hhuangMITRE

**Issues:**

- https://github.com/openmpf/openmpf/issues/1771

2024-04-04 04:27 UTC, hhuangMITRE reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/359)* status: 0 of 28 files reviewed, 18 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[`python/AzureTranslation/LICENSE` line 1 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/359#-NubIM1Y2iZevRLcVWvk:-NubIM1Y2iZevRLcVWvl:bmyd2p0) ([raw file](https://github.com/openmpf/openmpf-components/blob/434f1cad172900e75071736defba9b9514262dd9/python/AzureTranslation/LICENSE#L1)):*
> ```
> /*****************************************************************************
> ```

(Jeff, Howard):  I need to add WtP and spaCy to the LICENSE file 
___
*[`python/AzureTranslation/acs_translation_component/acs_translation_component.py` line 430 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/359#-NubJyd82PV5UtH1H2tJ:-NubJyd82PV5UtH1H2tK:b-j6m17n) ([raw file](https://github.com/openmpf/openmpf-components/blob/77bbe50dd5f0d8a1a295617beeaad9398dd44cb8/python/AzureTranslation/acs_translation_component/acs_translation_component.py#L430)):*
> ```Python
> class BreakSentenceClient:
>     """
>     Class to interact with Azure's "/breaksentence" endpoint. It is only used when the text to
> ```

(Old Code, Reviewed by Jeff):

Please remove this

`formerly interacts with Azure's "/breaksentence" endpoint.`

There's no need to mention what the component used to do. It's all there in the git history if we ever want to go back.
___
*[`python/AzureTranslation/acs_translation_component/acs_translation_component.py` line 441 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/359#-NubH2HW3ac3vP2mO2Pd:-NubH2HW3ac3vP2mO2Pe:b-njv0v6) ([raw file](https://github.com/openmpf/openmpf-components/blob/c502b2f5adb58036573dad69e3558ca6b7384a5b/python/AzureTranslation/acs_translation_component/acs_translation_component.py#L441)):*
> ```Python
> 
> 
> class BreakSentenceClient:
> ```


(Jeff) Looking at this:
```
 class BreakSentenceClient:
```
"Client" is no longer accurate as this class no longer interacts with a server. Rename to "SentenceSplitter". Also, rename the "break-sentence" dir to "sentence-splitter". Look for other usages of BreakSentence and update them.
___
*[`python/AzureTranslation/acs_translation_component/acs_translation_component.py` line 468 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/359#-NubHEfD-lAydRZjssBn:-NubHEfD-lAydRZjssBo:b-vfbkh3) ([raw file](https://github.com/openmpf/openmpf-components/blob/c502b2f5adb58036573dad69e3558ca6b7384a5b/python/AzureTranslation/acs_translation_component/acs_translation_component.py#L468)):*
> ```Python
>     def split_input_text(self, text: str, from_lang: Optional[str],
>                          from_lang_confidence: Optional[float]) -> SplitTextResult:
>         """
> ```

(Jeff)  Looking at this:
```
       Breaks up the given text in to chunks that are under TRANSLATION_MAX_CHARS. Each chunk
        will contain one or more complete sentences as reported by the break sentence endpoint.
```
There is no longer a "break sentence endpoint". Please update this comment.
___
*[`python/AzureTranslation/acs_translation_component/acs_translation_component.py` line 496 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/359#-NubHMRbB6p87uejUD_k:-NubHMRbB6p87uejUD_l:b-ay9z73) ([raw file](https://github.com/openmpf/openmpf-components/blob/c502b2f5adb58036573dad69e3558ca6b7384a5b/python/AzureTranslation/acs_translation_component/acs_translation_component.py#L496)):*
> ```Python
>                 self._sentence_model)
> 
>         chunks = list(divided_text_list)
> ```

(Jeff) Looking at this:

```
        log.warning(f'Broke text up in to {len(chunks)} chunks. Each chunk will be sent to '
                    'the translation endpoint.')

        log.info('Grouped sentences into %s chunks.', len(chunks))
```

I don't think you need the warning and the info log statements. Remove the warning.
___
*[`python/AzureTranslation/acs_translation_component/acs_translation_component.py` line 606 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/359#-NubHZJM2Bu6yEeywjVa:-NubHZJM2Bu6yEeywjVb:b-wmhagi) ([raw file](https://github.com/openmpf/openmpf-components/blob/c502b2f5adb58036573dad69e3558ca6b7384a5b/python/AzureTranslation/acs_translation_component/acs_translation_component.py#L606)):*
> ```Python
> class NewLineBehavior:
>     """
>     The Azure translation service treats newlines a separator between sentences. This results in
> ```

(Jeff): “The Azure translation service treats newlines a separator between”

Update to: "treats newlines *as* a separator"
___
*[`python/AzureTranslation/nlp_text_splitter/text_splitter.py` line 64 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/359#-NubFrJxCz7tf3oerIa_:-NubFrJxCz7tf3oerIaa:b-6lv0e0) ([raw file](https://github.com/openmpf/openmpf-components/blob/c502b2f5adb58036573dad69e3558ca6b7384a5b/python/AzureTranslation/nlp_text_splitter/text_splitter.py#L64)):*
> ```Python
>                 self._update_spacy_model(model_name)
>                 self.split = self._split_spacy
>                 log.info(f"Setup up spaCy model: {model_name}")
> ```


Jeff:

Typo in these. Remove "up" from "Setup up":

                log.info(f"Setup up WtP model: {model_name}")
                log.info(f"Setup up spaCy model: {model_name}")
___
*[`python/AzureTranslation/nlp_text_splitter/text_splitter.py` line 99 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/359#-NuWaGTXBWj8euOt7Lrt:-NuWaGTXBWj8euOt7Lru:bj75pza) ([raw file](https://github.com/openmpf/openmpf-components/blob/c502b2f5adb58036573dad69e3558ca6b7384a5b/python/AzureTranslation/nlp_text_splitter/text_splitter.py#L99)):*
> ```Python
>             iso_lang = WtpLanguageSettings.convert_to_iso(lang)
>             if iso_lang:
>                 return self.wtp_model.split(text, lang_code=iso_lang) # type: ignore
> ```

(Jeff) Looking at this code:

```
    def _split_wtp(self, text: str, lang: Optional[str] = None) -> List[str]:
        if lang:
            iso_lang = WTPLanguageSettings.convert_to_iso(lang)
            if iso_lang:
                return self.wtp_model.split(text, lang_code=iso_lang) # type: ignore
        return self.wtp_model.split(text) # type: ignore

```

If iso_lang is returned as None, should we log a warning?
___
*[`python/AzureTranslation/nlp_text_splitter/text_splitter.py` line 100 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/359#-NuWaMc2-2gNVfEOVL_k:-NuWaMc2-2gNVfEOVL_l:b9mtusw) ([raw file](https://github.com/openmpf/openmpf-components/blob/c502b2f5adb58036573dad69e3558ca6b7384a5b/python/AzureTranslation/nlp_text_splitter/text_splitter.py#L100)):*
> ```Python
>             if iso_lang:
>                 return self.wtp_model.split(text, lang_code=iso_lang) # type: ignore
>         return self.wtp_model.split(text) # type: ignore
> ```

Looking at this code:

```
        return self.wtp_model.split(text, lang_code=iso_lang) # type: ignore
        return self.wtp_model.split(text) # type: ignore
```
What do you mean by "type: ignore" ?
___
*[`python/AzureTranslation/nlp_text_splitter/text_splitter.py` line 134 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/359#-NubGaRL4U2Nporv7-5U:-NubGaRL4U2Nporv7-5V:b-9k60h) ([raw file](https://github.com/openmpf/openmpf-components/blob/c502b2f5adb58036573dad69e3558ca6b7384a5b/python/AzureTranslation/nlp_text_splitter/text_splitter.py#L134)):*
> ```Python
>             self.set_text(text)
> 
>     def set_text(self, text: str):
> ```

(Jeff):
I'm trying to make sense of the units for the last line of code shown here:

```
    def set_text(self, text: str):
        self._text = text
        self._text_full_size = self._get_text_size(text)
        chars_per_size = len(text) / self._text_full_size
        self._num_overhead_bytes = self._get_text_size('')

        self._soft_limit = int(self._limit * chars_per_size) - self._num_overhead_bytes
```
<…>
How can we subtract b [...]

2024-04-04 04:39 UTC, hhuangMITRE reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/359)* status: 0 of 28 files reviewed, 18 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[`python/AzureTranslation/nlp_text_splitter/text_splitter.py` line 100 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/359#-NuWaMc2-2gNVfEOVL_k:-NubO1g2AGULDgn82RuN:b-otwivr) ([raw file](https://github.com/openmpf/openmpf-components/blob/c502b2f5adb58036573dad69e3558ca6b7384a5b/python/AzureTranslation/nlp_text_splitter/text_splitter.py#L100)):*
(Brian)
> \# type: ignore

That disables the static type checker for that line. When libraries do not include type annotations, the static type checker infers them. Sometimes it isn't able to correctly determine the exact type so it will say that a function returns something more general than it does to be safe. It is also bad at inferring generics. For `self.wtp_model.split(text)` the inferred return value is:

`List[Unknown] | Generator[List[Unknown], Any, None]`

The actual return value is:

`List[str] | Generator[List[str], Any, None]`

If `WTP.split` were properly annotated it would end up being:

`class WTP: @typing.overload def split(text: str) -> List[str]: ... @typing.overload def split(texts: Iterable[str]) -> Generator[List[str], Any, None]: ...`

We only ever pass a single string to WTP.split, so we know that it will always return a `List[str]`. A slightly better option than the suppression comment is to use:

`def _split_wtp(self, text: str) -> List[str]: return typing.cast(List[str], self.wtp_model.split(text))`

It doesn't matter though because it is only for the static type checker and has no effect at runtime.
___
*[`python/AzureTranslation/nlp_text_splitter/text_splitter.py` line 134 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/359#-NubGaRL4U2Nporv7-5U:-NubMHlzBhZNs3IHdTeP:bi85ka4) ([raw file](https://github.com/openmpf/openmpf-components/blob/c502b2f5adb58036573dad69e3558ca6b7384a5b/python/AzureTranslation/nlp_text_splitter/text_splitter.py#L134)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

(Jeff):
I'm trying to make sense of the units for the last line of code shown here:

```
    def set_text(self, text: str):
        self._text = text
        self._text_full_size = self._get_text_size(text)
        chars_per_size = len(text) / self._text_full_size
        self._num_overhead_bytes = self._get_text_size('')

        self._soft_limit = int(self._limit * chars_per_size) - self._num_overhead_bytes
```
<…>
How can we subtract bytes from chars? Are we assuming one byte per char since we only work with UTF-8?
 
[For this PR] we do this:

```
        actual = list(TextSplitter.split(input_text, # text
            BreakSentenceClient.TRANSLATION_MAX_CHARS, # limit
            BreakSentenceClient.TRANSLATION_MAX_CHARS, # num_boundary_chars
            get_azure_char_count, # _get_text_size() --> For azure, emojis count as 2 chars
            self.wtp_model))
```

So here's what we have:

```
        self._soft_limit = int(self._limit * chars_per_size) - self._num_overhead_bytes
		              = int(AZURE_TOKENS * CHARS/AZURE_TOKENS) - CHARS
                         = int(CHARS) - CHARS
```

Here, `self._num_overhead_bytes` is a bit misleading since we're dealing with a char count, not bytes. Although one UTF-8 char is one byte. Should we rename this to `overhead_size`? 

Related, we use `_get_text_size()` in the following lines:

        self._text_full_size = self._get_text_size(text)
		
        self._num_overhead_bytes = self._get_text_size('')

But the first variable ends with `_size` while the second ends with `_bytes`.
</blockquote></details>

Summarizing follow-up: 

Azure sometimes will treat certain characters as having size 2 (i.e. emojis often are counted as 2 characters).

We agreed that we should rename `num_overhead_bytes` to `overhead_size` for clarity. Then:

`self._num_overhead_bytes = self._get_text_size('')`

Becomes:

`self._overhead_size = self._get_text_size('')`

Which pairs nicely with:

`self._text_full_size = self._get_text_size(text)`
___
*[`python/AzureTranslation/tests/test_acs_translation.py` line 864 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/359#-NubI02SAXZLt3l5IiHG:-NubNweJ5GRoitjzcbGx:b-cnp41d) ([raw file](https://github.com/openmpf/openmpf-components/blob/c502b2f5adb58036573dad69e3558ca6b7384a5b/python/AzureTranslation/tests/test_acs_translation.py#L864)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

What do comments mean above each line here?
```
        # a.bc,
        self.assertEqual('a.bc,', actual[0])
        # bc,d.
        self.assertEqual('d.efg', actual[1])
        # efg,h
        self.assertEqual(',hij ', actual[2])
        # hij k
        self.assertEqual('kl\n\n', actual[3])
        # kl\n\nm
        self.assertEqual('mnopq', actual[4])
        # mnopq
        self.assertEqual('rs.tu', actual[5])
```
I can understand "# a.bc," since that is the first 5 chars the splitter is working on; however, I don't understand "# bc,d.". It wouldn't go back and look at "bc," again since it already made that part of the first split, right?

You reuse the same line comments for the spaCy test right after WtP one.
</blockquote></details>

(Brian)

 > What do comments mean above each line here? # a.bc,

In the original test, the comments showed the input to the sentence break guesser. The test is setup so that the break sentence endpoint accepts only up to 5 characters, so the comments always contain 5 characters. 

In the original test, I check that the sentence break guesser decided that the first sentence was "a." because it should favor breaking at the sentence ending punctuation. 

The updated test in the PR essentially verifies that sentence splitting is NOT working because it always outputs the 5 character string that is received as input.


<!-- Sent from Reviewable.io -->

2024-04-04 05:27 UTC, hhuangMITRE reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/359)* status: 0 of 28 files reviewed, 18 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[`python/AzureTranslation/LICENSE` line 1 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/359#-NubIM1Y2iZevRLcVWvk:-NubOuRK3zaLfz6Ru4Qg:bsps0nh) ([raw file](https://github.com/openmpf/openmpf-components/blob/434f1cad172900e75071736defba9b9514262dd9/python/AzureTranslation/LICENSE#L1)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

(Jeff, Howard):  I need to add WtP and spaCy to the LICENSE file
</blockquote></details>

Made the requested change, thanks!
___
*[`python/AzureTranslation/acs_translation_component/acs_translation_component.py` line 430 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/359#-NubJyd82PV5UtH1H2tJ:-NubPD7j6Vo3RIgFZScp:b-begipp) ([raw file](https://github.com/openmpf/openmpf-components/blob/77bbe50dd5f0d8a1a295617beeaad9398dd44cb8/python/AzureTranslation/acs_translation_component/acs_translation_component.py#L430)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

(Old Code, Reviewed by Jeff):

Please remove this

`formerly interacts with Azure's "/breaksentence" endpoint.`

There's no need to mention what the component used to do. It's all there in the git history if we ever want to go back.
</blockquote></details>

Changes made, thank you!
___
*[`python/AzureTranslation/acs_translation_component/acs_translation_component.py` line 496 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/359#-NubHMRbB6p87uejUD_k:-NubPMnM2jMvJnJ6kT2h:b8bdh4n) ([raw file](https://github.com/openmpf/openmpf-components/blob/c502b2f5adb58036573dad69e3558ca6b7384a5b/python/AzureTranslation/acs_translation_component/acs_translation_component.py#L496)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

(Jeff) Looking at this:

```
        log.warning(f'Broke text up in to {len(chunks)} chunks. Each chunk will be sent to '
                    'the translation endpoint.')

        log.info('Grouped sentences into %s chunks.', len(chunks))
```

I don't think you need the warning and the info log statements. Remove the warning.
</blockquote></details>

Warning removed.
___
*[`python/AzureTranslation/acs_translation_component/acs_translation_component.py` line 606 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/359#-NubHZJM2Bu6yEeywjVa:-NubPOptC2QG01Lmygid:bw8ysw8) ([raw file](https://github.com/openmpf/openmpf-components/blob/c502b2f5adb58036573dad69e3558ca6b7384a5b/python/AzureTranslation/acs_translation_component/acs_translation_component.py#L606)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

(Jeff): “The Azure translation service treats newlines a separator between”

Update to: "treats newlines *as* a separator"
</blockquote></details>

Fixed, thank you.
___
*[`python/AzureTranslation/nlp_text_splitter/text_splitter.py` line 64 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/359#-NubFrJxCz7tf3oerIa_:-NubPTQZ6540RI8-zLuW:bj3eoea) ([raw file](https://github.com/openmpf/openmpf-components/blob/c502b2f5adb58036573dad69e3558ca6b7384a5b/python/AzureTranslation/nlp_text_splitter/text_splitter.py#L64)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

Jeff:

Typo in these. Remove "up" from "Setup up":

                log.info(f"Setup up WtP model: {model_name}")
                log.info(f"Setup up spaCy model: {model_name}")
</blockquote></details>

Fixed, thanks.
___
*[`python/AzureTranslation/nlp_text_splitter/text_splitter.py` line 99 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/359#-NuWaGTXBWj8euOt7Lrt:-NubPayEBZWhZVeVlLGy:b-wbuy3l) ([raw file](https://github.com/openmpf/openmpf-components/blob/c502b2f5adb58036573dad69e3558ca6b7384a5b/python/AzureTranslation/nlp_text_splitter/text_splitter.py#L99)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

(Jeff) Looking at this code:

```
    def _split_wtp(self, text: str, lang: Optional[str] = None) -> List[str]:
        if lang:
            iso_lang = WTPLanguageSettings.convert_to_iso(lang)
            if iso_lang:
                return self.wtp_model.split(text, lang_code=iso_lang) # type: ignore
        return self.wtp_model.split(text) # type: ignore

```

If iso_lang is returned as None, should we log a warning?
</blockquote></details>

Added the log.warning below, also asked users to consider spaCy's model if WtP is not working well. 
___
*[`python/AzureTranslation/nlp_text_splitter/text_splitter.py` line 100 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/359#-NuWaMc2-2gNVfEOVL_k:-NubQutN94SCSPWEov_p:bisi0w) ([raw file](https://github.com/openmpf/openmpf-components/blob/c502b2f5adb58036573dad69e3558ca6b7384a5b/python/AzureTranslation/nlp_text_splitter/text_splitter.py#L100)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

(Brian)
> \# type: ignore

That disables the static type checker for that line. When libraries do not include type annotations, the static type checker infers them. Sometimes it isn't able to correctly determine the exact type so it will say that a function returns something more general than it does to be safe. It is also bad at inferring generics. For `self.wtp_model.split(text)` the inferred return value is:

`List[Unknown] | Generator[List[Unknown], Any, None]`

The actual return value is:

`List[str] | Generator[List[str], Any, None]`

If `WTP.split` were properly annotated it would end up being:

`class WTP: @typing.overload def split(text: str) -> List[str]: ... @typing.overload def split(texts: Iterable[str]) -> Generator[List[str], Any, None]: ...`

We only ever pass a single string to WTP.split, so we know that it will always return a `List[str]`. A slightly better option than the suppression comment is to use:

`def _split_wtp(self, text: str) -> List[str]: return typing.cast(List[str], self.wtp_model.split(text))`

It doesn't matter though because it is only for the static type checker and has no effect at runtime.
</blockquote></details>

Thanks Brian! 

In that case, I think it's best to leave out the `type: ignore` comment, I feel that the ideal solution would be for `WTP.split` to have proper annotation. 

As our changes have no effect at runtime, I'm leaning towards keeping`self.wtp_model.split(text)` as is, but I can also add in the suppression comment if that's preferred. 
___
*[`python/AzureTranslation/nlp_text_splitter/text_splitter.py` line 134 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/359#-NubGaRL4U2Nporv7-5U:-NubSl9lAQr7EVcExMHL:b-1wf0n5) ([raw file](https://github.com/openmpf/openmpf-components/blob/c502b2f5adb58036573dad69e3558ca6b7384a5b/python/AzureTranslation/nlp_text_splitter/text_splitter.py#L134)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

Summarizing follow-up: 

Azure sometimes will treat certain characters as having size 2 (i.e. emojis often are counted as 2 characters).

We agreed that we should rename `num_overhead_bytes` to `overhead_size` for clarity. Then:

`self._num_overhead_bytes = self._get_text_size('')`

Becomes:

`self._overhead_size = self._get_text_size('')`

Which pairs nicely with:

`self._text_full_size = self._get_text_size(text)`
</blockquote></details>

Changes make, thanks everyone for following up on this!
___
*[`python/AzureTranslation/nlp_text_splitter/text_splitter.py` line 145 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/359#-NubGs6VEFDx8Bl03LSd:-NubSsfz6A2Mic0rp7h9:b-40mpxj) ([raw file](https://github.com/openmpf/openmpf-components/blob/c502b2f5adb58036573dad69e3558ca6b7384a5b/python/AzureTranslation/nlp_ [...]

2024-04-09 18:29 UTC, jrobble requested changes
> Reviewed 10 of 20 files at r1, 9 of 14 files at r3.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/359)* status: 19 of 28 files reviewed, 9 unresolved discussions (waiting on @brosenberg42 and @hhuangMITRE)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf-components/359#-Nv36VE97A7ECNaP9fEt:-Nv36VE97A7ECNaP9fEu:bviif3g) (no related file):*
Please merge develop into this so that it includes your hotfix.

___
___
*[`python/AzureTranslation/README.md` line 65 at r5](https://reviewable.io/reviews/openmpf/openmpf-components/359#-Nv36QxO3_NZrpNlZGB5:-Nv36QxO3_NZrpNlZGB6:bxibvor) ([raw file](https://github.com/openmpf/openmpf-components/blob/4c6fd7adc404745d8ec2b0808267b42e63e860ae/python/AzureTranslation/README.md#L65)):*
> ```Markdown
> 
> 
> # Text Splitter Job Properties
> ```

I pushed an update to improve the formatting of this file.
___
*[`python/AzureTranslation/README.md` line 74 at r5](https://reviewable.io/reviews/openmpf/openmpf-components/359#-Nv35kvS7qkSDoU9Ivjt:-Nv35kvS7qkSDoU9Ivju:b5jqxao) ([raw file](https://github.com/openmpf/openmpf-components/blob/4c6fd7adc404745d8ec2b0808267b42e63e860ae/python/AzureTranslation/README.md#L74)):*
> ```Markdown
> 
> WtP models are trained to split up multilingual text by sentence without the need of an
> input language tag. The disadvantage is that the most accurate WtP models will need ~3.5
> ```

You mention GPU models here and in the description of `SENTENCE_MODEL`, but there's no way to use them with this component since `"cpu"` is hard-coded. This is confusing. Consider exposing a property to use GPU or CPU, but default to CPU.
___
*[`python/AzureTranslation/nlp_text_splitter/text_splitter.py` line 100 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/359#-NuWaMc2-2gNVfEOVL_k:-Nv26ysE3PJdFQsavCGh:bkp1a5o) ([raw file](https://github.com/openmpf/openmpf-components/blob/c502b2f5adb58036573dad69e3558ca6b7384a5b/python/AzureTranslation/nlp_text_splitter/text_splitter.py#L100)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

Thanks Brian! 

In that case, I think it's best to leave out the `type: ignore` comment, I feel that the ideal solution would be for `WTP.split` to have proper annotation. 

As our changes have no effect at runtime, I'm leaning towards keeping`self.wtp_model.split(text)` as is, but I can also add in the suppression comment if that's preferred.
</blockquote></details>

I don't have a strong preference either way. Now that I know why those comments are there I'm fine with leaving them if it helps prevent the static type checker from reporting non-issues. It's probably not worth modifying our code much to make the type checker happy.
___
*[`python/AzureTranslation/nlp_text_splitter/text_splitter.py` line 101 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/359#-Nv25KOj2J8CKxH00wVk:-Nv25KOk7xQimCW016UF:bbbn40o) ([raw file](https://github.com/openmpf/openmpf-components/blob/a74b91916b300b1593f7bf1c2604606d86b29bff/python/AzureTranslation/nlp_text_splitter/text_splitter.py#L101)):*
> ```Python
>                 return self.wtp_model.split(text, lang_code=iso_lang)
>             else:
>                 log.warning(f"Warning: Language {lang} was not used to train WtP model."
> ```

Let's rephrase this as:

```python
"Language {lang} was not used to train WtP model. "
"If text splitting is not working well with WtP, "
"consider trying spaCy's sentence detection model."
```

You don't need to include "Warning: " since the line will be logged using the warning level. I added a space after the first period. Also, let's not get too specific about how to use spaCy. That may change in the future.
___
*[`python/AzureTranslation/nlp_text_splitter/text_splitter.py` line 143 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/359#-Nv27qBH-33u6yXqxQxq:-Nv27qBH-33u6yXqxQxr:bh36vcg) ([raw file](https://github.com/openmpf/openmpf-components/blob/a74b91916b300b1593f7bf1c2604606d86b29bff/python/AzureTranslation/nlp_text_splitter/text_splitter.py#L143)):*
> ```Python
>         self._text_full_size = self._get_text_size(text)
>         chars_per_size = len(text) / self._text_full_size
>         self._overhead_size = self._get_text_size('')
> ```

Note that changes to `nlp_text_splitter` also need to be applied to other components that use the text splitter.
___
*[`python/AzureTranslation/tests/test_acs_translation.py` line 618 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/359#-Nv2dP128UmOOjYGdvfl:-Nv2dP128UmOOjYGdvfm:boap3vm) ([raw file](https://github.com/openmpf/openmpf-components/blob/a74b91916b300b1593f7bf1c2604606d86b29bff/python/AzureTranslation/tests/test_acs_translation.py#L618)):*
> ```Python
>         self.assertEqual(sum(expected_chunk_lengths), len(text))
> 
>         # WtP will split by newlines, so some of the chunks
> ```

It also doesn't seem to care about the wide period character.
___
*[`python/AzureTranslation/tests/test_acs_translation.py` line 855 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/359#-Nv2VJrID6YxDoIL7ACG:-Nv2VJrID6YxDoIL7ACH:b-nqp2vs) ([raw file](https://github.com/openmpf/openmpf-components/blob/a74b91916b300b1593f7bf1c2604606d86b29bff/python/AzureTranslation/tests/test_acs_translation.py#L855)):*
> ```Python
> 
> 
>     def test_guess_split_edge_cases(self):
> ```

Let's move this after `test_guess_split_simple_sentence` and `test_split_sentence_end_punctuation` since those are simpler tests.


<!-- Sent from Reviewable.io -->

2024-04-09 18:30 UTC, jrobble requested changes
> Reviewed 2 of 20 files at r1, 2 of 3 files at r2, 2 of 14 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/359)* status: all files reviewed, 10 unresolved discussions (waiting on @brosenberg42 and @hhuangMITRE)

___
*[`python/AzureTranslation/README.md` line 77 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/359#-Nv3050b4qZpxG-8CsVx:-Nv3050d2GRXsDI4CNWw:b-wjtg6j) ([raw file](https://github.com/openmpf/openmpf-components/blob/a74b91916b300b1593f7bf1c2604606d86b29bff/python/AzureTranslation/README.md#L77)):*
> ```Markdown
>   Through preliminary investigation, we identified the [WtP library ("Where's the Point")](https://github.com/bminixhofer/wtpsplit)
>   and spaCy's multilingual sentence detection model for identifying sentence breaks
>   in a large section of text.
> ```

You linked to WtP. Also link to spaCy. 


<!-- Sent from Reviewable.io -->

2024-04-12 14:12 UTC, hhuangMITRE reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/359)* status: 23 of 28 files reviewed, 9 unresolved discussions (waiting on @brosenberg42 and @jrobble)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf-components/359#-Nv36VE97A7ECNaP9fEt:-NvGJBVs5UI3cYMGQGNb:b-896fja) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please merge develop into this so that it includes your hotfix.
</blockquote></details>

Done!

___
___
*[`python/AzureTranslation/README.md` line 77 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/359#-Nv3050b4qZpxG-8CsVx:-NvGK2t86UfInvAt5Cbh:bb6un1j) ([raw file](https://github.com/openmpf/openmpf-components/blob/a74b91916b300b1593f7bf1c2604606d86b29bff/python/AzureTranslation/README.md#L77)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

You linked to WtP. Also link to spaCy.
</blockquote></details>

Done
___
*[`python/AzureTranslation/README.md` line 65 at r5](https://reviewable.io/reviews/openmpf/openmpf-components/359#-Nv36QxO3_NZrpNlZGB5:-NvGJCsq-Pny0jlCkUH7:btp6kku) ([raw file](https://github.com/openmpf/openmpf-components/blob/4c6fd7adc404745d8ec2b0808267b42e63e860ae/python/AzureTranslation/README.md#L65)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I pushed an update to improve the formatting of this file.
</blockquote></details>

Thank you, I've transferred the changes in. I did another scan to make sure these changes were not overwritten by the merge from develop.
___
*[`python/AzureTranslation/README.md` line 74 at r5](https://reviewable.io/reviews/openmpf/openmpf-components/359#-Nv35kvS7qkSDoU9Ivjt:-NvGJFFuAGnw8CtYkZkE:b4004se) ([raw file](https://github.com/openmpf/openmpf-components/blob/4c6fd7adc404745d8ec2b0808267b42e63e860ae/python/AzureTranslation/README.md#L74)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

You mention GPU models here and in the description of `SENTENCE_MODEL`, but there's no way to use them with this component since `"cpu"` is hard-coded. This is confusing. Consider exposing a property to use GPU or CPU, but default to CPU.
</blockquote></details>

Understood, I've added in `SENTENCE_MODEL_CPU_ONLY` to toggle CPU vs GPU behavior. During this time, I've also added in `SENTENCE_MODEL_WTP_DEFAULT_ADAPTOR_LANGUAGE`.

More advanced WtP models (ones with the language adaptor feature) would require the source text language being provided, so if the component fails to provide a valid language, we'll need to go with a default language for those cases. I've the checks in the text_splitter to support this property also as well as a localized test (I didn't want to download another WtP model for the Docker image just to support this test). 
___
*[`python/AzureTranslation/nlp_text_splitter/text_splitter.py` line 100 at r2](https://reviewable.io/reviews/openmpf/openmpf-components/359#-NuWaMc2-2gNVfEOVL_k:-NvGKXvg6kCKkofWUzNQ:bw9a5ap) ([raw file](https://github.com/openmpf/openmpf-components/blob/c502b2f5adb58036573dad69e3558ca6b7384a5b/python/AzureTranslation/nlp_text_splitter/text_splitter.py#L100)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I don't have a strong preference either way. Now that I know why those comments are there I'm fine with leaving them if it helps prevent the static type checker from reporting non-issues. It's probably not worth modifying our code much to make the type checker happy.
</blockquote></details>

Sounds good! Resolving this discussion then.
___
*[`python/AzureTranslation/nlp_text_splitter/text_splitter.py` line 101 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/359#-Nv25KOj2J8CKxH00wVk:-NvGKaG73Zdksswd3yIS:b-dtkds3) ([raw file](https://github.com/openmpf/openmpf-components/blob/a74b91916b300b1593f7bf1c2604606d86b29bff/python/AzureTranslation/nlp_text_splitter/text_splitter.py#L101)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Let's rephrase this as:

```python
"Language {lang} was not used to train WtP model. "
"If text splitting is not working well with WtP, "
"consider trying spaCy's sentence detection model."
```

You don't need to include "Warning: " since the line will be logged using the warning level. I added a space after the first period. Also, let's not get too specific about how to use spaCy. That may change in the future.
</blockquote></details>

Done, thanks!
___
*[`python/AzureTranslation/nlp_text_splitter/text_splitter.py` line 143 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/359#-Nv27qBH-33u6yXqxQxq:-NvGKbff0Zcb9TfBlf82:bo7gy5g) ([raw file](https://github.com/openmpf/openmpf-components/blob/a74b91916b300b1593f7bf1c2604606d86b29bff/python/AzureTranslation/nlp_text_splitter/text_splitter.py#L143)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Note that changes to `nlp_text_splitter` also need to be applied to other components that use the text splitter.
</blockquote></details>

That change is coming in shortly in a separate PR. 
___
*[`python/AzureTranslation/tests/test_acs_translation.py` line 618 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/359#-Nv2dP128UmOOjYGdvfl:-NvGKfVGDcBn9KUflBBI:b-vcmpam) ([raw file](https://github.com/openmpf/openmpf-components/blob/a74b91916b300b1593f7bf1c2604606d86b29bff/python/AzureTranslation/tests/test_acs_translation.py#L618)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

It also doesn't seem to care about the wide period character.
</blockquote></details>

It seems that the extra newlines can cause WtP to split text prematurely. When Azure properly detects Chinese and trims out the excess newlines, the splitting behavior does take into account the wide periods ('。' ) but I feel it doesn't always have priority. 

However, if language detection fails and the newlines are kept, seems that WtP favors dividing by newline instead.
___
*[`python/AzureTranslation/tests/test_acs_translation.py` line 855 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/359#-Nv2VJrID6YxDoIL7ACG:-NvGL0wx67Nd_qkWqO3y:b-896fja) ([raw file](https://github.com/openmpf/openmpf-components/blob/a74b91916b300b1593f7bf1c2604606d86b29bff/python/AzureTranslation/tests/test_acs_translation.py#L855)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Let's move this after `test_guess_split_simple_sentence` and `test_split_sentence_end_punctuation` since those are simpler tests.
</blockquote></details>

Done!


<!-- Sent from Reviewable.io -->

2024-04-15 18:57 UTC, jrobble requested changes
> Reviewed 4 of 5 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/359)* status: all files reviewed, 10 unresolved discussions (waiting on @brosenberg42 and @hhuangMITRE)

___
*[`python/AzureTranslation/Dockerfile` line 44 at r7](https://reviewable.io/reviews/openmpf/openmpf-components/359#-NvY0Lei7wo8oYHNbS_d:-NvY0Lei7wo8oYHNbS_e:b-vpg2l0) ([raw file](https://github.com/openmpf/openmpf-components/blob/983dce7016bab8d531ee9c0690dc8bf4dc31f9df/python/AzureTranslation/Dockerfile#L44)):*
> ```Dockerfile
> # Install WtP and spaCy
> RUN pip install --upgrade pip && \
>     pip install spacy>=3.7.4 && \
> ```

These `>=` lines aren't enforcing a version, rather, they are redirecting the log output:

```
root@7a452a7c8b0c:/home/mpf/component_src# ls -la
total 32
drwxr-xr-x 1 root root  4096 Apr 12 19:56  .
drwxr-xr-x 1 root root  4096 Apr 10 13:45  ..
-rw-r--r-- 1 root root 11673 Apr 12 19:56 '=1.3.0'
-rw-r--r-- 1 root root 11011 Apr 12 19:56 '=3.7.4'

root@7a452a7c8b0c:/home/mpf/component_src# head -5 \=1.3.0
Collecting wtpsplit
  Downloading wtpsplit-1.3.0-py3-none-any.whl.metadata (497 bytes)
Collecting onnxruntime>=1.13.1 (from wtpsplit)
  Downloading onnxruntime-1.17.1-cp38-cp38-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (4.3 kB)
Collecting transformers>=4.22.2 (from wtpsplit)

root@7a452a7c8b0c:/home/mpf/component_src# head -5 \=3.7.4
Collecting spacy
  Downloading spacy-3.7.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (27 kB)
Collecting spacy-legacy<3.1.0,>=3.0.11 (from spacy)
  Downloading spacy_legacy-3.0.12-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting spacy-loggers<2.0.0,>=1.0.0 (from spacy)
root@7a452a7c8b0c:/home/mpf/component_src#
```
___
*[`python/AzureTranslation/README.md` line 38 at r7](https://reviewable.io/reviews/openmpf/openmpf-components/359#-NvX0toH8BirNjaf1Fhs:-NvX0toH8BirNjaf1Fht:bmzghvk) ([raw file](https://github.com/openmpf/openmpf-components/blob/983dce7016bab8d531ee9c0690dc8bf4dc31f9df/python/AzureTranslation/README.md#L38)):*
> ```Markdown
>   not end with `/translate` because two separate endpoints are
>   used. `ACS_URL + '/translate'` is used for translation.
>   `ACS_URL + '/breaksentence'` is used to break up text when it is too long
> ```

The breaksentence endpoint is no longer used. Please remove this to avoid confusion.
___
*[`python/AzureTranslation/README.md` line 50 at r7](https://reviewable.io/reviews/openmpf/openmpf-components/359#-NvX1M1qACXlBxsUeD0-:-NvX1M1qACXlBxsUeD00:b4xjdsz) ([raw file](https://github.com/openmpf/openmpf-components/blob/983dce7016bab8d531ee9c0690dc8bf4dc31f9df/python/AzureTranslation/README.md#L50)):*
> ```Markdown
> # Primary Job Properties
> - `TO_LANGUAGE`: The BCP-47 language code for the language that the properties
> -    should be translated to.
> ```

This should not be formatted as a bullet.
___
*[`python/AzureTranslation/README.md` line 122 at r7](https://reviewable.io/reviews/openmpf/openmpf-components/359#-NvX2U8QEN0q3M2Z9kE2:-NvX2U8R3JLZnNmnIuAu:b-rfukdo) ([raw file](https://github.com/openmpf/openmpf-components/blob/983dce7016bab8d531ee9c0690dc8bf4dc31f9df/python/AzureTranslation/README.md#L122)):*
> it is recommended to set `SENTENCE_MODEL_CPU_ONLY=FALSE` as such models can use up to to ~3.5 GB of GPU memory.

You have "to" in there twice.

Let's rephrase this as:

>  If using more advanced WtP models like`wtp-canine-s-12l`, it is recommended to set `SENTENCE_MODEL_CPU_ONLY=FALSE` to improve performance. That model can use up to ~3.5 GB of GPU memory.
___
*[`python/AzureTranslation/nlp_text_splitter/text_splitter.py` line 103 at r7](https://reviewable.io/reviews/openmpf/openmpf-components/359#-NvY-Sl_--ovbNXrtW1E:-NvY-SlaEVjJFs38Iayi:bq00v9b) ([raw file](https://github.com/openmpf/openmpf-components/blob/983dce7016bab8d531ee9c0690dc8bf4dc31f9df/python/AzureTranslation/nlp_text_splitter/text_splitter.py#L103)):*
> ```Python
>             self.wtp_model =  WtP(wtp_model_name)
> 
>             if model_setting != "cpu" and model_setting != "cuda":
> ```

"cuda" is not a valid option because earlier in the code you do:

```python
   if not nlp_model_setting:
            nlp_model_setting = "gpu"
```

I changed the last line to use "cuda", ran this job:

```json
{
  "jobProperties": {
    "SENTENCE_MODEL": "wtp-canine-s-1l",
    "SENTENCE_MODEL_CPU_ONLY": "false"
  },
  "media": [
    {
      "mediaUri": "file:///opt/mpf/share/remote-media/art-of-war.txt"
    }
  ],
  "pipelineName": "AZURE TRANSLATION TEXT FILE PIPELINE"
}
```

And got this in the log output:

```
2024-04-15 18:52:24,979 WARN  [text_splitter.py:98] - [Job 56:art-of-war.txt] Model wtp-canine-s-1l not found, downloading from hugging face.
2024-04-15 18:52:53,690 ERROR [acs_translation_component.py:128] - [Job 56:art-of-war.txt] Failed to complete job due to the following exception:
Traceback (most recent call last):
  File "/opt/mpf/plugin-venv/lib/python3.8/site-packages/acs_translation_component/acs_translation_component.py", line 122, in get_detections_from_non_composite
    tc = TranslationClient(job.job_properties, sentence_model)
  File "/opt/mpf/plugin-venv/lib/python3.8/site-packages/acs_translation_component/acs_translation_component.py", line 190, in __init__
    self._sentence_splitter = SentenceSplitter(job_properties, sentence_model)
  File "/opt/mpf/plugin-venv/lib/python3.8/site-packages/acs_translation_component/acs_translation_component.py", line 472, in __init__
    self._sentence_model.update_model(nlp_model_name, nlp_model_setting, wtp_default_language)
  File "/opt/mpf/plugin-venv/lib/python3.8/site-packages/nlp_text_splitter/text_splitter.py", line 67, in update_model
    self._update_wtp_model(model_name, model_setting, default_lang)
  File "/opt/mpf/plugin-venv/lib/python3.8/site-packages/nlp_text_splitter/text_splitter.py", line 107, in _update_wtp_model
    self.wtp_model.to(model_setting)
  File "/opt/mpf/plugin-venv/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2576, in to
    return super().to(*args, **kwargs)
  File "/opt/mpf/plugin-venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1152, in to
    return self._apply(convert)
  File "/opt/mpf/plugin-venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 802, in _apply
    module._apply(fn)
  File "/opt/mpf/plugin-venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 802, in _apply
    module._apply(fn)
  File "/opt/mpf/plugin-venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 802, in _apply
    module._apply(fn)
  File "/opt/mpf/plugin-venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 825, in _apply
    param_applied = fn(param)
  File "/opt/mpf/plugin-venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1150, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/opt/mpf/plugin-venv/lib/python3.8/site-packages/torch/cuda/__init__.py", line 293, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
2024-04-15 18:52:53,691 ERROR [org.mitre.mpf.detection:0] - [Job 56:art-of-war.txt] An error occurred while invoking the "get_detections_from_generic" method on the Python component: AssertionError: Torch not compiled with CUDA enabled

At:
  /opt/mpf/plugin-venv/lib/python3.8/site-packages/torch/cuda/__init__.py(324): _lazy_init
  /opt/mpf/plugin-venv/lib/python3.8/site-packages/torch/nn/modules/module.py(1150): convert
  /opt/mpf/plugin-venv/lib/python3.8/site-packages/torch/nn/modules/module.py(825): _apply
  /opt/mpf/plugin-venv/lib/python3.8/site-packages/torch/nn/modules/module.py(802): _apply
  /opt/mpf/plugin-venv/lib/python3.8/site-packages/torch/nn/modules/module.py(802): _apply
  /opt/mpf/plugin-venv/lib/python3.8/site-packages/torch/nn/modules/module.py(802): _apply [...]

2024-04-16 13:56 UTC, hhuangMITRE reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/359)* status: 22 of 28 files reviewed, 10 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[`python/AzureTranslation/Dockerfile` line 44 at r7](https://reviewable.io/reviews/openmpf/openmpf-components/359#-NvY0Lei7wo8oYHNbS_d:-Nva0qjV44dUXEPWTLKv:b9kn83o) ([raw file](https://github.com/openmpf/openmpf-components/blob/983dce7016bab8d531ee9c0690dc8bf4dc31f9df/python/AzureTranslation/Dockerfile#L44)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

These `>=` lines aren't enforcing a version, rather, they are redirecting the log output:

```
root@7a452a7c8b0c:/home/mpf/component_src# ls -la
total 32
drwxr-xr-x 1 root root  4096 Apr 12 19:56  .
drwxr-xr-x 1 root root  4096 Apr 10 13:45  ..
-rw-r--r-- 1 root root 11673 Apr 12 19:56 '=1.3.0'
-rw-r--r-- 1 root root 11011 Apr 12 19:56 '=3.7.4'

root@7a452a7c8b0c:/home/mpf/component_src# head -5 \=1.3.0
Collecting wtpsplit
  Downloading wtpsplit-1.3.0-py3-none-any.whl.metadata (497 bytes)
Collecting onnxruntime>=1.13.1 (from wtpsplit)
  Downloading onnxruntime-1.17.1-cp38-cp38-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (4.3 kB)
Collecting transformers>=4.22.2 (from wtpsplit)

root@7a452a7c8b0c:/home/mpf/component_src# head -5 \=3.7.4
Collecting spacy
  Downloading spacy-3.7.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (27 kB)
Collecting spacy-legacy<3.1.0,>=3.0.11 (from spacy)
  Downloading spacy_legacy-3.0.12-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting spacy-loggers<2.0.0,>=1.0.0 (from spacy)
root@7a452a7c8b0c:/home/mpf/component_src#
```
</blockquote></details>

Fixed. Thanks for spotting that.
___
*[`python/AzureTranslation/README.md` line 38 at r7](https://reviewable.io/reviews/openmpf/openmpf-components/359#-NvX0toH8BirNjaf1Fhs:-Nva1DWg4oqH7CXTF-2w:b-896fja) ([raw file](https://github.com/openmpf/openmpf-components/blob/983dce7016bab8d531ee9c0690dc8bf4dc31f9df/python/AzureTranslation/README.md#L38)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

The breaksentence endpoint is no longer used. Please remove this to avoid confusion.
</blockquote></details>

Done!
___
*[`python/AzureTranslation/README.md` line 50 at r7](https://reviewable.io/reviews/openmpf/openmpf-components/359#-NvX1M1qACXlBxsUeD0-:-Nva1EXH70wYEsERMzfP:bt2vr0y) ([raw file](https://github.com/openmpf/openmpf-components/blob/983dce7016bab8d531ee9c0690dc8bf4dc31f9df/python/AzureTranslation/README.md#L50)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

This should not be formatted as a bullet.
</blockquote></details>

Fixed!
___
*[`python/AzureTranslation/README.md` line 122 at r7](https://reviewable.io/reviews/openmpf/openmpf-components/359#-NvX2U8QEN0q3M2Z9kE2:-Nva1G013kYHyAElMGad:b-fhnrkm) ([raw file](https://github.com/openmpf/openmpf-components/blob/983dce7016bab8d531ee9c0690dc8bf4dc31f9df/python/AzureTranslation/README.md#L122)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

> it is recommended to set `SENTENCE_MODEL_CPU_ONLY=FALSE` as such models can use up to to ~3.5 GB of GPU memory.

You have "to" in there twice.

Let's rephrase this as:

>  If using more advanced WtP models like`wtp-canine-s-12l`, it is recommended to set `SENTENCE_MODEL_CPU_ONLY=FALSE` to improve performance. That model can use up to ~3.5 GB of GPU memory.
</blockquote></details>

Done, thanks for spotting that.
___
*[`python/AzureTranslation/nlp_text_splitter/text_splitter.py` line 103 at r7](https://reviewable.io/reviews/openmpf/openmpf-components/359#-NvY-Sl_--ovbNXrtW1E:-Nva1PSk5UE8SeSCmHGJ:b-n4tntz) ([raw file](https://github.com/openmpf/openmpf-components/blob/983dce7016bab8d531ee9c0690dc8bf4dc31f9df/python/AzureTranslation/nlp_text_splitter/text_splitter.py#L103)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

"cuda" is not a valid option because earlier in the code you do:

```python
   if not nlp_model_setting:
            nlp_model_setting = "gpu"
```

I changed the last line to use "cuda", ran this job:

```json
{
  "jobProperties": {
    "SENTENCE_MODEL": "wtp-canine-s-1l",
    "SENTENCE_MODEL_CPU_ONLY": "false"
  },
  "media": [
    {
      "mediaUri": "file:///opt/mpf/share/remote-media/art-of-war.txt"
    }
  ],
  "pipelineName": "AZURE TRANSLATION TEXT FILE PIPELINE"
}
```

And got this in the log output:

```
2024-04-15 18:52:24,979 WARN  [text_splitter.py:98] - [Job 56:art-of-war.txt] Model wtp-canine-s-1l not found, downloading from hugging face.
2024-04-15 18:52:53,690 ERROR [acs_translation_component.py:128] - [Job 56:art-of-war.txt] Failed to complete job due to the following exception:
Traceback (most recent call last):
  File "/opt/mpf/plugin-venv/lib/python3.8/site-packages/acs_translation_component/acs_translation_component.py", line 122, in get_detections_from_non_composite
    tc = TranslationClient(job.job_properties, sentence_model)
  File "/opt/mpf/plugin-venv/lib/python3.8/site-packages/acs_translation_component/acs_translation_component.py", line 190, in __init__
    self._sentence_splitter = SentenceSplitter(job_properties, sentence_model)
  File "/opt/mpf/plugin-venv/lib/python3.8/site-packages/acs_translation_component/acs_translation_component.py", line 472, in __init__
    self._sentence_model.update_model(nlp_model_name, nlp_model_setting, wtp_default_language)
  File "/opt/mpf/plugin-venv/lib/python3.8/site-packages/nlp_text_splitter/text_splitter.py", line 67, in update_model
    self._update_wtp_model(model_name, model_setting, default_lang)
  File "/opt/mpf/plugin-venv/lib/python3.8/site-packages/nlp_text_splitter/text_splitter.py", line 107, in _update_wtp_model
    self.wtp_model.to(model_setting)
  File "/opt/mpf/plugin-venv/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2576, in to
    return super().to(*args, **kwargs)
  File "/opt/mpf/plugin-venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1152, in to
    return self._apply(convert)
  File "/opt/mpf/plugin-venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 802, in _apply
    module._apply(fn)
  File "/opt/mpf/plugin-venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 802, in _apply
    module._apply(fn)
  File "/opt/mpf/plugin-venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 802, in _apply
    module._apply(fn)
  File "/opt/mpf/plugin-venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 825, in _apply
    param_applied = fn(param)
  File "/opt/mpf/plugin-venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1150, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/opt/mpf/plugin-venv/lib/python3.8/site-packages/torch/cuda/__init__.py", line 293, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
2024-04-15 18:52:53,691 ERROR [org.mitre.mpf.detection:0] - [Job 56:art-of-war.txt] An error occurred while invoking the "get_detections_from_generic" method on the Python component: AssertionError: Torch not compiled with CUDA enabled

At:
  /opt/mpf/plugin-venv/lib/python3.8/site-packages/torch/cuda/__init__.py(324): _lazy_init
  /opt/mpf/plugin-venv/lib/python3.8/site-packages/torch/nn/modules/module.py(1150): convert
  /opt/mpf/plugin-venv/lib/python3.8/site-packages/torch/nn/modules/module.py(825): _apply
  /opt/mpf/plugin-venv/lib/python3.8/site-packages/torch/nn/modules/module.py(802): _apply
  /opt/mpf/plugin-venv/lib/python3.8/site-packages/torch/nn/modules/module.py(802): _apply
  /opt/mpf/plugin-venv/lib/python3.8/site-packages/torch/nn/modules/module.py(802): _apply
  /opt/mpf/plugin-venv/lib/python3.8/site-packages/torch/nn/modules/module.py(1152): to
  /opt/m [...]

2024-04-18 01:19 UTC, jrobble requested changes
> Reviewed 1 of 6 files at r8, 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/359)* status: all files reviewed, 2 unresolved discussions (waiting on @brosenberg42 and @hhuangMITRE)

___
*[`python/AzureTranslation/nlp_text_splitter/text_splitter.py` line 90 at r9](https://reviewable.io/reviews/openmpf/openmpf-components/359#-NvikxM3E8Yvd_qp7wiU:-NvikxM3E8Yvd_qp7wiV:bils052) ([raw file](https://github.com/openmpf/openmpf-components/blob/9657eee6a2a2bca4a0fbad30bb95a5d82af24fba/python/AzureTranslation/nlp_text_splitter/text_splitter.py#L90)):*
This is logged as a warning, so no need to say "Warning" in the message. Also, I ran a test using a version of the Docker image with GPU support built in and got the "no cuda support for this installation of PyTorch" message in the log file, which was misleading. To find the underlying reason I did:

```
root@90e56804e80c:/opt/mpf/plugin-venv/bin# . ./activate
(plugin-venv) root@90e56804e80c:/opt/mpf/plugin-venv/bin# python3
Python 3.8.10 (default, Nov 22 2023, 10:22:35)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
/opt/mpf/plugin-venv/lib/python3.8/site-packages/torch/cuda/__init__.py:141: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11060). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
False
```

Please update the message to:

> "PyTorch determined that CUDA is not available. "
> "You may need to update the NVIDIA driver for the host system, " 
> "or reinstall PyTorch with GPU support by setting "
> "`ARGS BUILD_TYPE=gpu` in the Dockerfile when building this component."
___
*[`python/AzureTranslation/tests/test_acs_translation.py` line 618 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/359#-Nv2dP128UmOOjYGdvfl:-Nvh_FnTDWoTn7UAm1we:b-wsvas3) ([raw file](https://github.com/openmpf/openmpf-components/blob/a74b91916b300b1593f7bf1c2604606d86b29bff/python/AzureTranslation/tests/test_acs_translation.py#L618)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

To clarify: Azure Translation has a feature for language detection of input text (so this would usually involve text extracted from other documents). If the detected language is a variant of Chinese, the newlines in the document would be replaced with an empty character '', otherwise whitespace ' ' would be added in.

I misspoke earlier when I said the newlines are kept. Rather, the newlines are incorrectly replaced with extra whitespace. 

WtP doesn't care about whitespace as much so the behavior being seen during the test is mostly due to the extra characters altering the amount of text being processed by WtP and being split apart. From my testing, some of the wide space characters are being separated out, but not all of them.

When testing Chinese text with WtP outside of the component, I noticed that it's sensitive to newlines even more than the wide period character. Every time there's a newline, there seems to be another split.

In general, that newline WtP behavior should be captured in the tests, so I've added a quick one for newlines vs no-newlines (also compared spaCy and WtP) in a separate test.

```
# Result after passing Chinese text sample through WtP.split(), no newline replacement
['兵者，國之大事，死生之地，存亡之道，不可不察也。\n',
 '故經之以五事，校之以計，而索其情：',
 '一曰道，二曰天，三曰地，四曰將，五曰法。',
 '道者，令民於上同意，可與之死，可與之生，\n',
 '而不危也；天者，陰陽、寒暑、時制也；地者，遠近、險易、廣狹、死生也；將者，智、信、仁、勇、嚴也；法者，曲制、官道、\n',
 '主用也。凡此五者，將莫不聞，知之者勝，不知之者不勝。故校之以計，而索其情，曰：主孰有道？將孰有能？天地孰得？法令孰行？\n',
 '兵眾孰強？士卒孰練？賞罰孰明？吾以此知勝負矣。將聽吾計，用之必勝，留之；將不聽吾計，用之必敗，去之。計利以聽，乃為之勢，\n',
 '以佐其外。勢者，因利而制權也。兵者，詭道也。故能而示之不能，用而示之不用，近而示之遠，遠而示之近。利而誘之，亂而取之，\n',
 '實而備之，強而避之，怒而撓之，卑而驕之，佚而勞之，親而離之，攻其無備，出其不意。此兵家之勝，不可先傳也。\n',
 '夫未戰而廟算勝者，得算多也；未戰而廟算不勝者，得算少也。多算勝少算，而況於無算乎！吾以此觀之，勝負見矣。']
```
</blockquote></details>

Thanks for the explanation.
___
*[`python/AzureTranslation/tests/test_acs_translation.py` line 603 at r9](https://reviewable.io/reviews/openmpf/openmpf-components/359#-NvhZLNPCtGNCrOEqYSF:-NvhZLNPCtGNCrOEqYSG:b4c9lyr) ([raw file](https://github.com/openmpf/openmpf-components/blob/9657eee6a2a2bca4a0fbad30bb95a5d82af24fba/python/AzureTranslation/tests/test_acs_translation.py#L603)):*
> ```Python
> 
> 
>     def test_split_engine_difference(self):
> ```

:thumbsup: 


<!-- Sent from Reviewable.io -->

2024-04-18 01:20 UTC, jrobble reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/359)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42 and @hhuangMITRE)

___
*[`python/AzureTranslation/nlp_text_splitter/text_splitter.py` line 103 at r7](https://reviewable.io/reviews/openmpf/openmpf-components/359#-NvY-Sl_--ovbNXrtW1E:-NvimUky9997eJTxAWP0:b-jur04k) ([raw file](https://github.com/openmpf/openmpf-components/blob/983dce7016bab8d531ee9c0690dc8bf4dc31f9df/python/AzureTranslation/nlp_text_splitter/text_splitter.py#L103)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

Thank you. Added `torch.cuda.is_available():` check in.

In addition, our current Dockerfile build only allows for the cpu version of PyTorch without cuda support.  

To fully enable this option, I've added a parameter to the Dockerfile to toggle cpu vs gpu PyTorch installations and added the info for setting this parameter in the README. 

Overall, the build seems to be working, but MITRE's machines are blocking the HuggingFace model, so I'm going to retest one more time. I'll ping this message again when this check is complete.
</blockquote></details>

The build arg for GPU support looks good to me.


<!-- Sent from Reviewable.io -->

2024-04-18 02:24 UTC, hhuangMITRE reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/359)* status: 27 of 28 files reviewed, 1 unresolved discussion (waiting on @brosenberg42 and @jrobble)

___
*[`python/AzureTranslation/nlp_text_splitter/text_splitter.py` line 103 at r7](https://reviewable.io/reviews/openmpf/openmpf-components/359#-NvY-Sl_--ovbNXrtW1E:-Nvj-T_m9SF_VRbHIcqN:b-8q9578) ([raw file](https://github.com/openmpf/openmpf-components/blob/983dce7016bab8d531ee9c0690dc8bf4dc31f9df/python/AzureTranslation/nlp_text_splitter/text_splitter.py#L103)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

The build arg for GPU support looks good to me.
</blockquote></details>

Thanks, I'll rerun the Jenkins build again also. 
___
*[`python/AzureTranslation/nlp_text_splitter/text_splitter.py` line 90 at r9](https://reviewable.io/reviews/openmpf/openmpf-components/359#-NvikxM3E8Yvd_qp7wiU:-Nvj-q11A57WFm_sy_Pk:b-n5rnm5) ([raw file](https://github.com/openmpf/openmpf-components/blob/9657eee6a2a2bca4a0fbad30bb95a5d82af24fba/python/AzureTranslation/nlp_text_splitter/text_splitter.py#L90)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

This is logged as a warning, so no need to say "Warning" in the message. Also, I ran a test using a version of the Docker image with GPU support built in and got the "no cuda support for this installation of PyTorch" message in the log file, which was misleading. To find the underlying reason I did:

```
root@90e56804e80c:/opt/mpf/plugin-venv/bin# . ./activate
(plugin-venv) root@90e56804e80c:/opt/mpf/plugin-venv/bin# python3
Python 3.8.10 (default, Nov 22 2023, 10:22:35)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
/opt/mpf/plugin-venv/lib/python3.8/site-packages/torch/cuda/__init__.py:141: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11060). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
False
```

Please update the message to:

> "PyTorch determined that CUDA is not available. "
> "You may need to update the NVIDIA driver for the host system, " 
> "or reinstall PyTorch with GPU support by setting "
> "`ARGS BUILD_TYPE=gpu` in the Dockerfile when building this component."
</blockquote></details>

Done! I also need to get into the habit of remembering that the message will start with `WARNING:`
___
*[`python/AzureTranslation/tests/test_acs_translation.py` line 618 at r4](https://reviewable.io/reviews/openmpf/openmpf-components/359#-Nv2dP128UmOOjYGdvfl:-Nvj-n9C2Iz9So1Hpnhh:btz4zth) ([raw file](https://github.com/openmpf/openmpf-components/blob/a74b91916b300b1593f7bf1c2604606d86b29bff/python/AzureTranslation/tests/test_acs_translation.py#L618)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Thanks for the explanation.
</blockquote></details>

Of course, thanks for double checking this as well!


<!-- Sent from Reviewable.io -->

2024-04-18 23:50 UTC, jrobble approved these changes
> Reviewed 1 of 1 files at r10, 9 of 9 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/359)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

___
*[`python/AzureTranslation/Dockerfile` line 65 at r11](https://reviewable.io/reviews/openmpf/openmpf-components/359#-Nvn_w3L3mhF_4ZAwnZV:-Nvn_w3L3mhF_4ZAwnZW:b39ze74) ([raw file](https://github.com/openmpf/openmpf-components/blob/9d4dfcb54fa6354cbdf26a792aaa2695e5bffc6e/python/AzureTranslation/Dockerfile#L65)):*
> ```Dockerfile
> 
> # Environment variables required by nvidia runtime.
> ENV NVIDIA_VISIBLE_DEVICES=all
> ```

Technically, I don't think these env. var. are required since I was able to get the prev version without these to work by setting the env. var in the service entry in the compose file:

```yaml
  azure_translation:
    depends_on:
      - workflow-manager
    deploy:
      mode: replicated
      replicas: 1
    environment:
      WFM_PASSWORD: mpfadm
      WFM_USER: admin
      MPF_PROP_ACS_URL: [REDACTED]
      MPF_PROP_ACS_SUBSCRIPTION_KEY: [REDACTED]
      NVIDIA_VISIBLE_DEVICES: 2
    image: someregistry/openmpf_azure_translation:deleteme-jrobble-gpu
    volumes:
      - shared_data:/opt/mpf/share:rw
```

However, we do set these in many of our other components, so let's keep them for consistency.
___
*[`python/AzureTranslation/LICENSE` line 30 at r11](https://reviewable.io/reviews/openmpf/openmpf-components/359#-NvnYtiK6uwxwS-OFJrG:-NvnYtiLBywiBo9Z1muX:bksp1ws) ([raw file](https://github.com/openmpf/openmpf-components/blob/9d4dfcb54fa6354cbdf26a792aaa2695e5bffc6e/python/AzureTranslation/LICENSE#L30)):*
> ```
> MIT License
> 
> Copyright (c) 2024 Benjamin Minixhofer
> ```

Did you intend to update someone else's license?
___
*[`python/AzureTranslation/LICENSE` line 56 at r11](https://reviewable.io/reviews/openmpf/openmpf-components/359#-NvnYzIZ8xpMD7tyA6vs:-NvnYzIZ8xpMD7tyA6vt:bksp1ws) ([raw file](https://github.com/openmpf/openmpf-components/blob/9d4dfcb54fa6354cbdf26a792aaa2695e5bffc6e/python/AzureTranslation/LICENSE#L56)):*
> ```
> The MIT License (MIT)
> 
> Copyright (C) 2016-2024 ExplosionAI GmbH, 2016 spaCy GmbH, 2015 Matthew Honnibal
> ```

Did you intend to update someone else's license?


<!-- Sent from Reviewable.io -->

2024-04-19 15:01 UTC, jrobble approved these changes
> Reviewed 2 of 2 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/359)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)



<!-- Sent from Reviewable.io -->

2024-04-19 15:05 UTC, merged