Add OrToolsSubjectComponent
openmpf/openmpf-components pull request #378
Opened 2024-07-10 17:39 UTC by brosenberg42

**Issues:**

- https://github.com/openmpf/openmpf/issues/1 < Example
- https://github.com/openmpf/openmpf/issues/2 < Example

If a related issue doesn't exist, then create one first and assign it to yourself.

**Related PRs:**

- https://github.com/openmpf/openmpf/pull/22 < Example
- https://github.com/openmpf/openmpf/pull/53 < Example

Please review our [Contributor Guide](https://openmpf.github.io/docs/site/Contributor-Guide/index.html).

2024-09-24 15:42 UTC, jrobble requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/378)* status: all files reviewed, 11 unresolved discussions (waiting on @brosenberg42)

___
*[`python/OrToolsSubjectComponent/Dockerfile` line 33 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/378#-O4ljGDVE3X6ji4pauYS:-O4ljGDVE3X6ji4pauYT:bdegnz1) ([raw file](https://github.com/openmpf/openmpf-components/blob/0dac6f85be519f0eb44e071a788a9c27ae22d947/python/OrToolsSubjectComponent/Dockerfile#L33)):*
> ```Dockerfile
> RUN pip install ortools
> 
> RUN --mount=target=.,readwrite install-component.sh
> ```

Eventually we'll need to add unit tests to this.
___
*[`python/OrToolsSubjectComponent/Dockerfile` line 39 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/378#-O4krlVC0ZAfJacH_SD9:-O4krlVC0ZAfJacH_SDA:busu6dq) ([raw file](https://github.com/openmpf/openmpf-components/blob/0dac6f85be519f0eb44e071a788a9c27ae22d947/python/OrToolsSubjectComponent/Dockerfile#L39)):*
> ```Dockerfile
> COPY --from=build_component $COMPONENT_VIRTUALENV $COMPONENT_VIRTUALENV
> 
> COPY --from=build_component $PLUGINS_DIR/OrToolsSubjectComponent $PLUGINS_DIR/OrToolsSubjectComponent
> ```

Please add labels like these:

```yaml
LABEL org.label-schema.license="Apache 2.0" \
      org.label-schema.name="OpenMPF Azure Read Text Detection" \
      org.label-schema.schema-version="1.0" \
      org.label-schema.url="https://openmpf.github.io" \
      org.label-schema.vcs-url="https://github.com/openmpf/openmpf-components" \
      org.label-schema.vendor="MITRE"
```

I know this is a first cut so things like this are missing. Before we land this, please add a `README.md`, `LICENSE`, and `NOTICE`.
___
*[`python/OrToolsSubjectComponent/pyproject.toml` line 27 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/378#-O4ksqFV-ENGS7xI-ehG:-O4ksqFV-ENGS7xI-ehH:bi0nia4) ([raw file](https://github.com/openmpf/openmpf-components/blob/0dac6f85be519f0eb44e071a788a9c27ae22d947/python/OrToolsSubjectComponent/pyproject.toml#L27)):*
> ```TOML
> #############################################################################
> 
> [build-system]
> ```

Do we not need `setup.cfg` anymore?
___
*[`python/OrToolsSubjectComponent/or_tools_component/__init__.py` line 1 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/378#-O4kuJNz6IcvWnTVSvfr:-O4kuJNz6IcvWnTVSvfs:b8j2vou) ([raw file](https://github.com/openmpf/openmpf-components/blob/0dac6f85be519f0eb44e071a788a9c27ae22d947/python/OrToolsSubjectComponent/or_tools_component/__init__.py#L1)):*
> ```Python
> #############################################################################
> ```

For detection components the `__init__.py` uses `from`. For example:

```python
from .acs_read_detection_component import AcsReadDetectionComponent
```

Looking around on forums, the consensus seems to be that in most cases `__init_py` should have little in it, unless you have package-level instantiation code, or are writing a library that's so small/basic that you don't need to break it out into modules.

What's your motivation? I'm assuming it's the latter.

If I remember correctly, I think you mentioned that it's basically unnecessary to have an `__init__.py` that just imports one thing.

Making a note here for myself that a similar change was made to`__init.py__` in the example PythonSubjectComponent and `subject/api/mpf_subject_api/__init__.py`.

If this is the direction we're going, should we make these changes to the detection components, or is it such a minor / optional thing it's unnecessary?
___
*[`python/OrToolsSubjectComponent/or_tools_component/__init__.py` line 70 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/378#-O4lImlKBY7osZOehoU_:-O4lImlKBY7osZOehoUa:b-tjto82) ([raw file](https://github.com/openmpf/openmpf-components/blob/0dac6f85be519f0eb44e071a788a9c27ae22d947/python/OrToolsSubjectComponent/or_tools_component/__init__.py#L70)):*
> ```Python
> 
>         relationships = get_relationship_dict(assignments, non_subject_entities, media_id)
>         num_entities = sum(len(es) for es in all_entities.values())
> ```

What does `es` stand for?
___
*[`python/OrToolsSubjectComponent/or_tools_component/__init__.py` line 71 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/378#-O4lJ9VL6ZEDRypC-YN1:-O4lJ9VL6ZEDRypC-YN2:b-jmcqyf) ([raw file](https://github.com/openmpf/openmpf-components/blob/0dac6f85be519f0eb44e071a788a9c27ae22d947/python/OrToolsSubjectComponent/or_tools_component/__init__.py#L71)):*
Let's log:

> Finished running subject tracking job. Found X subjects and Y non-subject entities.
___
*[`python/OrToolsSubjectComponent/or_tools_component/__init__.py` line 178 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/378#-O4lidd_5R0LIwK3AwLq:-O4lidd_5R0LIwK3AwLr:bylx24) ([raw file](https://github.com/openmpf/openmpf-components/blob/0dac6f85be519f0eb44e071a788a9c27ae22d947/python/OrToolsSubjectComponent/or_tools_component/__init__.py#L178)):*
> ```Python
> class Assignment:
>     @classmethod
>     def assign_tracks(
> ```

I'm assuming this method takes the most amount of time. Please add a log line stating how much time it took to run. Add other timing log lines that you think might be helpful.
___
*[`python/OrToolsSubjectComponent/or_tools_component/__init__.py` line 196 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/378#-O4leK_T9QngeVViptFd:-O4leK_T9QngeVViptFe:b-q0zu0e) ([raw file](https://github.com/openmpf/openmpf-components/blob/0dac6f85be519f0eb44e071a788a9c27ae22d947/python/OrToolsSubjectComponent/or_tools_component/__init__.py#L196)):*
> ```Python
>                     assignment_var = AssignmentVar(model_var, ft, pt, score)
>                     face_to_person_assignments.append(assignment_var)
>                     model_vars_grouped_by_person[id(pt)].append(model_var)
> ```

Interesting use of memory address for the unique id.
___
*[`python/OrToolsSubjectComponent/or_tools_component/__init__.py` line 202 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/378#-O4ldqxX1CXp5hMkVZIR:-O4ldqxY-sP9-NoenbA_:b-mau83w) ([raw file](https://github.com/openmpf/openmpf-components/blob/0dac6f85be519f0eb44e071a788a9c27ae22d947/python/OrToolsSubjectComponent/or_tools_component/__init__.py#L202)):*
> ```Python
>                 yield TrackAssignment.face_only(ft)
> 
>         for person_face_assignment_group in model_vars_grouped_by_person.values():
> ```

Add a comment here. For example:

"Ensure that each person track is only assigned to one face track."
___
*[`python/OrToolsSubjectComponent/or_tools_component/__init__.py` line 220 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/378#-O4ldNRz2ab9kgBdw9YM:-O4ldNRz2ab9kgBdw9YN:b-qf3slf) ([raw file](https://github.com/openmpf/openmpf-components/blob/0dac6f85be519f0eb44e071a788a9c27ae22d947/python/OrToolsSubjectComponent/or_tools_component/__init__.py#L220)):*
> ```Python
> 
>     @staticmethod
>     def _add_overlap_constraints(
> ```

Please add a method comment explaining what this does. For example:

"Ensure that only person tracks with no frames in common are assigned to the same face track."
___
*[`python/OrToolsSubjectComponent/or_tools_component/__init__.py` line 392 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/378#-O4lYIPt5YYP0arJIv-j:-O4lYIPt5YYP0arJIv-k:b-3152za) ([raw file](https://github.com/openmpf/openmpf-components/blob/0dac6f85be519f0eb44e071a788a9c27ae22d947/python/OrToolsSubjectComponent/or_tools_component/__init__.py#L392)):*
> ```Python
> # TODO include in output
> def get_subject_to_subject_relationships(
>             assignments: Sequence[TrackAssignment], media_id: mpf_sub.MediaId):
> ```

Missing `->` type annotation for the return value.
___
*[`python/OrToolsSubjectComponent/or_tools_component/config.json` line 10 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/378#-O4lZOgb5tSjgsJs1qe9:-O4lZO [...]

2024-10-01 17:36 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/378)* status: 4 of 6 files reviewed, 11 unresolved discussions (waiting on @jrobble)

___
*[`python/OrToolsSubjectComponent/pyproject.toml` line 27 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/378#-O4ksqFV-ENGS7xI-ehG:-O7dHHKoAS1CGJtiujqI:b-6ptqgd) ([raw file](https://github.com/openmpf/openmpf-components/blob/0dac6f85be519f0eb44e071a788a9c27ae22d947/python/OrToolsSubjectComponent/pyproject.toml#L27)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Do we not need `setup.cfg` anymore?
</blockquote></details>

No, not unless we are doing something complicated with setuptools.
___
*[`python/OrToolsSubjectComponent/or_tools_component/__init__.py` line 1 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/378#-O4kuJNz6IcvWnTVSvfr:-O7dJdK-7tC_d-BET4X9:b-axpqli) ([raw file](https://github.com/openmpf/openmpf-components/blob/0dac6f85be519f0eb44e071a788a9c27ae22d947/python/OrToolsSubjectComponent/or_tools_component/__init__.py#L1)):*

It has been a while since our Python SDK was initially released and things change. For a while `__init__.py` was just used as a marker file. It is more common now to include code in `__init__.py`. 


> are writing a library that's so small/basic that you don't need to break it out into modules.

This approach doesn't prevent you from using multiple Python files or using sub-packages. You can both have code in `__init__.py` and other Python files.


> If this is the direction we're going, should we make these changes to the detection components, or is it such a minor / optional thing it's unnecessary?

There is no need to go back and update the other components. It is very minor. It also should be the component developer that decides how best to break up the code. Sometimes one file is sufficient, sometimes it isn't. It would be like saying to be consistent all Python components must use exactly 2 .py files
___
*[`python/OrToolsSubjectComponent/or_tools_component/__init__.py` line 70 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/378#-O4lImlKBY7osZOehoU_:-O7dKqWC8x1W3XKvYJei:b-sqmhn9) ([raw file](https://github.com/openmpf/openmpf-components/blob/0dac6f85be519f0eb44e071a788a9c27ae22d947/python/OrToolsSubjectComponent/or_tools_component/__init__.py#L70)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

What does `es` stand for?
</blockquote></details>

When you use lambdas or other constructs where the scope of a variable is a single line, it is common to use single letter variable names and to pluralize them with `s`. `e` is for entity, but the entities are in a nested collection. `es` is used to make it clear that it is a collection of entities, not a single entity.
___
*[`python/OrToolsSubjectComponent/or_tools_component/__init__.py` line 71 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/378#-O4lJ9VL6ZEDRypC-YN1:-O87aNe79AYx1_BGJAoD:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/0dac6f85be519f0eb44e071a788a9c27ae22d947/python/OrToolsSubjectComponent/or_tools_component/__init__.py#L71)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Let's log:

> Finished running subject tracking job. Found X subjects and Y non-subject entities.
</blockquote></details>

Done.
___
*[`python/OrToolsSubjectComponent/or_tools_component/__init__.py` line 178 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/378#-O4lidd_5R0LIwK3AwLq:-O7d_HvKEx5g3dMYfnK9:b6wjcqc) ([raw file](https://github.com/openmpf/openmpf-components/blob/0dac6f85be519f0eb44e071a788a9c27ae22d947/python/OrToolsSubjectComponent/or_tools_component/__init__.py#L178)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I'm assuming this method takes the most amount of time. Please add a log line stating how much time it took to run. Add other timing log lines that you think might be helpful.
</blockquote></details>

I don't think we should be including code for timing things like that. The way you address things that are taking too long is to use a profiler. Following your instructions here is just going to give people an inaccurate idea of what is actually going on. Your assumption may be inaccurate, but could be verified by using a profiler. Adding timing information to just that one method will not allow you to verify your assumption.

I can add log lines stating that we are assigning tracks, but it wouldn't include timing information. An interested party would need to subtract the timestamps.
___
*[`python/OrToolsSubjectComponent/or_tools_component/__init__.py` line 202 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/378#-O4ldqxX1CXp5hMkVZIR:-O87bIn79tN4XLHJvtB8:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/0dac6f85be519f0eb44e071a788a9c27ae22d947/python/OrToolsSubjectComponent/or_tools_component/__init__.py#L202)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Add a comment here. For example:

"Ensure that each person track is only assigned to one face track."
</blockquote></details>

Done.
___
*[`python/OrToolsSubjectComponent/or_tools_component/__init__.py` line 220 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/378#-O4ldNRz2ab9kgBdw9YM:-O87e2Ru2m-xWNM6pj92:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/0dac6f85be519f0eb44e071a788a9c27ae22d947/python/OrToolsSubjectComponent/or_tools_component/__init__.py#L220)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please add a method comment explaining what this does. For example:

"Ensure that only person tracks with no frames in common are assigned to the same face track."
</blockquote></details>

Done.
___
*[`python/OrToolsSubjectComponent/or_tools_component/__init__.py` line 392 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/378#-O4lYIPt5YYP0arJIv-j:-O87eF3i1SU1lk8A4bVQ:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/0dac6f85be519f0eb44e071a788a9c27ae22d947/python/OrToolsSubjectComponent/or_tools_component/__init__.py#L392)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Missing `->` type annotation for the return value.
</blockquote></details>

Done.
___
*[`python/OrToolsSubjectComponent/or_tools_component/config.json` line 10 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/378#-O4lZOgb5tSjgsJs1qe9:-O87eUpa-Ir15mxdp0o5:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/0dac6f85be519f0eb44e071a788a9c27ae22d947/python/OrToolsSubjectComponent/or_tools_component/config.json#L10)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I think this should be `entity_type`. That's what you call it in the code.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-09 16:43 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/378)* status: 2 of 9 files reviewed, 11 unresolved discussions (waiting on @jrobble)

___
*[`python/OrToolsSubjectComponent/Dockerfile` line 39 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/378#-O4krlVC0ZAfJacH_SD9:-ODgIYeXA9uiSMTSYCXt:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/0dac6f85be519f0eb44e071a788a9c27ae22d947/python/OrToolsSubjectComponent/Dockerfile#L39)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please add labels like these:

```yaml
LABEL org.label-schema.license="Apache 2.0" \
      org.label-schema.name="OpenMPF Azure Read Text Detection" \
      org.label-schema.schema-version="1.0" \
      org.label-schema.url="https://openmpf.github.io" \
      org.label-schema.vcs-url="https://github.com/openmpf/openmpf-components" \
      org.label-schema.vendor="MITRE"
```

I know this is a first cut so things like this are missing. Before we land this, please add a `README.md`, `LICENSE`, and `NOTICE`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-20 20:49 UTC, jrobble requested changes
> Reviewed 2 of 2 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/378)* status: all files reviewed, 2 unresolved discussions (waiting on @brosenberg42)

___
*[`python/OrToolsSubjectComponent/or_tools_component/__init__.py` line 178 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/378#-O4lidd_5R0LIwK3AwLq:-O9Qp-oqDFgGvapgaHoP:b-8dfs5a) ([raw file](https://github.com/openmpf/openmpf-components/blob/0dac6f85be519f0eb44e071a788a9c27ae22d947/python/OrToolsSubjectComponent/or_tools_component/__init__.py#L178)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I don't think we should be including code for timing things like that. The way you address things that are taking too long is to use a profiler. Following your instructions here is just going to give people an inaccurate idea of what is actually going on. Your assumption may be inaccurate, but could be verified by using a profiler. Adding timing information to just that one method will not allow you to verify your assumption.

I can add log lines stating that we are assigning tracks, but it wouldn't include timing information. An interested party would need to subtract the timestamps.
</blockquote></details>

For now we agreed that there may be a better way to get timing info. There are some things to consider:

- Getting enough info to triage an issue, like knowing if it's related to the env., and knowing what the overall behavior is that's causing the issue. 
- Getting enough info to technically debug an issue (profile).
- Getting stats for comparison, like frames/sec, faces/sec, entities/sec.
- Enabling someone not familiar with the code to get stats / enough log info to understand expected performance, and easily compare performance when things change (like libs) and running on different hardware (GPUs).


<!-- Sent from Reviewable.io -->

2025-01-02 17:59 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/378)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @jrobble)

___
*[`python/OrToolsSubjectComponent/Dockerfile` line 33 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/378#-O4ljGDVE3X6ji4pauYS:-OFc9ruf4TPmoAMzzMky:bc6zwsm) ([raw file](https://github.com/openmpf/openmpf-components/blob/0dac6f85be519f0eb44e071a788a9c27ae22d947/python/OrToolsSubjectComponent/Dockerfile#L33)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Eventually we'll need to add unit tests to this.
</blockquote></details>

Added to https://github.com/openmpf/openmpf/issues/1866
___
*[`python/OrToolsSubjectComponent/or_tools_component/__init__.py` line 178 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/378#-O4lidd_5R0LIwK3AwLq:-OFbr-11CfJ4kxnlFvXE:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/0dac6f85be519f0eb44e071a788a9c27ae22d947/python/OrToolsSubjectComponent/or_tools_component/__init__.py#L178)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

For now we agreed that there may be a better way to get timing info. There are some things to consider:

- Getting enough info to triage an issue, like knowing if it's related to the env., and knowing what the overall behavior is that's causing the issue. 
- Getting enough info to technically debug an issue (profile).
- Getting stats for comparison, like frames/sec, faces/sec, entities/sec.
- Enabling someone not familiar with the code to get stats / enough log info to understand expected performance, and easily compare performance when things change (like libs) and running on different hardware (GPUs).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-02-05 18:34 UTC, jrobble requested changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/378)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

___
*[`python/OrToolsSubjectComponent/or_tools_component/__init__.py` line 434 at r6](https://reviewable.io/reviews/openmpf/openmpf-components/378#-OILpD7K8h6lBjLB1CM8:-OILpD7K8h6lBjLB1CM9:bzhwn27) ([raw file](https://github.com/openmpf/openmpf-components/blob/c8d75b1f0d97077489448d9628a33d479a57c5d6/python/OrToolsSubjectComponent/or_tools_component/__init__.py#L434)):*
> ```Python
>         entity_track: NonSubjectEntity) -> List[FrameIndex]:
>     return sorted(
>         fi for fi, subj_rects, det_rect in get_items_with_common_keys(
> ```

Why is this `det_rect` and not `det_rects`?


<!-- Sent from Reviewable.io -->

2025-02-06 03:46 UTC, jrobble reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/378)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

___
*[`python/OrToolsSubjectComponent/or_tools_component/__init__.py` line 385 at r6](https://reviewable.io/reviews/openmpf/openmpf-components/378#-OIOMS248EKNwGLDDxpm:-OIOMS25AvXjrBAOWZ-k:b-r22vv4) ([raw file](https://github.com/openmpf/openmpf-components/blob/c8d75b1f0d97077489448d9628a33d479a57c5d6/python/OrToolsSubjectComponent/or_tools_component/__init__.py#L385)):*
> ```Python
> 
> 
> @timing.time_func('Finding relationships')
> ```

Great job with the timer and user of decorators.


<!-- Sent from Reviewable.io -->

2025-02-06 12:46 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/378)* status: all files reviewed, 1 unresolved discussion (waiting on @jrobble)

___
*[`python/OrToolsSubjectComponent/or_tools_component/__init__.py` line 434 at r6](https://reviewable.io/reviews/openmpf/openmpf-components/378#-OILpD7K8h6lBjLB1CM8:-OIQGVJY9nMknS-6TK0A:b6pd2xj) ([raw file](https://github.com/openmpf/openmpf-components/blob/c8d75b1f0d97077489448d9628a33d479a57c5d6/python/OrToolsSubjectComponent/or_tools_component/__init__.py#L434)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Why is this `det_rect` and not `det_rects`?
</blockquote></details>

`subj_rects` is a `List[Rect[int]]`, but `det_rect` is a `Rect[int]`. This difference is a bit more obvious if you look at the call to `any_intersection` on line 436 below. `det_rect` needs to put in to a tuple because it is not a collection.


<!-- Sent from Reviewable.io -->

2025-02-10 16:31 UTC, jrobble approved these changes

2025-02-10 17:29 UTC, merged