Make argos use SELECTED_CONTENT
openmpf/openmpf-components pull request #383
Opened 2024-09-20 17:53 UTC by brosenberg42

**Issues:**

- https://github.com/openmpf/openmpf/issues/1 < Example
- https://github.com/openmpf/openmpf/issues/2 < Example

If a related issue doesn't exist, then create one first and assign it to yourself.

**Related PRs:**

- https://github.com/openmpf/openmpf/pull/22 < Example
- https://github.com/openmpf/openmpf/pull/53 < Example

Please review our [Contributor Guide](https://openmpf.github.io/docs/site/Contributor-Guide/index.html).

2024-10-10 18:19 UTC, jrobble requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/383)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

___
*[`python/ArgosTranslation/argos_translation_component/argos_translation_component.py` line 69 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/383#-O7_1u_pALN7Xw58aqxZ:-O7_1u_pALN7Xw58aqx_:bmqadmt) ([raw file](https://github.com/openmpf/openmpf-components/blob/473d6867cc5c65beca0e565492891b053cdc9a67/python/ArgosTranslation/argos_translation_component/argos_translation_component.py#L69)):*
Update to:

> Job did not contain a feed forward track or specify selected content.


<!-- Sent from Reviewable.io -->

2024-10-11 18:14 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/383)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jrobble)

___
*[`python/ArgosTranslation/argos_translation_component/argos_translation_component.py` line 69 at r1](https://reviewable.io/reviews/openmpf/openmpf-components/383#-O7_1u_pALN7Xw58aqxZ:-O8wmQvmCINqNBHhH5zl:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/473d6867cc5c65beca0e565492891b053cdc9a67/python/ArgosTranslation/argos_translation_component/argos_translation_component.py#L69)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Update to:

> Job did not contain a feed forward track or specify selected content.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-16 14:07 UTC, jrobble reviewed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/383)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)



<!-- Sent from Reviewable.io -->

2025-02-14 12:30 UTC, brosenberg42 reviewed
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/383)* status: 13 of 24 files reviewed, 8 unresolved discussions (waiting on @jrobble)

___
*[`python/ArgosTranslation/plugin-files/descriptor/descriptor.json` line 131 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/383#-OIqMSUz5-U6dk4PCqTV:-OJ-bOaqA49gZw13XLaW:b-ue0afa) ([raw file](https://github.com/openmpf/openmpf-components/blob/bab8ca2c2c902b339e8e8ec383055fd4f57aadb6/python/ArgosTranslation/plugin-files/descriptor/descriptor.json#L131)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Usually pipelines have task merging enabled. 

I think we should either enable it here or change the name of the pipeline to "(WITH FASTTEXT LANGUAGE ID AND NO TASK MERGING)" for clarity. My preference would be to enable it. I see that you use this pipeline for a system test. Consider disabling task merging using a job property.
</blockquote></details>

Users will expect the tracks with the translation to be in TRANSLATION section of the output object. They will be confused if the translation is in the LANGUAGE section. Task merging doesn't make sense for this pipeline, so including it in the name just makes things confusing.
___
*[`python/FastTextLanguageDetection/Dockerfile` line 37 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/383#-OIqNEh92DCPqsyVAcTa:-OJ3EJyoD6nDDf-gVeKT:b-bi3m5e) ([raw file](https://github.com/openmpf/openmpf-components/blob/bab8ca2c2c902b339e8e8ec383055fd4f57aadb6/python/FastTextLanguageDetection/Dockerfile#L37)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Have you tested this offline to make sure this works?
</blockquote></details>

"This" is a line that only gets executed when running `docker build`. It does require network access. It downloads the model so that the component Docker image works offline.
___
*[`python/FastTextLanguageDetection/LICENSE` line 25 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/383#-OIqNS4IEOF-S6N92pFS:-OJ3BWI43IBwZEQ2SHSS:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/bab8ca2c2c902b339e8e8ec383055fd4f57aadb6/python/FastTextLanguageDetection/LICENSE#L25)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Check line length.
</blockquote></details>

Done.
___
*[`python/FastTextLanguageDetection/README.md` line 21 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/383#-OIqa1YT3L63wprEN2ax:-OJ3HNmw3oY8iZbrQhSE:b-4oup12) ([raw file](https://github.com/openmpf/openmpf-components/blob/bab8ca2c2c902b339e8e8ec383055fd4f57aadb6/python/FastTextLanguageDetection/README.md#L21)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

The language detection component in the other repo does this:

```python
        if no_language_detected:
            detection_properties["MYCOMPONENT_NO_LANGUAGE_DETECTION"] = "TRUE"
            self.processing_count += 1
            return

        report = "; ".join(
            f"lang: {r.language.lower()}-"
            f"{r.script.lower()}, "
            f"section: {r.section.start_index}-{r.section.end_index}, "
            f"conf: {r.confidence}"
            for r in report_list
        )
        if primary_language:
            detection_properties["ISO_LANGUAGE"] = primary_language
        if primary_script:
            detection_properties["ISO_SCRIPT"] = primary_script
```

Let's take a similar approach for the fast text component to be consistent.

Specifically, that component sets `*_NO_LANGUAGE_DETECTION` to true and omits the `ISO_LANGUAGE` and `ISO_SCRIPT` properties.

Alternatively, let's talk about creating a task to update the other component if you think your approach is better.
</blockquote></details>

In the way I did it, the job consumer only needs to check two fields. In the approach above, the user needs to check an additional field. Since the name of the component is in the field, a user needs to customize their code based on what component is doing the language detection. It prevents us from being able to use multiple language detection components interchangeably.
___
*[`python/FastTextLanguageDetection/README.md` line 43 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/383#-OIqq-_DACA3-VDUJFr4:-OJ3C8zjCJqIl33x_s6e:b-col8q) ([raw file](https://github.com/openmpf/openmpf-components/blob/bab8ca2c2c902b339e8e8ec383055fd4f57aadb6/python/FastTextLanguageDetection/README.md#L43)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Explain that the component reports unknown instead of `lzh_Hani`. (Although, see my other comment about not reporting a language or script instead of unknown.)
</blockquote></details>

`<UNKNOWN>` is already mentioned in the readme.
___
*[`python/FastTextLanguageDetection/fast_text_language_detection_component/__init__.py` line 82 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/383#-OIqbpZ90rz0botqlrbX:-OJ3CFNj1JJrQohxZ5wz:b-896fix) ([raw file](https://github.com/openmpf/openmpf-components/blob/bab8ca2c2c902b339e8e8ec383055fd4f57aadb6/python/FastTextLanguageDetection/fast_text_language_detection_component/__init__.py#L82)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

The language detection component in the other repo says the following to be more specific:

> "Component can only process feed forward jobs for videos, "

However, in other places it just says:

> "Component can only process feed forward jobs"

In general , the latter is confusing because both that component and this Fast Text component can process text files in a single-stage pipeline. Please reword it in both components for clarity.
</blockquote></details>

Done.
___
*[`python/FastTextLanguageDetection/plugin-files/descriptor/descriptor.json` line 23 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/383#-OIql_4fCiLU_pPuHHcy:-OJ3CicW0_GcvPd71vek:bmbf3zt) ([raw file](https://github.com/openmpf/openmpf-components/blob/bab8ca2c2c902b339e8e8ec383055fd4f57aadb6/python/FastTextLanguageDetection/plugin-files/descriptor/descriptor.json#L23)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Does Fast Text / GlotLID have a text length threshold? I could not readily find anything online about a Fast Text / GlotLID limit. 

Have you done any testing to determine the affect of text length on accuracy? If not, please run a few tests.

The NLLB component has a max length of 360 chars and uses the text splitter when over that. See [here](https://github.com/openmpf/openmpf-components/blob/feature/nllb_translation_component/python/NllbTranslation/nllb_component/nllb_translation_component.py#L129). Granted, that's a translation component and Fast Text is language detection, so it may be a non-issue.

The language detection component in the other repo uses the text splitter, but only because of limitations on the number of bytes that can be sent to the server. We're not using a server here, so there's no reason to use a text splitter for that reason alone.
</blockquote></details>

There is no length limit. I have not seen a case where a human could determine the language, but the component couldn't. It is not possible to determine the language of very short strings like "abc" or "animal" (it is the same in Spanish). 


<!-- Sent from Reviewable.io -->

2025-02-14 15:22 UTC, jrobble requested changes
> Reviewed 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/383)* status: all files reviewed, 3 unresolved discussions (waiting on @brosenberg42)

___
*[`python/FastTextLanguageDetection/README.md` line 21 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/383#-OIqa1YT3L63wprEN2ax:-OJ40pIRAUeKjBxxx5JH:b-cu7jyn) ([raw file](https://github.com/openmpf/openmpf-components/blob/bab8ca2c2c902b339e8e8ec383055fd4f57aadb6/python/FastTextLanguageDetection/README.md#L21)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

In the way I did it, the job consumer only needs to check two fields. In the approach above, the user needs to check an additional field. Since the name of the component is in the field, a user needs to customize their code based on what component is doing the language detection. It prevents us from being able to use multiple language detection components interchangeably.
</blockquote></details>

Please look into how downstream translation components handle `<UNKNOWN>`. I agree that `MYCOMPONENT_*` should be removed, but if we go with the `<UNKNOWN>` approach that property is not necessary. Our goal is to make sure the language detection components are consistent.
___
*[`python/FastTextLanguageDetection/README.md` line 43 at r3](https://reviewable.io/reviews/openmpf/openmpf-components/383#-OIqq-_DACA3-VDUJFr4:-OJ41_W64bGmneu-hQfv:b-we2j8f) ([raw file](https://github.com/openmpf/openmpf-components/blob/bab8ca2c2c902b339e8e8ec383055fd4f57aadb6/python/FastTextLanguageDetection/README.md#L43)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

`<UNKNOWN>` is already mentioned in the readme.
</blockquote></details>

Please mention unknown again here.


<!-- Sent from Reviewable.io -->

2025-02-18 23:14 UTC, jrobble requested changes
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/383)* status: all files reviewed, 2 unresolved discussions (waiting on @brosenberg42)

___
*[`python/ArgosTranslation/argos_translation_component/argos_translation_component.py` line 91 at r5](https://reviewable.io/reviews/openmpf/openmpf-components/383#-OJQJ41S738bUO6z_ZTR:-OJQJ41S738bUO6z_ZTS:b-txuc8g) ([raw file](https://github.com/openmpf/openmpf-components/blob/7f992f0a22dc30cc93466f8e6dfceb55fdf15082/python/ArgosTranslation/argos_translation_component/argos_translation_component.py#L91)):*
> ```Python
>             if job_feed_forward is None:
>                 raise mpf.DetectionError.UNSUPPORTED_DATA_TYPE.exception(
>                     f'Component can only process feed forward '
> ```

There are two spaces between "forward" and "jobs". Also, there is an extra space after the period.

Instead of fixing that please update this component to use `fail_when_missing_feed_forward()`. There are a lot of components that do feed-forward which we could update as well, but for now let's just make sure the translation ones are consistent.


<!-- Sent from Reviewable.io -->

2025-02-20 23:13 UTC, jrobble approved these changes
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-components/383)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)



<!-- Sent from Reviewable.io -->

2025-02-21 16:07 UTC, merged